source-postgres/main.go

Adds a special case check for Postgres database addresses ending in `.pooler.supabase.com:6543` and `.pooler.supabase.com` (that latter address is _also_ invalid since the pooler isn't running  on the default Postgres port, but the user intent is clear so we might as well present the appropriate error message then too).
We should still try to add generic connection pooler detection logic in the future (https://github.com/estuary/connectors/issues/1576) but even after such logic exists it's probably still useful to have special cases for common ones like this so that we can provide an even more tailored error message. This one, for instance, will tell the user as clearly as I could manage that `address must be a direct connection: address %q is using the Supabase …

source-postgres: Special-case check for Supabase connection pooler

---

source-postgres-batch/.snapshots/TestBasicCapture-Discovery
source-postgres-batch/.snapshots/TestBasicDatatypes-Discovery
source-postgres-batch/.snapshots/TestKeyDiscovery
source-postgres-batch/.snapshots/TestSchemaFilter-FilteredIn
source-postgres-batch/.snapshots/TestSchemaFilter-Unfiltered
source-postgres-batch/.snapshots/TestSpec
source-postgres-batch/driver.go
source-postgres-batch/main.go

This PR modifies the `source-postgres-batch` connector in two related ways:
- The polling query is tweaked so that it should work correctly even when the XID epoch wraps around (provided that the source table is updated more frequently than that wraparound happens -- if that's an issue I have ideas and believe it's fixable, but it felt out of scope for the current goal).
- The resource config now leaves the template empty and expects the connector to supply the default behavior. Since the template used to hard-code in a table name, there are now two new resource config fields for the schema/table name, which simply get plumbed into the template. This means that if there's some minor issue with the polling query behavior we can fix it in the future by rolling out a new …

source-postgres-batch: Correctly handle XID wraparound

---

source-mysql/discovery.go

Previously out-of-range enum indices would fall through the value translation logic and be emitted as integers (which would then immediately fail schema validation). This makes the source of the failure more immediately evident.
This fixes https://github.com/estuary/connectors/issues/1625
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1633)

source-mysql: Error on out-of-range enum index

---

materialize-bigquery/transactor.go
materialize-databricks/driver.go
materialize-elasticsearch/transactor.go
materialize-mongodb/transactor.go
materialize-mysql/driver.go
materialize-postgres/driver.go
materialize-redshift/driver.go
materialize-snowflake/snowflake.go
materialize-sqlserver/driver.go
tests/materialize/fixture.json

- It is possible to have documents with `it.Delete` that have not previously existed in the destination. For hard deletions, we want to ignore these documents and avoid inserting them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/16 …

materialize-*: handle hard deletion of nonexistent docs

---

materialize-mysql/.snapshots/TestSQLGeneration
materialize-mysql/sqlgen.go

Flow supports characters from the utf8mb4 character set and we create MySQL tables explicitly with that character set. But we weren't setting that character set for LOAD DATA LOCAL INFILE queries, which results in MySQL defaulting to whatever the server default is. In cases where we may encode 4-byte characters but the server default character set is utf8mb3, that will cause errors since the input is not valid utf8mb3. This fixes that scenario by explicitly declaring the utf8mb4 character set for LOAD DATA LOCAL INFILE queries. …

materialize-mysql: specify character set for LOAD DATA LOCAL INFILE queries

---

materialize-elasticsearch/driver.go

This is a config option that is available for the ElasticSearch client that we weren't using. The hope is that this reduces our egress costs, and may help with system that have a limited acceptable payload size for certain requests.
- - - …

materialize-elasticsearch: enable compression for request bodies

---

filesource/state.go
filesource/state_test.go

Adds some additional debug log information for filesource captures when they skip files due to modification times being either too recent or too old.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1646)

filesource: log modTimes and time boundaries for skipped files

---

source-shopify/test.flow.yaml
source-shopify/tests/snapshots/source_shopify_tests_test_snapshots__capture__capture.stdout.json

stream is outputting data to snapshots in a inconsistent manner, breaking tests all the time
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1652)

source-shopify: removing inventory_items stream from tests

---

source-mysql/.snapshots/TestGeneric-SpecResponse
source-mysql/main.go
source-postgres/main.go
source-sqlserver/main.go
sqlcapture/capture.go
sqlcapture/interface.go

Adds an advanced config option allowing `source-mysql` captures to override the heartbeat write interval from its default of 60s. This is primarily useful because MySQL has a bunch of old archaic storage engines, some of which (*cough* MyISAM *cough*) don't even support transactions. And when changes are made to a table using one of these storage engines, there may not be any transaction-committing `XIDEvent` in the binlog.
But as long as the watermarks table is created with the InnoDB storage engine we are guaranteed to see a regular and reliable source of transaction commits, so things still mostly work when capturing data from tables using a non-transactional storage engine. Except...we only write watermarks every 60s by default, and it would be nice to at least bring …

source-mysql: Configurable heartbeat/watermark interval

---

source-shopify/acmeCo/custom_collections.schema.yaml
source-shopify/acmeCo/customers.schema.yaml
source-shopify/acmeCo/flow.yaml
source-shopify/acmeCo/inventory_items.schema.yaml
source-shopify/acmeCo/locations.schema.yaml
source-shopify/acmeCo/metafields.schema.yaml
source-shopify/acmeCo/order_risks.schema.yaml
source-shopify/acmeCo/orders.schema.yaml
source-shopify/acmeCo/price_rules.schema.yaml
source-shopify/acmeCo/products.schema.yaml
source-shopify/acmeCo/refunds.schema.yaml
source-shopify/acmeCo/transactions.schema.yaml
source-shopify/source_shopify/tap_shopify/schemas/abandoned_checkout.json
source-shopify/source_shopify/tap_shopify/schemas/carrier_service.json
source-shopify/source_shopify/tap_shopify/schemas/collect.json
source-shopify/source_shopify/tap_shopify/schemas/custom_collection.json
source-shopify/source_shopify/tap_shopify/schemas/customer.json
source-shopify/source_shopify/tap_shopify/schemas/discount_code.json
source-shopify/source_shopify/tap_shopify/schemas/inventory_item.json
source-shopify/source_shopify/tap_shopify/schemas/inventory_level.json
source-shopify/source_shopify/tap_shopify/schemas/location.json
source-shopify/source_shopify/tap_shopify/schemas/metafield.json
source-shopify/source_shopify/tap_shopify/schemas/order.json
source-shopify/source_shopify/tap_shopify/schemas/price_rule.json
source-shopify/source_shopify/tap_shopify/schemas/product.json
source-shopify/source_shopify/tap_shopify/schemas/refund.json
source-shopify/source_shopify/tap_shopify/schemas/risk.json
source-shopify/source_shopify/tap_shopify/schemas/transaction.json
source-shopify/source_shopify/tap_shopify/schemas/user.json
source-shopify/tests/snapshots/source_shopify_tests_test_snapshots__discover__capture.stdout.json

Correcting `source-shopify`  schemas. 
Both `source-shopify` and `source-google-ads` schemas are breaking, this PR solves all
schema related issues after the new streams were added in `source-shopify`
To evalute all changes, tests were made using a local flow instance and materializing to a Supabase DB 
**All 15 streams were captured and materialized**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1655)

source-shopify: corrected schemas & tests

---

source-airtable/acmeCo/test_base/flow.yaml
source-airtable/acmeCo/test_base/pizzas/flow.yaml
source-airtable/acmeCo/test_base/soups/flow.yaml
source-airtable/source_airtable/schema_helpers.py
source-airtable/source_airtable/source.py
source-airtable/test.flow.yaml
source-airtable/tests/conftest.py
source-airtable/tests/snapshots/snapshots__capture__capture.stdout.json
source-airtable/tests/snapshots/snapshots__discover__capture.stdout.json
source-airtable/tests/test_helpers.py

Schema is now being inferred instead of generated by a bunch of confusing properties rules. Because of that, two tests on test_helpers.py file were removed, since the expected schema would not be inferred by the airbyte schemahelper.
Also removed the table_id from all table names. It didnt play a important role, its value is already inside each doc and probably made for SQL queries to be big and "dirty"
All tests are passing on both pytest and a local flow version i ran with custom credentials
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1647)

source-airtable: Updating schema generation and table names

---

source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture1
source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture2
source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture3
source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture4
source-postgres/capture_test.go
source-postgres/prerequisites.go
source-postgres/replication.go
sqlcapture/capture.go

This PR fixes the behavior of `source-postgres` when the replication slot is deleted and then recreated, so that it will error out until the user re-backfills all bindings (the intended behavior) instead of just silently skipping an unknown amount of change data and then continuing where it left off (the behavior prior to today).
While I was at it I also threw in a change I've been meaning to get around to, which makes the automated diagnostics queries run once at capture startup. This is a good idea in general because it gives us more debugging information in certain cases where tasks are consistently failing before they reach the replication diagnostics timeout, and I went ahead and did it as part of this work because the extra logging made it easier to verify exactly …

source-postgres: Check for slot delete/recreate and error out

---

materialize-boilerplate/stream-encode/parquet.go

Somehow I neglected to test these kinds of values, and attempting to materialize them would result in an error. This is the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1676)

materialize-iceberg: handle strings with numeric formats

---

sqlcapture/capture.go

These messages were originally written before we had prerequisite validation for a lot of the basic errors, which is why the error for the watermarks table not showing up via discovery is "table doesn't exist" -- because that used to be by far the most likely reason we'd see that.
But now we already check for the basics so we should really give the wordier and more complicated but actually precise description of what's gone wrong there.
Then while I was at it I tweaked a couple of adjacent messages for consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1678)

sqlcapture: Tweak table activation error messages

---

filesink/store.go
materialize-s3-csv/.snapshots/TestSpec
materialize-s3-parquet/.snapshots/TestSpec

Adds the "secret" annotation for the `AWSSecretAccessKey` configuration that is used by `materialize-s3-csv` and `materialize-s3-parquet`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1683)

materialize-s3-*: set "secret" annotation for access key

---

materialize-sql/column_validation.go

It is fairly rare that this condition is ever hit since it means that a user manually changed the type of a target table column, but the "no column validator found" messaging is kind of obscure in that case. A better way to state it is that the connector doesn't support materializing to that type of column, so that is what it will say now.
- - -
This …

materializations: update error message for unsupported column types

---

materialize-s3-iceberg/driver.go

At least with the AWS Glue catalog (which is the only one we use right now), table identifiers are always lowercase. So if you have a resource with a table that has uppercase letters, right now we can't find that table. This fix will have use always treat table identifiers with lowercase, which should fix that problem.
- - - …

materialize-iceberg: table identifiers are always lowercase

---

source-oracle-flashback/config.yaml
source-oracle-flashback/source_oracle_flashback/__init__.py
source-oracle-flashback/source_oracle_flashback/resources.py

- RDS instances report flashback as OFF because it cannot be enabled on the whole database, but it is enabled for tables. On RDS instances we skip the flashback_on check.
- Users will still end up needing to skip Flashback checks since RDS instances usually have small undo retentions which are problematic, but at least the error is not misleading
- - - …

source-oracle-flashback: skip flashback_on check on RDS instances

---

source-mysql/database.go
source-mysql/docker-compose.yaml
source-mysql/main.go
source-mysql/main_test.go
source-mysql/prerequisites.go
source-mysql/replication.go

This PR fixes the `source-mysql` connector to support MySQL 8.4, which was released a couple of months ago. This involved a couple of trivial incompatibilities and a version bump to the CI database dockerfile, and then the main thing was that MySQL 8.4 went and fully removed the deprecated `SHOW MASTER STATUS` command.
This command was deprecated in MySQL 8.0.22 in favor of a new `SHOW BINARY LOG STATUS` which does the exact same thing. Since we want to support MySQL <8.0.22 we used the old query exclusively, but now that's no longer sufficient and there is no single query that works on all versions of MySQL. So to handle this we have to actually keep track of the database version and issue the appropriate query depending on what server we're connected to.
This was done …

source-mysql: Support for MySQL v8.4

---

source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture1
source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture2
source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture3
source-postgres/.snapshots/TestCaptureFailsAfterSlotDropped-capture4
source-postgres/capture_test.go
source-postgres/prerequisites.go
source-postgres/replication.go
sqlcapture/capture.go

This is a revert of a revert, plus a fix for the bug which required a revert. Previously merged as https://github.com/estuary/connectors/pull/1653, the goal of this PR was just to add some checking around Postgres replication slot validity so that we can provide the user with more friendly error messages when stuff goes wrong.
However, previously this failed because one of the replication slot info columns we request is `wal_status`, which turns out to have only been added in Postgres 13. We definitely do want that information if it's available, because when `wal_status = lost` we want to be able to give the user a friendly error message telling them to drop the slot and backfill everything, instead of the current error they'll see which is a significantly less friendly …

source-postgres: Additional replication slot validation, take two

---

source-oracle-flashback/source_oracle_flashback/api.py
source-oracle-flashback/source_oracle_flashback/resources.py

- Previously we would filter out schemas in code after having queried tables from all schemas. This was not the most efficient solution and would cause the error below if there were more than 1000 schemas (even if they specified advanced.schemas config):
```
ORA-01795: maximum number of expressions in a list is 1000
```
- A customer actually hit this error, which was due to the filtering we do in `fetch_columns` on schemas.
- Move the filtering logic to the `fetch_tables` query so that subsequently `fetch_columns` will also only filter on the limited schemas
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZN …

source-oracle-flashback: filter out schemas at query time

---

source-klaviyo/acmeCo/events.schema.yaml
source-klaviyo/source_klaviyo/schemas/events.json
source-klaviyo/source_klaviyo/streams.py
source-klaviyo/tests/snapshots/source_klaviyo_tests_test_snapshots__discover__capture.stdout.json

event_name field was set to be created with a None/NULL value. Instead, it should've been created only with a string value, and if requirements to create it are not met, it should not be created at all. This commit fixes that, along with updating tests and schema.
Tested using flowctl and a local flow setup with a supabase DB as destination.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1695)

source-klaviyo: fixing event_name field

---

materialize-elasticsearch/transactor.go

Adding some logging to aid in troubleshooting when this unexpected condition happens.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1700)

materialize-elasticsearch: log received document when there are no source fields

---

source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture1
source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture2
source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture3
source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture4
source-postgres/capture_test.go
source-postgres/database.go
source-postgres/replication.go

This is a more cautious attempt to get out the replication slot LSN checking.
The check was previously merged in https://github.com/estuary/connectors/pull/1653, then reverted because of a query failure on older database versions in which replication slots don't have a `wal_status` column. This was fixed and the check was merged again in https://github.com/estuary/connectors/pull/1679, which was then reverted because we saw failures in production which suggested that there might be something wrong with our assumption that the connector's restart checkpoint LSN would always be greater than or equal to the latest LSN confirmed with the database.
So this time we're taking it even slower. This PR adds the same `queryReplicationSlotInfo` helper function, a test case covering …

source-postgres: Replication slot validation, take three

---

source-mongodb/.snapshots/TestDiscover
source-mongodb/.snapshots/TestDiscoverAllDatabases
source-mongodb/.snapshots/TestDiscoverMultipleDatabases
source-mongodb/change_stream.go
source-mongodb/discovery.go
source-mongodb/pull.go

Recent versions of MongoDB make pre-images for update, replace, and delete events available if the MongoDB collections are configured for it. This is useful to capture if it is there, so we will capture these pre-images if they are available.
We'll probably need to implement support for splitting large events at some point, so we will only request these pre-images on versions of MongoDB that support `$changeStreamSplitLargeEvent`. I think we are safe to not do that right now, since it will be fairly complicated and it is not common for documents to be that large - and if there are hopefully they don't have pre-images enabled on their collections.
The existing unit and integration tests confirm the connector output is identical after this change for collections that don't …

source-mongodb: request pre-images for change events if available

---

source-shopify/acmeCo/orders.schema.yaml
source-shopify/source_shopify/tap_shopify/client.py
source-shopify/source_shopify/tap_shopify/schemas/order.json
source-shopify/source_shopify/tap_shopify/streams.py
source-shopify/source_shopify/tap_shopify/tap.py
source-shopify/tests/snapshots/source_shopify_tests_test_snapshots__capture__capture.stdout.json
source-shopify/tests/snapshots/source_shopify_tests_test_snapshots__discover__capture.stdout.json
source-shopify/tests/snapshots/source_shopify_tests_test_snapshots__spec__capture.stdout.json

"Orders" stream takes a long time to sync and ofter breaks. Because of that its state would be written and trigger the incremental step in the capture, instead of finishing backfill. Now that the stream is ordered and the incremental step was limited, the connector will only enter its "incremental" step after synced the whole stream since start_date
Tested using a local flow setup, with materialization to a supabase DB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1714)

source-shopify: ordering "Orders" stream and substreams

---

materialize-snowflake/pipe.go

- Add requestId to error logs of pipe
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1716)

materialize-snowflake: log requestId when pipe requests fail

---

source-klaviyo/acmeCo/events.schema.yaml
source-klaviyo/source_klaviyo/schemas/events.json
source-klaviyo/source_klaviyo/streams.py
source-klaviyo/tests/snapshots/source_klaviyo_tests_test_snapshots__discover__capture.stdout.json

Removing `event_name` Field
Updated `campaign_id` Field extraction. Now its extracted from "event_properties", instead of the  included query result.
Tested with a local flow instance, materialized to a Supabase DB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1718)

source-klaviyo: updating campaign_id extraction

---

materialize-snowflake/.snapshots/TestConfigURI-Optional_Parameters
materialize-snowflake/.snapshots/TestConfigURI-v1_User_&_Password_Authentication
materialize-snowflake/.snapshots/TestConfigURI-v2_User_&_Password_Authentication
materialize-snowflake/.snapshots/TestSpecification
materialize-snowflake/client.go
materialize-snowflake/config.go
materialize-snowflake/config_test.go
materialize-snowflake/pipe.go
materialize-snowflake/snowflake.go
materialize-snowflake/snowflake_test.go

Snowflake does not require an `account` query parameter in the connection string, so this change makes the `account` input optional. The `go-snowflake` driver's `sf.DSN` method for building the connection string can error out when `account` isn't provided, so instead we build the connection string ourselves.
The [Snowflake materialization docs](https://github.com/estuary/flow/blob/master/site/docs/reference/Connectors/materialization-connectors/Snowflake.md) will need updated to reflect that `account` is not required.
Tested locally with:
- both password & JWT authentication.
- both flavors of Snowflake `host` URL formats 
- …

materialize-snowflake: make account field optional

---

materialize-elasticsearch/client.go

Rather than always create the meta index with 1 shard, create it with the server default number of shards by leaving the "shards" parameter unspecified.
We might not really need more than 1 shard for this index, but there are near-term plans to not create the meta index at all and instead use the "last spec" available in Validate and Apply requests. This change should also allow our connector to work with serverless Elasticsearch, which does not allow setting the number of shards or replicas for indices.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing …

materialize-elasticsearch: create the meta index with the server default number of shards

---

materialize-elasticsearch/client.go
materialize-elasticsearch/driver.go
materialize-elasticsearch/transactor.go

This option isn't supported when connecting to serverless clusters (they don't have shards), so we need to detect when we are connecting to a serverless cluster and not set it if we are.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors …

materialize-elasticsearch: don't waitForActiveShards when connecting to serverless clusters

---

source-postgres/replication.go

I'm making an educated guess that this is responsible for a user's capture OOMing, and I suspect that 16k is much too large anyway.
As we know from queuing theory, in the steady state a buffer is always either empty or full. And I have a strong suspicion that this buffer is basically always emptyish in most production capture tasks and the only purpose it actually serves is helping smooth out the work passing so that both the replication thread and the main capture serialization thread can keep busy.
Based on that intuition, I figure that 16 should actually be plenty to keep the threads from blocking on each other most of the time, while being much less likely to cause OOMing if it does fill up temporarily.
- - - …

source-postgres: Lower replication buffer from 16k to 16

---

source-postgres/replication.go

Followup to https://github.com/estuary/connectors/pull/1735
Just to make absolutely sure that this buffer isn't the issue here. If this doesn't fix the OOMs we're seeing in production, we should revert it and figure out what else is going wrong.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1737)

source-postgres: Try lowering replication buffer size to one event

---

source-postgres/replication.go

Reverts estuary/connectors#1737
That PR was always meant to be a short-lived test if it didn't work. And it didn't work, so back up to 16 we go!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1738)

Revert "source-postgres: Try lowering replication buffer size to one event"

---

source-mysql/.snapshots/TestSecondaryIndexDiscovery-index_and_fk
source-mysql/discovery.go
source-mysql/discovery_test.go

Previously the secondary-index discovery query had a bug in its join against `information_schema.table_constraints` which would crop up if there were multiple constraints on the same table, with the same constraint name, but different constraint types. For instance, a `UNIQUE` constraint and a `FOREIGN KEY` one.
But after rereading the relevant discovery query I'm not sure why we're even looking at that table in the first place. All we used that join for was a `tco.constraint_type != 'PRIMARY KEY'` filter clause, but as we can see in the primary-key discovery query we can also just check whether `stat.index_name = 'PRIMARY'` so the join should be entirely unnecessary.
This commit also adds a subtest to `TestSecondaryIndexDiscovery` which reproduces the scenario that …

source-mysql: Simplify secondary index discovery

---

source-mysql/.snapshots/TestPartialRowImages-delete
source-mysql/.snapshots/TestPartialRowImages-init
source-mysql/.snapshots/TestPartialRowImages-main
source-mysql/capture_test.go
source-mysql/replication.go

Makes partial row images work correctly by omitting the unspecified columns from the resulting change document rather than filling them out with implicit nulls.
Also adds a test verifying the correct behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1736)

source-mysql: Support partial row images properly

---

.github/workflows/ci.yaml
materialize-s3-iceberg/driver.go
materialize-s3-iceberg/driver_test.go
materialize-s3-iceberg/glue.go
materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
tests/materialize/materialize-s3-iceberg/checks.sh
tests/materialize/materialize-s3-iceberg/cleanup.sh
tests/materialize/materialize-s3-iceberg/config.yaml
tests/materialize/materialize-s3-iceberg/fetch.sh
tests/materialize/materialize-s3-iceberg/setup.sh
tests/materialize/materialize-s3-iceberg/snapshot.json

For efficiency, we will only list tables that are included in the list of resources for the materialization. For the purposes of computing apply actions and validation constraints, we don't care about tables other than these, and attempting to list their information can really slow things down if there are a lot of non-related pre-existing namespaces and tables.
This will also take care of problems with pre-existing tables in the user's system that are not iceberg format where we don't care about them for calculating constraints or doing table modifications.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZN …

materialize-s3-iceberg: filter out irrelevant tables from info schema 

---

source-hubspot-native/source_hubspot_native/api.py
source-hubspot-native/source_hubspot_native/resources.py
source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json

Closes https://github.com/estuary/connectors/issues/1724
The main change here is adding the ability for the `deals` and `companies` bindings to fall back to using the [HubSpot search API](https://developers.hubspot.com/docs/api/crm/search) when there are more than 10,000 changed records to fetch. The "legacy" APIs we use for listing changes of these objects do not let you page back further than 10,000 items, so this is necessary to avoid needing to completely re-backfill the binding.
One assumption here is that by using the legacy API to get the ~10,000 records that we can, we won't run into issues with the Search API returning bogus results for very "recent" data, as it is known to do. For example, if a source HubSpot account has 20,000 updates to `deals` all right about …

source-hubspot-native: search API fallback for certain bindings

---

materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
materialize-s3-iceberg/transactor.go

Trivial logging addition to assist in troubleshooting failures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1752)

materialize-iceberg: log the values for "previous" and "next" checkpoints when appending files

---

source-postgres/.snapshots/TestGeneric-SpecResponse
source-postgres/backfill.go
source-postgres/main.go

This is completely untested except to make sure it doesn't break anything else in our automated test suite, but the XMIN filtering logic is taken from our batch Postgres connector and this is a pretty straightforward bit of plumbing directly from the advanced connector config into the relevant backfill query generation, so it'll either work or it won't.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1753)

source-postgres: Add 'MinimumBackfillXID' advanced option

---

source-mongodb/.snapshots/TestCaptureSplitLargeDocuments
source-mongodb/change_stream.go
source-mongodb/main_test.go

For deployments that support splitting large change stream event documents, include that pipeline stage and handle the resulting fragments.
It is possible for a change stream event document to exceed the standard 16MiB limit when it includes a pre-image and is an update to a very large document, which can sometimes happen.
- - - …

source-mongodb: split large change stream event documents

---

source-postgres/datatype_test.go
source-postgres/datatypes.go

The package upgrade to PGX v5 caused a lot of churn around how we translate various datatypes, and the array handling had to be rewritten entirely. Looks like I missed an edge case because the dimensions list is serialized as `null` when it should be `[]` for an empty array coming from the DB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1759)

source-postgres: Fix empty array serialization after PGX v5

---

source-mongodb/.snapshots/TestCaptureSplitLargeDocuments
source-mongodb/change_stream.go
source-mongodb/main_test.go
source-mongodb/pull.go

This is a modification to the way we check for pre-image support, and a re-application of the commit https://github.com/estuary/connectors/commit/5f66809a67e39f53a73030069fd081e4382f3e5a where the `$changeStreamSplitLargeEvent` pipeline stage was added.
The problem from that initial attempt was that the split event pipeline stage is not supported on somewhat-commonly used versions of MongoDB Atlas. Unfortunately there's no way to know if we are connected to one of those or not without just trying to create a change stream with that pipeline stage enabled.
The first commit here updates the check for pre-image support (which by extension is checking for support of `$changeStreamSplitLargeEvent`) to verify that the split event stage works by trying to create a change stream …

source-mongodb: split large change stream event documents v2

---

materialize-postgres/driver.go

For both the load and store connections, run a `set statement_timeout = 0;` statement to prevent our statements from timing out if a different default timeout is set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1764)

materialize-postgres: override statement_timeout to never timeout

---

source-postgres/datatype_test.go
source-postgres/datatypes.go

This was broken in the PGX v5 upgrade and not caught because we didn't have a test case for `NaN` values in `NUMERIC` columns.
This commit adds such a test and fixes the translation logic so that it works correctly. I'm not entirely sure why I went with such a convoluted mechanism for producing a numeric string before when it turns out that `x.Value()` works exactly as we'd want, but whatever.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1763)

source-postgres: Fix `NaN` value of `NUMERIC` column

---

source-http-ingest/Cargo.lock
source-http-ingest/Cargo.toml
source-http-ingest/Dockerfile

Updates the swagger-ui and related dependencies to the latest versions. Also updates the `time` dependency to be compatible with rust 1.80, and updates rust to 1.80.
No user-facing changes here. The swagger UI looks and functions essentially the same.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1762)

source-http-ingest: update swagger dependency

---

materialize-boilerplate/stream-encode/parquet.go

Fields of `type: number` that contain values without any fractional part may be encoded as FDB integers, and those need to be cast to float64 for writing them to parquet DOUBLE columns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/ …

materialize-parquet: handle number types encoded as integers

---

materialize-s3-iceberg/glue.go

Don't run the alter table `iceberg-ctl` command if there are no new columns or nullability constraints to drop, since those are the only table alternations currently supported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1772)

materialize-s3-iceberg: don't run table alter command if there are no alterations

---

source-mysql/replication.go

When they're used, `SAVEPOINT` query events tend to be absurdly spammy so we definitely don't want to be logging them at `INFO` level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1774)

source-mysql: Silently ignore `SAVEPOINT` queries

---

source-postgres/replication.go
sqlcapture/capture.go

Hopefully this will be enough to show us what, if anything, is going wrong in rare cases to cause the 'confirmed_flush_lsn is greater than resume LSN' warning to fire.
The most important thing here is the introduction of a new INFO level debug message which will output the confirmed LSN immediately before we send it to the server in a "Standby Status Update", if it's different from the previous update. Since we send these updates every 10 seconds this could be moderately spammy, producing up to 6 log messages each minute where previously our steady-state streaming behavior was to emit 2 log messages each minute, a 4x increase. But I think it's worth doing that temporarily across the board so we can actually be 100% certain, the next time we see that warning trigger, …

source-postgres: LSN commit logging tweaks

---

.github/workflows/ci.yaml
source-sqlserver/README.md
source-sqlserver/docker-initdb.sh
tests/source-sqlserver/cleanup.sh
tests/source-sqlserver/setup.sh

Apparently in late July, Microsoft pushed an update to the `2022-latest` Docker image we use for SQL Server in CI builds. (I didn't notice this locally because how often does one run a `docker pull` for a relatively stable test dependency, but for the past couple of weeks all SQL Server CI builds were failing.)
The update contained two notable changes:
- The directory `/opt/mssql-tools` which contains the `sqlcmd` binary was renamed to `/opt/mssql-tools18`
- The `sqlcmd` binary was upgraded and the new version defaults to stricter certificate validation that a self-hosted server in a CI build fails.
The fix was very simple, just changing the path to the binary and adding a `-C` flag which means "trust the server certificate". I'm also leaving in place a couple of the …

source-sqlserver: Fix CI builds consistently failing

---

source-postgres/database.go
source-postgres/replication.go

One easily-overlooked way that one might end up with a task's restart LSN being less than the slot's confirmed flush LSN is if there are multiple captures from the same database trying to use the same replication slot.
We should at least try to avoid giving a misleading "the slot was probably dropped and recreated" message in this case, which can be done by checking whether the slot is already active before we've started replication.
Note that this isn't bulletproof, since it's possible for the other of the two misconfigured captures to be momentarily offline when we're doing this check, but it's still better than nothing.
- - - …

source-postgres: Add check for active replication slot

---

source-notion/source_notion/spec.json
source-notion/tests/snapshots/snapshots__spec__capture.stdout.json

Removes the "pattern_descriptor" property from the configuration, since I don't believe it was actually doing something and seems to have recently cause the endpoint config to fail to work with config encryption for unknown reasons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1784)

source-notion: remove pattern_descriptor from config

---

materialize-s3-iceberg/driver.go
materialize-s3-iceberg/glue.go
materialize-s3-iceberg/type_mapping.go

Adds the ignoreStringFormat field configuration which when set will materialize string fields as regular strings, disregarding any format annotation they might have.
Manually tested by first materializing a collection without the field config set and seeing the column as a timestamptz, then adding the field configuration which causes an unsatisfiable constraint. Increasing the backfill counter allows the materialization to proceed by re-creating the table with a string type for the column, and string values are added to the column
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that …

materialize-s3-iceberg: add ignoreStringFormat field configuration

---

source-zendesk-support/source_zendesk_support/streams.py
source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json
source-zendesk-support/tests/unit_test.py

`tickets` and `users` streams were previously using incremental timestamp-based pagination, resulting in duplicated data. It was also possible for the connector to get stuck making the same request if 1,000+ documents were modified at the same time. By moving to [incremental cursor pagination](https://developer.zendesk.com/documentation/ticketing/managing-tickets/using-the-incremental-export-api/#cursor-based-incremental-exports), these issues are resolved.
The `test_check_stream_state` unit test is no longer applicable, since the `cursorField` is not longer within each document. The `cursorField` is instead only in the response body, and the `IncrementalMixin`'s `state` setters and getters are used to checkpoint cursors between requests. The …

source-zendesk-support: Fix pagination issues with `tickets` and `users` streams

---

materialize-bigquery/transactor.go

If hard deletions are enabled it is possible that a transaction will contain only a single record for a document that is being deleted and doesn't already exist. In this case we won't write any data to the staged file or table.
This scenario uniquely impacts materialize-bigquery, since BigQuery requires there to actually be at least one file present when doing the equivalent of `SELECT * FROM gs://bucket/*.json`, and the rare case of a binding with only deletion of non-existent keys with hard deletions enabled will result in there not being any data to load.
There is likely a more principled way to accomplish this fix, but moving the "starting" of the staged file down a few lines gets it done quickly and easily, and in a way that is assured to not cause any other …

materialize-bigquery: don't start the staged file unless there is data to write to it

---

materialize-bigquery/bigquery.go
materialize-bigquery/bigquery_test.go
materialize-bigquery/client.go
materialize-databricks/client.go
materialize-databricks/driver.go
materialize-motherduck/client.go
materialize-motherduck/driver.go
materialize-motherduck/driver_test.go
materialize-mysql/client.go
materialize-mysql/driver.go
materialize-mysql/driver_test.go
materialize-postgres/client.go
materialize-postgres/driver.go
materialize-postgres/driver_test.go
materialize-redshift/client.go
materialize-redshift/driver.go
materialize-redshift/driver_test.go
materialize-snowflake/client.go
materialize-snowflake/snowflake.go
materialize-snowflake/snowflake_test.go
materialize-sql/driver.go
materialize-sql/endpoint.go
materialize-sqlite/sqlite.go
materialize-sqlserver/client.go
materialize-sqlserver/driver.go
materialize-sqlserver/driver_test.go
materialize-starburst/client.go
materialize-starburst/starburst.go
tests/materialize/materialize-databricks/config.yaml

Many SQL materializations have come to need to run queries or otherwise interact with the destination system as part of their endpoint initialization. This effectively bypasses the pre-requisite checking that is currently implemented in the `Client.Prereqs` method, and can result in confusing and misleading raw error messages if the connector is misconfigured.
The fix here is to make the prereqs checking a separate function that is called prior to creating the endpoint. This implementation tends toward a quick-and-dirty fix, and a more satisfying code structuring would probably involve a much larger refactoring that would incorporate generics. But I'm holding off on doing that for now to get the better error messages working again ASAP.
(How does one …

materialize-sql: run preReqs check before endpoint initialization

---

source-zendesk-support/acmeCo/ticket_audits.schema.yaml
source-zendesk-support/source_zendesk_support/schemas/ticket_audits.json
source-zendesk-support/source_zendesk_support/streams.py
source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json
source-zendesk-support/tests/unit_test.py

Schema violations were occurring because the `value` in a `ticket_audits` document could be an integer. Also, `ticket_audits` were taking a significant amount of time to complete reading documents. This is because the API endpoint does not support filtering results by a start date, so we were reading all documents available. To fix this, logic to filter client-side has been added for the `ticket_audits` stream
No documentation updates needed.
Tested on a local stack with a non-trivial amount of documents. Ensured the document that previously caused a schema violation no longer causes an issue. Confirmed pagination works, and stream still …

source-zendesk-support: fix `ticket_audits` schema and pagination

---

source-zendesk-support/source_zendesk_support/streams.py

Very rarely, we get boolean values in a `TicketSkips` stream's custom field values. This change coerces those bools to strings, when present. Using the `parse_response` method for this purpose is similar to its use in other streams, like `TicketComments`.
No documentation updates needed.
Tested on a local stack. Confirmed that boolean values `True` and `False` are changed to strings & that when the value is not a boolean it's left unchanged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1802)

source-zendesk-support: handle bools in `ticket_skips` documents

---

materialize-bigquery/bigquery.go
materialize-databricks/driver.go
materialize-motherduck/driver.go
materialize-mysql/driver.go
materialize-postgres/driver.go
materialize-redshift/driver.go
materialize-snowflake/snowflake.go
materialize-sql/driver.go
materialize-sqlite/sqlite.go
materialize-sqlserver/driver.go
materialize-starburst/starburst.go
tests/materialize/materialize-elasticsearch/snapshot.json
tests/materialize/materialize-google-sheets/snapshot.json
tests/materialize/materialize-snowflake/snapshot.json

5183d03 changed the pre-requisite checks to run prior to initializing the `sql.Endpoint` struct, but that causes problems if there is a network tunnel configured since the network tunnel was only started as part of creating that struct.
This creates a separate `StartTunnel` function that is a property of `sql.Driver` which must be called before the database can be interacted with, which is taken care of by the materialize-sql framework before it runs Validate, Apply, or Open.
We've accumulated quite a lot of tech debt around this whole setup process and I'd like to refactor it more comprehensively soon. Right now this should work though, although I'm not very happy with how things currently have to be structured.
(How does one use this feature, and how …

materialize-sql: start network tunneling prior to checking pre-reqs

---

source-zendesk-support/source_zendesk_support/streams.py
source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/unit_test.py

Zendesk's API allows the use of both offset pagination and cursor pagination to get documents. Previously, we were using offset pagination, which is limited to only getting the first 100 pages of documents. Cursor pagination does not have this limit, so all streams using offset pagination have been changed to use cursor pagination.
Since many streams inherit from common classes, some logic was pushed down the inheritance chain to streams that don't use cursor pagination.
Additionally, the `TicketAudits` stream was previously retrieving all pages of documents. This has been changed to only get pages containing documents after the start date/last seen date.
No …

source-zendesk-support: change streams to cursor pagination

---

source-zendesk-support/source_zendesk_support/schemas/posts.json
source-zendesk-support/test.flow.yaml
source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json
source-zendesk-support/tests/test_snapshots.py

Zendesk automatically archives some data, which alters the capture snapshot even though nothing in the connector has changed. Redacting these fields makes the capture snapshot test a little more robust. Some other fields may need redacted in the future if we find they're changing too, but this should be a good start.
Additionally, the posts schema was made more permissive due to schema violations we've encountered.
No documentation updates needed.
- - - …

source-zendesk-support: redact fields in capture snapshot

---

source-postgres/.snapshots/TestDiscoveryComplex
source-postgres/.snapshots/TestGeneric-KeylessDiscovery
source-postgres/.snapshots/TestGeneric-SimpleDiscovery
source-postgres/datatype_test.go
source-postgres/datatypes.go
source-postgres/discovery.go

Adds support for NaN (and Infinity and -Infinity) values in float4/float8 columns. Previously these didn't work because we serialize them as JSON numbers and there's no legal JSON representation of a floating-point NaN or infinity. Now we stringify just those three special values, which required also updating the discovery output for those column types to `{type: [string, number], format: number}` but I am assured that our materializations should handle that correctly so it should basically be a no-op for any dataflows that don't encounter NaNs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1812)

source-postgres: Support NaN values in float4/float8 columns

---

sqlcapture/capture.go

Currently if the context passed to 'streamToWatermarkWithOptions' is cancelled but the events channel doesn't close, the connector will continue to wait for a watermark which may never arrive.
Most of the time when the context is cancelled it's at the top level of the capture so this doesn't come up, but the indefinite streaming state is currently modelled as a process of running the change streaming process in a worker thread with a second thread which will wait for a reasonable period of time and then write the watermark.
The problem is, if this watermark write fails we want the work context cancellation to cause the stream-until-watermark thread to also shut down, and as currently written it doesn't.
- - - …

sqlcapture: Handle context cancellation during change streaming

---

estuary-cdk/estuary_cdk/shim_airbyte_cdk.py

The new `source-pendo` connector was failing with schema violations - the documents didn't have a `row_id` in the `_meta` property. However, they did have a `meta_` property with a `row_id`. This fix puts `row_id` in the documents' `_meta` property.
- - - …

estuary-cdk: Fix adding `op` and `row_id` to the `meta_` property.

---

source-mysql/replication.go

We use the Vitess SQL parser to parse MySQL query events so that we can apply DDL changes to our table metadata tracking. But the Vitess SQL parser is a reimplementation of the MySQL grammar and it can be a bit spotty in its support for various edge cases.
But in practice, we don't care about those edge cases. The things we care about are basic `ALTER / DROP / TRUNCATE / RENAME` table operations which are pretty well supported, and the failures are all in the long tail of niche statements we'd like to ignore anyway.
We've been treating parse failures as a fatal error for some time now (I want to say it's been over a year?) and as far as I can recall this has never caught a legitimate issue, instead it just makes the capture more flaky than it needs to be.
So given the …

source-mysql: Ignore unparseable query events

---

source-zendesk-support/config.yaml
source-zendesk-support/source_zendesk_support/__main__.py
source-zendesk-support/source_zendesk_support/spec.json
source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/snapshots/snapshots__spec__capture.stdout.json

The imported `source-zendesk-support` connector's OAuth did not work. The OAuth code in `__main__.py` was updated to work with the OAuth app created in our Zendesk testing account.
I also changed the subdomain of our testing account to "d3v-estuary" since it might be viewable if someone inspects HTTP requests during the OAuth process., Although the subdomain change is reflected in the capture snapshot, I don't anticipate we will need to change this again, so the affected snapshotted properties don't need redacted.
When creating a Zendesk Support capture, enter the subdomain, then click the OAuth button. Follow the prompts to login to your Zendesk account, then allow Estuary access.
Docs will need updated - …

source-zendesk-support: fix oauth

---

source-oracle/Dockerfile
source-oracle/capture_test.go
source-oracle/discovery.go
source-oracle/prerequisites.go

- RDS instances require a different command to enable supplemental logging
- Log warning for unsupported data types but allow discovery (same logic as flashback)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1839)

source-oracle: better message for supplemental logging

---

source-oracle/discovery.go

- Filter out problematic schemas from table discovery
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1840)

source-oracle: filter out RDS_ADMIN and GGS_ADMIN from discovery

---

source-mysql/backfill.go
source-mysql/discovery.go
source-mysql/main.go
source-mysql/prerequisites.go
source-mysql/replication.go
source-oracle/main.go
source-postgres/backfill.go
source-postgres/capture_test.go
source-postgres/prerequisites.go
source-postgres/replication.go
source-sqlserver/backfill.go
source-sqlserver/collation_test.go
source-sqlserver/prerequisites.go
sqlcapture/capture.go
sqlcapture/discovery.go
sqlcapture/tests/tests.go

I'm about to take a stab at a fairly large refactor around how watermarking works, so it seemed prudent to make sure that the connectors in question were lint-clean beforehand.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1836)

sql captures: Fix `staticcheck` lint complaints

---

source-postgres/replication.go

The big SQL Server CDC overhaul which was merged recently fixed a missing error return path when the Acknowledge method fails, but apparently it had always been returning an error the very first time for a Postgres capture because the first checkpoint a Postgres capture emits after being started up with all-new bindings has an empty cursor string on purpose.
This fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1838)

source-postgres: Fix minor bug in acknowledgement handling

---

source-oracle/.snapshots/TestAllTypes-discover
source-oracle/.snapshots/TestCapitalizedTables-Discover
source-oracle/.snapshots/TestGeneric-KeylessDiscovery
source-oracle/.snapshots/TestGeneric-MissingTable
source-oracle/.snapshots/TestGeneric-SimpleDiscovery
source-oracle/.snapshots/TestNullValues-discover
source-oracle/.snapshots/TestStringKey-discover
source-oracle/.snapshots/TestTrickyColumnNames-discover
source-oracle/discovery.go
source-oracle/main.go

Fixes a couple of minor issues discovered when I tried running the test suite for myself. Other than some snapshot updates the actual changes are fixing the 'Skip Backfills' logic to use case-insensitive table name comparison and fixing the stringification of the discovered Oracle column type struct so the "include source type info in discovered schemas" feature produces nice readable descriptions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1837)

source-oracle: Minor cleanups

---

source-oracle/main.go

In https://github.com/estuary/connectors/pull/1836 I changed the name of the `isRDS()` method to be capitalized `IsRDS()` so that the linter wouldn't complain that it wasn't currently used (since the connector is still new and I suspected it was probably meant to be used soon).
Unfortunately it looks like the change which added a use of that method landed concurrently with my "make the linter happy" PR, so now the build is failing because of the mismatch and there's no longer any actual reason to capitalize it. Whoops.
So this is just a trivial fix to undo that one character diff.

source-oracle: Undo capitalization tweak

---

materialize-bigquery/sqlgen.go
materialize-databricks/sqlgen.go
materialize-motherduck/sqlgen.go
materialize-mysql/sqlgen.go
materialize-postgres/sqlgen.go
materialize-redshift/sqlgen.go
materialize-sql/element_converter.go
materialize-sql/element_converter_test.go
materialize-sqlserver/sqlgen.go

This removes the CheckedInt64 converter, the only purpose of which was to evaluate if a value would fit into a signed 64-bit integer column, and produce a nice error message if it didn't.
It was flawed because it did not account for values transmitted as floats when they are small and have no fractional component.
I may revisit this in the future. For now this just takes out the check.
(anything that …

materialize-sql: remove CheckedInt64 converter

---

source-oracle/.snapshots/TestUnsupportedTypes-backfill
source-oracle/.snapshots/TestUnsupportedTypes-discover
source-oracle/.snapshots/TestUnsupportedTypes-replication
source-oracle/capture_test.go
source-oracle/decode.go
source-oracle/discovery.go
source-oracle/replication.go

- the first run will not be able to find any archive logs with dictionaries, so it will yield NULL for `MAX(NEXT_CHANGE#) from V$ARCHIVELOG`. In these instances we just find the first log file that contains the SCN range we are looking for.
- SCNs are actually 48 bit in size, so we should store them in int64s, updated that
- Turns out if there is an `ANYDATA` column in a table, the logminer query will use a table alias (presumable to use another alias for the anydata in case its properties need to be updated). As I wrote a test for unsupported data types, also found this issue, which is now resolved by parsing the left hand side of comparison expressions in `WHERE` statements as `sqlparser.ColName` and using the column name without its alias qualification.
- Also remove …

source-oracle: fix first run on redo log files with no dictionary

---

source-pendo/source_pendo/manifest.yaml
source-pendo/tests/snapshots/snapshots__discover__capture.stdout.json

`source-pendo` uses version 4.4.2 of the AirbyteCDK, and a warning is logged in this version by the [`_filter_schema_invalid_properties` method](https://github.com/airbytehq/airbyte/blob/59d0cb6c5375abd7fd6dc17876764cca5cf199c7/airbyte-cdk/python/airbyte_cdk/sources/streams/core.py#L634-L636) when a property exists on a document that isn't specified in the schema. The `_meta` property we add was causing this warning to be logged, and adding `_meta` to each stream's schema within `manifest.yaml` prevents the warning from being logged.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) …

source-pendo: address logged warning

---

materialize-databricks/sqlgen.go
materialize-sql/type_mapping.go

Although this would appear to be a backward compatible transition, the explicit
casting to `NUMERIC(38,0)` that is done in Store queries does not work with
pre-existing `LONG` columns.
Any materializations with pre-existing `LONG` columns for `type: string, format:
integer` fields will need the `LONG` DDL field configuration to be upgraded.
There are a few more of these than I wanted to deal with manually but it
shouldn't be _that_ bad, and it will set us up better for the future. …

materialize-databricks: do not validate string integers as LONG columns

---

source-zendesk-support/source_zendesk_support/spec.json
source-zendesk-support/tests/snapshots/snapshots__spec__capture.stdout.json

The description of the `ignore_pagination` checkbox in the UI was confusing at best. It was not clear whether leaving it unchecked or checked causes streams to read a single page on each sweep and be significantly slower.
The description shown on the UI has been updated to more clearly state that checking the box makes the connector read a single page per sweep. …

source-zendesk-support: clarify functionality of ignore_pagination

---

source-mixpanel-native/source_mixpanel_native/schemas/export.json
source-mixpanel-native/source_mixpanel_native/streams/export.py
source-mixpanel-native/tests/snapshots/source_mixpanel_native_tests_test_snapshots__discover__capture.stdout.json

Correcting the primary key for the `export` stream to be `insert_id`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1877)

source-mixpanel-native: change export stream primary key

---

source-mixpanel-native/source_mixpanel_native/streams/base.py
source-mixpanel-native/source_mixpanel_native/streams/export.py

source-mixpanel-native: Remove state checkpoint property for `export`

---

materialize-databricks/driver.go
tests/materialize/materialize-databricks/snapshot.json

- Tested by running integration tests, and by reducing the staged file size threshold and running a task with that configuration. With 128 files per merge query, the length of the query string itself is small enough to fit databricks limits, but it means we may process up to ~16GB of data in a single query, which I also think should be okay.
- I didn't apply the same batching on load queries, since for load queries, if we consider each ID to be 36 bytes (that's a uuid, I think this is one of the larger common key types, whereas most keys will be ~8 bytes as int64 or similar), we  can fit ~3M ids in a single staged file for load phase, and before we hit 128 files to batch up the query, we will have ~477M ids in those 128 files.
(How does one use this …

materialize-databricks: batch merge queries into smaller sections

---

source-zendesk-support/source_zendesk_support/streams.py
source-zendesk-support/test.flow.yaml
source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json
source-zendesk-support/tests/unit_test.py

Tasks have had issues with `ticket_metrics` and `ticket_metric_events` taking a very long time to backfill. Fixes are detailed below.
The endpoint we were using before wasn't appropriate for capturing changes to ticket metrics; it was returning metrics in descending order of when the associated ticket was created, _not_ when the ticket was updated. 
To fix this, the stream was changed to use the same incremental logic & endpoint as the `tickets` stream, and sideload in the metrics for each ticket. This gives us all the benefits of the recent `tickets` improvements (emitting state every 1k documents, good cursor-based incremental sync).
This stream functions correctly & behaves incrementally, but it's extremely dense and takes a long time to complete the initial backfill. …

source-zendesk-support: fix `ticket_metrics` and `ticket_metric_events`

---

tests/run.sh

~~Most captures already test discovery as part of their unit testing, and
`flowctl-go` doesn't work for this anymore. `flowctl raw discover` doesn't work
quite the same way and I couldn't come up with a very satisfying way to replace
it with that.~~
~~Eventually we should rework these tests to use `flowctl preview` along with
`flowctl raw discover`. I've made a couple of attempts at that and have found it
to be more of an effort that I want to take on right now, so this does the
simple thing and just disables the non-working `flowctl-go api discover`.~~
Edit: Actually ended up getting this working with `flowctl raw discover`; see updated commit description.
(list …

tests: use flowctl raw discover instead of flowctl-go in capture tests

---

source-postgres/.snapshots/TestScanKeyTypes-MAC6
source-postgres/.snapshots/TestScanKeyTypes-MAC8
source-postgres/datatype_test.go
source-postgres/datatypes.go
source-postgres/main.go

Previously MAC addresses as primary keys didn't work. Or possibly this was broken as part of the PGX v5 upgrade and we didn't notice because we didn't have a test case for MAC address PKs.
Either way, this PR adds a couple of test cases and the necessary FDB key serialization special case to make them work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1899)

source-postgres: Suport MAC addresses as primary keys

---

sqlcapture/main.go

And deletes the previous one now that it's taken effect on the intended capture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1904)

sqlcapture: Two more production cursor replacements

---

sqlcapture/main.go

Added in https://github.com/estuary/connectors/pull/1904, these have had their intended effect in production and it's good practice to clean them up immediately now that they're no longer needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1905)

sqlcapture: Remove cursor replacements

---

source-mysql/replication.go
sqlcapture/capture.go
sqlcapture/interface.go

This introduces a new replication event type `KeepaliveEvent` which is effectively a no-op which non-change non-commit WAL events can be translated to, and modifies the MySQL replication logic to use that when filtering out changes from non-captured tables.
In theory I could have kept this entirely within the MySQL code, but I've elected to make it part of the generic machinery since we'll need something very similar if/when we implement read-only replica support for Postgres or SQL Server, and also because in connectors which send a `KeepaliveEvent` this finally resolves the annoying thing where the `processed replication events` logging only counted changes from active bindings.
This is likely to fix https://github.com/estuary/connectors/issues/1909 (if my theory about …

source-mysql: Send a 'Keepalive Event' for inactive table changes

---

materialize-s3-iceberg/catalog.go
materialize-s3-iceberg/driver.go
materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
materialize-s3-iceberg/icebergctl.go
materialize-s3-iceberg/transactor.go

Some catalogs disregard the configured table path when a table is created, and just do their own thing. To make sure data files get put into the right place, we need to retrieve the actual path of created tables.
- - - …

materialize-s3-iceberg: use table paths of loaded tables

---

source-mysql-batch/main.go

Restructures some of the error reporting around MySQL database connection attempts. Previously there were two issues:
- Error messages sometimes got swallowed and reported as `unable to connect to database: <nil>` because of incorrect variable shadowing.
- We try to connect with both TLS and not-TLS, but in some cases the server will require TLS and the non-TLS connection attempt will fail for that reason, but we didn't report the reason the with-TLS connection attempt failed. Now we report the TLS failure reason when both fail.
Also this commit fixes the "incorrect username/password" special case since that got broken in the upgrade to v1.8.1 of the MySQL client library.
This fixes https://github.com/estuary/connectors/issues/1923
- - - …

source-mysql-batch: Improve connection error reporting

---

source-postgres/.snapshots/TestCaptureDomainJSONB-capture1
source-postgres/.snapshots/TestCaptureDomainJSONB-capture2
source-postgres/capture_test.go
source-postgres/replication.go

As explained in the added code, a user-defined domain type (which can be created via `CREATE DOMAIN name AS base_type` and which is basically just a type alias with optional constraints) ought to be decoded the same as a value of the base type.
We accomplish this by processing the `TypeMessage` event and when the namespace is omitted (which implicitly means "pg_catalog", if the Postgres docs can be trusted here) we look up the type name in the type map and register the user type OID as having the name and codec of the base type (if found).
Also adds a test case which exercises this behavior. If not for the fix in this commit, snapshot `TestCaptureDomainJSONB-capture2` would have its JSONB values emitted as strings rather than as raw JSON.
This fixes …

source-postgres: Register domain type OIDs as aliases

---

source-sqlserver/.snapshots/TestDeletedTextColumn-init
source-sqlserver/.snapshots/TestDeletedTextColumn-main
source-sqlserver/main_test.go
source-sqlserver/replication.go

According to MS docs, these columns always hold null values in the CDC table for a delete op, and blindly emitting those is incorrect and can cause schema validation failures if the text column is non-nullable.
The fix is to omit the property when the value is nil, the type is text/image/ntext, and the operation is a delete. In theory
this is always fine, because if the preimage value is a real null then we already have that in the LHS document that the delete will be merged into.
We could probably be even more aggressive in omitting properties here, honestly, but there's no real motivation to do that so I have gone with the minimal fix that only impacts the datatypes for which the default behavior is definitely wrong.
This fixes …

source-sqlserver: Omit null text/image/ntext values on deletes

---

materialize-postgres/client.go

Provide a specific error message when creating a table if the additional user-supplied SQL fails to execute.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1911)

materialize-postgres: separate table create error for user-supplied additional SQL

---

materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py

The transaction context manager will actually commit the transaction even if an exception is raised by any of its operations. This means that setting the table property and then attempting to add a data file where the data file addition operation fails would still update the table checkpoint, resulting in Flow transaction erroneously being acknowledged even when data wasn't added to the table.
Using the explicit transaction handle and committing it does seem to work as expected though, where if there is an exception before the `commit` none of the operations will be applied.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4w …

materialize-s3-iceberg: don't use context manager for transaction

---

source-mongodb/.snapshots/TestDiscover
source-mongodb/.snapshots/TestDiscoverAllDatabases
source-mongodb/.snapshots/TestDiscoverMultipleDatabases
source-mongodb/discovery.go

This adds the (conditional) reduction strategy to deletion events to merge them into existing documents. For materializations using soft deletions, this will have the effect of only updating the `_meta/op` column to `"d"` for the materialized row, instead of removing all of the values from other non-key columns.
This will make soft deletions for MongoDB-captured collections work the same way as other CDC connectors, while still using the top-level "last write wins" reductions strategy for other events, most notably updates, where we don't emit explicit `null` values for removed fields (yet). …

source-mongodb: merge deletion events

---

materialize-dynamodb/transactor.go

Log out information about the batch attempting to be stored if the store operation fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1937)

materialize-dynamodb: log failed batch writes in stores

---

source-http-ingest/src/lib.rs

The previous commit added some println statements to help debug an issue, and I forgot to remove them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1941)

source-http-ingest: remove printlns

---

materialize-redshift/driver.go

Until the staged file handles are flushed, they will keep a partial part of a multipart upload to S3 buffered. If there are a lot of bindings, this can be a lot of partial chunks and can potentially cause memory issues with the connector.
We can safely flush the staged files for store bindings based on the binding number incrementing, as we have for many other materializations. This will minimize memory usage for materializations with lots of bindings.
Closes https://github.com/estuary/connectors/issues/837
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing …

materialize-redshift: flush bindings when stores are complete

---

source-mysql/datatype_test.go
source-mysql/discovery.go

As discussed on Slack earlier today, this PR causes the zero value `0000-00-00` of the MySQL `date` column type to be serialized as `0001-01-01` going forward so that it can satisfy `format: date` validation. Both values are outside of the range of legal nonzero date values and all existing user collections treat these as generic strings anyway, so this is a backwards-compatible change as far as we're concerned and should not break any existing dataflows.
While the new value is compatible with JSON schema `format: date` validation we are not changing the discovery output at this time, because that could break preexisting datasets with the old zero value. Users who need these columns to be materialized as dates can adjust their read schema appropriately.
This fixes …

source-mysql: Replace date `0000-00-00` with `0001-01-01`

---

estuary-cdk/estuary_cdk/http.py
source-stripe-native/source_stripe_native/models.py
source-stripe-native/source_stripe_native/resources.py
source-stripe-native/tests/snapshots/snapshots__discover__stdout.json

Stripe API keys that start with `rk_` are restricted keys that may not have permissions for all API endpoints. If a restricted key is provided, we have to check each stream's accessibility during a discover.
Most child streams' accessibilities are the same as their parent stream. But `UsageRecords` is the exception - it can be inaccessible when its parent is accessible. This requires some special handling, like the `discoverPath` property within the `STREAMS` data structure.
When `discoverPath` is present on a child stream, an invalid parent id is used. This works since the Stripe API checks accessibilty before checking whether the requested resource exists, so we can key off the returned error code to determine accessibility. I did this instead of finding a valid parent …

source-stripe-native: only discover accessible streams

---

source-postgres/.snapshots/TestScanKeyTypes-OID
source-postgres/datatype_test.go
source-postgres/discovery.go

Previously OID values "worked" (they've always been captured as integer values and it was possible to use them as the backfill key as far as the connector was concerned), but were discovered as the catch-all schema `{}` which meant that OID primary keys would produce a collection with an invalid collection key.
This commit fixes that by changing OID discovery to say they're integers, and adds some test cases to make sure OIDs work as we intend both as values and as primary keys.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1966)

source-postgres: Discover OIDs as integers and add tests

---

go/dbt/trigger.go
materialize-bigquery/.snapshots/TestSpecification
materialize-bigquery/bigquery.go
materialize-databricks/.snapshots/TestSpecification
materialize-databricks/config.go
materialize-mysql/.snapshots/TestSpecification
materialize-mysql/driver.go
materialize-postgres/.snapshots/TestSpecification
materialize-postgres/driver.go
materialize-redshift/.snapshots/TestSpecification
materialize-redshift/driver.go
materialize-snowflake/.snapshots/TestSpecification
materialize-snowflake/config.go
materialize-sqlserver/.snapshots/TestSpecification
materialize-sqlserver/driver.go

- "dbt" should be spelled lowercase
- Added support for specifying `region`, dbt Cloud has introduced EU region account prefixes (see https://docs.getdbt.com/docs/cloud/about-cloud/access-regions-ip-addresses)
- Introduced another "special" account prefix `cloud` to support old accounts that still use that API
- - - …

dbt: cloud prefix, allow region specification, fix dbt case

---

.github/workflows/python.yaml
source-stripe-native/config.yaml
source-stripe-native/source_stripe_native/api.py
source-stripe-native/source_stripe_native/models.py
source-stripe-native/source_stripe_native/resources.py
source-stripe-native/tests/snapshots/snapshots__discover__stdout.json
source-stripe-native/tests/snapshots/snapshots__spec__stdout.json

This PR covers a handful of quick updates:
- Remove a redundant line in the GH python workflow.
- Rename the config's `stop_date` to `start_date`.
- Update the default `start_date` to be 30 days in the past rather than a fixed date in 2010.
- Improve typing.
- Create classes that contain shared attributes among models.
- Add typing to `fetch_*` functions in `api.py`.
- Minor refactors related to variable naming & reuse that improve readability.
Spec snapshot changes are expected due to the `start_date` updates. 
Discover snapshot changes are expected due to the new classes containing shared attributes. The `created` field exists on all non-child streams' documents, and we were already relying on `created` to know when to stop backfilling. Making `created` explicit in the …

source-stripe-native: config update, typing, and refactors

---

materialize-snowflake/.snapshots/TestConfigURI-User_&_Password_Authentication
materialize-snowflake/.snapshots/TestConfigURI-v1_User_&_Password_Authentication
materialize-snowflake/.snapshots/TestConfigURI-v2_User_&_Password_Authentication
materialize-snowflake/config.go
materialize-snowflake/config_test.go

The user/password encoding that `uri.User.String()` uses is actually slightly different than `url.QueryEscape()`, and the latter is what is needed to handle inputs with special characters to build a compatible Snowflake DSN.
- - - …

materialize-snowflake: percent encode username + password input

---

source-hubspot-native/source_hubspot_native/models.py

This has been observed in a production task, and for now we will not capture associations beyond the first page. This could be reconsidered in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1974)

source-hubspot-native: ignore extra associations page results

---

source-postgres/discovery.go

This is a "system schema" added by the pglogical extension [1] and I don't believe the typical user who happens to have that extension installed wants these tables captured in the first place.
[1] https://www.2ndquadrant.com/en/resources-old/pglogical/pglogical-docs/
Discovery will no longer produce bindings for tables in the `pglogical` schema in cases where previously it did.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1975)

source-postgres: Exclude `pglogical` schema from discovery

---

source-impact-native/source_impact_native/api.py
source-impact-native/source_impact_native/resources.py

The Actions stream response seems to be ignoring the creation date order, and it also seems to not be returning data as in order of last updated record, only of impact creation. in order to support that, im removing the smaller logcursor check which would cause the connector to not return every record in incremental sync
The Actions stream response seems to be ignoring the creation date order, and it also seems to not be returning
data as in order of last updated record, only of impact creation. in order to support that, im removing the smaller logcursor check
which would cause the connector to not return every record in incremental
- - - …

source-impact-native: removing logcursor check for Actions streams

---

source-stripe-native/source_stripe_native/models.py
source-stripe-native/tests/snapshots/snapshots__discover__stdout.json

Sometimes, `account.updated` events do not have a `created` field in the document, causing failures when we validate the document against its model. Making `created` optional will avoid these failures and reflect the API's actual response. The default value of `None` is removed from the schema to keep it aligned with how we understand the `created` field: it's either present as an `int` or it's not present at all. In other words, it's an optional, non-nullable field.
Note: I've only noted that this occurs for `account.updated` events for when the user's own Stripe account is created. I couldn't confirm if all `account.updated` events have `created` missing in the document, or if `Accounts` documents really don't have `created` fields at all. If this becomes an issue …

source-stripe-native: make created optional for Accounts

---

source-linkedin-ads-v2/source_linkedin_ads_v2/spec.json
source-linkedin-ads-v2/source_linkedin_ads_v2/streams.py
source-linkedin-ads-v2/tests/snapshots/source_linkedin_ads_v2_tests_test_snapshots__spec__capture.stdout.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1984)

source-linkedin-ads: nit: fixing oauth provider spec

---

source-impact-native/source_impact_native/models.py
source-impact-native/tests/snapshots/source_impact_native_tests_test_snapshots__discover__stdout.json

after fixing the tombstone value with the correct class, the connector still broke due to tombstone failures. The newer bugs happened because there were still a pk required that was not being fed to the newer tombstone model. In order to fix that, i've removed all previous pk from snapshot models and fixated all pks to _meta/row_id ( the default strategy )
All changes were tested using a local flow instance, and materialized to a free-tier neon POSTGRES db
All snapshot streams were tested and materialized
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1980)

source-impact-native: switching snapshots pk to _meta/row_id

---

source-stripe-native/source_stripe_native/api.py
source-stripe-native/source_stripe_native/models.py

Child streams, like `InvoiceLineItems` perform incremental replication by watching for events on their associated parent resource, then requesting all child resources for that parent when an event happens. However, since there can be some time between when we process an event & what actually happens in Stripe, it's possible for us to request child resources of a deleted parent. Stripe returns a `404` code and somewhat unique text to indicate this. We can safely skip requesting these resources when this happens.
This situation can happen if a creation/update is quickly followed by a deletion. If the connector is stuck for a while and a backlog of events we haven't processed builds up, there's even more opportunity for us to request deleted resources.
I noticed this issue …

source-stripe-native: handle responses for children of deleted resources

---

source-http-ingest/Cargo.lock
source-http-ingest/Cargo.toml
source-http-ingest/src/main.rs
source-http-ingest/src/server.rs
source-http-ingest/src/transactor.rs
source-http-ingest/tests/test.rs

Removes the use of `serde_json::Value` for parsed documents, and instead use `RawValue` as much as possible. This is done in order to reduce memory usage, as the overhead of `Value` is quite high.
Also changes to using a `String` to represent the fully prepared documents to be captured. This allows us to skip an extra serialization step since the capture protocol requires these documents to be `String`s anyway.
This unfortunately required changing how we validate documents, since the `doc::Validator` can only be used with parsed documents. So we instead use a `json::Validator`, which can validate the `String` directly.
Also changes to using jemalloc instead of the system allocator.
- - - …

source-http-ingest: Stop using serde_json::Value

---

go/dbt/trigger.go
materialize-bigquery/.snapshots/TestSpecification
materialize-databricks/.snapshots/TestSpecification
materialize-mysql/.snapshots/TestSpecification
materialize-postgres/.snapshots/TestSpecification
materialize-redshift/.snapshots/TestSpecification
materialize-snowflake/.snapshots/TestSpecification
materialize-sqlserver/.snapshots/TestSpecification

- Require https:// in Access URL
- Tested using jsonforms debug page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1989)

dbt: require https:// in AccessURL

---

source-zendesk-support/acmeCo/posts.schema.yaml
source-zendesk-support/acmeCo/ticket_metrics.schema.yaml
source-zendesk-support/acmeCo/ticket_skips.schema.yaml
source-zendesk-support/source_zendesk_support/schemas/ticket_skips.json
source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json
source-zendesk-support/tests/test_snapshots.py

We have encountered schema violations for `ticket_skips` where a custom field's value is an array of strings. The `ticket_skips.json` schema has been updated to allow this.
I missed updating `posts.schema.yaml` and `ticket_metrics.schema.yaml` in previous PRs, so I've updated them now. Those previous PRs are:
- https://github.com/estuary/connectors/pull/1807 (posts)
- https://github.com/estuary/connectors/pull/1917 (ticket_metrics)
The capture snapshot test has also been flaky because Zendesk Support seems to delete & re-add the default tag I assumed would always be present. I added an organization tag in our Zendesk Support testing account to ensure a tag will always be present, and I redacted the tag fields in the capture snapshot so the test is more reliable.
Discover …

source-zendesk-support: update ticket_skips schema

---

source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json

Over the weekend, it looks like Zendesk Support added a `configuration.explore_reports` field to all custom roles returned via their API. This is causing our `source-zendesk-support` capture snapshot test to fail, so updating the snapshot will let our tests pass. This is preventing the build for #1988 from succeeding (tests passed Friday for the PR, but they didn't pass this morning when I merged :sweat:).
Since `configuration.explore_reports` isn't included in the official Zendesk Support docs yet, I'm holding off on adding that field to the stream's schema in case Zendesk removes it. …

source-zendesk-support: update capture snapshot

---

materialize-bigquery/transactor.go
materialize-databricks/driver.go
materialize-motherduck/driver.go
materialize-mysql/driver.go
materialize-postgres/.snapshots/TestValidateAndApply
materialize-postgres/driver.go
materialize-postgres/sqlgen.go
materialize-redshift/driver.go
materialize-snowflake/snowflake.go
materialize-sql/driver.go
materialize-sql/endpoint.go
materialize-sqlite/sqlite.go
materialize-sqlserver/driver.go
materialize-starburst/starburst.go

Materialize UUID formatted strings as UUID columns, but continue to allow TEXT columns to validate for these fields since there are pre-existing columns and we don't want to force a backfill of them. Transferring the values of the fields is the same if they are UUID columns vs. TEXT columns.
Going forward new or re-backfilled tables will have UUID formatted strings materialized as UUID columns.
Also: Create load tables for `materialize-postgres` with column DDL based on the key columns of the target tables. This is required for join query comparisons to work correctly for pre-existing tables that have UUID fields materialized as TEXT columns. Most of the diff is a result of this change. …

materialize-postgres: materialize UUID formatted strings as UUID columns

---

materialize-sql/driver.go

Fixes a bug where an uninitialized resource was being used to populate the resourcePaths list. The standard InfoSchema builder only really cares about the "schema" part of the resource path, so this handling was actually working most of the time when a materialization's tables were all in the same schema as its metadata tables. But if there are tables in other schemas, they weren't being property enumerated.
**Notes for …

materializations: use correct resource path when building InfoSchema in Open

---

materialize-snowflake/snowflake.go

- when tasks have a large number of bindings, we keep retrying for too long. In cases where the ingestion reports are expired, this creates a forever loop. This pull-request limits the length of time we retry to 5 minutes maximum.
- - - …

materialize-snowflake: limit number of retries based on pipe numbers

---

source-postgres/.snapshots/TestEnumScanKey
source-postgres/datatype_test.go
source-postgres/discovery.go

Previously we treated enum primary keys as having a predictable ordering [1], which fails the moment somebody actually tries to capture a table with an enum primary key where the cases are not listed in alphabetical order because we just serialize the string representation of the enum value as the backfill row key.
[1] Here, "predictable" means not just that the ordering can be predicted in theory, but that it is encoded in the bytewise lexicographic ordering of serialized row keys.
This commit adds a test and the discovery tweak that makes it pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2005)

source-postgres: Treat enum primary keys as unpredictable

---

source-zendesk-support/source_zendesk_support/streams.py
source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/test_futures.py
source-zendesk-support/tests/unit_test.py

The `Groups` and `Organizations` streams were missing data. This PR addresses the issues causing these streams to miss data.
Deleted groups were not being retrieved previously. By including the `exclude_deleted` query param and setting it to `false`, the Zendesk Support API is now returning deleted groups.
Only 10k organizations were being retrieved previously. The `Organizations` stream was using page numbers to paginate through results. This is an older, but still supported, pagination method for Zendesk Support, and they only allow you to paginate through 10k results even if there are more. Using the page number based pagination method was causing us to only retrieve 10k documents and miss any remaining ones.
I've updated the `Organizations` stream to use Zendesk's …

source-zendesk-support: fix Groups and Organizations streams

---

source-oracle-flashback/source_oracle_flashback/models.py

- We were getting tons of these errors:
```
Expected `bool` but got `str` - serialized value may not be as expected
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2009)

models: quoted_* methods return str, not bool

---

materialize-motherduck/client.go
materialize-mysql/client.go
materialize-postgres/client.go
materialize-redshift/.snapshots/TestSQLGeneration
materialize-redshift/client.go
materialize-redshift/driver.go
materialize-redshift/driver_test.go
materialize-redshift/sqlgen.go
materialize-redshift/sqlgen_test.go
materialize-sql/std_sql.go

Adds compression for checkpoints that are stored in the checkpoints table, which should significantly increase the maximum size of checkpoint the 1 MiB VARBYTE column can hold.
VARBYTE columns can also be made larger than 1 MiB (up to 16 MiB, with added query overhead), so if this still ends up not being enough we can add automatic enlargement of the VARBYTE columns, similar to what we have for VARCHAR columns in Redshift already.
The changes in this commit really lean into Redshift handling metadata in its own weird way. Previously the general "install fence" routine was modified to all a decoding callback which was only used by Redshift. Rather than add an additional encoding callback that only Redshift would use, we'll just have Redshift do its own thing entirely and …

materialize-redshift: compress checkpoints

---

materialize-motherduck/client.go
materialize-mysql/client.go
materialize-postgres/client.go
materialize-redshift/.snapshots/TestSQLGeneration
materialize-redshift/client.go
materialize-redshift/driver.go
materialize-redshift/driver_test.go
materialize-redshift/sqlgen.go
materialize-redshift/sqlgen_test.go
materialize-sql/std_sql.go

The first commit is a revert of a revert that was reviewed in https://github.com/estuary/connectors/pull/1999. But there was an issue with that, which the second commit here fixes:
Redshift will throw an error if your `FROM_VARBYTE` operation results in a string that is too long for VARCHAR. So we have to just accept the bytes it sends back to us, which are Hex encoded and not subject to the VARCHAR length limits.
**Notes for …

materialize-redshift: client-side hex decoding of checkpoint & spec bytes

---

source-oracle-flashback/source_oracle_flashback/__init__.py
source-oracle-flashback/source_oracle_flashback/resources.py

- Until now we were doing a full discovery for each Validate and Open call, but normally other connectors only operate on the requested bindings. Here I'm implementing the same logic so that we don't have to do a full discovery every time, instead we only validate tables that match bindings.
- This originally came about because we have tasks which take so long to discover that their Validate request was timing out. Most of the time spent during the request was spent on getting the `MAX_ROWID` of tables. By reducing the number of tables that we query to only the enabled ones, we should be able to run Validates much faster.
- Tested with integration tests and manually running a task with disabled bindings
(How does one use this feature, and how has it …

source-oracle-flashback: only validate and operate on enabled bindings

---

source-zendesk-support/source_zendesk_support/streams.py

Previously, `TicketMetricEvents` was only emitting documents and checkpointing state after reading all available documents from Zendesk Support & getting caught up to the present. `TicketMetricEvents` can take multiple hours to backfill, and any task restarts during the backfill cause `TicketMetricEvents` to start over completely instead of picking back up where it left off before the restart.
Setting [`state_checkpoint_interval`](https://docs.airbyte.com/connector-development/cdk-python/incremental-stream#interval-based-checkpointing) tells `TickeMetricEvents` to checkpoint state & emit documents after every 1000 documents, and this allows the stream to pick up where it left off if it's interrupted during a backfill.
(How does one use this feature, …

source-zendesk-support: checkpoint `TicketMetricEvents` state after every 1000 documents

---

source-sqlserver/.snapshots/TestComputedColumn-capture
source-sqlserver/.snapshots/TestComputedColumn-discovery
source-sqlserver/backfill.go
source-sqlserver/discovery.go
source-sqlserver/main_test.go
source-sqlserver/replication.go
sqlcapture/discovery.go
sqlcapture/interface.go

According to [Microsoft documentation](https://learn.microsoft.com/en-us/sql/relational-databases/system-functions/cdc-fn-cdc-get-all-changes-capture-instance-transact-sql?view=sql-server-ver16):
> Computed columns that are included in a capture instance always have a value of NULL.
This means that we cannot capture computed column values via CDC. And if we can't capture them via CDC, then we shouldn't capture them in backfills either since the values could quickly become stale and incorrect. And if we're not capturing them via CDC or backfills then we shouldn't mention them in our discovered schemas either.
This fixes https://github.com/estuary/connectors/issues/1995
Captures will no longer include values for computed columns in their output …

source-sqlserver: Exclude computed columns from discovery, backfills, and replication

---

source-pendo/source_pendo/__init__.py
source-pendo/source_pendo/resources.py

Previously, users could successfully create a task with an invalid Pendo API key. Pendo returns a `403` code when we send a request with an invalid API key, and we now key off that to prevent tasks with invalid API keys from being created.
A screenshot of the error rendered in the UI is below:
Tested on a local stack. Confirmed:
- an error is thrown before task creation when an invalid API key is …

source-pendo: validate API key

---

source-pendo/source_pendo/api.py
source-pendo/source_pendo/models.py
source-pendo/source_pendo/resources.py
source-pendo/tests/snapshots/snapshots__discover__capture.stdout.json

For Pendo accounts with a significant amount of data, the strategy of asking for all data up until the present does not work. Pendo's response time is long enough to cause `TimeoutError`s, and responses that are received end up OOM-ing the connector.
To fix this, there is now a distinct backfill process for events and aggregated events. 
Notable changes include:
- Separating backfills from ongoing incremental replication.
- Backfills try to get at max a day's worth of data. Incremental replication continues to get all data up to the present.
- The cutoff between backfills and incremental replication is shifted backwards 12 hours due to delays between when an event occurred and when it is available in the API. This is to prevent backfills from mistaking this delay as a …

source-pendo: separate backfill from incremental

---

materialize-redshift/driver.go

We were always calling `FinishedResourceCommit` for bindings even if they had no data, which was resulting in bogus log lines. This fixes the logic to not invoke the logging mechanisms for bindings with no data.
- - - …

materialize-redshift: fix logging of Store bindings with no data

---

source-mysql-batch/main.go
source-mysql/main.go

I hate this TLS vs non-TLS connection retrying thing and how it results in two distinct errors, let's just make sure to log both so I can at least figure out what went wrong in all cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2031)

source-mysql: More connection error logging

---

source-http-ingest/src/server.rs
source-http-ingest/tests/test.rs

Fixes a bug in the source-http-ingest connector where it would use the incorrect uri in cases where the collection schema already contained an `$id`. Now it uses the uri that was actually resolved while building the schema.
Also tweaks the logging of errors to use the more complete degub representation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2034)

source-http-ingest: use proper schema uri

---

source-postgres/discovery.go

The `citext` column type is added by the `citext` extension and stores text with a case-insensitive comparison operator. In my testing it looks like we're capturing these values correctly as strings, but discovery is emitting the catch-all schema which can cause some materializations to do...suboptimal things with those values.
This commit adds `"citext"` to the discovery type mapping table so it should work correctly, but doesn't add any test cases as it's an extension type (even though the extension is a standard part of the Postgres release and has been for ages so we could probably add the requisite `CREATE EXTENSION "citext"` statement to the test DB setup script and then treat it like any other built-in type...)
- - - …

source-postgres: Discover 'citext' columns as strings

---

source-postgres/.snapshots/TestGeneric-SpecResponse
source-postgres/database.go
source-postgres/discovery.go
source-postgres/main.go
source-postgres/prerequisites.go

This is an advanced option which, when set, instructs the capture to only return discovery results for tables which are already in the publication.
This is useful in cases where users might wish to administer the set of tables which are being captured by adding or removing the table from the publication in the source DB.
I implemented a test case for this, but since our CI test database is currently created with a `FOR ALL TABLES` publication it can't currently be added to the CI test suite.
By default nothing should change. When the advanced option "Discover Only Published Tables" is enabled, the capture will omit discovery bindings for any tables which aren't already present in the publication. This allows users to control which tables are to be …

source-postgres: Add 'Discover Only Published Tables' setting

---

materialize-boilerplate/logging.go

The use of a mutex in both the extended logger event handler and the async logger functions was simple, but there was a potential deadlock if the event handler needed to stop the logger and wait for it to stop while holding the lock, and the logger timer ticked over at nearly the same instant making the logger need to get the lock also to finish its last log before exiting.
This updates the extended logger to not use locks at all, since it wasn't far from being able to do that in the first place. The "count" values that are read concurrently by the async loggers have been changed to use atomics, and for good measure the "round" counter is provided as an explicit argument to them, even though it doesn't strictly need to be, it's just easier to understand this way. …

materialize: don't use locks in the extended logger

---

source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/test_snapshots.py

The [`/tags`](https://developer.zendesk.com/api-reference/ticketing/ticket-management/tags/#list-tags) endpoint returns the most popular tags used in the last 60 days. After 60 days, it's possible for existing tags to not be returned if they weren't used recently. Because we aren't going into Zendesk & using tags every once in a while, the capture snapshot has been failing in CI. Instead of making a reminder to go into Zendesk every 2 months and use a tag, I think it's easier to just remove tags from the capture snapshot. …

source-zendesk-support: omit tags from capture snapshot

---

materialize-mysql/.snapshots/TestValidateAndApplyMigrationsMariaDB
materialize-mysql/docker-compose.yaml
materialize-mysql/driver.go
materialize-mysql/driver_test.go
materialize-mysql/sqlgen.go
materialize-mysql/sqlgen_test.go

- [MariaDB does not have a distinct `JSON` type, it is instead a `LONGTEXT` alias](https://mariadb.com/kb/en/json-data-type/), so for MariaDB instances from now on we actually create a `LONGTEXT` to avoid confusing the connector over compatibility of MULTIPLE fields.
- Added MariaDB to our tests so we can check that flow_documents is not modified when running an Apply RPC against a MariaDB instance. I ran the tests and can confirm we do not attempt to migrate `flow_document` with this update. MySQL instances will retain their previous behavior (also verified using our tests).
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4 …

materialize-mysql: use longtext instead of JSON for mariadb

---

source-postgres/discovery.go

We already don't fetch the tables themselves from system schemas, so fetching column descriptions is pointless. And empirically, the part of the query expression that actually gets the description often fails with errors like `permission denied for schema cron` in production.
Hopefully if we explicitly filter out those schemas we'll see it succeed more often.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2054)

source-postgres: Don't fetch column descriptions in system schemas

---

materialize-boilerplate/logging.go

Right now there is no immediate log message when evaluating loads starts, but there is supposed to be. This adds that missing log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2055)

materialize: add missing log message for when evaluating loads starts

---

source-mysql/discovery.go
source-mysql/replication.go

The collation families `utf8_whatever` and `ascii_whatever` are explicitly added to the charsets table so we stop logging errors reading `unknown charset for collation, assuming UTF-8` and just do that without complaining because UTF-8 is in fact correct.
The `replication connected without TLS` log message is downgraded from WARN to INFO to match the main (non-replication) connection logging.
Between these fixes, that's all the main sources of errors and warnings in our production MySQL tasks, so hopefully that will be much less noisy to keep an eye on in the future.
This fixes https://github.com/estuary/connectors/issues/2056
- - - …

source-mysql: Fix some benign error/warnings that get logged

---

source-oracle-flashback/config.yaml
source-oracle-flashback/source_oracle_flashback/models.py
source-oracle-flashback/tests/snapshots/snapshots__discover__stdout.json

- `_meta/soruce/row_id` is the primary key of documents in some cases when a natural key cannot be found. This property is always present so it should be marked as required so that materializations can materialize it as non-nullable
- - - …

source-oracle-flashback: make sure _meta/source/row_id is required

---

materialize-boilerplate/logging.go

The round counter is incremented when the materialization starts its commit, and the general idea of starting the entire commit happens before performing the sub-operations for committing to each resource. So the "round" counter for committing to each resource is actually 1 less than currently tabulated.
The "round" counter offset by 1 is overall pretty convoluted and I may need to think about some kind of "load round" counter instead that stores are associated with, although I'm not sure that would be any better. The async operations of the materialization protocol just makes this a bit tricky …

materialize: fix round counter error in binding events logger

---

materialize-bigquery/binding.go
materialize-bigquery/transactor.go

Following #1913 and various updates to other materializations that were before that, this brings in the memory optimization to flush staged files during the Store phase after the binding ticks over to the next one.
- - - …

materialize-bigquery: flush bindings when stores are complete

---

source-hubspot-native/source_hubspot_native/resources.py

Some HubSpot endpoints like `/v3/properties/{objectType}` do not work for every custom object type. However, these endpoints do work if we prepend a `p_` to the beginning of the custom object name and use that in the path instead.
I chose to add `path_component` to the `crm_object_with_associations` function signature mainly so we only prepend `p_` in one spot rather than in two. I'm not dead-set on this approach though, and I can adjust if there's a better/more desireable solution. …

source-hubspot-native: custom object path components

---

source-hubspot-native/source_hubspot_native/models.py
source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json

An existing task is failing because email events it's receiving have a `FORWARD` type, which isn't allow in the model. This PR adds `FORWARD` as an allowed email event type.
Relevant HubSpot docs are [here](https://legacydocs.hubspot.com/docs/methods/email/email_events_overview). Skimming through them, we may need to add more email event types in the future (`PRINT` ? ), but that can be done later if needed.
Discover snapshot changes are expected since a new email event type was added to the `EmailEvent` model.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or …

source-hubspot-native: add "FORWARD" to email event types

---

source-hubspot-native/source_hubspot_native/models.py
source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json

We've encountered even more email event types and need to expand the model to include them. Relevant HubSpot docs are [here](https://legacydocs.hubspot.com/docs/methods/email/email_events_overview).
Interestingly, the `SUPPRESSED` type isn't documented in HubSpot's docs but we have seen it used in existing records. The similarly named `SUPPRESSION` type is listed in the docs; I'm not sure if this is a typo on HubSpot's end, or if they have an undocumented `SUPPRESSED` type. If it turns out `SUPPRESSION` is a HubSpot typo, we can remove it later.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp= …

source-hubspot-native: add more email event types

---

source-hubspot-native/source_hubspot_native/api.py

Delayed incremental streams should be wrapped in a `try/except` block to trigger automatic backfills if we encounter a `MustBackfillBinding` error.
I kept the recent incremental streams wrapped in the existing `try/except` that serves the same purpose since it's possible for `MustBackfillBinding` exceptions to be raised if a task is disabled long enough for the cursor to fall far enough behind the recent changes available from HubSpot. …

source-hubspot-native: add auto backfills for delayed streams

---

source-zendesk-support/source_zendesk_support/streams.py

For tasks that have a significant number of audit logs in Zendesk Support, it can take more than 24 hours to backfill. With the current `AuditLogs` stream strategy of reading records in descending order then stopping when we've reached a record we already read, we can't checkpoint until the backfill is completed. This means tasks that take more than 24 hours to backfill `AuditLogs` can get stuck restarting & attempting to backfill.
This PR updates the `AuditLogs` stream to read records in ascending order. This lets the connector checkpoint after each response & pick up where it left off when it's restarted.
Some noteable changes include:
- Passing a list containing `start_time` and `end_time` for the `filter[created_at][]` query param to bound the responses' results to …

source-zendesk-support: checkpoint during `AuditLogs` stream

---

source-sqlserver/replication.go

While debugging a SQL Server replication issue, I noticed that we're not currently capturing this as part of our diagnostics. (I don't think this would give us anything useful for the issue I was just debugging, but in other cases it would be good to have this information).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2067)

source-sqlserver: Add another query to replication diagnostics

---

materialize-s3-iceberg/catalog.go
materialize-s3-iceberg/driver.go
materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
materialize-s3-iceberg/iceberg-ctl/poetry.lock
materialize-s3-iceberg/iceberg-ctl/pyproject.toml

Adds concurrency to fetching table storage paths, since otherwise this can take a really long time if there are lots of enabled bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2071)

materialize-s3-iceberg: fetch table paths concurrently

---

source-mysql/replication.go

Apparently COMMIT query events (in a context where there aren't any uncommitted changes on non-transactional tables we care about) are the primary source of ops log spam from SQL CDC connectors at the moment.
I'm pretty confident our handling is correct, so let's stop logging those.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2072)

source-mysql: Silently ignore COMMIT query events

---

source-mysql/main.go

Reverts estuary/connectors#2073
Somehow the read/write timeouts appear to be set once and then somehow getting stuck -- captures consistently start up and then fail **exactly** one minute after the initial database connection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2074)

Revert "source-mysql: Set ReadTimeout/WriteTimeout on connection"

---

materialize-snowflake/snowflake.go
materialize-snowflake/sqlgen.go

Some users actually want to materialize columns as TIMESTAMP_NTZ, so we need to detect when that parameter has been explicitly set and use it if it has.
The general case of the parameter being unset and defaulting to TIMESTAMP_NTZ will continue to behave like before and use TIMESTAMP_LTZ, but if it is set to TIMESTAMP_NTZ at the account/role/user level, we will use TIMESTAMP_NTZ for columns.
(anything …

materialize-snowflake: respect TIMESTAMP_TYPE_MAPPING if it is explicitly set to TIMESTAMP_NTZ

---

source-bigquery-batch/.snapshots/TestDatetimeCursor-Capture
source-bigquery-batch/.snapshots/TestDatetimeCursor-Discovery
source-bigquery-batch/driver.go
source-bigquery-batch/main.go
source-bigquery-batch/main_test.go

BigQuery DATETIME columns only support microsecond precision, but the default serialization of the Go `civil.DateTime` struct uses nanosecond precision. Which is fine for output only, and *also* is fine for cursors until the capture restarts, and *also* is fine when the datetime values are whole seconds.
But a fractional-second datetime used as a cursor will be stored as a string in the state checkpoint, and trying to feed that back to BigQuery after a restart will produce an error because there are too many digits of precision.
The fix is to handle the formatting of `civil.DateTime` values into strings ourselves and make sure it only has six digits.
- - - …

source-bigquery-batch: Fix behavior of `DATETIME` cursors with fractional-second precision

---

source-zendesk-support/source_zendesk_support/streams.py

For users with a lot of data, the `ticket_comments` stream can take a while to backfill, especially given the 30 requests/60 seconds rate limit for this endpoint. Checkpointing that stream will help if that backfill complete over connector restarts, and it'll provide an indicator in the UI that the connector is still processing records.
I've also added logging to catch if the `ticket_comments` cursor does not increase & to log the status codes for non-200 responses to help troubleshoot if the connector is stuck making the same failing request.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sh …

source-zendesk-support: add logging & `ticket_comments` checkpoint

---

materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py

An absent checkpoint table property is allowed to accommodate cases where the user may have manually dropped the table and the materialization automatically re-created it, outside the normal backfill counter increment process.
- - - …

materialize-s3-iceberg: always allow appends to a table with an empty checkpoint property

---

go/network-tunnel/network_tunnel.go
materialize-elasticsearch/driver.go
materialize-mongodb/driver.go
materialize-mysql/driver.go
materialize-postgres/driver.go
materialize-redshift/driver.go
source-mongodb/main.go
source-mysql/main.go
source-oracle/main.go
source-postgres/main.go
source-sqlserver/main.go

Sister pull-request of https://github.com/estuary/network-tunnel/pull/9 to surface the underlying SSH client error when network-tunnel fails to establish a SSH tunnel
Example output:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/208 …

network-tunnel: exit without logging an error on EOF before READY

---

source-mysql/.snapshots/TestDateNormalization
source-mysql/capture_test.go
source-mysql/discovery.go

This commit factors out the date-normalization we apply to the date portions of timestamps and datetimes, and applies that same logic to the values of date columns.
For valid values this makes no difference. For the zero value this also makes no difference. But MySQL, while it normally rejects dates like `2024-00-00` or `2024-10-00` as invalid, has some mode settings which allows those, and currently we capture them verbatim. Which is a problem because the month or date components of a `format: date` string cannot be zero, and while we don't _currently_ discover `date` columns as a `format: date` string that's only because of compatibility issues and is something we'd like to change in the near future (and also we currently recommend that people add it to the read schema …

source-mysql: Normalize invalid dates the same as timestamp date parts

---

source-mysql-batch/main.go
source-mysql/main.go

This PR modifies the MySQL connection / error reporting logic so that it should hopefully be a bit clearer in certain edge cases why the connection failed. Specifically:
* We'll now check both the with-TLS and without-TLS error for an "incorrect username/password" condition, where previously it was just the with-TLS error getting checked.
* When none of the special cases apply, we'll report a more verbose error which includes both the with-TLS and without-TLS failure reasons.
* There is an explicit special case for the "TLS is required" error, and only when that case is hit do we report just the with-TLS failure and omit the "TLS required" error.
I'm optimistic that maybe this will be adequate, finally.
This fixes https://github.com/estuary/connectors/issues/2075
- - - …

source-mysql: Improve connection error reporting

---

materialize-mysql/docker-compose.yaml

- the existing healthcheck fails and that means running integration tests fails
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2098)

materialize-mysql: fix docker healthcheck for mariadb

---

materialize-snowflake/snowflake.go

We have observed runtime errors for specific cases of sending loaded documents to the runtime, and this debug logging can be enabled to see which query produced those documents, and specifically for which collection.
- - - …

materialize-snowflake: debug log the Load query before sending loaded documents

---

source-mysql/.snapshots/TestAddBinaryColumn
source-mysql/capture_test.go
source-mysql/datatype_test.go
source-mysql/discovery.go
source-mysql/replication.go

A `BINARY(N)` column holds fixed-length byte data, with zero- padding to the specified length. This all works as expected for backfills, but the actual binlog data stores the value with any trailing zeroes stripped so that's what we get via replication.
This commit adds a new datatype test case verifying the behavior around trailing zero bytes and implicit padding (and just for good measure it also makes the nonzero bytes an invalid UTF-8 byte sequence), modifies discovery to keep track of the length of a `BINARY(N)` column, and modifies the value translation code to zero-pad as necessary.
Bindings which are initialized after this change will discover and initialize the column metadata with a length property for binary columns, which is used to …

source-mysql: Fix BINARY(N) inconsistency

---

materialize-s3-iceberg/catalog.go
materialize-s3-iceberg/driver.go
materialize-s3-iceberg/driver_test.go
materialize-s3-iceberg/icebergctl.go
materialize-s3-iceberg/transactor.go

We have observed that append requests can hang indefinitely when using a REST catalog. This implements a conservative timeout of 5 minutes for these append requests, so that the connector can log an error and re-start if an append request takes an extremely long time.
- - - …

materialize-s3-iceberg: set a timeout on append files

---

go/dbt/trigger.go
materialize-bigquery/.snapshots/TestSpecification
materialize-bigquery/transactor.go
materialize-boilerplate/boilerplate.go
materialize-boilerplate/transactions_stream.go
materialize-databricks/.snapshots/TestSpecification
materialize-databricks/driver.go
materialize-mysql/.snapshots/TestSpecification
materialize-mysql/driver.go
materialize-postgres/.snapshots/TestSpecification
materialize-postgres/driver.go
materialize-redshift/.snapshots/TestSpecification
materialize-redshift/driver.go
materialize-snowflake/.snapshots/TestSpecification
materialize-snowflake/snowflake.go
materialize-sqlserver/.snapshots/TestSpecification
materialize-sqlserver/driver.go

- Move dbt job trigger logic to materialize-boilerplate where it can be better integrated with sync frequency logic, and makes it easier for materialization connectors to integrate the functionality in general
- - - …

dbt: move to materialize-boilerplate, only trigger after delay

---

source-klaviyo/source_klaviyo/streams.py

My earlier commit (dfbe8b5714bf76b053f971d5352e95d26f471d08 in PR #2037 ) was too broad in changing all incremental streams to use `>=` in the `filter` query param. The `/profiles` endpoint used by both the `Profiles` and `GlobalExclusions` streams do not support filtering with `>=`, so they have to use `>`.
For streams that do use `>`, I subtracted one second (the smallest time granularity for Klaviyo timestamps) before the first request to avoid missing records that were updated in the same second but weren't available in the API at the exact same time.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM …

source-klaviyo: filter `Profiles` with > instead of >=

---

source-klaviyo/source_klaviyo/streams.py

The `raise_on_http_errors` property has been suppressing all errors for the `Profiles` and `GlobalExclusions` streams. It looks like this was originally done because Klaviyo sometimes returns a `503` when paginating per the Airbyte comments. I have not been able to replicate this. If that does happen, we should now get an error message, the shard should fail & restart, and the stream should pick up where it last left off paginating. …

source-klaviyo: raise errors for `Profiles` and `GlobalExclusions`

---

source-redshift-batch/driver.go

This commit copies over some discovery changes from the `source-postgres` CDC connector (from which the Redshift discovery logic is mostly derived) to allow a source DB type to be mapped to multiple JSON types instead of just one.
Then that feature is used so that float4/float8 columns can be discovered as "either string-format-number or number". This is consistent with what `source-postgres` does and might help us with NaN-handling at some point in the future, but the real reason it's useful *right now* is that it unblocks a production capture which is currently having trouble with a column type changing from `NUMERIC` to `FLOAT`, because schema inference says that values are string-format-number and discovery says that values are numbers and Flow says that there are no …

source-redshift-batch: Discover float as number-or-string

---

source-hubspot-native/source_hubspot_native/api.py

There is an undocumented failure of the search API when trying to page beyond 10,000 results. It's also possible that there are more than 10,000 records modified at the same time.
Previously the only way out of this was to re-backfill the binding. This adds a cycle-breaker routine that walks ids in ascending order that were all modified at the exact same time to avoid looping forever.
(anything that …

source-hubspot-native: search API breaks out of cycles with more than 10k records

---

source-hubspot-native/source_hubspot_native/api.py

Quick fix of a bug introduced by the ordering of the the logging statement in `fetch_search_objects_modified_at`, where `result.total` is not available initializing the variable in the first loop.
- - - …

source-hubspot-native: fix variable access bug

---

sqlcapture/main.go

A production task ran into trouble and needs its binlog cursor manually adjusted using the mechanism we built for doing that.
Ask Will or Dave for further context (or just read the recent Slack thread in #integrations)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2123)

sqlcapture: Cursor replacement for production task

---

source-postgres-batch/.snapshots/TestFloatNaNs-Capture
source-postgres-batch/.snapshots/TestFloatNaNs-Discovery
source-postgres-batch/main.go
source-postgres-batch/main_test.go
source-redshift-batch/.snapshots/TestFloatNaNs-Capture
source-redshift-batch/main.go
source-redshift-batch/main_test.go

Adds support in the batch Postgres and Redshift captures for the special floating-point values `'NaN'`, `'Infinity'`, and `'-Infinity'`, which are translated into the corresponding strings as we do for other captures.
Since Postgres batch relies on schema inference for non-key property types and Redshift batch already has logic to discover floating-point columns as `type: [number, string], format: number` for other reasons, this doesn't require any discovery changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2131)

source-{redshift,postgres}-batch: Support NaNs

---

materialize-webhook/driver.go

Changes include:
- Supporting custom headers.
- Requiring collection keys in field selection.
- Chunking transactions across multiple webhooks.
- Webhook bodies are ~100 MiB or less.
- Removing retry mechanism in favor of allowing the connector to fail & retry the webhook when it is automatically restarted.
The HTTP Webhook [docs](https://docs.estuary.dev/reference/Connectors/materialization-connectors/http-webhook/) should be updated to reflect the configuration options.
Tested on a local stack. Confirmed:
- A single webhook only contains documents from a single binding.
- Webhooks are finished & closed once they reach/exceed the 100 MiB …

materialize-webhook: support custom headers & chunk transactions across multiple webhooks

---

estuary-cdk/estuary_cdk/shim_airbyte_cdk.py

Some imported connectors have errant `print` calls or similar that output directly to stdout, which Flow will otherwise interpret as a captured document or checkpoint.
This is really ugly, but to prevent it from happening we can redirect stdout to stderr after the task outputs have been initialized. That way the printed output is treated as logs instead of capture data. …

shim-airbyte-cdk: redirect rogue outputs to stdout

---

source-postgres/discovery.go

Filters out temporary and unlogged tables during discovery. These tables cause validation to fail because they cannot be added to publications. The filtering is done based on the `pg_class.relpersistence` values, described in the docs: https://www.postgresql.org/docs/current/catalog-pg-class.html#CATALOG-PG-CLASS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2133)

source-postgres: exclude temp tables from discovery

---

materialize-boilerplate/test_support.go
materialize-dynamodb/apply.go
materialize-dynamodb/driver.go
materialize-dynamodb/driver_test.go
materialize-sql/test_support.go
tests/materialize/materialize-dynamodb/snapshot.json

DynamoDB has a limit of 400KB for any single "item" stored, which is problematic for persisting a materialization spec.
We now have the prior materialization spec for validate & apply as part of the protocol messages, so we can use those instead.
This implementation is a short-term hack for unblocking a current task which is stuck trying to persist a spec that is too large, and we should come back and fix it up when we incorporate the prior spec from the validate & apply protocol messages more generally, see issue #2076. …

materialize-dynamodb: don't require a persisted spec

---

source-genesys/source_genesys/api.py

Since we haven't been able to test with a production Genesys account, it'll be nice to have logging to monitor the progress of the `conversations` Genesys job in case something we didn't anticipate happens.
Tested on a local stack to confirm logging occurs.
- - - …

source-genesys: add logging to `conversations`

---

source-genesys/source_genesys/models.py
source-genesys/tests/snapshots/snapshots__spec__capture.stdout.json

Changes include:
- Add a `discriminator` to the endpoint config's `credentials` so it's easier to add more authentication methods later if needed.
- Wrap the `ClientCredentialsOAuth2Credentials` class in a more user-friendly name since it shows up in the UI somehow. There's likely a more elegant & correct solution to fix this, but I haven't found it yet.
After these changes, the UI looks like the below: …

source-genesys: add discriminator to endpoint config's credentials

---

sqlcapture/main.go

Reverts estuary/connectors#2147
The reverted PR was a one-off adjustment to a specific task in production and should be removed again after that adjustment has taken effect.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2148)

Revert "sqlcapture: Cursor replacement for production task"

---

source-snowflake/.snapshots/TestBasicDatatypes-main
source-snowflake/.snapshots/TestDynamicTable-discovery
source-snowflake/.snapshots/TestDynamicTable-initial
source-snowflake/.snapshots/TestDynamicTable-subsequent
source-snowflake/README.md
source-snowflake/capture.go
source-snowflake/capture_test.go
source-snowflake/database.go
source-snowflake/discovery.go

As a general rule, if a connector returns something from discovery then we should be able to capture that thing without errors, and if we can't capture a particular type of entity then it shouldn't be suggested by discovery in the first place. A user should be able to just blindly click 'Next' in the capture creation flow and end up with something that works.
This was not previously the case for dynamic tables in Snowflake. They're tantalizingly close to working without any extra action, but for reasons known only to them Snowflake is very nitpicky about making you acknowledge that a table is dynamic. For instance you can't just say `CREATE STREAM ... ON TABLE`, you have to tell them `CREATE STREAM ... ON DYNAMIC TABLE`.
So dynamic tables didn't work, but our discovery …

source-snowflake: Support (incremental) dynamic tables

---

source-kinesis/capture.go

Currently an error for getting a shard iterator is just swallowed entirely. We should probably fail the capture when this happens, but as a really low-effort debugging benefit we can at least log these errors if they happen.
- - - …

source-kinesis: logging if getting a shard iterator fails

---

source-front/tests/snapshots/snapshots__spec__capture.stdout.json

I missed updating the spec snapshot after I corrected the documentation URL in https://github.com/estuary/connectors/pull/2150. This PR updates the spec snapshot to fix that oversight.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2 …

source-front: update spec snapshot

---

source-mysql/replication.go

In several places, MySQL represents binlog offsets within a file as a 32-bit unsigned integer. Most notably for our purposes are the binlog event header `log_pos` field, and the offset argument to the `COM_BINLOG_DUMP` command.
The upshot of this is that we can't necessarily trust the offset to be correct when a file grows past 4GB, and even if we tracked the "full offset" ourselves we wouldn't be able to resume from there after a connector restart.
This normally isn't an issue because binlog files are never supposed to grow that large. The system setting `max_binlog_size` which governs the point after which the file is rotated has a maximum possible value of just 1GB. Problem is, that's a soft limit and it's possible to force MySQL to stuff arbitrarily large amounts of …

source-mysql: Detect binlog offset wraparound

---

source-kafka/src/discover.rs
source-kafka/src/lib.rs

This timeout is used for fetching cluster metadata during the interactive discover and validation operations.
We need some kind of timeout here since its not uncommon for misconfigured configurations to end up hanging forever when trying to connect, but it can also take a little while for all the metadata to be returned from a Kafka cluster if there is a lot of it.
This extends the timeout from a pretty restrictive 5 seconds to a much more permissive 60 seconds. 60 seconds is quite a while for a discover/validate attempt to hang if the configuration is incorrect but that seems like a better direction to err on than failing correct configurations too soon for particularly large clusters. …

source-kafka: extend metadata timeout

---

source-mysql/main.go

[Previously](github.com/estuary/connectors/pull/2074) when we set read/write timeouts on the MySQL connection we saw a bunch of captures in production consistently fail exactly one timeout-duration after they connected.
I have sinced debugged this (see the comment which makes up the majority of this commit's lines changed) and believe that I have a viable workaround while we try to get the client library fixed.
Note that even with this workaround, we won't have timeouts on subsequent database communications when using TLS until the bug is fixed upstream (and we've upgraded the dependency version). Once it's fixed upstream this workaround is basically a no-op and can be removed at our leisure.
Even without timeouts on subsequent interactions, the timeout is still useful to …

source-mysql: Connection read/write timeouts redux

---

source-mysql/main.go
sqlcapture/main.go

This PR does two things, which I've combined into one PR because they're both tiny and this was more convenient:
1. Adds another temporary cursor replacement rule to get a production task rewound to an earlier portion of the binlog.
2. Adds a special-case to the "Skip Backfills" advanced config option so that the value `*.*` means "all tables". This doesn't generalize to like `schema.*` or anything right now, it's literally just matching that one string, but we needed a way to stop all tables in a capture from backfilling simultaneously with the cursor reset, and this seemed like the least bad option that could be done quickly.
The one capture that this is all targeted at is currently disabled. After these changes are live in production, that capture …

source-mysql: Two bits of production wrangling

---

materialize-mongodb/transactor.go

When setting a `notBefore` configuration there will be transactions with 0 stored documents. This adds a condition to prevent a panic trying to send a batch in Store when there aren't any documents to store.
- - - …

materialize-mongodb: don't send a batch if there were 0 documents

---

source-facebook-marketing/source_facebook_marketing/source.py
source-facebook-marketing/source_facebook_marketing/utils.py

Currently, the connector does not validate user provided account IDs can be successfully used to hit the Facebook Marketing API. This PR adds a check for this before task creation.
Tested on a local stack. Confirmed invalid account IDs are detected before task creation, and an error message is displayed indicating which account IDs are invalid.
- - - …

source-facebook-marketing: validate account ids

---

source-postgres/.snapshots/TestCIText-Capture
source-postgres/.snapshots/TestCIText-Discovery
source-postgres/capture_test.go
source-postgres/datatype_test.go
source-postgres/datatypes.go
source-postgres/discovery.go
source-postgres/docker-entrypoint-initdb.d/init-user-db.sh
source-postgres/main.go
source-postgres/replication.go

Arrays of `citext` are tricky because `citext` is an extension type which means that it has no stable OID, and as a result the PGX client library doesn't have any default type mappings for it. In the absence of any registered codec, values are always captured in their stringified text-protocol format.
However our discovery logic still notices that it's an array and emits the appropriate schema for an array of text values, which means there's a mismatch and we're not satisfying our own schema. Which is bad. While `citext` is an extension type, it's a common one and the citext extension ships as part of the Postgres release, so I believe we should still support it as best we can.
This commit fixes that by extending the "datatype tweaks" logic with a query against …

source-postgres: Support `_citext` columns

---

source-kinesis/connection.go

The AWS v2 Go SDK has a built in retry mechanism, but the default only retries 3 times before returning a fatal error.
This bumps that limit up so that the connector will continue retrying for ~5 minutes before failing with an error. This is the same configuration as we use for source-dynamodb - see https://github.com/estuary/connectors/blob/bf70257ea9a2dc3f56d9705c83751f67d50222e0/source-dynamodb/main.go#L74-L88 …

source-kinesis: bump maximum retry attempts

---

source-postgres/main.go

We're seeing frequent connection failures for some captures, so kinda just hoping that this might help with those.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2171)

source-postgres: increase connect timeout to 20s

---

go/network-tunnel/network_tunnel.go

Currently `source-oracle` does an unconditional `db.tunnel.Stop()` during shutdown regardless of whether a network tunnel exists, but the implementation of `Stop()` assumes that the tunnel must not be nil. This disagreement could be resolved in either direction, but it seemed cleaner to just make `Stop()` a no-op for nil receivers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2175)

network-tunnel: Don't fail on Stop() of nil tunnel

---

source-twilio/source_twilio/streams.py

`MessageMedia` was previously checking every message between the config's start date and the present for new media, then filtering out any media created before the last seen cursor value. That made incremental syncs take an extremely long time without any apparent progress; the stream could be searching through the past few years of messages when it usually only needs to search through the past few minutes.
This change makes the `MessageMedia` stream only check messages created since the most recent cursor value, falling back to the config's start date if no cursor value is present. This significantly speeds up the connector during incremental syncs.
This change also increases the date window size used when fetching a message's media from 1 year to 100 years. This reduces …

source-twilio: improve MessageMedia incremental sync speed

---

source-boilerplate/feature_flags.go
source-redshift-batch/.snapshots/TestBasicDatatypes-Capture
source-redshift-batch/.snapshots/TestFeatureFlagUseSchemaInference-Discovery
source-redshift-batch/.snapshots/TestFloatNaNs-Capture
source-redshift-batch/.snapshots/TestFloatNaNs-Discovery
source-redshift-batch/.snapshots/TestSpec
source-redshift-batch/driver.go
source-redshift-batch/main.go
source-redshift-batch/main_test.go

This PR introduces the `/advanced/feature_flags` config setting to the Redshift batch capture, adds a helper function in `source-boilerplate` for parsing those flags with default values and support for `no_` prefixes, and then uses that feature flags infrastructure to add a new one named `use_schema_inference` which when set causes discovered collection schemas to have `x-infer-schema: true` set so that they use the inferred schema in conjunction with the discovered schema.
This is useful because Redshift is a data warehouse where users often use very loose declared types on the tables, and then want to be able to rely on more precise as-used-in-practice type guarantees when materializing their dataset. For example, it's tolerably common to have no declared primary keys …

source-redshift-batch: Add the 'use_schema_inference' feature flag

---

source-sqlserver/.snapshots/TestFilegroupAndRole
source-sqlserver/.snapshots/TestGeneric-SpecResponse
source-sqlserver/main.go
source-sqlserver/main_test.go
source-sqlserver/prerequisites.go
source-sqlserver/replication.go

This commit adds new advanced options for the CDC instance filegroup and role_name arguments. If set, these values will be plugged into the appropriate query parameters whenever the connector tries to autocreate CDC instances. (If unset, they will be omitted so the behavior will be the same as it was prior to this change.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2180)

source-sqlserver: filegroup and role_name settings

---

source-postgres/database.go

When querying replication slot info for an invalidated slot, the `restart_lsn` column is typically null which resulted in a:
```
error querying replication slots: can't scan into dest[5]: can not scan <nil> to LSN
```
warning rather than the intended behavior where the query itself succeeds and because `wal_status == 'lost'` we instead warn that:
```
replication slot was invalidated by the server, it must be deleted and all bindings backfilled
```
Note that in either case this is currently just a warning and the actual error today is still:
```
runTransactions: readMessage: error creating replication stream: unable to start replication: ERROR: cannot read from logical replication slot "flow_slot" (SQLSTATE 55000)
```
I would like to get the logic working reliably in warn-mode before we …

source-postgres: Handle null restart_lsn values

---

go/network-tunnel/interface.go
go/network-tunnel/network_tunnel.go
source-bigquery-batch/main.go
source-mysql-batch/.snapshots/TestSpec
source-mysql-batch/main.go
source-postgres-batch/.snapshots/TestSpec
source-postgres-batch/main.go
source-redshift-batch/.snapshots/TestSpec
source-redshift-batch/main.go

Integrates network/SSH tunneling into the batch SQL connectors, with the exception of `source-bigquery-batch` since it's not self-evident how to apply it there and I'm just picking some extremely low-hanging fruit here.
In order to avoid copy-pasting a bunch of unnecessary bits of boilerplate, I have factored out some of the config structs and startup logic that other connectors used into the network tunnel Go package and am using that here. I have not gone back and modified the other dozen connectors with SSH tunneling support to use the more concise integration in this PR, but it's something we might want to do at some point just for code health reasons.
- - - …

Network Tunneling in Batch SQL Connectors

---

source-braintree-native/source_braintree_native/api.py
source-braintree-native/source_braintree_native/models.py
source-braintree-native/tests/snapshots/snapshots__spec__capture.stdout.json

Users have enough data in Braintree that a window size of 1 day (the smallest previously possible) wasn't small enough to ensure the connector wasn't missing data. Window size is now specified in hours, with the default updated to 24 hours.
- - - …

source-braintree-native: change window size from days to hours

---

source-braintree-native/source_braintree_native/models.py
source-braintree-native/source_braintree_native/resources.py
source-braintree-native/tests/snapshots/snapshots__discover__capture.stdout.json

Keys on full refresh resources need to be non-nullable. The key for these resources is now `_meta/row_id` instead of `id`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2192)

source-braintree-native: fix nullable key on full refresh resources

---

source-mysql/.snapshots/TestPrimaryKeyUpdate
source-mysql/capture_test.go
source-mysql/main_test.go
source-mysql/replication.go
source-postgres/.snapshots/TestPrimaryKeyUpdate
source-postgres/capture_test.go
source-sqlserver/.snapshots/TestPrimaryKeyUpdate
source-sqlserver/main_test.go

This PR adds tests to `source-{postgres,mysql,sqlserver}` exercising the capture behavior when a row is updated in a way which modifies its primary key. There are two ways this could be handled:
1. Just transcribe the update literally, with the new row as the collection key and the old primary-key value in the before-state metadata.
2. Generate a synthetic pair of a delete event for the old primary-key value, and an insert event for the new value.
Option (2) is more correct because it results in a deletion of the old row being propagated to any standard / merge update materializations, and also maintains the "the first mention of any previously-nonexisting key should be an insert event" invariant that is sometimes useful. Especially when combined with hard deletions, this …

source-mysql: Treat CDC updates which change the primary key as implicit deletions

---

source-braintree-native/source_braintree_native/api.py

~~The Braintree SDK's API calls are all synchronous, so they block the event loop, meaning only a subset of streams can make progress at a time. Adding `await asyncio.sleep(0)` to the top of the various fetch functions allows other streams to make progress since these functions now yield to the event loop.~~
~~Using `await asyncio.sleep(0)` within the connector-specific code for this purpose is a temporary measure until I refactor the connector to make asynchronous API requests.~~
I also fixed an issue with the search limit error message where the f-strings were not concatenated together & the full error message wasn't getting displayed. …

source-braintree-native: concatenate search limit error message

---

source-braintree-native/source_braintree_native/api.py

The Braintree SDK makes synchronous HTTP requests, which was blocking the main thread and preventing separate streams from sending concurrent API calls. Any HTTP requests made by the Braintree SDK are now wrapped in [`asyncio.to_thread`](https://docs.python.org/3/library/asyncio-task.html#asyncio.to_thread), which runs the function in a separate thread. This unblocks the main thread and lets separate streams make concurrent API calls.
The `maximum_size` property that indicates how many results are found in a specific date window is now used to throw search limit errors sooner instead of after we iterate through & count up all results.
Note: The `disputes` stream cannot use the `maximum_size` property because the Braintree SDK returns a `PaginatedCollection` instead of a …

source-braintree-native: run synchronous API calls in separate threads

---

source-http-ingest/Cargo.lock
source-kafka/Cargo.lock

Updates the Flow protocol pin for rust connectors to include array information in projection inference, per the changes in
https://github.com/estuary/flow/pull/1787.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2197)

source-{http-ingest,kafka}: update flow protocol pin

---

materialize-databricks/driver.go

Databricks Store queries may be split into multiple separate items for large file sizes. This fixing the logging so that the started / ending commit messaging is not emitted for each of the split queries, but rather for the entire binding.
- - - …

materialize-databricks: fix commit logging for split queries

---

source-mysql/.snapshots/TestPrimaryKeyUpdateOfOnlyChangesBinding
source-mysql/capture_test.go
sqlcapture/capture.go

We recently (in https://github.com/estuary/connectors/pull/2185) added some logic to `source-mysql` which detects row update events which modify the collection key of the row. Or more pedantically, it detects row updates which modify the value of "whatever columns we consider the row key to be made of", which is almost always the collection key.
_(We play a little fast-and-loose with the concepts at times and it works out because in practice nobody ever sets the collection key to something other than the source DB primary key or tries to tells us to backfill using some other key distinct from the collection key. In fact we should probably deprecate the ability to have a backfill key distinct from the collection key since it's an undocumented backwards-compatibility …

source-mysql: Fix primary-key update logic when applied to only-changes bindings

---

source-postgres/.snapshots/TestGeneric-SpecResponse
source-postgres/Dockerfile
source-postgres/capture_test.go
source-postgres/database.go
source-postgres/main.go
source-postgres/main_test.go
source-postgres/prerequisites.go
source-postgres/replication.go

This PR replaces the PostgreSQL CDC fence logic which was previously based on detection of our own watermark writes with some new (actually heavily copied from MySQL) fence logic based entirely on WAL LSN positions.
However by default we still write a watermark as part of establishing a fence position, in order to guarantee that there will be at least one WAL event whose LSN is greater than the minimum fence LSN. So the other half of this PR was adding a new advanced setting (`"Read-Only Capture"`) which disables that behavior.
Disabling watermark writes is not without its tradeoffs. Put simply, due to the way Postgres reorders and cleans up the underlying WAL events when doing logical replication, we can't always guarantee that the latest LSN value obtained from …

source-postgres: Support CDC without watermarks

---

source-hubspot-native/source_hubspot_native/api.py

The search API is used for requesting a stream of "delayed" records, held back by a 1 hour horizon, to account for the eventual consistency of the HubSpot APIs in general.
Sometimes we see that a record in our search result is returned out of order with respect to its "updated at" timestamp. When this happens, there ends up being a record with an "updated at" timestamp fairly near the present, and outside the upper limit that was requested.
We can only speculate as to why this happens, but it could be because the record is getting updated around the same time as we make our search request, and it is getting included in the search results based on its original timestamp, but we are getting the updated record in the place of where the original one should have been. …

source-hubspot-native: ignore search results with timestamps more recent than the requested window

---

source-genesys/source_genesys/api.py

In Python, default parameters are evaluated once when the function definition is executed ([source](https://docs.python.org/3/reference/compound_stmts.html#function-definitions)). This means that a default param of `datetime.now(tz=UTC)` is only evaluated when the program starts up, and that same value is used for each subsequent function call. Meaning that within the connector, `_perform_conversation_job` was using a fixed end date and not incrementing it over time.
Now, a default value of `None` is used in `_perform_conversation_job` to indicate that the current time should be used as the end date. …

source-genesys: fix `conversations` default param bug

---

source-bigquery-batch/Dockerfile
source-mysql-batch/Dockerfile
source-postgres-batch/Dockerfile
source-redshift-batch/Dockerfile

Left this out of https://github.com/estuary/connectors/pull/2190 by mistake.
Using network tunneling with a batch SQL capture ought to work now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2219)

source-*-batch: Add missing network-tunnel binary

---

source-hubspot-native/source_hubspot_native/resources.py
source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json

Not all HubSpot accounts have enough permissions to access the endpoint for the `email_events` binding. This binding is now discovered only if we can successfully hit the associated endpoint without a permissions error.
The permissions checking code isn't very reusable, but it can be refactored later if/when the connector needs to conditionally discover other bindings.
Tested on a local stack. Confirmed …

source-hubspot-native: conditionally discover `email_events` binding

---

materialize-s3-iceberg/catalog.go
materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
materialize-s3-iceberg/transactor.go

For materializations with a large number of bindings, running each "table append" action sequentially can end up taking quite a while.
These append actions can be run concurrently which requires some restructuring, but should make the commits complete quite a bit faster, and provide a significant reduction in latency.
- - - …

materialize-s3-iceberg: run table appends concurrently

---

materialize-s3-iceberg/catalog.go
materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
materialize-s3-iceberg/transactor.go

This reverts commit a79a235fa5439c1bf3ebef589bea1f8d9c3f8d42.
I'm seeing (intermittent) failures with the many concurrent requests to REST catalogs. The relevant error information doesn't seem to be making it through the Go/Python interface. Likely there needs to be some kind of retry mechanism implemented. I am reverting this for now until that can be investigated, since the intermittent crashes this is causing are probably worse than the latency boost it offered. …

Revert "materialize-s3-iceberg: run table appends concurrently"

---

source-oracle-flashback/source_oracle_flashback/api.py
source-oracle-flashback/source_oracle_flashback/resources.py

- debug logs to investigate an issue with a backfill task
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2227)

source-oracle-flashback: debug logs in backfill

---

source-oracle-flashback/source_oracle_flashback/api.py

- We were using `ROWNUM` to limit the number of rows, but that filter is applied before ordering, and that would lead to inconsistencies if ROWIDs were not in the order of insertion (sometimes ROWIDs can be reused if they have been freed up due to deletion / resize of data in data segments), a common pitfall of `ROWNUM` filtering which I fell for
- This was not  covered by our test cases because reproducing this behaviour is hard, we need ot somehow force the database to allocate an "older" ROWID to a new row
- Instead of using `ROWNUM` filtering we can use `FETCH NEXT %d ROWS ONLY` which has been introduced in Oracle 12c (released 2013). An alternative implementation is using a subquery like `SELECT * FROM (SELECT ...) WHERE ROWNUM < 50000` for older versions, but I'm …

source-oracle-flashback: order first, then limit row count

---

materialize-kafka/src/configuration.rs
source-kafka/src/configuration.rs

It seems SCREAMING-KEBAB-CASE does not put a dash before numbers. Tested by running `cargo test` with a `test.flow.yaml` file that had `credentials.mechanism: SCRAM-SHA-256` and verified with this PR the error no longer appears
- - - …

kafka: SASL mechanism must have a dash between before numbers

---

source-oracle-flashback/source_oracle_flashback/resources.py

update shortlinks to flashback docs instead of cdc oracle docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2230)

source-oracle-flashback: update docs links

---

source-stripe-native/source_stripe_native/api.py
source-stripe-native/tests/snapshots/snapshots__capture__stdout.json

The scope of this PR includes:
- Handling results that don't have a `created` field. 
- When backfilling, the connector was relying on all results having a `created` field to determine whether the result was within the backfill timespan. However, `Accounts` results do not always have a `created` field (I assume a legacy Stripe system or Stripe support created these accounts & circumvented whatever system adds the `created` field). Since the connector can't tell otherwise without `created`, it assumes the result is within the backfill timespan and yields it.
- Improving handling for when `Persons` cannot be read for an external account.
- Handling insufficient permission errors for `ExternalBankAccount` and `ExternalAccountCards` streams if the error is due to insufficient …

source-stripe-native: fix `Accounts` related bugs

---

source-braintree-native/source_braintree_native/api.py
source-braintree-native/tests/snapshots/snapshots__capture__capture.stdout.json
source-braintree-native/tests/test_snapshots.py

The `most_recent_created_at` bug detailed in this [PR](https://github.com/estuary/connectors/pull/2217) was also affecting other incremental streams, causing the connector to emit duplicate documents and progress very slowly through results. This PR fixes that bug for the other affected incremental streams - `customers`, `credit_card_verifications`, and `subscriptions`.
Fields within the capture snapshot test have also been redacted. These fields will change every month since they're related to subscriptions & monthly billing, so I'd rather redact them instead of updating them every month. …

source-braintree-native: fix cursor update bug for incremental streams

---

filesink/filesink.go
materialize-bigquery/.snapshots/TestValidateAndApply
materialize-bigquery/.snapshots/TestValidateAndApplyMigrations
materialize-databricks/.snapshots/TestValidateAndApply
materialize-databricks/.snapshots/TestValidateAndApplyMigrations
materialize-elasticsearch/.snapshots/TestValidateAndApply
materialize-elasticsearch/type_mapping.go
materialize-motherduck/.snapshots/TestValidateAndApply
materialize-motherduck/.snapshots/TestValidateAndApplyMigrations
materialize-mysql/.snapshots/TestValidateAndApply
materialize-mysql/.snapshots/TestValidateAndApplyMigrations
materialize-mysql/.snapshots/TestValidateAndApplyMigrationsMariaDB
materialize-postgres/.snapshots/TestValidateAndApply
materialize-postgres/.snapshots/TestValidateAndApplyMigrations
materialize-redshift/.snapshots/TestValidateAndApply
materialize-redshift/.snapshots/TestValidateAndApplyMigrations
materialize-s3-iceberg/.snapshots/TestValidateAndApply
materialize-s3-iceberg/type_mapping.go
materialize-snowflake/.snapshots/TestValidateAndApply
materialize-snowflake/.snapshots/TestValidateAndApplyMigrations
materialize-sql/type_mapping.go
materialize-sqlserver/.snapshots/TestValidateAndApply
materialize-sqlserver/.snapshots/TestValidateAndApplyMigrations
materialize-starburst/.snapshots/TestValidateAndApply
tests/materialize/materialize-elasticsearch/snapshot.json

This updates the materialize-elasticsearch constraints to be consistent with SQL materializations etc., where only the `_meta/op` field among `_meta/*` fields is recommended by default.
Pre-existing materializations will continue to recommended all previously selected fields, so this change is backward-compatible.
- - - …

materialize-elasticsearch: don't recommend _meta fields other than _meta/op

---

tests/materialize/run.sh

flowctl is required to run the materialization tests, not flowctl-go anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2237)

tests: update materialization tests to check for flowctl rather than flowctl-go

---

materialize-mysql/driver.go

For transactions with 0 Store requests, which may happen when a `notBefore` is set on the materialization, prevent a panic by not trying to flush the "final" binding when there aren't any bindings with data.
- - - …

materialize-mysql: handle transactions with 0 Store requests

---

source-mixpanel-native/source_mixpanel_native/source.py
source-mixpanel-native/source_mixpanel_native/spec.json
source-mixpanel-native/source_mixpanel_native/streams/base.py
source-mixpanel-native/source_mixpanel_native/streams/cohort_members.py
source-mixpanel-native/source_mixpanel_native/streams/engage.py
source-mixpanel-native/source_mixpanel_native/streams/export.py
source-mixpanel-native/tests/snapshots/snapshots__discover__capture.stdout.json
source-mixpanel-native/tests/snapshots/snapshots__spec__capture.stdout.json

A production `source-mixpanel-native` capture is OOM-ing on the `cohort_members` stream (and likely would OOM on the `engage` stream if it was enabled). This is happening because a single API response is large enough that it OOMs the connector. Typically this could be managed by using a smaller page size for API responses, but the Mixpanel API has a harsh rate limit (1 request / minute) and using a page size small enough to *not* OOM would make the connector take over 24 hours to complete (our self-enforced limit before restarting connectors). To address this, the `engage` stream now works as an incremental stream & the `cohort_members` stream only gets the minimum properties necessary to identify which document in the `engage` stream is associated with a given …

source-mixpanel-native: incremental `engage` & new config settings

---

source-mixpanel-native/source_mixpanel_native/streams/cohort_members.py

Follow up to https://github.com/estuary/connectors/pull/2244 to enable the `minimal_cohort_members_properties` functionality. All existing tasks that have `cohort_members` enabled have been updated with the appropriate `minimal_cohort_members_properties` config value, so it's safe to turn on the associated functionality.
- - - …

source-mixpanel-native: enable `minimal_cohort_members_properties` functionality

---

source-hubspot-native/config.yaml
source-hubspot-native/source_hubspot_native/api.py
source-hubspot-native/source_hubspot_native/resources.py

This makes the property history configuration active, so that users can optionally opt-in to capturing property history.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2258)

source-hubspot-native: enable the property history configuration

---

materialize-bigquery/query.go

The retry logical calculation was going haywire at larger retry counts. I think it might have been due to an overflow, although I am unable to reproduce this on my local machine and am not 100% convinced it is the cause.
But this change is very simple and I can't see how it wouldn't work at higher retry counts, so I'd like to see if it takes care of the problem. …

materialize-bigquery: fix query retry logic calculation

---

source-intercom-native/source_intercom_native/api.py
source-intercom-native/source_intercom_native/models.py
source-intercom-native/source_intercom_native/resources.py
source-intercom-native/tests/snapshots/snapshots__spec__capture.stdout.json

Intercom has two separate endpoints for retrieving companies: `/companies/list` (limited to 10k companies) and `/companies/scroll` (limited to only one "scroll" happening at a time). For users that have more than 10k companies in their Intercom account, they will need to use the `/companies/scroll` endpoint to ensure no data is missed.
The connector previously always used the `/companies/list` endpoint, and this PR adds the ability to use the `/companies/scroll` endpoint instead. The new `use_companies_list_endpoint` config option controls which of the two company-related endpoints are used. Within the connector, an `asyncio.Lock` is used to avoid attempting concurrent "scrolls" between the two streams that want to use `/companies/scroll` - `companies` and …

source-intercom-native: add config option to use `/companies/scroll` endpoint

---

source-hubspot-native/source_hubspot_native/models.py

Omit the frivolous empty object for an empty propertiesWithHistory, so that it is not picked up by schema inference. The default setting will not capture propertiesWithHistory so having this empty object in every document would likely be confusing.
- - - …

source-hubspot-native: don't serialize empty object for empty propertiesWithHistory

---

source-hubspot-native/acmeCo/companies.schema.yaml
source-hubspot-native/acmeCo/contacts.schema.yaml
source-hubspot-native/acmeCo/deals.schema.yaml
source-hubspot-native/acmeCo/engagements.schema.yaml
source-hubspot-native/acmeCo/line_items.schema.yaml
source-hubspot-native/acmeCo/products.schema.yaml
source-hubspot-native/acmeCo/tickets.schema.yaml
source-hubspot-native/source_hubspot_native/models.py
source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json

Since the top-level document has `additionalProperties: false`, the optional `propertiesWithHistory` property needs to be in the schema, otherwise when the option is turned on the capture this property there will be a schema violation.
This adds the property back to the schema, but makes it nullable, since it won't always be there.
- - -
This change …

source-hubspot-native: schematize propertiesWithHistory, but make it nullable

---

materialize-boilerplate/logging.go
materialize-boilerplate/logging_test.go

Materializations can send acknowledgement messages concurrently with reading load or flush messages. This would show up occasionally as a panic due to concurrent access of variables in the "waiting for documents" part of the extendedLogger event handler.
This adds a mutex to guard that concurrent access.
- - - …

materialize-boilerplate: fix race condition in extended logger

---

source-firestore/pull.go

Typically the whole "we have to go re-backfill the collection because it's inconsistent" thing only triggers on massive collections which are likely to fail again in the future, _and_ Firestore is really an expensive datastore, so having a default of re-backfilling these collections at most once per day is a nontrivial cost savings.
I'm taking the simplest, dumbest possible route here and just changing the existing hard-coded constant from 6 to 24 hours.
I'd like to go and make this user-configurable at some point, but that's actually more complicated than it seems because of how multiple bindings can share a collection ID and thus fail and need restarting as a group.
This fixes https://github.com/estuary/connectors/issues/2250
- - - …

source-firestore: Increase re-backfill period from 6h to 24h

---

source-bigquery-batch/driver.go
source-mysql-batch/driver.go
source-mysql-batch/main.go
source-postgres-batch/driver.go
source-redshift-batch/driver.go

This PR adds no-data watchdog timeouts to all of the batch SQL connectors, such that if a long period of time passes without any rows being received (when we're awaiting polling query results) it will kill the capture. The time period is pretty generous: 30 minutes when we're waiting for the first result row and 5 minutes for subsequent rows. Pretty much the only times this watchdog should fire are:
- When the database connection has silently dropped on us (which is a thing that happens sometimes, especially when using SSH tunneling)
- When the polling query is performing a full-table sort on some massive dataset. And generally speaking if that hasn't finished after 30 minutes it's not likely that we'll actually end up with a successful capture and a pleasant user …

source-*-batch: Timeouts and partial-progress logging

---

source-facebook-marketing/source_facebook_marketing/schemas/ads_insights.json
source-facebook-marketing/tests/snapshots/snapshots__discover__capture.stdout.json

Multiple production tasks have encountered errors where any async job requesting the `wish_bid` field have started consistently failing on Facebook's side. Async jobs that do not request `wish_bid` still succeed.
Removing `wish_bid` from the `ads_insights.json` schema file also removes it from the list of fields requested from async jobs, and tasks that were previously failing should now work fine. It's unclear to me what changed that causes async jobs requesting the `wish_bid` field to fail, and maybe it can be added back later if there's motivation to investigate further & determine root cause.
Discover snapshot changes are expected since `wish_bid` has been removed from the `ads_insights` stream and its children.
(How does one use this feature, and …

source-facebook-marketing: remove wish_bid from `ads_insights.json`

---

materialize-bigquery/bigquery.go
materialize-bigquery/transactor.go

The storage read API is dramatically faster at retrieving large query results than the standard job read or table read API. On a test with 10 million rows of synthetic data returned by a load query, I have observed a reduction in processing time from ~21 minutes using the job read API down to ~3 minutes using the storage read API with a `materialize-bigquery` task running on our public data plane.
Historically we have not enabled the storage read API due to its extreme negative effect on memory usage in the connector. Based on testing with the more recent version of the BigQuery client we are now using, this memory situation seems to no longer be an issue at all, with query results read by the storage read API using comparable amounts of memory as the slower standard …

materialize-bigquery: use the storage read API if available for load queries

---

source-postgres/main.go

Statement timeouts are never our friend. Let's try disabling the timeout unconditionally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2283)

source-postgres: Try setting statement_timeout = 0

---

source-postgres/replication.go

It's causing problem for at least one production task and the failure mode this guards against is much less important in the immediate term than allowing production to catch back up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2285)

source-postgres: Make stream-to-fence watchdog 12 hours

---

source-mysql/.snapshots/TestGeneric-SpecResponse
source-mysql/discovery.go
source-mysql/main.go

Adds an advanced option which allows users to explicitly list which schemas they want to discover tables from. If unset we'll continue to discover all non-system schemas as before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2289)

source-mysql: Discovery schema whitelist option

---

source-zendesk-support/acmeCo/ticket_audits.schema.yaml
source-zendesk-support/source_zendesk_support/schemas/ticket_audits.json
source-zendesk-support/source_zendesk_support/streams.py
source-zendesk-support/test.flow.yaml
source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json
source-zendesk-support/tests/unit_test.py

The previously used `/ticket_audits` endpoint used to list all ticket audits always returns results in descending order and did not let us specify a date window/start date to filter what results are returned. This prevented the connector from checkpointing during backfills, and if backfills spanned 24+ hours, they wouldn't complete since the CDK restarts the connector after it's been running for 24 hours.
The `ticket_audits` stream now uses `tickets` as a parent stream, fetching an updated ticket then fetching the audits for that ticket. Although this makes the stream slower since it now makes more HTTP requests to get results, this is the only way I found to get `ticket_audits` in ascending order & let us checkpoint progress for backfills spanning 24+ hours.
Additional …

source-zendesk-support: update `ticket_audits` to checkpoint during backfills

---

source-zendesk-support/acmeCo/ticket_audits.schema.yaml
source-zendesk-support/source_zendesk_support/schemas/ticket_audits.json
source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json

Fast follow-up to https://github.com/estuary/connectors/pull/2288. Existing captures have started hitting schema violations for `ticket_audits`. This PR addresses the violations I've seen so far, but more may pop up later & need addressed as captures backfill.
- - - …

source-zendesk-support: address various ticket_audits schema violations

---

source-sqlserver/.snapshots/TestAlterationAddColumn-Automatic
source-sqlserver/.snapshots/TestDroppedAndRecreatedTable
source-sqlserver/.snapshots/TestGeneric-SpecResponse
source-sqlserver/discovery.go
source-sqlserver/main.go
source-sqlserver/main_test.go

This commit adds a new feature flag (and since this is the first one added to the SQL Server capture, all of the feature flag boilerplate as well) which when set causes the connector to use capitalized variants of all discovery queries.
Previously table names, column names, and the like were lowercase in our discovery queries because it looks nicer and the distinction doesn't matter in most databases since they use a case-insensitive collation for table names anyway. But there exists at least one locale where the distinction matters, so we should probably have that capitalized normally anyway.
I'm reasonably sure the case change itself is a safe change to make across the board, but it's Friday and I'm fighting off a cold so I would really prefer not to make any …

source-sqlserver: Uppercase discovery flag

---

source-braintree-native/source_braintree_native/api.py
source-braintree-native/source_braintree_native/models.py
source-braintree-native/source_braintree_native/resources.py

Incremental streams (except `transactions`) must be periodically backfilled to capture updates. This PR splits incremental streams into distinct backfill & incremental processes so the connector can continue making incremental progress while periodic backfills run.
The window size for `disputes` is also restricted to always be 24 hours or more due to the `date` granularity of the `received_date` search field used; searching with date windows smaller than 24 hours will return duplicate results & slow the stream down, especially during backfills.
After merging, existing captures should be backfilled. We may want to consider timing this release with a planned periodic backfill. …

source-braintree-native: split incremental streams into distinct incremental & backfill processes

---

materialize-elasticsearch/type_mapping.go
tests/materialize/materialize-elasticsearch/snapshot.json

Strings formatted as numeric values have have source fields with multiple types of `string` and `integer` / `number`, but these values should not be wrapped a synthetic flattened object since they aren't really "multiple type" fields, but are materialized as their respective numeric value.
- - - …

materialize-elasticsearch: don't flatten strings formatted as numeric values

---

source-mysql/discovery.go
source-oracle/discovery.go
source-postgres/.snapshots/TestFloatKeyDiscovery
source-postgres/.snapshots/TestFloatKeyDiscovery-capture
source-postgres/.snapshots/TestScanKeyTypes-Double
source-postgres/.snapshots/TestScanKeyTypes-Real
source-postgres/datatypes.go
source-postgres/discovery.go
source-postgres/discovery_test.go
source-sqlserver/discovery.go
sqlcapture/discovery.go
sqlcapture/interface.go

Flow won't / can't accept a `type: [string, number], format: number` as a collection key. We have to support strings as serialized float values because they need to be able to hold special values such as `"NaN"` and `"Infinity"`, so in order to make float keys work right we have to always stringify them.
Capturing from tables with `REAL` and `DOUBLE PRECISION` primary keys should now Just Work, where previously it would inevitably fail. Any captures which were previously working should be unaffected, because this only changes the behavior when the floating-point value occurs in the primary key of the table.
- - - …

source-postgres: Always stringify float keys

---

materialize-sql/std_sql.go

- The previous log line made it seem like it was actually doing the migration, but in reality it is only rendering queries for migration. In cases of multiple column migration the previous message made it seem like all but the last column had already been migrated in milliseconds while the last one was taking its time. This threw me off just now while debugging a task. …

materialize-sql: change column migration misleading log message

---

materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
materialize-s3-iceberg/transactor.go

This fixes a bug where the previous/current tracked checkpoint hash for disabled bindings would be erroneously advanced for disabled bindings that have a pending staged commit that will be applied if their binding is ever enabled again.
It also includes a temporary disabling of the sanity check that ensures checkpoint hashes advanced as we expect, since some tasks are in a state where this is not true. …

materialize-s3-iceberg: fix checkpoint accounting for disabled bindings

---

source-oracle/prerequisites.go

- When we check supplemental logging, we do it on the CDB level because it is a database-level configuration, but if database-level supplemental logging is not enabled, when checking table-level we need to check on the PDB level because that's where the tables are
- - - …

source-oracle: fix prerequisites table-level logging check run on pdb

---

source-oracle/discovery.go

- Turns out these some of these `NUMBER` fields used by one of our customers are actually primary keys. We now allow floating point keys, so I'm removing this check in the connector
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2314 …

source-oracle: floating points can be keys

---

source-mysql/replication.go

Generally speaking we shouldn't see BEGIN/COMMIT/ROLLBACK events in the binlog, and we can't actually support a rollback on a table that we're actively processing since we've already emitted the changes. But since we do see them in certain edge cases we ought to ignore them properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2321)

source-mysql: Ignore ROLLBACK query events

---

estuary-cdk/estuary_cdk/http.py
estuary-cdk/estuary_cdk/incremental_json_processor.py
estuary-cdk/pyproject.toml
estuary-cdk/tests/test_incremental_json_processor.py
source-google-sheets-native/source_google_sheets_native/api.py
source-zendesk-support-native/source_zendesk_support_native/api.py

A prior implementation of incremental JSON processing was able to yield records from a JSON stream by prefix, discarding everything else from the stream. That suits cases where the entire dataset is represented in a single large response, but there are cases where the dataset is represented by multiple potentially very large responses, and each of those responses contains some extra information we need to proceed, such as a paging token. Parsing and processing those responses while keeping memory usage efficient within the connector can be a challenge.
This adds the ability to read a JSON stream incrementally and yield records by prefix, while also returning anything that's left at the end. Effectively this "remainder" is built up while processing the document as an …

estuary-cdk: expand capabilities for incremental json processing

---

source-firestore/.snapshots/TestDocumentReferences-backfill
source-firestore/.snapshots/TestDocumentReferences-replication
source-firestore/main_test.go
source-firestore/pull.go

This PR adds a test demonstrating that backfills and replication used to emit Firestore document references in two different representations. In replication we would emit the path as a string like:
```
"projects/project-id-123456/databases/(default)/documents/flow_source_tests/TestDocumentReferences/docs/1"
```
whereas in backfills we would emit a hairy recursive struct like:
```
{
"Parent": {
"Parent": {
"Parent": {
"Parent": null,
"Path": "projects/project-id-123456/databases/(default)/documents/flow_source_tests",
"ID": "flow_source_tests"
},
"Path": "projects/project-id-123456/databases/(default)/documents/flow_source_tests/TestDocumentReferences",
"ID": "TestDocumentReferences"
},
"Path": "projects/project-id-123456/databases/(default)/documents/flow_source_tests/Test …
```

source-firestore: Capture document references as strings in backfills too

---

source-zendesk-support-native/source_zendesk_support_native/api.py
source-zendesk-support-native/source_zendesk_support_native/models.py
source-zendesk-support-native/source_zendesk_support_native/resources.py

This PR includes a few miscellaneous fixes for bugs in `source-zendesk-support-native`. These fixes include:
1. Validating the `start_date` is at least the epoch so converting to a timestamp always results in a non-negative number.
2. Avoiding `aiohttp` `TimeoutError`s for ticket child streams by not trying to maintain a long-lived streaming response when fetching parent tickets.
3. Using a smaller page size for `ticket_metrics` to reduce how much processing Zendesk must do for a response & avoid intermediate gateways from sending us 504 timeout responses.
i. We might want to make this configurable later or surface 5xx responses through our CDK at some point, but that level of effort isn't necessary right now.
(How does one use this feature, and how …

source-zendesk-support-native: misc fixes

---

source-zendesk-support-native/source_zendesk_support_native/api.py
source-zendesk-support-native/source_zendesk_support_native/models.py
source-zendesk-support-native/source_zendesk_support_native/resources.py
source-zendesk-support-native/tests/snapshots/snapshots__spec__capture.stdout.json

If a user's Zendesk account has extremely large tickets/users and we request a sufficiently large number of results per page, it's possible to receive 504 responses from the intermediate gateways if Zendesk takes too long to send back results. Instead of tinkering with this in the connector code whenever this comes up, I'm opting to make this a configurable setting that's easily adjusted on a per capture basis.
A future improvement would be to automatically detect these types of 504 responses & dynamically reduce the page size. That's a bit more involved though since our CDK automatically retries any requests that receive 5xx responses, meaning the connector code never sees these 5xx errors. Determining if/how the CDK should expose 5xx responses is left as a later …

source-zendesk-support-native: add configurable page size for incremental export streams

---

source-sqlserver/backfill.go
source-sqlserver/docker-initdb.sh
source-sqlserver/main.go
source-sqlserver/main_test.go
source-sqlserver/prerequisites.go
source-sqlserver/replication.go

This PR adds support to the SQL Server CDC connector for running without watermark writes. This new support exists side-by-side with the existing watermark-based mechanism, and can be enabled on a specific capture by adding the `read_only` feature flag to the advanced endpoint config.
Watermark-free CDC requires an additional database permission (`VIEW DATABASE STATE`, or in SQL Server 2022+ `VIEW DATABASE PERFORMANCE STATE` also suffices) which isn't granted by default, so we can't currently turn it on for preexisting captures. However other than the setup obstacle, there should be no downside to the new implementation [1].
[1] This is contrasted with the PostgreSQL situation, where read-only CDC has legitimate operational downsides and so we expect to retain both modes …

source-sqlserver: Support CDC without watermarks

---

source-postgres/.snapshots/TestGeneric-SpecResponse
source-postgres/discovery.go
source-postgres/main.go
source-postgres/main_test.go
sqlcapture/discovery.go
sqlcapture/interface.go

This PR adds a feature flag `use_schema_inference` to `source-postgres` which when set causes `x-infer-schema: true` to be added to discovered schemas.
Actually figuring out the right spot to add the `x-infer-schema` annotation was surprisingly tricky, what I ended up doing was adding a third "partial schema" to the top-level `allOf`, where the new schema is literally just `{"x-infer-schema": true}`. I think that works?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2337)

source-postgres: Feature flag `use_schema_inference`

---

materialize-snowflake/.snapshots/TestSQLGeneration
materialize-snowflake/sqlgen.go
tests/materialize/materialize-snowflake/snapshot.json

When querying data from staged JSON files, Snowflake interprets a present JSON `null` value as a JSON null rather than a SQL null, and we end up with values in variant columns that aren't SQL null, but are actually JSON null instead.
The most expedient way to fix this it seems to is to do some casting in the queries that interact with the staged JSON files, replacing JSON nulls with SQL nulls where needed.
Closes [#2068](https://github.com/estuary/connectors/issues/2068) …

materialize-snowflake: use SQL nulls instead of JSON nulls for null variants

---

materialize-s3-iceberg/driver.go
materialize-s3-iceberg/driver_test.go

Unless the delta updates configuration is explicitly false, we will consider delta updates to be enabled.
Practically speaking the connector only works in delta updates mode, and will error out if this is set to false.
This will allow the materialization to work with a `sourceCapture` set, with new bindings added an absent configuration value for `delta_updates`. …

materialize-s3-iceberg: default to delta updates if config is absent

---

materialize-snowflake/sqlgen.go

All of our upstream processing allows JSON objects with duplicate keys to exist, so it is possible for an object like this to end up in Snowflake's JSON parsing.
Unfortunately the default Snowflake parsing behavior is to error out if there is a duplicate key, but this configuration will instead cause it to follow the convention of just taking the last value for the duplicated key.
It's set on the created stage for simplicity. This means it won't retroactively apply to all existing stages, but this is a very rare thing so I think it's fine to handle on a go-forward basis. If it happens (again) with any existing materialization, the resolution is to run the query `ALTER STAGE flow_v1 SET FILE_FORMAT = (TYPE = JSON BINARY_FORMAT = BASE64 ALLOW_DUPLICATE = TRUE);`. If this …

materialize-snowflake: set the file format to allow duplicate keys

---

materialize-snowflake/.snapshots/TestSQLGeneration
materialize-snowflake/snowflake.go
materialize-snowflake/sqlgen.go
materialize-snowflake/sqlgen_test.go

Bound load queries by the minimum & maximum values for observed keys to load. This may help reduce costs associated with scanning data which we know does not contain values we are interested in.
See also https://github.com/estuary/connectors/pull/2348, which implemented this in a very similar way for `materialize-bigquery`
- - - …

materialize-snowflake: use range hints for load queries

---

source-oracle/main.go

- The default value meant that if somebody clicked on Advanced and set something else, their watermarks table would be set to the literal `USER.FLOW_WATERMARKS` which would be wrong in most cases
- - - …

source-oracle: fix wrong default value for watermarks table

---

source-mysql/.snapshots/TestGeneric-SpecResponse
source-mysql/discovery.go
source-mysql/main.go
source-mysql/main_test.go

Adds feature flag `date_schema_format` which when set will cause date columns to have `format: date` in their discovery output.
If absolutely necessary you could add that manually to a task's advanced config, but if you can wait a bit I'm going to change the default in the near future and then no action will be required for new tasks and preexisting tasks will be able to opt in by removing the `no_date_schema_format` flag setting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2374)

source-mysql: Feature-flagged date fix

---

source-mysql/.snapshots/TestMariaDBTypeUUID-capture
source-mysql/.snapshots/TestMariaDBTypeUUID-discovery
source-mysql/.snapshots/TestMariaDBTypeUUID-scankey
source-mysql/datatype_test.go
source-mysql/discovery.go

MySQL doesn't have a dedicated UUID column type but MariaDB does. This commit adds a test case and support for the column type. The only tricky bit is that we get UUID values back in their standard string format from backfills and as 16 raw bytes from replication, so we need to support both representations and emit them both such that they satisfy `{type: string, format: uuid}`.
This fixes https://github.com/estuary/connectors/issues/2376
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2377)

source-mysql: Support MariaDB 'UUID' column type

---

docs/feature_flags.md
scripts/bulk-config-editor.sh
scripts/bulk-config-editor/editing.go
scripts/bulk-config-editor/main.go
scripts/bulk-publish.sh
scripts/bulk-publish/main.go
scripts/list-tasks.sh
scripts/list-tasks/main.go

This PR adds the following:
* Documentation in `docs/feature_flags.md` which describes the intended purpose of connector feature flags, how to introduce a new feature flag when changing the default behavior of a connector, and how to set a flag on all production tasks.
* A tool `scripts/list-tasks.sh` which can query the Supabase `live_specs` table to list all tasks running (any variant of) a particular connector and, optionally, add them all to the active `flowctl` draft.
* Another tool `scripts/bulk-config-editor.sh` which can edit all endpoint config YAML files under a particular directory to add a feature flag setting. It handles encrypted-vs-plaintext configs, extends or introduces the `/advanced/feature_flags` property as needed, and skips configs which already have …

Docs and scripts for bulk editing feature flags

---

source-postgres/backfill.go
source-postgres/datatype_test.go
source-postgres/datatypes.go
source-postgres/discovery.go
source-postgres/main.go
source-postgres/replication.go

This PR adds two new feature flags:
- The `date_as_date` flag causes DATE columns to be captured as YYYY-MM-DD dates which satisfy `{type: string, format: date}` where previously they were serialized as full RFC3339 timestamps.
- The `time_as_time` flag causes TIME (aka TIME WITHOUT TIME ZONE) columns to be captured as HH:MM:SS.PPPZ time values which satisfy `{type: string, format: time}` where previously they were captured as Unix microsecond timestamps.
Both of these changes are long-awaited fixes to user complaints that would have been trivial to address except that it would conflict with an unknown amount of historical collection data.
We will be setting `no_date_as_date,no_time_as_time` on all production captures in the near future and then flipping the default so …

source-postgres: Flagged DATE and TIME fixes

---

source-postgres/backfill.go
source-postgres/datatype_test.go
source-postgres/datatypes.go
source-postgres/discovery.go
source-postgres/main.go
source-postgres/replication.go

Reverts estuary/connectors#2381
Bug in null value handling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2393)

Revert "source-postgres: Flagged DATE and TIME fixes"

---

source-jira-native/source_jira_native/streams.py

I missed applying the fix in e329435 to the `project_avatars`, `project_components`, and `project_permission_schemes` streams.
I did not test on a local stack to confirm this works, but I'm fairly confident it will considering it's the same issue that should be resolved by https://github.com/estuary/connectors/pull/2394.
- - - …

source-jira-native: skip fetching child resources of deleted projects (additional streams)

---

source-postgres/.snapshots/TestCIText-Discovery
source-postgres/discovery.go

Previously the generated JSON schema for a nullable array-valued column in Postgres would have duplicate `type` properties: one nullable and one not. This fixes that duplication.
I did a quick check and it appears that this is only an issue for Postgres and only shows up in this one test snapshot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2392)

source-postgres: Fix duplicate `type` on arrays

---

source-postgres/.snapshots/TestGeneratedColumn-capture
source-postgres/.snapshots/TestGeneratedColumn-discovery
source-postgres/backfill.go
source-postgres/capture_test.go
source-postgres/discovery.go

Generated columns cannot be captured via logical replication, so we should't mention them in our discovered schemas or capture their values via backfill either.
This bring PostgreSQL up to parity with how SQL Server handles computed columns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2397)

source-postgres: Omit generated columns from schemas

---

materialize-azure-fabric-warehouse/.snapshots/TestSQLGeneration
materialize-azure-fabric-warehouse/sqlgen.go
materialize-azure-fabric-warehouse/staged_file.go
materialize-boilerplate/stream-encode/csv.go
materialize-boilerplate/stream-encode/csv_test.go
materialize-sql/templating.go

Eliminate allocations and allow for specifying an alternate quote character to improve the performance of CSV encoding.
The benefits from these changes are pretty significant, about an order of magnitude faster encoding for streams of representative JSON documents. For optimum performance it is important to not have to escape many quote characters, so picking something than a double quote is best since our JSON documents will typically have a lot of those ex. the `flow_document` field.
The CSV encoder is about equivalent with our optimized JSON encoder now, and the CPU time for both is dominated by the compression activity rather than the serialization.
(list any …

materialize-boilerplate: CSV encoder optimizations

---

source-postgres/discovery.go

The new generated columns logic assumed that the PostgreSQL version is recent enough to support generated columns, but they were only added in v12 and we support earlier versions, so we ought to handle failures of that query non-fatally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2403)

source-postgres: Don't fail on pre-12 PostgreSQL

---

estuary-cdk/estuary_cdk/__init__.py
estuary-cdk/estuary_cdk/requests_session_send_patch.py
estuary-cdk/estuary_cdk/shim_airbyte_cdk.py
source-airtable/source_airtable/__main__.py
source-asana/source_asana/__main__.py
source-brevo/source_brevo/__main__.py
source-facebook-marketing/source_facebook_marketing/__main__.py
source-google-ads/source_google_ads/__main__.py
source-hubspot/source_hubspot/__main__.py
source-iterable/source_iterable/__main__.py
source-jira-native/source_jira_native/__main__.py
source-klaviyo/source_klaviyo/__main__.py
source-linkedin-ads-v2/source_linkedin_ads_v2/__main__.py
source-linkedin-pages/source_linkedin_pages/__main__.py
source-mixpanel-native/source_mixpanel_native/__main__.py
source-recharge/source_recharge/__main__.py
source-twilio/source_twilio/__main__.py
source-zendesk-support/source_zendesk_support/__main__.py

There have been tricky, intermittent cases of imported Airbyte connectors hanging with essentially no network traffic. I've added some additional logging when a `SIGQUIT` is injected & in the `CaptureShim`'s methods to help debug when these imports hang.
I also have a theory that since Airbyte imports use the `requests` package to make synchronous HTTP requests, the `requests` package doesn't have any default timeouts, and I can't find anywhere in the `airbyte_cdk` where a timeout is specified for `requests`, that setting a timeout for `requests` _might_ prevent Airbyte imports from hanging until the connector is restarted after 24 hours. I've made `requests_session_send_patch.py` to patch in a default timeout, and imported it in all Airbyte imports. I'm not certain the …

estuary-cdk: additional SIGQUIT logging & patching `requests.Session.send` for Airbyte imports

---

sqlcapture/main.go

Rewinding binlog cursor to hopefully get a couple production tasks unstuck. Ask @willdonnelly for additional context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2408)

sqlcapture: Cursor replacements for prod tasks

---

source-postgres/backfill.go
source-postgres/datatype_test.go
source-postgres/datatypes.go
source-postgres/discovery.go
source-postgres/main.go
source-postgres/replication.go

This reverts commit 8fd9b99543b28e2fd47891956ae4af66b25ff55c, which was itself a revert of the original implementation, and adds fixes/tests for:
- The incorrect null-value handling that forced the revert.
- Also arrays-of-dates being translated incorrectly when the new flag is set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2395)

source-postgres: Flag for new DATE and TIME format

---

source-klaviyo/source_klaviyo/streams.py
source-klaviyo/tests/test_streams.py

While most streams are using version 2023-10-15 of Klaviyo's API, `campaigns` and `profiles` are on earlier versions. This PR updates both streams to use API version 2023-10-15.
Changes from the updates are mainly to the location of certain properties in each stream's documents.
The `attributes.message` property is now under the `relationships.campaign-messages.data[0].id` location.
The `attributes.subscriptions.email.marketing.suppressions` field is renamed to `attributes.subscriptions.email.marketing.suppression` (i.e. from plural to singular).
A note about `campaigns`. In API versions including 2023-10-15 and later, Klaviyo now has different types of campaigns. Previously, only email campaigns were returned from the `/campaigns` endpoint, but in version 2023-10-15 SMS …

source-klaviyo: upgrade API version for `campaigns` and `profiles` to 2023-10-15

---

source-zendesk-support-native/acmeCo/account_attributes.schema.yaml
source-zendesk-support-native/acmeCo/automations.schema.yaml
source-zendesk-support-native/acmeCo/custom_roles.schema.yaml
source-zendesk-support-native/acmeCo/flow.yaml
source-zendesk-support-native/acmeCo/group_memberships.schema.yaml
source-zendesk-support-native/acmeCo/organizations.schema.yaml
source-zendesk-support-native/acmeCo/post_comment_votes.schema.yaml
source-zendesk-support-native/acmeCo/post_comments.schema.yaml
source-zendesk-support-native/acmeCo/post_votes.schema.yaml
source-zendesk-support-native/acmeCo/posts.schema.yaml
source-zendesk-support-native/acmeCo/schedules.schema.yaml
source-zendesk-support-native/acmeCo/sla_policies.schema.yaml
source-zendesk-support-native/acmeCo/ticket_forms.schema.yaml
source-zendesk-support-native/acmeCo/topics.schema.yaml
source-zendesk-support-native/source_zendesk_support_native/api.py
source-zendesk-support-native/source_zendesk_support_native/models.py
source-zendesk-support-native/source_zendesk_support_native/resources.py
source-zendesk-support-native/test.flow.yaml
source-zendesk-support-native/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support-native/tests/snapshots/snapshots__discover__capture.stdout.json

- Adding streams to bring `source-zendesk-support-native` on (and above) stream parity with the imported `source-zendesk-support`.
-  Added streams include:
- `account_attributes`
- `automations`
- `custom_roles`
- `group_memberships`
- `organizations`
- `post_comment_votes`
- `post_comments`
- `post_votes`
- `posts`
- `schedules`
- `sla_policies`
- `ticket_forms`
- `topics`
- Increasing the default interval for resources that have infrequent updates.
- Conditionally discover `account_attributes` and `audit_logs` if the provided credentials have access to the appropriate endpoints.
See individual commits for more details.
Documentation …

source-zendesk-support-native: add streams to achieve parity with imported connector

---

source-mysql/.snapshots/TestAlterTable_RenameColumnCaseInsensitive-discover
source-mysql/.snapshots/TestAlterTable_RenameColumnCaseInsensitive-init
source-mysql/.snapshots/TestAlterTable_RenameColumnCaseInsensitive-renamed
source-mysql/main_test.go
source-mysql/replication.go

Apparently column names in MySQL are always case-insensitive, which means that it's possible to issue a DDL query naming a column with different capitalization from what we've got in our metadata, and that ought to work.
This is solved by using a case-sensitive lookup from the column name in the DDL alteration query to an index in our metadata, and then "canonicalizing" the name to match what's in our metadata so that the rest of the metadata update logic works reliably.
This fixes https://github.com/estuary/connectors/issues/2421
No user action required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2422)

source-mysql: Handle inconsistent column name case

---

source-sqlserver/main.go

This commit just flips the default setting for the `read_only` feature flag so that any new captures without `no_read_only` set will operate in watermark-less mode. It will be merged immediately after `no_read_only` is set on all captures currently in production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2385)

source-sqlserver: Make 'read_only' the default

---

source-postgres/replication.go

Apparently Google's AlloyDB added a gratuitous fifth field to the IDENTIFY_SYSTEM command results, which currently breaks the helper function pglogrepl.IdentifySystem which expects there to be exactly the four fields one gets back from PostgreSQL.
The only thing we use IdentifySystem for is to establish the WAL flush location on the server, and we already have our own function (`queryLatestServerLSN`) which does precisely that and doesn't rely on parsing the IDENTIFY_SYSTEM result, so let's just use that one instead.
There shouldn't be any user-visible impact except that AlloyDB captures work.
- - - …

source-postgres: Don't use IDENTIFY_SYSTEM

---

source-mysql/datatype_test.go
source-mysql/main.go

This commit flips the default behavior for the `date_schema_format` feature flag. It will be merged immediately after all production MySQL captures have been modified with the `no_date_schema_format` setting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2384)

source-mysql: Make `date_schema_format` the default

---

source-sqlserver/.snapshots/TestGeneric-SpecResponse
source-sqlserver/main.go

Changes the wording of the watermarks table advanced config property to tell users that it's deprecated for new captures.
Part of https://github.com/estuary/connectors/issues/2339
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2429)

source-sqlserver: Watermarks config is deprecated

---

source-postgres/database.go
source-postgres/replication.go

In normal operation a replication slot will always have a non-null `confirmed_flush_lsn`, but we saw the other day that it _is_ actually possible to observe a null value for that field if the replication slot is stuck in the middle of being created because it has to wait for a long-running transaction to complete.
Since one major cause of replication slot recreation is when the old slot gets invalidated, and one major cause of invalidation is when a long-running transaction forces excessive WAL retention, this is actually less rare than it seems. It will happen any time a long-running transaction causes slot invalidation and the user just hits "Backfill All" without killing the transaction (assuming it didn't end on its own, of course).
Since I would really like to make …

source-postgres: Handle NULL confirmed_flush_lsn

---

source-intercom-native/source_intercom_native/api.py

In `conversation_parts`, we attempt to only yield parts that have been updated since the previous sweep. Because of this, we can only checkpoint after checking a full date window. If a date window contains a large number of updated conversations, it can take `conversation_parts` more than one day to check all those conversations for updated parts. This has been observed for at least one task; about 4,000 pages of conversations were updated within 1 day (the smallest configurable date window).
This commit adds some dynamic reduction logic to size of the date window `conversation_parts` checks in a single `fetch_conversation_parts` invocation. If there are more than 25 pages of conversations, then the date window is split in half until there are <= 25 pages or the date …

source-intercom-native: dynamically reduce `conversation_parts` window size

---

source-mixpanel-native/source_mixpanel_native/streams/funnels.py

This implements the fix made to `annotations` in https://github.com/estuary/connectors/pull/2389 to the `funnels` stream. The connector has to send at least one API request for each funnel, and for users with hundreds of funnels, this will at minimum take multiple hours. If the connector uses a small date window size & makes more than a single request per funnel, then it's possible for `funnels` to never complete in 24 hours. 
Since each funnel typically only has KB of data, we can force `funnels` to make a single request per funnel by using a very large date window size.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1 …

source-mixpanel-native: increase `funnels` date window size

---

source-sqlserver/.snapshots/TestComputedPrimaryKey-capture
source-sqlserver/.snapshots/TestComputedPrimaryKey-discovery
source-sqlserver/main_test.go
sqlcapture/discovery.go

We omit columns from discovered schemas when they're things we can't reliably capture, as is the case with SQL Server or Postgres computed columns.
At least in SQL Server, but I think probably also in Postgres, it is possible to use such a column as the primary key of a table. When this happens we currently emit a nonsensical schema in which the column isn't defined as a property of the output documents, but _is_ listed as required and is suggested as the collection key.
This is incorrect both because the schema is incoherent, and because that column isn't going to be reliably present (it won't be present in replicated changes, specifically) so it can't be a collection key anyway. The best outcome here is just to treat the table as keyless, so I've put some …

sqlcapture: Treat tables with omitted primary-key columns as keyless

---

source-postgres-batch/.snapshots/TestCaptureFromView-Capture
source-postgres-batch/.snapshots/TestCaptureFromView-DiscoveryWithViews
source-postgres-batch/.snapshots/TestCaptureFromView-DiscoveryWithoutViews
source-postgres-batch/.snapshots/TestCaptureWithTwoColumnCursor-Capture
source-postgres-batch/.snapshots/TestCaptureWithTwoColumnCursor-Discovery
source-postgres-batch/.snapshots/TestCaptureWithUpdatedAtCursor-Capture
source-postgres-batch/.snapshots/TestCaptureWithUpdatedAtCursor-Discovery
source-postgres-batch/.snapshots/TestFullRefresh-Capture
source-postgres-batch/.snapshots/TestFullRefresh-Discovery
source-postgres-batch/.snapshots/TestQueryTemplates-MultiCursorFirstQuery
source-postgres-batch/.snapshots/TestQueryTemplates-MultiCursorSubsequentQuery
source-postgres-batch/.snapshots/TestQueryTemplates-SingleCursorFirstQuery
source-postgres-batch/.snapshots/TestQueryTemplates-SingleCursorSubsequentQuery
source-postgres-batch/.snapshots/TestQueryTemplates-XMinFirstQuery
source-postgres-batch/.snapshots/TestQueryTemplates-XMinSubsequentQuery
source-postgres-batch/.snapshots/TestSpec
source-postgres-batch/driver.go
source-postgres-batch/main.go
source-postgres-batch/main_test.go

This PR bundles together three closely-related fixes to the `source-postgres-batch` connector:
- Support for non-XMIN cursor settings. Previously there was a user-modifiable cursor property in the resource spec, but in practice if it ever got set to something other than `["xmin"]` without the user also supplying their own query template this would just break. We omit query templates by default, so for that reason it makes sense that we'd want this to just work automatically (applying the same full-refresh or cursor-incremental polling behavior that other connectors use).
- Support for view discovery. Implements a new advanced option `Discover Views` which when set causes views to be returned by discovery. In a truly stunning coincidence, we need the non-XMIN cursor …

source-postgres-batch: XID wraparound fix and view discovery option

---

source-postgres/.snapshots/TestConfigURI-Basic
source-postgres/.snapshots/TestConfigURI-IncorrectSSL
source-postgres/.snapshots/TestConfigURI-RequireSSL
source-postgres/main.go

This means we show up like this in pg_stat_replication:
postgres=> SELECT * FROM pg_stat_replication;
-[ RECORD 1 ]----+------------------------------
pid              | 36917
usesysid         | 16540
usename          | flow_capture
application_name | estuary_flow
client_addr      | 99.27.226.225
client_hostname  |
client_port      | 40560
backend_start    | 2025-02-25 16:40:03.981342+00
[...]
Currently the `application_name` field is entirely blank, so it seems like having anything at all there is a clear win. We might consider making it customizable or filing in the capture task name in the future, but for now this is better than nothing.
- - - …

source-postgres: Set application_name param

---

source-intercom-native/source_intercom_native/api.py
source-intercom-native/source_intercom_native/models.py
source-intercom-native/tests/snapshots/snapshots__capture__capture.stdout.json
source-intercom-native/tests/test_snapshots.py

A contact contain multiple sub-resources, like tags. There can be a large number of sub-resources attached to one contact, but only a subset are included when fetching a contact from Intercom's API. For example, only the [first 10 tags](https://developers.intercom.com/docs/references/2.8/rest-api/api.intercom.io/models/contact_tags) are included in a contact. To get all sub-resources, the connector would need to make an additional request to fetch them then hydrate the contact with the full set of sub-resources.
This commit adds this hydration functionality for tags within a contact. There are other possible sub-resources that we could hydrate (notes, companies, opted_out_subscription_types, etc.), but users are only asking about tags right now. So I'm only adding …

source-intercom-native: hydrate `contacts` with all attached tags

---

source-postgres-batch/.snapshots/TestQueryTemplates-XMinFirstQuery
source-postgres-batch/.snapshots/TestQueryTemplates-XMinSubsequentQuery
source-postgres-batch/main.go

This reverts commit e57acbcb75aed8f74b15ff6cfeeb9ed3e200f981 and un-fixes https://github.com/estuary/connectors/issues/2383
Turns out the particular function we're using here doesn't work on a standby replica, which is...bad. Since the XID wraparound failure mode this guards against is still mostly theoretical (has never been seen in production yet) and the failures on read-only standby replicas are very much real, we should revert this and then revisit how to make it work on a standby as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2466)

Revert "source-postgres-batch: Fix XID wraparound behavior"

---

source-sftp/main.go

Extends the SSH client config with two more key-exchange algorithms which golang.org/x/crypto/ssh supports but doesn't include in its default list. This means we support all currently-supported ones, but it's been written like this so that if the package itself adds new ones in the future we don't have to explicitly update our code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2469)

source-sftp: Additional key-exchange algorithms

---

go/common/feature_flags.go

Makes it so a setting like `do_foo, do_bar` parses the same as `do_foo,do_bar`.
Without this fix it instead parses the second one as a flag setting `" do_bar"` which is clearly very distinct from the intended `"do_bar"` flag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2470)

common/feature_flags: Trim whitespace

---

source-postgres/.snapshots/TestFeatureFlagFlattenArrays-Disabled-Capture
source-postgres/.snapshots/TestFeatureFlagFlattenArrays-Disabled-Discovery
source-postgres/.snapshots/TestFeatureFlagFlattenArrays-Enabled-Capture
source-postgres/.snapshots/TestFeatureFlagFlattenArrays-Enabled-Discovery
source-postgres/capture_test.go
source-postgres/datatypes.go
source-postgres/discovery.go
source-postgres/main.go

Currently source-postgres captures array columns as a JSON object with dimensions and elements properties, each of which is an array. This is because PostgreSQL arrays are inherently multidimensional, and we're trying to preserve them as faithfully as possible.
But it turns out that nobody ever wants that, they just want simple, boring one-dimensional arrays of values to translate into a JSON array of equivalent values. So we should do that by default going forward.
This partially addresses https://github.com/estuary/connectors/issues/2460
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2471)

source-postgres: Add 'flatten_arrays' flag

---

source-postgres/.snapshots/TestCIText-Capture
source-postgres/.snapshots/TestCIText-Discovery
source-postgres/datatype_test.go
source-postgres/discovery.go
source-postgres/main.go

Another feature-flagged default change. This one will make new captures going forward discover array columns as just the JSON array of flattened element values.
As with other changes of this kind, this will only be merged after I have set the corresponding `no_<flag>` on all tasks in production to preserve current behavior.
This is part of https://github.com/estuary/connectors/issues/2460
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2475)

source-postgres: Set 'flatten_arrays' by default

---

source-google-analytics-data-api-native/source_google_analytics_data_api_native/__init__.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/api.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/models.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/resources.py

Users have quickly run into errors when creating custom reports. We weren't validating the dimensions or metrics specified in custom reports, so the connector was failing after it was published if an invalid dimension/metric was specified. This PR adds validation of all dimensions and metrics specified in any custom reports. The Google API has a handy `/metadata` endpoint that returns all valid dimensions & metrics, so that list is used when validating the user's custom report input.
This validation does _not_ extend to any filters included in custom reports. We need to have a better model for the various types of valid filters before we even think about validating their contents, and developing that model would take a lot more time than I think it's worth investing right …

source-google-analytics-data-api-native: validate dimensions and metrics for custom reports

---

source-google-analytics-data-api-native/source_google_analytics_data_api_native/models.py

Turns out that sometimes those other fields in the `MetadataResponse` aren't present, and the connector is failing validation when they aren't present. This commit strips `MetadataResponse` to only include the fields we need.
- - - …

source-google-analytics-data-api-native: only require apiName in metadata

---

scripts/feature-flag-automation.sh

This adds a new script which is a lightweight wrapper around the `list-tasks`, `bulk-config-editor`, and `bulk-publish` scripts to make it even easier to set a `no_foobar` flag on all tasks using a particular set of connectors. Example:
$ ./feature-flag-automation.sh no_keyless_row_id source-postgres-batch source-mysql-batch source-redshift-batch source-bigquery-batch
Setting flag 'no_keyless_row_id' on connectors: source-postgres-batch source-mysql-batch source-redshift-batch source-bigquery-batch
Working directory: specs_no_keyless_row_id_20250304_114701
Plan:
./list-tasks.sh --connector=source-postgres-batch --pull --missing=no_keyless_row_id --dir=specs_no_keyless_row_id_20250304_114701
./list-tasks.sh --connector=source-mysql-batch --pull --missing=no_keyless_row_id …

scripts/feature-flag-automation: Even more automated

---

materialize-cratedb/driver.go
materialize-cratedb/sqlgen.go

* Make integration ~tests pass by tweaking a fixture value~ and modifying two cratedb types.
* Add remove temp tables
I'm not sure if this is the right place to delete tables, I tried to do at the end of `Load` but on the last load iteration it tries to insert a new value, and of course the temp table does not exist.
Next best thing I thought was to delete when the session was over, similarly to how postgres temp table works, I worked out that `Destroy` was the right place to do that, on top of that I'm also trying to delete the binding `before` adding a new Binding, just in case.
In the `Destroy` thingy, I'm just creating a blank `context.Background()` for `removeBinding`, does that affect in any way?, in …

Remove delete tables

---

source-braintree-native/source_braintree_native/resources.py
source-braintree-native/tests/snapshots/snapshots__capture__capture.stdout.json
source-braintree-native/tests/test_snapshots.py

When a scheduled backfill occurs, it's possible for a "gap" to exist where the old incremental task left off & the new incremental task picks up. For instance, if the incremental task is caught up at 19:58 UTC & is sleeping until it's `interval` has elapsed, and a scheduled backfill re-initializes the capture's state at 20:01 UTC, there's now a gap between 19:58 - 20:01 UTC where the incremental task did not check for newly created data. The backfill will eventually check this gap, but it could take days for the backfill to progress to that point.
This commit shifts the cutoff between backfill & incremental tasks so these gaps are covered by the new incremental tasks instead of the backfill tasks. This should ensure any gaps resulting from scheduled backfills when an …

source-braintree-native: cover potential gaps after scheduled backfills with the incremental tasks

---

filesink/filesink.go

Adds some additional logging to assist with troubleshooting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2495)

filesink: log the resource path when failing to encode a row

---

materialize-databricks/driver.go

- I realised we were suppressing logs from databricks sql driver, I'm changing this to only suppress those logs in INFO level. Initially I had seen it log a lot in INFO mode and be confusing for customers, but on debug this could have helped us uncover the databricks bug earlier
- - - …

materialie-databricks: let databricks driver logs through on debug

---

materialize-iceberg/emr.go
materialize-iceberg/python/common.py
materialize-iceberg/python/load.py
materialize-iceberg/python/merge.py
materialize-iceberg/python/python.go
materialize-iceberg/transactor.go

The maximum argument length for an EMR job is actually quite limited, around 10k characters, so if the command input for a job gets very long it will fail. This will happen if any number of significant bindings is associated with a transaction or even a single binding with a large number of fields, since all of the fields and their types need to be provided to the script in a serialized form, in addition to the query to execute.
The fix here is to write out the input to a temporary cloud storage file and read that in the PySpark script. Rather than providing the input as an argument, the input is now a URI to the input file. …

materialize-iceberg: serialize pyspark command inputs to a file

---

source-oracle/.snapshots/TestIntegerKey-backfill
source-oracle/.snapshots/TestIntegerKey-discover
source-oracle/.snapshots/TestIntegerKey-replication
source-oracle/backfill.go
source-oracle/capture_test.go
source-oracle/discovery.go
source-oracle/main.go
source-oracle/replication.go

- A customer hit an issue when using integer columns with precision < 18 as primary keys, this is a case that we had not covered with our tests, so I added tests, reproduced the issue and here is the implemented fix. Left comments to explain the various changes.
- - - …

source-oracle: fix integer key encoding

---

source-mongodb/change_stream.go

Debug logging for when documents are discarded because they are not for a tracked operation type, or because the full document is empty. Both of these event types should be fairly low-volume.
Also adds a sanity check when combining fragments from a split event to make sure that a source MongoDB collection is determined, which could otherwise cause a false negative when checking if that collection is among the tracked collections. I have no present reason to think this will ever happen, but it seems worthwhile to verify. …

source-mongodb: additional debug logs when discarding documents

---

source-stripe-native/config.yaml
source-stripe-native/source_stripe_native/resources.py
source-stripe-native/tests/snapshots/snapshots__capture__stdout.json

Modify base_object, child_object, split_child_object, usage_records, and no_events_object methods to handle cases where no connected accounts are provided. When no connected accounts are present, the methods now use a single fetch function with a None account_id instead of creating per-account fetch functions.
- - - …

source-stripe-native: Handle empty connected account list in resource methods

---

go.mod
go.sum
materialize-databricks/driver.go
tests/materialize/materialize-databricks/snapshot.json

I have a temporary fix for the databricks driver bug in my fork: https://github.com/mdibaiee/databricks-sql-go/commit/c54f93acc0f1450585fbf34b2bea5dce1fb3ff3e
I have not run this version against a full test suite of databricks driver, but I have run our integration tests and I have also run it against the code that would reproduce the bug, and confirmed the bug does not happen with this version and the error is correctly surfaced.
I'm going to deploy this for one customer who is dealing with this issue without merging it, after approval, to test it out. The customer's pipeline has been struggling because of this issue as MERGE INTO queries are too slow for large backfills. …

materialize-databricks: use mahdi's fork of databricks driver

---

estuary-cdk/estuary_cdk/capture/common.py
estuary-cdk/estuary_cdk/http.py
source-gladly/source_gladly/api.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/api.py
source-google-sheets-native/source_google_sheets_native/api.py
source-shopify-native/source_shopify_native/api.py
source-zendesk-support-native/source_zendesk_support_native/api.py
source-zendesk-support-native/tests/snapshots/snapshots__capture__capture.stdout.json

This PR adds functionality to `estuary-cdk` that will be needed for the `source-salesforce-native` connector I'm working on. The functionality includes:
- Allowing connectors to discover disabled bindings.
- Surfacing response headers.
- I implemented this for `HTTPSession.request_stream` since I plan to use this within `source-salesforce-native`. I also did so for `HTTPSession.request_lines` since it's only used by a single, low-use connector `source-gladly`. I did not update `HTTPSession.request` to surface headers since that would affect a significant number of connectors & none of them need access to response headers yet. …

estuary-cdk: surface headers and discover disabled bindings

---

source-hubspot-native/acmeCo/engagements.schema.yaml
source-hubspot-native/source_hubspot_native/models.py
source-hubspot-native/tests/snapshots/snapshots__capture__stdout.json
source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json

Expand HubSpot Engagement associations to support multiple object types. Update the Engagement model and schema to include associations for contacts, companies, tickets, content, quotes, orders, emails, meetings, notes, tasks, and carts.
[HubSpot's V1 API for Engagements](https://developers.hubspot.com/docs/reference/api/crm/engagements/engagement-details#get-an-engagement) returns the following associations:
```
"engagement": {
...
"associations": {
"contactIds": [],
"companyIds": [],
"dealIds": [],
"ownerIds": [],
"workflowIds": [],
"ticketIds": [],
"contentIds": [],
"quoteIds": [],
"marketingEventIds": [],
"partnerClientIds": [],
"orderIds": [],
"cartIds": []
},
...
}
```
However, when testing each using [HubSpot's batch read associations …

source-hubspot-native: Expand HubSpot Engagement associations

---

materialize-sql/templating.go

At least one destination (BigQuery) has known issues with keys that are date-times with sub-microsecond precision when used as a merge bound. For simplicity such formatted strings will never appear in merge bounds, although we should figure out how to do this more selectively in the future.
I suspect that at least Redshift would also fail with a nanosecond timestamp if included in a merge bound query, but haven't tested that directly. These types of keys are pretty rare. …

materialize-sql: don't use merge bounds for datetimes

---

materialize-iceberg/.snapshots/TestSpec
materialize-iceberg/config.go

It always should have been "namespace", and this is just fixing that typo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2515)

materialize-iceberg: replace "schema" in resource config json with "namespace"

---

materialize-databricks/.snapshots/TestValidateAndApply
materialize-databricks/staged_file.go

- I noticed this error seems to happen randomly across different tasks that use Databricks and it causes a full restart of the connector which is very inefficient specially for large tasks, usually means discarding a lot of work. Adding a simple retry mechanism here would go a long way
- - - …

materialize-databricks: retry PUT file upload query

---

source-google-analytics-data-api-native/source_google_analytics_data_api_native/api.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/models.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/resources.py
source-google-analytics-data-api-native/tests/snapshots/snapshots__discover__capture.stdout.json
source-google-analytics-data-api-native/tests/snapshots/snapshots__spec__capture.stdout.json

Per a user, GA4 data underlying some reports can still change N days after the report was captured. As the connector is right now, the incremental task fetches the most recent day's report & never looks back to recapture previous days reports. Meaning, the older reports can be outdated if the underlying data changed. The value of N seems to vary depending on the type of data, report, ingestion method, etc. based on these [Google docs](https://support.google.com/analytics/answer/11198161).
To fix this, this PR adds a configurable lookback window that forces the incremental task to always fetch reports for the past `lookback_window_size` days whenever it runs.
The …

source-google-analytics-data-api-native: add lookback window functionality

---

materialize-iceberg/python/load.py
materialize-iceberg/python/merge.py

This configuration is apparently needed to completely disable escaping in the Spark CSV writer, otherwise it will add an extra backslash in front of backslashes that are within double quotes.
Also log out the query for failed merge queries. This is mostly nice so we can tell which source collection it is that is failing to merge.
- - -
This change …

materialize-iceberg: disable escaping in load responses entirely & log failed merged queries

---

materialize-iceberg/python/load.py
materialize-iceberg/python/merge.py

PySpark requires this option when reading CSV data that may contain newline characters, even if they are within quotes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2521)

materialize-iceberg: use multiLine option for CSV reading

---

source-oracle/.snapshots/TestGeneric-SpecResponse
source-oracle/.snapshots/TestSchemaChanges-delete
source-oracle/.snapshots/TestSchemaChanges-init
source-oracle/.snapshots/TestSchemaChanges-insert-after
source-oracle/.snapshots/TestSchemaChanges-insert-before
source-oracle/.snapshots/TestSchemaChanges-update
source-oracle/replication.go

- We would search for the latest log file that covers the SCN range we want to capture which begins a dictionary so that in case of schema changes, we have the dictionary information available, however in online mode we are using the current dictionary of the table, and we don't need to look for dictionary in log files. This meant that in online mode we were reading a lot more log files than necessary, slowing us down considerably. …

source-oracle: no need to find earliest dictionary in online mode

---

materialize-databricks/.snapshots/TestSpecification
materialize-databricks/client.go
materialize-databricks/driver.go

Tested manually by running a task with additional SQL set to add a TBLPROPERTY to one of the tables, it worked as expected 👍🏽 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2530)

materialize-databricks: support AdditionalSql in binding configuration

---

materialize-bigquery/transactor.go

Although this really shouldn't ever happen, like so many things that shouldn't happen it has happened and the panic is not as useful of an error message as it could be. So we will return a bit more of an instructive error message when it does happen.
- - - …

materialize-bigquery: return and error rather than panic if table metadata can't be found

---

estuary-cdk/estuary_cdk/http.py
source-gladly/source_gladly/api.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/api.py
source-google-sheets-native/source_google_sheets_native/api.py
source-shopify-native/source_shopify_native/api.py
source-zendesk-support-native/source_zendesk_support_native/api.py

This reverts commit 33e17bb8fc825c8b82529dc396fa4990ae421636. Ongoing production issues around making more DNS lookups/connections than usual makes this change suspect due to the timing & scope. We want to test reverting this to see if this change is related to the recent production issues.
- - - …

estuary-cdk: revert 33e17bb8fc825c8b82529dc396fa4990ae421636

---

materialize-dynamodb/main.go
source-dynamodb/main.go

This is speculative, but we're seeing a lot of DNS resolution and re-connection for DynamoDB, and this may cause the connector to do a better job at connection re-use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2539)

dynamodb: bump allowed idle connections to avoid excessive re-creation

---

estuary-cdk/estuary_cdk/http.py
source-gladly/source_gladly/api.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/api.py
source-google-sheets-native/source_google_sheets_native/api.py
source-shopify-native/source_shopify_native/api.py
source-zendesk-support-native/source_zendesk_support_native/api.py

This reverts commit 9b0d10f75e02dcec0d18a15f811ffee2cc78a6c3 (which itself reverts 33e17bb8fc825c8b82529dc396fa4990ae421636). Reverting 33e17bb8fc825c8b82529dc396fa4990ae421636 in PR https://github.com/estuary/connectors/pull/2538 had no effect on the ongoing production issues, so it should be safe to add back in the functionality introduced in 33e17bb8fc825c8b82529dc396fa4990ae421636.
Surfacing response headers is necessary for the new `source-salesforce-native` connector, so this support needs added back into the CDK before merging https://github.com/estuary/connectors/pull/2519. …

estuary-cdk: re-add support for surfacing headers

---

source-oracle/prerequisites.go

- If a database is less than 24 hours old, skip retention checks because they will fail. This is mostly useful for demos and customers trialing on staging/test instances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2533)

source-oracle: skip retention checks for new databases

---

source-sqlserver-batch/.snapshots/TestSpec
source-sqlserver-batch/main.go

I can't remember why I made it 1h for this new capture when the others like MySQL (barring Postgres which is a special case as it uses xmin) default to 24h.
This changes the default behavior to 24h, when it's not overridden by either the endpoint spec or a particular resource config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2553)

source-sqlserver-batch: Default to 24h polling interval

---

source-postgres/.snapshots/TestSpecialTemporalValues
source-postgres/datatype_test.go
source-postgres/datatypes.go

Also adds a test of the various weird inputs that date/time columns accept, even though I think most of them translate to some specific date/time value and infinity is the only weird one here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2552)

source-postgres: Fix 'infinity' value in DATE column

---

source-intercom-native/source_intercom_native/api.py

Sometimes, a company retrieved via the Intercom API is an archived/deleted company. There is no property that indicates if a company is archived/deleted, so the connector doesn't know if that's the case until we try to fetch sub-resources (i.e. segments) of the company. When we try to fetch segments of a deleted/archived company, we receive a somewhat specific 404 response.
This PR handles those 404s more gracefully & moves on to fetches the next company's segments. …

source-intercom-native: handle 404 when fetching company segments

---

source-salesforce-native/source_salesforce_native/rest_query_manager.py
source-salesforce-native/source_salesforce_native/shared.py

In the initial version of `source-salesforce-native`, I made an assumption that all REST API queries would use the same page size. It turns out I was wrong; Salesforce dynamically reduces the page size for a query depending on how much data it returns. This means that when the connector uses more than one `Query` to fetch fields, it's possible for those queries to have different page sizes, and fields for a specific record could be on different pages for each query (ex: a set of fields could be on page 5 of query 1 but the other set of fields could be on page 6 of query 2). This breaks assumptions the `RestQueryManager` relied on.
To fix this, the `RestQueryManager` now builds records up across pages of separate queries, keeping records in memory until they're completed & …

source-salesforce-native: fix RestQueryManager to handle multiple large field chunks

---

materialize-dynamodb/main.go
source-dynamodb/backfill.go
source-dynamodb/capture.go
source-dynamodb/main.go
source-dynamodb/pull.go
source-dynamodb/stream.go

Previously concurrency limits were enforced only on a per-table basis, which can
result in very large numbers of concurrent requests if there are a lot of active
tables.
This adds a semaphore that will be used across all tables for both backfill
processes and streaming processes to limit the maximum number of in-flight
network requests and emitting of retrieved documents. This should prevent
excessive amounts of new HTTP connections from being created if the client
connection pool is exceeded, and also mitigate possible OOM scenarios if many
concurrent processes are holding onto data at the same time.
Closes https://github.com/estuary/connectors/issues/2562
(list …

source-dynamodb: enforce global concurrency limits for requesting data

---

source-dynamodb/main.go

In 6d4def8 global concurrency limits were implemented for source-dynamodb. I think this did cut down on the number of new connections being created quite a bit, but there are still plenty being made, and so the increased idle connection limits are probably helpful to keep implemented.
- - - …

source-dynamodb: re-apply increased allowed connection limits

---

source-salesforce-native/source_salesforce_native/bulk_job_manager.py
source-salesforce-native/source_salesforce_native/models.py
source-salesforce-native/tests/snapshots/snapshots__spec__capture.stdout.json

After watching a couple `source-salesforce-native` tasks run in production, there are a handful of error causing backfills to progress slower than they could.
When processing large CSV files, the `BulkJobManager` would raise an error like:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1328047: unexpected end of data
```
This was happening because `BulkJobManager._process_csv_lines` was attempting to decode chunks completely when they arrived, and if a multi-byte character (like `"`) was split across chunks, decoding would fail and raise an error. Instead, the connector needs to incrementally decode chunks, carrying over bytes belonging to characters split across chunks. Python has a built-in incremental decoder to do just that, and the connector …

source-salesforce-native: misc. fixes

---

source-boilerplate/boilerplate.go
sqlcapture/capture.go
sqlcapture/discovery.go
sqlcapture/main.go

Adds some very generic lifecycle status logging to `source-boilerplate` and more fine-grained but still pretty brief status messages throughout the SQL CDC capture logic. With these changes a generic Go capture with no other logging will produce:
Initializing connector   # Protocol initialization. May not be worth logging?
Starting capture         # When the '.Pull()' method of the driver is invoked
Capture started          # When the '.Ready()' message indicates it's started
And a SQL CDC connector will produce something like:
Initializing connector            # Very Briefly
Starting capture                  # Very Briefly
Connecting to database            # For however long this takes, usually not much
Verifying capture requirements    # For however long this takes, …

sqlcapture + source-boilerplate: The most trivial connector status implementation

---

source-sqlserver/main.go
source-sqlserver/replication.go

As described in the flag comment, when `tolerate_missed_changes` is true the connector will tolerate missed changes in the CDC stream and will not trigger an automatic re-backfill if changes go missing. This may be useful if the CDC event data starts to expire before it can be captured, but should generally only be needed in exceptional circumstances when recovering from some sort of major breakage.
If `tolerate_missed_changes` is set in a capture's feature flags, then _**if**_ there is no valid capture instance whose start LSN is <= the current capture resume LSN, we'll instead just select the capture instance with the earliest start LSN and use that.
To the best of my knowledge, if we then go ahead and try to poll changes from the selected CDC …

source-sqlserver: Flag to tolerate missed changes

---

source-mysql/main.go
source-mysql/replication.go
source-oracle/main.go
source-postgres/main.go
source-postgres/replication.go
source-sqlserver/backfill.go
source-sqlserver/main.go
source-sqlserver/replication.go
sqlcapture/capture.go

This commit adds two hidden features for internal use:
- For all three captures, setting the "Skip Backfills" advanced option to `*.*` will cause all tables to immediately transition to active without any backfilling. This lets us avoid needing to modify the capture mode for a whole bunch of bindings.
- For all three captures, it is possible to put a setting like `initial_backfill_cursor=12345` into the feature flags list. If this is done, the value `12345` will be used as the initial cursor value when there is no resume cursor, instead of the normal behavior of taking the current end of the WAL.
As a reminder, this is what cursor values look like for each DB:
// MySQL
binlog.12345:7890
// PostgreSQL
123/45678901
// SQL Server
ALUrCQADl2AAGA==
Set …

source-{mysql,postgres,sqlserver}: Initial backfill cursor

---

source-oracle-batch/.snapshots/TestKeyDiscovery
source-oracle-batch/driver.go
source-oracle-batch/main_test.go
source-oracle/.snapshots/TestSchemaChanges-delete
source-oracle/.snapshots/TestSchemaChanges-init
source-oracle/.snapshots/TestSchemaChanges-insert-after
source-oracle/.snapshots/TestSchemaChanges-insert-before
source-oracle/.snapshots/TestSchemaChanges-update
source-oracle/discovery.go

- We were using the wrong value for the ordinal position of the primary key in Oracle, updated the test to cover this case and fixed it on both source-oracle and source-oracle-batch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2579 …

source-oracle{-batch}: fix primary key ordinal position discovery

---

source-mysql/main.go
source-mysql/replication.go
source-postgres/main.go
source-postgres/replication.go
source-sqlserver/main.go
source-sqlserver/replication.go

This is like the 'initial_backfill_cursor=XYZ' flag hackery, but it doesn't even require that you perform a backfill to trigger it. This should generally be set, and then you watch it take effect, and then you immediately publish another change to unset it again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2581)

source-{mysql,postgres,sqlserver}: Add 'force_reset_cursor=XYZ'

---

materialize-boilerplate/validate.go
materialize-boilerplate/validate_test.go

- It is hard for users to find out which collection is affected in large tasks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2587)

materialize-boilerplate: collection name in backfill counter error

---

materialize-boilerplate/apply.go

The apply action that fails will cause a context cancellation, and all other actions will then fail due to that context being cancelled. This causes a bunch of log spam and makes it very difficult to see which action it was that failed for something other than a context cancellation.
This change will make it so only the erroring action will log out its action. …

materializations: don't log apply action for non-causal apply action failures

---

materialize-webhook/driver.go

The `http.DefaultClient` uses chunked transfer encoding when Content-Type header is not set or the request body doesn't have a set length (ex: an `*io.PipeWriter`). Some webhook destinations, like Azure Logic Apps, don't work well with chunked transfer encoding. This commit reverts the connector's behavior to not stream the request body as chunks & instead send the request all at once. Request bodies are maxed at ~1 MiB before they are sent. …

materialize-webhook: don't use chunked transfer encoding

---

estuary-cdk/estuary_cdk/requests_session_send_patch.py

I've seen a handful of imported connectors hit the 6 hour session timeout limit recently. Reducing the timeout to 2 hours should help reduce the impact when this happens. I'd like to reduce it even further, but some imported connectors (at least `source-mixpanel-native` and its `export` stream) do take over an hour to complete a single request when it's streaming in a lot of records.
(anything that might …

estuary-cdk: reduce requests session timeout patch

---

source-mongodb/.snapshots/TestSpec
source-mongodb/change_stream.go
source-mongodb/change_stream_test.go
source-mongodb/main.go
source-mongodb/pull.go

Sometimes a MongoDB collection is not being captured, but is part of a database
that is being captured. Normally this isn't a problem if the number and/or size
of change events for that MongoDB collection are small, but it can be
problematic otherwise & actually bog down the change stream processing.
This adds an advanced configuration option for these cases to allow MongoDB
collections to be exclude from the database change stream by way of a pipeline
filter.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, …

source-mongodb: advanced option to exclude specific collections from database change streams

---

source-boilerplate/testing/testing.go
source-sqlserver/main.go
source-sqlserver/main_test.go
source-sqlserver/replication.go

This PR adds support for SQL Server CDC capturing from a read-only standby replica. It does this by:
- Implementing a new fence mechanism in `streamToReplicaFence` which only consults information which is available on a read-only replica.
- Detecting at startup whether the target database is a read replica.
- Automatically using `streamToReplicaFence` when the target database is a read replica (or when the `replica_fencing` feature flag is explicitly enabled, just in case we need to be able to manually turn it on in other situations).
This new fence mechanism has a minor downside, which is that it doesn't (and can't, at least in every possible scenario) guarantee that when a row is modified concurrently with a backfill, the backfilled row state and the concurrent changes …

source-sqlserver: Read Replica CDC

---

source-intercom-native/source_intercom_native/api.py
source-intercom-native/source_intercom_native/resources.py
source-intercom-native/tests/snapshots/snapshots__capture__capture.stdout.json

`conversation_parts` works by fetching parts of updated conversations, then only yielding the parts that have been updated since the last log cursor. This was done to avoid yielding conversation parts that were previously yielded. However, this strategy has potential to miss data if another part is added to a conversation that's beyond the date window the connector is currently checking & the conversation is updated again before the connector checks the next date window.
For example, say there's a conversation `123` that had a part added to it at `1742999957`. The connector is checking the window of `1742999856` - `1742999956`. Before the connector finishes that date window, conversation `123` is updated again and it's `updated_at` is pushed to a later time `1743000057`. …

source-intercom-native: fix `conversation_parts` bug that could cause missing data

---

source-sqlserver/replication.go

If the `isReplicaDatabase()` function encounters an error, it will now assume that this is not a replica instead of erroring out. The main reason we're likely to see this is on databases which don't even have a `sys.dm_hadr_database_replica_states` table, so erring on the side of assuming it's the primary DB should always be fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2601)

source-sqlserver: Assume primary on error

---

source-mysql/backfill.go
source-oracle/backfill.go
source-postgres/backfill.go
source-sqlserver/backfill.go
sqlcapture/capture.go
sqlcapture/interface.go

As currently implemented, XMIN backfills have a problem.
The fundamental issue with XMIN backfills as they exist today is that we literally just slap in a `WHERE {xmin is within the specified range} filter or filters into the backfill queries without changing anything else about our behavior. And the problem with this is that our backfill logic is built around the assumption that we are getting result rows back.
This turns out to not be the case when doing an XMIN backfill of a large table (the only kind worth using XMIN backfills on) whose primary keys are mostly ordered (that is, most writes will be at the very end of the table).
What happens in this case is we tell the DB "hey can you give me any rows newer than {min_xid} and stop after N" and the DB says "Sure, I can …

source-postgres: Filter backfill XMIN on client side

---

source-chargebee-native/acmeCo/comments.schema.yaml
source-chargebee-native/acmeCo/contacts.schema.yaml
source-chargebee-native/acmeCo/flow.yaml
source-chargebee-native/acmeCo/gifts.schema.yaml
source-chargebee-native/acmeCo/promotional_credits.schema.yaml
source-chargebee-native/acmeCo/quote_line_groups.schema.yaml
source-chargebee-native/acmeCo/subscriptions_with_scheduled_changes.schema.yaml
source-chargebee-native/acmeCo/unbilled_charges.schema.yaml
source-chargebee-native/source_chargebee_native/__init__.py
source-chargebee-native/source_chargebee_native/api.py
source-chargebee-native/source_chargebee_native/models.py
source-chargebee-native/source_chargebee_native/resources.py
source-chargebee-native/test.flow.yaml
source-chargebee-native/tests/snapshots/snapshots__spec__stdout.json

Addresses: #2524 
Follow up to the following PR: #2583 
This expands the connector's resource handling capabilities:
Resource Additions:
- Added new Pydantic models, bindings, etc. for:
* Comments (with incremental sync support via created_at cursor)
* Contacts
* Gifts
* Promotional Credits
* Quote Line Groups (requires Performance/Enterprise plan)
* Subscriptions with Scheduled Changes
* Unbilled Charges
Configuration Improvements:
- Updated resource configurations to support both Product Catalog 1.0 and 2.0
- Enhanced validation logic for resource-specific configurations
- Added proper type hints and validation rules for all new schemas
API Integration Enhancements:
- Improved handling of associated resources with parent-child relationships
- Added support for filtering …

source-chargebee-native: support more streams and both product catalogs

---

source-salesforce-native/source_salesforce_native/bulk_job_manager.py

Python's `csv` module has a default field size limit of 131,072 bytes, and it will raise a `_csv.Error` exception if a field value is larger than that limit. Some users have fields larger than 131,072 bytes in their Salesforce accounts (ex: entire email bodies), so we increase the limit to 10 MiB, which should be sufficiently large.
Tested on a local stack with a Salesforce account that has field values …

source-salesforce-native: increase csv field size limit

---

source-postgres/.snapshots/TestBackfillQueryGeneration
source-postgres/.snapshots/TestKeylessBackfillQueryGeneration
source-postgres/backfill.go
source-postgres/backfill_test.go

When doing an XMIN filtered backfill, instead of reading out all rows and filtering solely on the client side, we can instead read out all rows satisfying the XID range _plus_ 0.1% of rows that don't.
This provides enough data movement to permit incremental progress through a table, while still eliminating 99.9% of unnecessary network throughput and connector CPU usage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2603)

source-postgres: Sample 0.1% of XMIN-excluded rows

---

source-postgres/.snapshots/TestLongYearTimestamps
source-postgres/.snapshots/TestScanKeyTimestamps
source-postgres/.snapshots/TestSpecialTemporalValues
source-postgres/backfill.go
source-postgres/datatype_test.go
source-postgres/main_test.go

This was a regression, previously 5-digit years worked correctly because we handled parsing issues during replication and during backfills the values came in as Unix microsecond timestamps which didn't need parsing. A while back we switched that over to use the text representation in backfills as well (because that way the timestamps from backfills and replication are consistently represented with the same time zone), but that meant that 5-digit years were no longer handled correctly and it took this long for somebody to hit that edge case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2619)

source-postgres: Handle timestamptz values with 5-digit years

---

source-criteo/pyproject.toml
source-hubspot-native/tests/snapshots/snapshots__capture__stdout.json
source-hubspot/config.yaml
source-hubspot/test.flow.yaml
source-hubspot/tests/snapshots/snapshots__capture__capture.stdout.json
source-hubspot/tests/snapshots/snapshots__discover__capture.stdout.json
source-hubspot/tests/test_snapshots.py
source-linkedin-pages/tests/test_snapshots.py
source-monday/tests/snapshots/snapshots__capture__stdout.json
source-monday/tests/test_snapshots.py
source-stripe-native/tests/snapshots/snapshots__capture__stdout.json
source-zendesk-support-native/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support-native/tests/test_snapshots.py
source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
source-zendesk-support/tests/test_snapshots.py

Tests for multiple Python connectors have been failing in CI for various reasons. Typically, the failures have been due to to the SaaS provider adding/removing fields, our credentials becoming invalid, or other testing related reasons that don't actually indicate issues with the connector. I've updated the failing tests to pass. See individual commits for details on each one.
This should help combat alert fatigue when inspecting test results.
I didn't look at fixing `source-oracle-flashback` tests. The fix for those look a little more involved, and I think that connector might be getting deprecated soon(?) anyway. …

source-{various Python connectors}: fix failing tests

---

materialize-snowflake/pipe.go
materialize-snowflake/snowflake.go
tests/materialize/materialize-snowflake/snapshot.json

- Instead of only cleaning up pipes after finishing a transaction for that specific pipe name as compared to a previous version, clean up all extra `FLOW_PIPE_%` pipes that are not pending use by checkpoint items and share the same table name and keyBegin
- While I was at it, improved our `pipeExists` logic to be more precise and likely more performant as well
- Tested this with our integration tests …

materialize-snowflake: a more thorough pipe cleanup

---

source-postgres/.snapshots/TestMultidimensionalArrays-Capture
source-postgres/.snapshots/TestMultidimensionalArrays-Discovery
source-postgres/capture_test.go
source-postgres/datatypes.go
source-postgres/discovery.go
source-postgres/main.go

Implements a new feature flag `multidimensional_arrays`. When set, PostgreSQL array types will be discovered as merely `{type: array}` without any element type information at all, but the capture output will be unflattened back into nested arrays of the appropriate dimensionality.
So for instance the array `[[a,b],[c,d]]` can be represented as such instead of flattened out to `[a, b, c, d]`.
Set the `multidimensional_arrays` feature flag in the advanced settings for the capture. This flag is not going to become the default, but it's present for power users.
I'm not sure if the test coverage for array unflattening is sufficient or not. On the one hand it seems to work both on simple cases like a 1D 4-element array vs a 2x2 array …

source-postgres: Feature flag for truly multidimensional arrays

---

source-zendesk-support-native/acmeCo/flow.yaml
source-zendesk-support-native/acmeCo/ticket_activities.schema.yaml
source-zendesk-support-native/source_zendesk_support_native/api.py
source-zendesk-support-native/source_zendesk_support_native/models.py
source-zendesk-support-native/source_zendesk_support_native/resources.py
source-zendesk-support-native/test.flow.yaml
source-zendesk-support-native/tests/snapshots/snapshots__discover__capture.stdout.json
source-zendesk-support-native/tests/test_snapshots.py

Adds the `ticket_activities` binding as an incremental cursor paginated stream. The `/ticket_activities` endpoint accepts a `since` parameter for filtering results & requires the value to be an ISO 8601 UTC datetime, which are both different from the existing incremental cursor paginated streams. Both `fetch_incremental_cursor_paginated_resources` and `backfill_cursor_paginated_resources` have been updated to handle this.
The connector docs should be updated to reflect the new stream.
Tested on a local stack. Confirmed:
- existing incremental cursor paginated streams `ticket_skips` and `ticket_metric_events` behave the same.
- …

source-zendesk-support-native: add `ticket_activities` stream

---

source-monday/source_monday/graphql.py
source-monday/source_monday/models.py
source-monday/tests/snapshots/snapshots__capture__stdout.json

- Added API response errors.
- Updated `fetch_boards` to first attempt fetching boards with the 'kind' field, falling back to individual board queries if necessary.
- Added logging for better traceability of query failures and retries.
- Modified `Board` model to include a nested `Workspace` model for better structure and clarity.
- - -
This change …

source-monday: handle template boards

---

source-oracle/backfill.go
source-oracle/discovery.go
source-oracle/replication.go

- Ordering the whole table based on `ROWID`, and then filtering for a specific ROWID range is slow. With some testing I found that if we order ROWIDs on their own (without all the other columns), and then filter based on them, it is much faster and actually workable.
- I also realised we were capturing all logminer events for all discovered tables and only filtering them later after fetching, which was quite inefficient. Changed the logic so we filter out disabled tables as part of the query we send to logminer and have noticed a performance improvement.
- Lastly found that it is possible for a log file to have both an ARCHIVED file and an ACTIVE file, similar to ARCHIVED and CURRENT, so updated the logic to allow for that as well
- Would like to try this with a customer …

source-oracle: optimise keyless backfill query

---

source-zendesk-support-native/source_zendesk_support_native/resources.py

Both the `/business_hours/schedules` and `/sla/policies` endpoints are only accessible for Enterprise tier or above Zendesk accounts, so we should conditionally discover them along with the other Enterprise-only streams.
It seems like there are also some other restrictions for other endpoints (ex: `/ticket_forms` is only for Professional or above accounts?). I haven't found good documentation from Zendesk yet about these types of restrictions, so rather than proactively guessing which streams are accessible on which tiers and potentially guessing wrong, I'd rather wait & address it when discovering a specific stream becomes a problem. …

source-zendesk-support-native: mark `schedules` and `sla_policies` as enterprise-only

---

materialize-boilerplate/stream-encode/csv.go
materialize-boilerplate/stream-encode/parquet.go

For both CSV and Parquet writing, we can avoid allocating unnecessary for string values by creating a read-only view of the string's bytes. This doesn't make a huge difference, but it is obviously safe to do and every little bit helps on these hot paths.
Also fixes a more significant omission in Parquet writing where pre-serialized RawMessages did not have a fast-path, and were going through the (slow) JSON serialization process. Adding the RawMessage case avoids that overhead.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified …

stream-encode: a couple of minor performance tweaks

---

source-postgres-batch/.snapshots/TestSpec
source-postgres-batch/driver.go
source-postgres-batch/main.go

I've gotten this one wrong twice now for subtle reasons so I actually sat down and put together a reliable repro case and verified that it works, however making the actual server-side query execution reliably take long enough to trigger a statement timeout requires either some ugly hacks or a ton of special-case plumbing that's only useful for that one job, so I'm not adding that test here.
However I think there is some utility to being able to override or set the default statement timeout via the advanced config, so I kept that bit in.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2655)

source-postgres-batch: Fix statement timeout handling

---

source-stripe-native/source_stripe_native/__init__.py

If the last config did not have a `capture_connected_accounts` field (like before the connected accounts functionality was introduced), the current code that retrieves the `capture_connected_accounts` value from the last config will default to returning `None`, and we'll end up comparing `None` to some boolean value. If the field is missing, it should return `False` instead so the connector doesn't incorrectly think `capture_connected_accounts` has changed when the config goes from not having the field to having it present & set to `False`.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=shari …

source-stripe-native: fix bug with validating changing capture_connected accounts

---

source-kinesis/capture.go

It would be a little unusual for a shard to repeatedly return no new records from GetRecords while also lagging behind the latest point of the stream. But it would be expected for GetRecords to return no records if the stream was caught up with the latest. So log an Info level log for the former since it's something we want to know about if it is happening a lot, and a debug log for the latter since it is probably not generally as useful of a message.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along …

source-kinesis: additional logging for reading shards

---

source-sqlserver/prerequisites.go

We already enable encryption and we have the default tlsmin=1.2, but a customer is insisting on making sure the connection is encrypted, so here is a log message to make sure the connection is encrypted.
There is no failure mode for this check, we always pass, and only log a DEBUG if we can't check for the status, this is intentionally a debug log to avoid freaking users out about encryption. Checking the status requires `VIEW SERVER STATE` permission which is quite broad and we will likely not have in most scenarios.
Logging the session ID allows an administrator from the customer side to check for encryption status themselves. …

source-sqlserver: check for encryption of connection

---

materialize-snowflake/pipe.go
materialize-snowflake/snowflake.go

- Switch back to using `SHOW PIPES` for `pipeExists` and for the new `cleanupPipes`. I had forgotten the original reason behind using it: to not wake up the warehouse!
- Do not run `cleanupPipes` if there are no current pipes.
- Tested with integration tests and some manual logging
- - - …

materialize-snowflake: use SHOW PIPES to avoid waking up warehouse

---

source-linkedin-ads-v2/source_linkedin_ads_v2/streams.py

The 202404 API verison has been sunset today, so we have to upgrade to a more recent version for the connector to work again.
Confirmed API calls & the connector work again with the 202502 API version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2679)

source-linkedin-ads-v2: upgrade API version

---

source-salesforce-native/source_salesforce_native/api.py
source-salesforce-native/source_salesforce_native/bulk_job_manager.py

I noticed that some formula field backfills were progressing significantly slower than I expected. For example, it would take the better part of a day to fetch < 10 GB in the Opportunity stream.
It turns out, Salesforce [says](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/query_get_job_results.htm#:~:text=If%20you%20are,the%20maximum%20size.):
> If you are working with a very large number of query results, you may experience a timeout before receiving all the data from Salesforce. To prevent a timeout, specify the maximum number of records your client is expecting to receive in the maxRecords parameter. This splits the results into smaller sets with this value as the maximum size.
My own testing pointed to a timeout issue too; the connector …

source-salesforce-native: request a max set size when reading bulk job results

---

source-google-analytics-data-api-native/config.yaml
source-google-analytics-data-api-native/source_google_analytics_data_api_native/api.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/models.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/resources.py

Users have requested support for [`metricAggregations`](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/MetricAggregation) for reports. These aggregations are returned under separate top-level fields (like "totals") intead of within the `rows` field of the response. For example, when using a "TOTAL" metric aggregation, the response can look like:
```json
{
"dimensionHeaders": [...],
"metricHeaders": [...],
"rows": [...],
"totals": [
{
"dimensionValues": [
{
"value": "RESERVED_TOTAL"
}
],
"metricValues": [
{
"value": "64"
}
]
}
],
...
}
```
We can treat aggregates like the other rows inside the `rows` field when they're present, and their dimension values will indicate the type of aggregation (ex: "RESERVED_TOTAL").
(How …

source-google-analytics-data-api-native: support metricAggregations

---

source-mysql/replication.go
source-oracle/replication.go
source-postgres/replication.go
source-sqlserver/replication.go
sqlcapture/capture.go
sqlcapture/interface.go
sqlcapture/main.go

The day we kept putting off has finally come, we finally need to represent replication stream state as something more complex than a simple LSN cursor into the WAL.
This commit should have no observable effect on its own. The representation of our current string cursors in state checkpoints is unchanged, all we've done is leave the bytes makine up that quoted string unparsed inside the generic machinery and made the database-specific logic do a bit more work to quote and unquote them.
But this will allow Oracle to migrate to a more complex object as its cursor value without the need for an ugly "JSON serialized and then quoted inside another JSON string" bit of nesting.
- - - …

sqlcapture: Refactor cursor to json.RawMessage

---

source-salesforce-native/source_salesforce_native/resources.py
source-salesforce-native/source_salesforce_native/supported_standard_objects.py

There are a few special custom objects that don't end in `__c`, and users are asking us to support them. This PR adds a few we're currently being asked about.
[Feeds](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_customobject__feed.htm) for custom objects end in `__Feed` and always have a `SystemModstamp` field.
Custom [metadata](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_custommetadatatype__mdt.htm) end in `__mdt` and always have a `SystemModstamp` field.
Sharing rules for custom objects end in `__Share` and always have a `LastModifiedDate` field.
There are other special, custom objects we don't support (like [change …

source-salesforce-native: discover custom share, feed, and metadata objects

---

source-firestore/.snapshots/TestInitResourceStates
source-firestore/main_test.go
source-firestore/pull.go

When change streaming fails to catch up, we allow the change stream to "skip ahead" and flag the binding as inconsistent so we can run another backfill in the future.
But previously, if change streaming failed repeatedly during an ongoing backfill, that backfill would keep getting interrupted and rescheduled for 24 hours in the future. This meant that a really flaky stream in conjunction with frequent task restarts could prevent the backfill from ever getting anything done, because it would keep on getting through just a small bit of the data, then the task would restart, we'd see the 'Inconsistent: true' flag, and we'd interrupt the backfill and schedule it to start over from the top the next day.
The solution is that we should never interrupt an ongoing backfill, once …

source-firestore: Don't interrupt ongoing backfills

---

source-boilerplate/testing/testing.go
source-mysql/replication.go
source-postgres/replication.go
sqlcapture/capture.go

This commit makes two logging changes:
1. The sqlcapture logic will now maintain separate counts of the important event types and log the counts separately rather than a single opaque "events" count.
2. Fixes a handful of spots I noticed while testing the previous change where serialized JSON values were being logged as byte arrays `[65 66 67]` which is ugly. Most of these are new from the cursors-as-JSON refactoring I did yesterday, so I figured I'd just address those real quick while I was at it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2691)

sqlcapture: Logging tweaks

---

materialize-iceberg/type_mapping.go

Materializations do not support nullable keys in general, and materialize-iceberg is no exception.
A non-required source collection field is allowed as a key if it has a default value set, and so if a key field has been selected we know it will never be null and should create the column for the key field accordingly. On a practical level, this is necessary since key fields are created as identity columns which cannot be not required. …

materialize-iceberg: always create identity columns as required

---

source-mysql/.snapshots/TestFeatureFlagTinyintAsBool-Default-Capture
source-mysql/.snapshots/TestFeatureFlagTinyintAsBool-Default-Discovery
source-mysql/.snapshots/TestFeatureFlagTinyintAsBool-Disabled-Capture
source-mysql/.snapshots/TestFeatureFlagTinyintAsBool-Disabled-Discovery
source-mysql/.snapshots/TestFeatureFlagTinyintAsBool-Enabled-Capture
source-mysql/.snapshots/TestFeatureFlagTinyintAsBool-Enabled-Discovery
source-mysql/discovery.go
source-mysql/main.go
source-mysql/main_test.go

MySQL doesn't technically have a boolean type. If you declare a column of type `BOOLEAN` what actually happens is it gets treated as an alias for `TINYINT(1)` and similarly `TRUE` and `FALSE` are just aliases for one and zero.
However, in practice nobody would ever bother adding a display width parameter of 1 on a tinyint _except_ as the idiomatic way of getting a MySQL boolean column, so we can reliably assume that if we see a tinyint column that is specifically `TINYINT(1)` the user intended for it to be treated as a boolean.
This PR adds a "tinyint1_as_bool" feature flag, currently defaulting to off. When this flag is enabled, columns of type `TINYINT(1)` and only `TINYINT(1)` will be treated as booleans in both discovery and value translation.
We might want to make …

source-mysql: Add "tinyint1_as_bool" feature flag

---

source-postgres/backfill.go
source-postgres/capture_test.go
source-postgres/discovery.go

I've just spent the past couple of hours up to my eyeballs in PostgreSQL XIDs and the different `txid_snapshot_foo(...)` functions so I'm going to take this opportunity to clean up and simplify some of the PostgreSQL CDC logic around XMIN filtered backfills while it's fresh in my mind.
Strictly speaking only one of these changes is truly needed ASAP, using `compareXID32` to do the appropriate circular comparison for XMIN filtering in the result row processing.
The other stuff is just cleanups, because we don't need to be using a complicated case statement based on whether or not we are hitting a standby when the `txid_snapshot_xmin/xmax` bits work perfectly fine on the master DB as well.
Should be no functional changes except that the XMIN filtering …

source-postgres: Cleaner XMIN filtering

---

source-postgres/.snapshots/TestBackfillQueryGeneration
source-postgres/.snapshots/TestKeylessBackfillQueryGeneration
source-postgres/backfill.go

Two issues, both of which I'm a bit confused how I failed to see them in the previous XMIN backfill tweaks PR but whatever:
- The lower-bound filter clause needs to be `>=` rather than `>` in order for our XMIN backfill test case to pass correctly.
- The query generation snapshots need to be updated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2696)

source-postgres: Fix XMIN backfill oversight

---

source-oracle/.snapshots/TestCrossSCNTransactions
source-oracle/backfill.go
source-oracle/capture_test.go
source-oracle/main_test.go
source-oracle/replication.go
sqlcapture/capture.go

- Transactions can span across multiple SCN ranges, when that happens, we would previously keep track of their messages in memory, but for long / large transactions that would lead to memory issues.
- In order to avoid memory consumption when working with large transactions, we now keep track of the starting SCN of and the XID of pending transactions, and we persist this information as part of the checkpoint
- Once we see terminal operation for pending transactions, if it is a rollback, we remove the transaction from checkpoint, and if it is a commit, we initiate an ad-hoc capture of that specific transaction, this means we process the SCN range from the beginning of that large transaction to the commit as usual (still paginated), but this time we will ask Logminer to …

source-oracle: track pending transactions and capture them separately

---

materialize-motherduck/.snapshots/TestSpecification
materialize-motherduck/driver.go

Adds a check on bucket names to make sure they don't contain dots since that breaks SSL verification. Also a speculative fix for the "Missing credentials" error that seems to occasionally happen.
Closes https://github.com/estuary/connectors/issues/2702
- - - …

materialize-motherduck: bucket name validation & missing credentials fix

---

source-mysql/backfill.go
source-mysql/database.go
source-mysql/discovery.go
source-mysql/main.go
source-mysql/prerequisites.go

The go-mysql client library's handling of read/write timeouts is kind of awful for reasons I'd rather not get into. [Previously](https://github.com/estuary/connectors/pull/2674) we disengaged all timeouts in favor of implementing our own deadline on the initial connection, but it turns out this leaves us at a real risk of indefinite hangs in some cases if the network connection silently gets dropped.
So in this commit we take matters into our own hands and set a deadline on the underlying net.Conn, implementing a timeout on the entire query/execute operation. For most queries we have a default timeout of 60s, and for backfills we override that with a much more generous 6h timeout.
- - - …

source-mysql: Query timeouts, take N+1

---

materialize-boilerplate/stream-encode/parquet_schema.go

The nullability evaluation for parquet schema columns was previously just plain wrong, since it didn't account for a field that was always present but could be an explicit null, so that's been fixed.
As an enhancement, it will now also consider a column to be required if its types do not allow an explicit null & it has a default value. In this case it is guaranteed that the field will always have a value that is not null, since if it is absent the default will kick in. This makes things consistent with how the boilerplate Apply handling does not drop NOT NULL constraints for fields with a default value, which is important for Iceberg tables where a file with an optional column cannot be appended to a table where that column is required.
(How does one …

parquet-schema: fix nullability evaluation & consider default values

---

source-boilerplate/testing/testing.go
source-postgres/.snapshots/TestCaptureOversizedFields
source-postgres/.snapshots/TestCaptureOversizedFields-Replication
source-sqlserver/.snapshots/TestOversizedFields
source-sqlserver/datatypes.go
source-sqlserver/datatypes_test.go
source-sqlserver/docker-initdb.sh
source-sqlserver/main_test.go

Same as we do for PostgreSQL, this PR adds a simple "if length > 8MiB truncate to 8MiB" check for SQL Server's "Large Object" types (text and image and varchar/varbinary(max)). This doesn't make it impossible for a document to exceed Flow's 64MiB limit, but it's a decent starting point that catches the common case where there's just one really huge column in a table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2700)

source-sqlserver: Truncate oversized fields to 8MiB

---

go.mod
go.sum
go/blob/azure.go
go/blob/bucket.go
go/blob/bucket_test.go
go/blob/gcs.go
go/blob/s3.go
materialize-boilerplate/stream-encode/parquet.go
materialize-boilerplate/stream-encode/parquet_schema.go
materialize-snowflake/.snapshots/TestSpecification
materialize-snowflake/.snapshots/TestStreamDatatypes-BOOLEAN
materialize-snowflake/.snapshots/TestStreamDatatypes-DATE
materialize-snowflake/.snapshots/TestStreamDatatypes-FLOAT
materialize-snowflake/.snapshots/TestStreamDatatypes-INTEGER
materialize-snowflake/.snapshots/TestStreamDatatypes-TEXT
materialize-snowflake/.snapshots/TestStreamDatatypes-TIMESTAMP_LTZ
materialize-snowflake/.snapshots/TestStreamDatatypes-TIMESTAMP_NTZ
materialize-snowflake/.snapshots/TestStreamDatatypes-TIMESTAMP_TZ
materialize-snowflake/.snapshots/TestStreamDatatypes-VARIANT
materialize-snowflake/bdec.go
materialize-snowflake/bdec_test.go
materialize-snowflake/config.go
materialize-snowflake/pipe.go
materialize-snowflake/snowflake.go
materialize-snowflake/snowflake_test.go
materialize-snowflake/stream.go
materialize-snowflake/stream_http.go
materialize-snowflake/stream_test.go
materialize-sql/std_sql.go
tests/materialize/materialize-snowflake/snapshot.json

Adds a new mode of operation for Snowflake bindings that use delta updates - [Snowpipe streaming](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-overview). As implemented here, this will use the post-commit apply pattern to achieve exactly-once semantics.
This includes a fair amount of code ported over from the Java Snowflake Ingest SDK for the specifics related to writing the data files and interacting with the Streaming HTTP API to write data from those files, which is primary in the `bdec.go` and `stream_http.go` file. Our materialization-specific logic is in `stream.go`, as well as being sprinkled in the 2 previously mentioned ones. For example, we aren't reading the entirety of a transaction into memory like the Java SDK does, and instead use a …

materialize-snowflake: support for Snowpipe streaming

---

source-mysql/backfill.go

Sometimes our backfill queries will be rather slow, for instance when we're doing a keyless backfill and we've reached a significant offset already. Running `EXPLAIN ANALYZE` asks the database to run the query and discard the result, which effectively means that the first query will be twice as slow. And in general we're not reading the explain output unless something's gone wrong, and even when we do a normal `EXPLAIN` is sufficient to answer questions like "is an index being used".
Also as a practical matter, the EXPLAIN query is currently subject to the default one-minute timeout we apply to non-backfill queries, and there appears to be something going wrong when we try to run a subsequent query after one has timed out (which in theory should work, but empirically it …

source-mysql: Only EXPLAIN, don't ANALYZE queries

---

materialize-iceberg/.snapshots/TestSpec
materialize-iceberg/.snapshots/TestValidateAndApplyLowercaseColumnNames
materialize-iceberg/config.go
materialize-iceberg/driver.go
materialize-iceberg/driver_test.go
materialize-iceberg/sqlgen.go
materialize-iceberg/sqlgen_test.go
materialize-iceberg/type_mapping.go
materialize-iceberg/type_mapping_test.go

Querying S3 table bucket tables with Athena doesn't work unless all the column names are lowercase. This seems pretty dumb and hopefully AWS fixes that eventually, but for now we have to accommodate it since that is a pretty obvious use case if you are using S3 tables.
We already had the general restriction that column names that differed only in caps weren't allowed since Glue etc. don't like that, so adding this option is too disruptive.
The docs will need updated for this new config option, and should mention something about it in the section about S3 table buckets.
- - -
This change …

materialize-iceberg: advanced config option to create all table columns as lowercase

---

source-braintree-native/source_braintree_native/__init__.py
source-chargebee-native/source_chargebee_native/__init__.py
source-front/source_front/__init__.py
source-gainsight-nxt/source_gainsight_nxt/__init__.py
source-genesys/source_genesys/__init__.py
source-gladly/source_gladly/__init__.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/__init__.py
source-google-sheets-native/source_google_sheets_native/__init__.py
source-hubspot-native/source_hubspot_native/__init__.py
source-impact-native/source_impact_native/__init__.py
source-intercom-native/source_intercom_native/__init__.py
source-iterate/source_iterate/__init__.py
source-monday/source_monday/__init__.py
source-oracle-flashback/source_oracle_flashback/__init__.py
source-pendo/source_pendo/__init__.py
source-salesforce-native/source_salesforce_native/__init__.py
source-shopify-native/source_shopify_native/__init__.py
source-stripe-native/source_stripe_native/__init__.py
source-zendesk-support-native/source_zendesk_support_native/__init__.py

When I made the CDK's `BaseCaptureConnector` mixin `HTTPMixin` in https://github.com/estuary/connectors/pull/2699, I missed removing the duplicate `HTTPMixin` for the individual connectors inheriting from `BaseCaptureConnector`. This is causing those connectors to log errors like `Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x75a0c8534710>` since we're entering the `HTTPMixin` twice, creating a second client session, and never closing it.
This commit removes the duplicate `HTTPMixin` from CDK connectors that are logging that error. …

source-{cdk connectors}: remove duplicate `HTTPMixin` from `Connector`

---

source-google-analytics-data-api-native/source_google_analytics_data_api_native/models.py
source-google-analytics-data-api-native/source_google_analytics_data_api_native/resources.py

Google enforces that reports have between 1 - 9 dimensions and between 1 - 10 metrics. This PR improves our validation of custom reports to also enforce those limitations & print out a clear error message if a custom report has too few/too many dimensions or metrics.
The custom reports section of the connector docs should be updated to mention that there must be between 1-9 dimensions and 1-10 metrics for custom reports.
Tested input validation on a local stack. Confirmed trying to use a custom report with too few/too many dimensions or metrics raises a validation error with clear error messages.
- - - …

source-google-analytics-data-api-native: validate dimension and metric counts in custom reports

---

estuary-cdk/estuary_cdk/capture/common.py
estuary-cdk/estuary_cdk/capture/response.py
estuary-cdk/estuary_cdk/capture/task.py

The Flow runtime has recently been updated to support `SourcedSchema` messages - schemas emitted by capture connectors to inform the runtime of some source-defined schema. See https://github.com/estuary/flow/pull/1946 for more details.
This PR adds support in our CDK for emitting `SourcedSchema` messages. `SourcedSchema` messages are written to each task's buffer and emitted as part of the next checkpoint.
`SourcedSchema` messages should be emitted after `open` is called. They can be emitted when opening a resource, like below:
```python
def open(
binding: CaptureBinding[ResourceConfig],
binding_index: int,
state: ResourceState,
task: Task,
all_bindings,
):
schema = {
"additionalProperties": False,
"type": "object",
"properties": {
"myPropertyName": {
"type": "string", …
```

estuary-cdk: support `SourcedSchema` messages

---

materialize-motherduck/config.go

Adds back trimming a leading '/' for bucket paths which was removed in #2720, but is necessary for backwards compatibility with pre-existing tasks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2730)

materialize-motherduck: trim leading / in bucket paths

---

source-stripe-native/source_stripe_native/api.py

We have evidence that Stripe's Events API is eventually consistent. Examples from [Sequin](https://blog.sequin.io/finding-and-fixing-eventual-consistency-with-stripe-events/) show how to combat this by yielding a cursor only if it is older than 5 seconds, otherwise do not update the cursor. This approach has been augmented for Estuary's connector to never fetch data that's more recent than 1 minute in the past by just returning and waiting for the connectors interval to pass. This means the most "real-time" the connector can be is 1 minutes (often a little more due to the default 5 minute interval), but it hopefully helps avoid eventual consistency issues causing the connector to miss updates. …

source-stripe-native: handle eventual consistency

---

source-chargebee-native/source_chargebee_native/api.py
source-chargebee-native/source_chargebee_native/models.py

This PR should fix an issue identified in a capture where the `start` was after the `end`  end time for `created_at[between]` and `updated_at[between]` for incremental `fetch_changes` due to updating the `max_updated_at` timestamp in the `while` loop without checking that it is before the `log_cursor` and simultaneously using the `max_updated_at` in the API request instead of using the same `start`/`end` times for the API requests.
This PR introduces a check that will skip yielding documents if the `updated_at` is beyond the `log_cursor` and keeps the `start` time for the API requests the same. Additionally, there is a `le=datetime.now(tz=UTC)` check on the `EndpointConfig` model which will prevent the user from specifying a `start_date` that is in the future.
**Workflow …

source-chargebee-native: ensure API request interval is valid

---

source-mongodb/backfill.go

Adds a log for when backfills start for a table, to complement the logs about when they are done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2744)

source-mongodb: log when backfills start for a table

---

source-intercom-native/source_intercom_native/api.py

When I built this connector, I mistakenly thought `log.fatal` would be presented nicely in the UI. I was mistaken, and I should have used `log.error` instead; `log.error` is presented better in the UI.
- - - …

source-intercom-native: fix log level for scroll endpoint error

---

source-shopify-native/source_shopify_native/graphql/orders/fulfillment_orders.py

It turns out that merchant requests in `fulfillment_orders` have an id like `gid://shopify/FulfillmentOrderMerchantRequest`, not `gid:://shopify/MerchantRequest`.
I didn't test this on a local stack, but I did inspect the JSONL response for a `fulfillment_orders` bulk job to confirm what the appropriate merchant request id looks like.
- - - …

source-shopify-native: fix id format for merchant requests in fulfillment orders

---

materialize-iceberg/transactor.go

The default line length limit of bufio.Scanner is 64KiB, which is quite a bit shorter than documents we commonly see.
There's no real reason for us to have any limit on this line length, since the data we are loading back is data we put there in the first place.
This change sets an initial relatively small buffer, but allows the scanner to resize it as large as it needs to based on the data received. …

materialize-iceberg: allow load result lines of any length

---

go.mod
go.sum

After merging https://github.com/estuary/connectors/pull/2733, intermittent began to show up with PUT queries - frequently enough to prevent the build from even going through, since the CI tests can't pass. There may be some regression in the Snowflake Go client, so this is reverting to the prior working version.
- - - …

Revert "build(deps): bump github.com/snowflakedb/gosnowflake"

---

source-kinesis/capture.go
source-kinesis/connection.go
source-kinesis/main.go

Right now, the capture will start up and log a few things, and then nothing forever until it restarts.
This adds some periodic logging of the capture's progress, to give an indication that it is still alive and doing stuff, and some insight into what the stuff is.
The output logs will look something like this:
```json
{
"_meta": {
"uuid": "48268d3c-26c8-11f0-8400-539167a7c504"
},
"shard": {
"kind": "capture",
"name": "bobCo/kinesistest/source-kinesis",
"keyBegin": "00000000",
"rClockBegin": "00000000",
"build": "110304b7d400007e"
},
"ts": "2025-05-01T20:10:09Z",
"level": "info",
"message": "processed stream records",
"fields": {
"whbTestStreamOne": {
"shardId-000000000000": {
"docs": 75,
"lag": "0s"
},
"shardId-000000000001": {
"docs": 76,
"lag": "0s"
}, …
```

source-kinesis: add periodic logging of capture progress

---

base-image/Dockerfile
materialize-bigquery/Dockerfile
materialize-databricks/Dockerfile
materialize-sqlserver/Dockerfile
materialize-starburst/Dockerfile

`curl` is generally useful to have available in a connector image to access Go's pprof HTTP server, so install it by default rather than needing to rely on annoying workarounds.
The automated CI tests aren't really effective for a change like this, since all connector images use the base image tagged as `v1`, rather than the one that is built on this branch. But I did spot check a connector container …

connectors: install curl for all Go connectors

---

source-salesforce-native/source_salesforce_native/bulk_job_manager.py

I noticed that for a normal backfill when there are a significant number of records in a date window & these records are potentially large (like `EmailMessage`s), the connector sometimes hangs when reading results. I suspect this is the same problem I tried to address in https://github.com/estuary/connectors/pull/2683, but the max set size I chose is still too high, so the connector can sometimes _still_ take too long to finish a single HTTP request & Salesforce times out the connection silently. I'd like to see if reducing the max set size helps.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?us …

source-salesforce-native: reduce max set size for reading bulk job results

---

source-firestore/.snapshots/TestSpec
source-firestore/main.go
source-firestore/main_test.go
source-firestore/pull.go

Adds a resource spec and advanced endpoint config setting for the minimum (re)backfill interval. If neither is set we will continue to apply the same "5m with a restart cursor and 24h otherwise" policy we always have, but if either is set we will use the specified interval instead. The resource level setting overrides the endpoint config, while the endpoint config allows users to set a default which will definitely be applied to any new bindings, so I think it's useful to have both.
I've tried to keep this PR limited to just adding that new setting, so it's worth noting that the current connector-restart behavior is absolutely terrible so I haven't even bothered updating it to account for the new customizable intervals. As just one concrete example, if change streaming …

source-firestore: Configurable backfill intervals

---

source-salesforce-native/source_salesforce_native/bulk_job_manager.py

We've still seen instances of backfills hanging when reading bulk job results, albeit less frequently. I suspect the bulk job query set size I chose in https://github.com/estuary/connectors/pull/2756 is still too high to work well for all situations (mostly those with large document sizes), so I'm reducing it even further.
An alternative solution is to only checkpoint between HTTP requests for bulk jobs. That would avoid potentially lengthy checkpoints in the middle of the connector processing an HTTP response, but it would also complicate the cursor management logic & cause that logic to differ between REST API queries and Bulk API queries. Instead of sinking time into that solution, I'm reducing the max set size further since that's a much smaller & quicker change. …

source-salesforce-native: further reduce max set size for reading bulk job results

---

source-shopify-native/source_shopify_native/__init__.py
source-shopify-native/source_shopify_native/resources.py

I've noticed unexpected logs in production captures, stating `BulkJobError: Unanticipated status CANCELING for job gid://shopify/BulkOperation/123456789.` This has been logged right after the same bulk job completed, which is a little perplexing. I'm suspecting that we're canceling our own ongoing bulk jobs during auto-discovers, causing these failures & seemingly random bulk job cancellations.
The connector should now only cancel bulk jobs only after receiving an `Open`, and auto-discovers shouldn't cancel bulk jobs any more. …

source-shopify-native: only cancel ongoing jobs when opening bindings

---

materialize-snowflake/snowflake.go

- Snowflake seems to be now returning 14 columns instead of 15, despite their docs also showing 15
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2770)

snowflake: fix SHOW PIPES scan destination count

---

materialize-cratedb/sqlgen.go

Change the integer types to adapt to the maximun/minimun in the schema with `MapSignedInt64`
Fixes https://github.com/crate/cratedb-estuary/issues/4
Tests still don't pass, that's because currently CrateDB does not permit to insert u64 values in objects, tracked https://github.com/crate/crate/issues/17669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2758)

materialize-cratedb: Change integer type mapping to more accurate types

---

materialize-cratedb/sqlgen.go

Minor type assignment change, fixes https://github.com/crate/cratedb-estuary/issues/12
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2764)

materialize-cratedb: Set sql.STRING_NUMBER to 'DOUBLE PRECISION' 

---

source-iterable/source_iterable/streams.py

Previously, the `IterableExportStream` streams would checkpoint state while processing records in a single response, inspecting the cursor field of each record & yielding it if it's more recent than the state. This works fine if records returned by the API are sorted based on their cursor fields, but the API does no such sorting. Because of that, the connector's state can jump ahead if it's restarted in the middle of processing a response. We've seen this cause lots of missing data.
Since we can't sort the API's results, the connector's been updated to checkpoint the end of the date window after processing all records in the date window. This ensures all records between the start & end are captured before checkpointing, preventing the connector's state from jumping ahead …

source-iterable: fix checkpointing behavior for `IterableExportStream` and family

---

source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture2
source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture3
source-postgres/capture_test.go
source-postgres/database.go
source-postgres/main.go
source-postgres/prerequisites.go
source-postgres/replication.go

The `create_replication_slot` flag setting is the default behavior and amounts to doing what we were already doing, but by adding a feature flag we can allow users to specify `no_create_replication_slot` in order to disable any automatic replication slot management on our part.
In conjunction with this change, I've reworked the "does the slot exist" validation check so that it never attempts to create the slot. This part is a change I've been meaning to make for a while, as once we've verified that the capture user has the REPLICATION role and that the slot doesn't already exist in another database, there is no way we could fail to recreate it later on when the capture proper starts.
The reason this is preferable is that it significantly reduces the chances of several …

source-postgres: Add "create_replication_slot" feature flag

---

source-monday/source_monday/api.py
source-monday/source_monday/graphql.py
source-monday/source_monday/models.py
source-monday/source_monday/resources.py
source-monday/tests/snapshots/snapshots__capture__stdout.json

This aims to fix missing items due to incorrect pagination of boards. Previously the backfill for `items` would only backfill the first 25 `boards` since we did not paginate through the boards in the `ITEMS` query.
- - - …

source-monday: update pagination handling for boards and items in API requests

---

source-monday/source_monday/api.py
source-monday/source_monday/graphql.py

There was a small bug introduced in a minor refactor that was apparently not tested as expected. We were backfilling up to the point a board did not have any items. This ensures that we backfill until there are no more boards. That is a key distinction since we want to check each board for items to backfill rather than stopping early when a board may not have items to backfill.
(anything that might help …

source-monday: fix handling of empty item responses items backfill

---

source-oracle/replication.go

- If a transaction is rolled back in a different SCN range than the original, we would sometimes let it stay in `pendingTransactions` forever...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2765)

source-oracle: clear rolled-back transactions from pending list

---

source-postgres/datatypes.go

The translateArray function constructs a "hypothetical scalar equivalent" column metadata which is used for the recursive translation of element values, however in some edge cases we may not actually have column metadata for the value in the first place.
If that happens, we should roll with it and produce a nil value for the scalar equivalent column as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2779)

source-postgres: Avoid nil dereference in edge case

---

materialize-motherduck/.snapshots/TestSQLGeneration
materialize-motherduck/driver.go
materialize-motherduck/sqlgen.go
materialize-motherduck/sqlgen_test.go

Adds merge bounds to load and store queries in MotherDuck, as we have added for the other warehouse materializations.
In the past I have mentioned a desire to have a more principled way to generally incorporate the "bounds" concept in materializations, since most of them will want access to those. My best idea for this so far is to incorporate them into the transactor, but that would also require more deeply incorporating the concept of "value converters" that materializations use to convert values to their specific needs. Probably a good idea, but a lot more work.
But there is an immediate use case for performance optimization of MotherDuck load queries, and following this pattern that we have used before is relatively simple and realistically I don't know if I'm ever …

materialize-motherduck: add merge bounds to load and store queries

---

estuary-cdk/estuary_cdk/capture/base_capture_connector.py
estuary-cdk/estuary_cdk/capture/common.py
estuary-cdk/estuary_cdk/capture/connector_status.py
estuary-cdk/estuary_cdk/capture/task.py

Adds some general logging of connectorStatus events for captures that use common.open_binding, which is currently ~all of them.
It is modeled after the SQL captures, which indicate how many bindings are still backfilling, or if they are all backfilled.
The CDK is highly async, with tasks that can spawn subtasks, and the structure of the CDK status logging reflects that. There's no primary loop that drives backfills & incremental captures in turn (they all kind of run at the same time), so the status logging itself runs on a polling loop that checks for any changes in the metrics we are logging about.
Closes [#2738](https://github.com/estuary/connectors/issues/2738) …

estuary-cdk: connectorStatus logging for captures that use common.open_binding

---

source-sqlserver/.snapshots/TestBitNotNullDeletion
source-sqlserver/datatypes_test.go
source-sqlserver/replication.go

We have now observed multiple unrelated SQL Server captures in production where a `BIT NOT NULL` column is/was captured as a null value in a deletion event. This should never happen [1] and is a pretty clear-cut violation of the documented CDC behavior around deletions, but nonetheless it's happened and continues happening so we need to deal with it somehow.
This PR fixes the entire class of issues by extending the existing "omit null values of image/text/ntext column in deletes" logic to also apply to null values of any column which should be non-nullable according to the source table schema.
[1] I suspect that there's an actual database bug here, possibly related to the decoding of multiple `BIT NOT NULL` columns packed into whatever sort of bitfield the SQL Server WAL …

source-sqlserver: Never emit nulls on NOT NULL column deletions

---

source-hubspot-native/source_hubspot_native/models.py
source-hubspot-native/tests/snapshots/snapshots__spec__stdout.json

In order to publish this connector in the HubSpot marketplace, HubSpot requires that "setup documentation [and] in platform experience should not include an app that requires API keys in order to be installed". Essentially, users should only be presented the option to authenticate with OAuth in the UI.
There are already existing captures authenticating with access tokens, so we can't simply strip out support for access token authentication. Patching model_json_schema to remove AccessToken makes OAuth2 the only authentication option in the UI, and effectively "hides" the capability to use access tokens. This should satisfy HubSpot's requirement while retaining support for access token authentication for already created captures.
Editing an existing capture that …

source-hubspot-native: hide access token auth in UI

---

source-mysql/.snapshots/TestTableNamesIdenticalUnderCapitalization-Capture
source-mysql/.snapshots/TestTableNamesIdenticalUnderCapitalization-Discover
source-mysql/backfill.go
source-mysql/capture_test.go
source-mysql/database.go
source-mysql/discovery.go
source-mysql/main.go
source-mysql/replication.go
source-oracle/backfill.go
source-oracle/discovery.go
source-oracle/main.go
source-oracle/replication.go
source-postgres/backfill.go
source-postgres/discovery.go
source-postgres/main.go
source-postgres/replication.go
source-sqlserver/backfill.go
source-sqlserver/discovery.go
source-sqlserver/replication.go
source-sqlserver/watermarks.go
sqlcapture/capture.go
sqlcapture/discovery.go
sqlcapture/interface.go
sqlcapture/main.go
sqlcapture/tests/helpers.go

This PR consists of:
- A fairly hefty refactoring which replaces the internal StreamID representation from a string to a struct type with separate schema and table name fields. This isn't strictly speaking necessary, but that refactoring is a good way of making sure that we are consistent in our usage of the IDs and have accounted for every edge case that might be impacted by changes to the StreamID representation.
- Removing the MySQL and SQL Server "tables whose names are identical but for capitalization are a fatal error and kill the entire capture" check. Even if we don't intend to fix case sensitivity everywhere else, this would probably be a good move because the check is probably more harmful than helpful since it's so over-broad.
- Adding a feature flag …

source-mysql: Add flag `case_sensitive_table_names`

---

source-pendo/source_pendo/api.py
source-pendo/source_pendo/models.py
source-pendo/source_pendo/resources.py
source-pendo/tests/snapshots/snapshots__discover__capture.stdout.json

- Capturing data for all applications within a single Pendo subscription.
- Adding the [`TrackType`](https://engageapi.pendo.io/#9f83f648-4fe7-45db-b30d-963679af6304) and [`Visitor`](https://engageapi.pendo.io/#dd943e68-5bff-4a1a-9891-b55638ae2c3d) streams that capture the same named resources from Pendo's aggregation API.
Some existing streams (`Page`, `Guide`, etc.) could also be captured incrementally via the aggregation API, and that would be better than constantly taking snapshots of all pages, guides, etc. like we currently do. But that would also require changing the primary key for those streams, and that'd impact existing Pendo captures. Changing those streams from full refresh to incremental can be done later when we have more time to …

source-pendo: add `TrackType` & `Visitor` streams, capture from all applications

---

estuary-cdk/estuary_cdk/capture/base_capture_connector.py
estuary-cdk/estuary_cdk/capture/connector_status.py

We've noticed imported Airbyte connectors using the `CaptureShim` have not been exiting after completing a sweep. This is likely due to the `periodic_log` coroutine being created in the top level `TaskGroup` and blocking on it. To avoid this, we're now kicking off `periodic_log` outside of the `TaskGroup`, like we do with `periodic_stop`.
- - -
This …

estuary-cdk: dont block on `periodic_log`

---

source-firestore/.snapshots/TestSpec
source-firestore/main.go
source-firestore/pull.go

Renames `min_backfill_interval` to `minBackfillInterval` since we only have one capture using it at present and that's more consistent with other resource config settings (though sadly it's inconsistent with other advanced config properties -- there is no solution here that's consistent with everything because the state of these names is already an incoherent mess).
Adds validation logic so that non-empty settings on the capture or resource specs for the `minBackfillInterval` property are validated in the Validate() method as is appropriate.
Adds a validation regexp to the JSON schema so that users will be prevented from adding invalid settings in the UI even before it reaches the capture's validation logic.
It should be harder for users to end up with …

source-firestore: Validate minBackfillInterval settings

---

source-salesforce-native/source_salesforce_native/bulk_job_manager.py
source-salesforce-native/source_salesforce_native/supported_standard_objects.py

This PR addresses/avoids issues a new capture is hitting:
- `RecordActionHistory` can't be queried by any cursor fields, despite cursor fields being present in the object.
- `EntityDefinition` can't be queried without using a `LIMIT`.
- The Bulk API sometimes returns `"0.0"` for standard integer fields when the field's value is the integer `0`.
More details are in the individual commits.
No captures except the newest one have `RecordActionHistory` or `EntityDefinition` enabled. The single capture that _does_ have it enabled has all 800+ bindings enabled. I highly doubt they want these two specific bindings, and if it turns out that they do, we can prioritize figuring out how to capture them at that point.
(How does one use this feature, and how has it …

source-saleforce-native: misc fixes

---

source-sqlserver-batch/.snapshots/TestBinaryTypes-Capture
source-sqlserver-batch/.snapshots/TestDateAndTimeTypes-Capture
source-sqlserver-batch/.snapshots/TestDatetimeLocation-Chicago
source-sqlserver-batch/.snapshots/TestDatetimeLocation-ExplicitNegativeOffset
source-sqlserver-batch/.snapshots/TestDatetimeLocation-ExplicitPositiveOffset
source-sqlserver-batch/.snapshots/TestDatetimeLocation-Tokyo
source-sqlserver-batch/.snapshots/TestDatetimeLocation-UTC
source-sqlserver-batch/.snapshots/TestFeatureFlagEmitSourcedSchemas-Default
source-sqlserver-batch/.snapshots/TestFeatureFlagEmitSourcedSchemas-Disabled
source-sqlserver-batch/.snapshots/TestFeatureFlagEmitSourcedSchemas-Enabled
source-sqlserver-batch/.snapshots/TestIntegerTypes-Capture
source-sqlserver-batch/.snapshots/TestNumericTypes-Capture
source-sqlserver-batch/.snapshots/TestStringTypes-Capture
source-sqlserver-batch/.snapshots/TestUUIDType-Capture
source-sqlserver-batch/.snapshots/TestXMLType-Capture
source-sqlserver-batch/discovery.go
source-sqlserver-batch/driver.go
source-sqlserver-batch/main.go
source-sqlserver-batch/main_test.go

As with https://github.com/estuary/connectors/pull/2798 and https://github.com/estuary/connectors/pull/2805, this PR modifies another batch SQL connector to:
1. Implement full column and type discovery. All columns of discovered tables will now be included in discovered (write) schemas with appropriate JSON schema types, rather than just primary-key columns with somewhat half-assed type translation.
2. Add the `emit_sourced_schema` feature flag, default off. When enabled, the capture will run discovery and output SourcedSchema updates immediately prior to polling a binding (subject to a minimum interval between rediscoveries, which is currently set to 5 minutes).
This is part of https://github.com/estuary/flow/issues/1919
All capture tasks will now …

source-sqlserver-batch: Add SourcedSchema feature flag

---

source-boilerplate/boilerplate.go

We have a 1MiB buffer on writes to stdout, which is normally flushed after each non-document message. (The reason for that being that it improves throughput if we allow multiple docs in a transaction to be batched up into a single stdout write).
The problem arises if we output >1MiB worth of data in a single Flow transaction, and then the connector errors out before emitting a checkpoint. One way this might happen is if a fatal error occurs partway through a backfill chunk, where the total amount of data is >1MiB.
Since the buffer is 1MiB and we've already written >1MiB of data to it, it will have flushed to stdout at least once. But the buffer doesn't care about our message framing, so it will likely have split the final message in half. Which is fine in normal operation …

source-boilerplate: Ensure stdout buffer flush on exit

---

source-kinesis/.snapshots/TestCaptureParsing
source-kinesis/capture.go
source-kinesis/capture_test.go

Use a skim parsing strategy for Kinesis JSON records, where only the top-level fields are parsed to allow for inserting our metadata into the document. This eliminates the unfortunate prior side-effect where large integer values were
being approximated due to their internal handing when parsed into a `map[string]any`. It should also be a little more performant, since we don't really care about anything beyond the top-level of fields.
Implementing this required thinking about what happens if the data from Kinesis already has a "_meta" property. We will do a shallow merge of the properties from an existing `_meta` object, giving preference to our own fields to avoid clobbering the required connector metadata.
(How does one use this feature, and how has …

source-kinesis: improve record parsing

---

source-http-ingest/src/lib.rs
source-http-ingest/src/snapshots/source_http_ingest__test__discover_backwards_compatibility.snap
source-http-ingest/src/snapshots/source_http_ingest__test__discover_with_paths.snap
source-http-ingest/tests/snapshots/test__discover.snap

Populates the resource path in discover responses, which is once again required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2837)

source-http-ingest: set resource paths in discover response

---

source-chargebee-native/source_chargebee_native/api.py

The prior way of checking and continuing would ignore most, if not all, documents that we receive in a batch because the check was incorrect. This updates the check to ensure the documents are within the time window, logs a debug message, and continues if this happens.
- - - …

source-chargebee-native: update document cursor value check against current log cursor

---

source-mysql-batch/.snapshots/TestDateAndTimeTypes-Discovery
source-mysql-batch/discovery.go

Looks like I did indeed miss an edge case when implementing the new more detailed type discovery. The goal of the newly detailed discovery types was/is purely to describe the current connector outputs and not to change those at the same time, so the correct solution is to remove the `format: date` on these strings for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2840)

source-mysql-batch: Remove format:date for now

---

source-outreach/source_outreach/models.py
source-outreach/tests/snapshots/snapshots__spec__capture.stdout.json

Including `access_token` and `expires_in` in the OAuth2 spec's `accessTokenResponseMap` ended up including them in the endpoint config's credentials. This was not intended; we only want the refresh token in the config, and the other access token response fields shouldn't persist across connector invocations.
Confirmed that removing `access_token` and `expires_in` from the `accessTokenResponseMap` in this …

source-outreach: remove `access_token` and `expires_in` from `accessTokenResponseMap`

---

source-postgres/replication.go

Adds another field to some should-never-be-happening debug logs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2843)

source-postgres: Add value to debug logs

---

source-postgres/replication.go

In theory we're not supposed to get non-null values when the tuple type is 'K' and the flags column indicates that it's not a key column.
In practice, we're seeing a table with a normal primary-key replica identity and appropriately non-null values for those columns, but where every column is reported as non-key in the relation message. This is clearly a bug (possibly introduce by Amazon RDS customizations), but since it can happen in the real world it's something we have to deal with.
It seems reasonable that if we get a non-null value for a column we should capture it, and this edge case shouldn't ever happen _unless_ there's a bug in the "is this a key?" bitflag, so this is a pretty minimal fix for the issue.
- - - …

source-postgres: Emit non-null values in keyOnly tuples

---

source-oracle-batch/.snapshots/TestBasicDatatypes-Capture
source-oracle-batch/.snapshots/TestDecimals
source-oracle-batch/.snapshots/TestFeatureFlagEmitSourcedSchemas-Default
source-oracle-batch/.snapshots/TestFloatNaNs-Capture
source-oracle-batch/main.go
source-oracle-batch/main_test.go

Feature flag default change, to be merged after setting `no_emit_sourced_schemas` on preexisting captures.
Part of https://github.com/estuary/flow/issues/1919
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2856)

source-oracle-batch: Set `emit_sourced_schemas` by default

---

source-jira-native/source_jira_native/api.py
source-jira-native/source_jira_native/models.py
source-jira-native/source_jira_native/resources.py

I forgot that not touching any connector code in https://github.com/estuary/connectors/pull/2862 would cause the Python Connectors workflow to not run. This just does some formatting/noop to get that workflow to actually run & re-build the image.
- - - …

source-jira-native: formatting to trigger build workflow

---

source-mysql/replication.go

It's a bit weird and normally we shouldn't be seeing these in the binlog unless something screwy is going on with query events and the binlog format, but they are not themselves an issue, we just don't care about this event type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2870)

source-mysql: Ignore INTVAR_EVENTs

---

go.mod
go.sum
materialize-boilerplate/ser_policy.go
materialize-snowflake/.snapshots/TestSpecification
materialize-snowflake/config.go
materialize-snowflake/snowflake.go
materialize-sql/driver.go
materialize-sql/endpoint.go

Allow connectors to define their serialization policy, rather than relying on hard-coded values in the runtime.
Technically this can be set per-binding in the protocol, but for now it will be exposed in connector configurations as a simple "disable field truncation entirely" advanced option.
`materialize-snowflake` is updated to have this configuration option available, since it is the currently-known use case for such a thing.
Depends on https://github.com/estuary/flow/pull/2179 having been merged & deployed. ~TODO: Update the flow pin in this PR once that is done to a SHA from the main branch.~ - done …

materialization-specific serialization policies

---

materialize-kafka/Cargo.lock
materialize-kafka/src/validate.rs
source-http-ingest/Cargo.lock
source-kafka/Cargo.lock

Updates the Flow dependency for Rust connectors. Also adds the specific serialization policy that materialize-kafka should use, which is the same as the hard-coded policy that is currently in the Flow runtime.
- - - …

update Flow dependencies for Rust connectors 

---

source-http-ingest/src/lib.rs
source-http-ingest/src/snapshots/source_http_ingest__test__discover_backwards_compatibility.snap
source-http-ingest/src/snapshots/source_http_ingest__test__discover_with_paths.snap

When I updated the Flow protocol dependency in 0c7846f, I neglected to set the `is_fallback_key` for for source-http-ingest discovered bindings.
This was causing the build to fail, because Rust requires all struct fields to be explicitly set. And since we are setting it, we might as well make it True, since the synthetic webhook ID does indeed meet the criteria for a fallback key.
(anything that might …

source-http-ingest: set `is_fallback_key` for discovered bindings

---

source-postgres/.snapshots/TestFeatureFlagFlattenArrays-Disabled-Discovery
source-postgres/discovery.go

When we capture arrays as {dimensions, elements} tuples, we need the generated JSON schema type to set `additionalProperties: false` in SourcedSchemas (because for schema inference purposes we always want to forbid additional properties). But since these values will never have additional properties we'll just add it unconditionally to the write schema for simplicity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2881)

source-postgres: Set additionalProperties to false on array objects

---

source-postgres/.snapshots/TestPartitionedCTIDBackfill
source-postgres/backfill.go
source-postgres/capture_test.go
source-postgres/main_test.go

This PR fixes the CTID backfill maximum page size and pages-per-chunk heuristics so that they work correctly on partitioned tables, and adds a test case demonstrating that the new logic works as intended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2890)

source-postgres: Partitioned CTID backfill fixes

---

source-google-ads/source_google_ads/google_ads.py
source-google-ads/source_google_ads/streams.py
source-google-ads/tests/common.py
source-google-ads/tests/test_google_ads.py
source-google-ads/tests/test_source.py

We've observed several hanging `source-google-ads` captures in production. I've tried recreating a hanging capture locally, but I haven't been successful yet. I suspect it's an intermittent issue that would require running the capture for hours to replicate. To speed up debugging, I'm adding a ton of logging to identify where the connectors are getting stuck when it happens in production again. We can revert the logging commit later once the problem is addressed.
My leading suspicion is that the Google API is silently dropping connections, and the connector's stuck waiting on a response that will never arrive. So, I also wired in a rough timeout to catch this if/when it happens. It's set at 5 minutes right now (which seems like a pretty generous duration).
**Workflow …

source-google-ads: add logging to debug hanging captures & add a request timeout

---

source-shopify-native/source_shopify_native/models.py
source-shopify-native/tests/snapshots/snapshots__spec__capture.stdout.json

Until our Shopify OAuth app is ready & the OAuth authentication option works, show the `AccessToken` auth option first.
Confirmed on a local stack that the `AccessToken` option shows up first instead of OAuth.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2905)

source-shopify-native: show `AccessToken` as first option under "Authentication"

---

go.mod
go.sum
source-oracle-batch/driver.go

- The go-ora library we use was outputting warning lines to stdout, breaking flow runtime message format. Updated the library in a fork (see https://github.com/sijms/go-ora/pull/679) to output those warnings to stderr instead. Tested this locally
- - - …

source-oracle-batch: use patched go-ora to avoid warning stdout

---

materialize-kafka/README.md
materialize-kafka/src/apply.rs
materialize-kafka/src/configuration.rs
materialize-kafka/src/transactor.rs
materialize-kafka/tests/snapshots/test__spec.snap
materialize-kafka/tests/test.flow.yaml
tests/materialize/materialize-kafka/setup.sh

Replace producer.flush() with custom AckTrackingContext that provides:
- Explicit delivery confirmation via ProducerContext callbacks
- Fail-fast on first delivery failure with proper error propagation
- Enhanced producer config (acks=-1, enable.idempotence=true)
This eliminates silent failures during broker instability by ensuring
StartCommit only proceeds after confirmed delivery of ALL messages.
(anything that might …

materialize-kafka: implement explicit delivery confirmation with fail-fast semantics

---

go.mod
go.sum
materialize-boilerplate/validate.go
materialize-boilerplate/validate_test.go

Implement folded field support in materialization connectors by setting the
FoldedField constraint when field names would be transformed during validation.
This enables proper field mapping when column names are modified by dialect-
specific transformations like case conversion or character translation.
A future control plane change will enforce disambiguation of folded
fields.
- FoldedField is now populated in Validated responses
(anything that might help someone review this …

materialize: add folded field constraint support

---

materialize-bigquery/.snapshots/TestSpecification
materialize-bigquery/bigquery.go
materialize-snowflake/.snapshots/TestSpecification
materialize-snowflake/config.go

Adds a similar option as what was recently added for materialize-snowflake.
The BigQuery truncation behavior was a little more generous than the standard limits. Truncation is needed for BigQuery because you can't load a row that is larger than 20MiB through a normal query, so rows can't be arbitrarily large.
But most of the time a row will be smaller than that, so disabling truncation is a reasonable thing to do.
**Notes for …

materialize-bigquery: configuration for disabling field truncation

---

source-monday/source_monday/graphql.py
source-monday/source_monday/models.py
source-monday/tests/snapshots/snapshots__spec__stdout.json

The `source-monday` connector has shown to miss boards during backfill. In testing, I found that the query to get `boards` may return nothing if there are no boards to get. This would fail before due to the Pydantic model type being wrong. I've updated this and added a few more updates for error handling.
- _Tested locally - I was able to see all the boards captured in a backfill without any issues. I am …

source-monday: enhance error handling and boards Pydantic model

---

materialize-iceberg/emr.go

We must handle arbitrarily large result sets for load queries, and the default 1 GiB limit is not compatible with that requirement.
This change removes the limit for result set size. It is possible that the Spark driver itself will OOM if the result set is too large, and in that case the user will need to set higher limits for the EMR Application.
- - - …

materialize-iceberg: do not limit result set size

---

source-postgres-batch/.snapshots/TestDateAndTimeTypes-Capture
source-postgres-batch/main.go
source-postgres-batch/main_test.go
source-redshift-batch/main.go

We represent timestamp values as RFC3339 strings, which only allow the year to range from 0 to 9999, so we need to normalize dates outside of that range to a sentinel value.
This fixes https://github.com/estuary/connectors/issues/2955
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2957)

source-postgres-batch: Normalize excessive dates/timestamps

---

filesource/filesource.go

Added a mutex to the reader struct to synchronize access to the shared PullOutput stream operations across all bindings. This fixes a concurrency issue where multiple bindings could interleave their `Documents()` and `Checkpoint()` calls.
The mutex ensures that when one binding is writing documents or checkpoints, other bindings must wait, maintaining consistency of the output stream.
We could update our `filesource` based connectors' docs with instructions on how to add multiple bindings with `flowctl` since they won't trample each others' states any more.
This isn't the most efficient solution - we _could_ allow separate bindings to emit …

filesource: don't emit documents/checkpoints concurrently across bindings

---

materialize-boilerplate/materializer.go

Materialization setup actions often require all namespaces to exist in order to run successfully. An example of this is SQL materializations that create a checkpoints table in the endpoint's configured schema.
- - - …

materializer: run Setup after creating namespaces

---

source-stripe-native/source_stripe_native/resources.py

The connector is OOM-ing when there are thousands of connected accounts. We need to figure out a strategy to capture from that many connected accounts without OOM-ing. Unfortunately, that will likely take a significant amount of time. In the meantime while we're figuring that out, only capture from the 100 most recent connected accounts to avoid OOMs.
Tested on a local stack. Confirmed the connector …

source-stripe-native: only capture from the most recent 100 connected accounts

---

materialize-iceberg/emr.go

Having vectorized reads was causing column migrations to fail in some cases.
Disabling vectorized reads seems to resolve this. I am not sure if there is any
performance impact to load queries, but I think it is unlikely.
- - - …

materialize-iceberg: disable vectorized iceberg reads in spark configuration

---

source-asana/connector_config.yaml

It's just better to have these encrypted. This was't a credential leak because:
* All API requests are authenticated via an access token.
* In order to get an access token, you need a client ID and secret, as well as a refresh token (docs). There is a plaintext client ID, but the client secret is encrypted, so there’s not enough to request a new access token.
* There is a plaintext access token, but it expired in 2023.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2999)

source-asana: Encrypt `access_token` and `refresh_token` in `connector_config.yaml`

---

source-shopify-native/source_shopify_native/graphql/orders/orders.py
source-shopify-native/tests/snapshots/snapshots__capture__capture.stdout.json

This pull request enhances the `Orders` class in the Shopify GraphQL integration by adding support for detailed line item data. It also updates the `process_result` method to handle line items and adjusts the test snapshots to reflect these changes.
This is a simple query update, so I did not test in a local stack. I did test with `flowctl preview` and verified the snapshots were updated too. The test …

source-shopify-native: add support for line items to orders binding

---

source-pendo/source_pendo/models.py
source-pendo/tests/snapshots/snapshots__discover__capture.stdout.json

Adds the `Account` stream to `source-pendo`.
Connector documentation will need updated to reflect the added stream.
Tested on a local stack. Confirmed accounts are captured similarly to the `Visitor` stream.
A note for myself in the future: the `"appId": "expandAppIds(\"*\")"` field in the request body doesn't seem to do anything for the `accounts` source - I think Pendo ignores it. That's fine since that field essentially tells Pendo to return data for all accounts; although we need to provide that field for the `visitors` and `trackType` sources, returning data for all accounts is inherently what the `accounts` source does anyway.
- - - …

source-pendo: add `Account` stream

---

go/auth/snowflake/.snapshots/TestConfigSchema
go/auth/snowflake/config.go
go/auth/snowflake/config_test.go
materialize-snowflake/config.go
materialize-snowflake/config_test.go
materialize-snowflake/pipe.go
materialize-snowflake/snowflake.go
materialize-snowflake/snowflake_test.go
materialize-snowflake/stream_http.go
source-snowflake/.snapshots/TestConfigURI-Optional_Parameters
source-snowflake/.snapshots/TestConfigURI-User_&_Password_Authentication
source-snowflake/config_test.go
source-snowflake/database.go
source-snowflake/main.go
source-snowflake/main_test.go

The scope of this PR includes:
- Make the `account` field optional & hidden for `source-snowflake` (similar to the work done for `materialize-snowflake` in https://github.com/estuary/connectors/pull/1725)
- Move the common Snowflake authentication config code between `source-snowflake` and `materialize-snowflake` into the `go/auth/snowflake` package.
- Update `source-snowflake` to support JWT authentication.
Documentation for `source-snowflake` should be updated to reflect the new JWT authentication option.
Tested on a local stack. Confirmed with `source-snowflake` that:
- JWT authentication works to create a capture and replicate data …

source-snowflake: add JWT auth and make `account` field optional/hidden

---

source-google-analytics-data-api-native/source_google_analytics_data_api_native/resources.py
source-google-analytics-data-api-native/tests/snapshots/snapshots__discover__capture.stdout.json

Users frequently do not want to re-capture the same day's reports every 30 minutes. Instead, default to a longer interval so users don't have to push the interval out themselves as often.
Connector docs should be updated to reflect the new default value of 12 hours.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3025)

source-google-analytics-data-api-native: increase default resource interval

---

source-facebook-marketing/source_facebook_marketing/utils.py

Facebook uses the user's timezone for the insights API, not UTC. We can't query for insights older than 37 months in the past, so `validate_start_date` pulls forward the start date to ensure we're submitting queries within that 37 month window. This works fine when the user's timezone is UTC or has a negative offset, but when a user has a positive offset (like +08:00), we end up pulling the start date up to 37 months and 1 day according to their timezone.
To avoid these timezone related issues, we can add a day to the originally calculated `retention_date` so we're always within the 37 month retention period. …

source-facebook-marketing: adjust retention date validation for timezone handling

---

materialize-boilerplate/apply.go
materialize-boilerplate/apply_test.go
materialize-boilerplate/info_schema.go
materialize-boilerplate/info_schema_test.go
materialize-boilerplate/materializer.go
materialize-redshift/driver_test.go
materialize-s3-iceberg/driver_test.go
materialize-sql-v2/validate_test.go
materialize-sql/std_sql.go
materialize-sql/validate_test.go

If a destination system does not allow materialized fields to differ in capitalization but does report out its fields while preserving their casing, don't try to create a new field even if the source Flow collection field has a different casing. By definition it won't work, so we should just proceed and assume that the pre-existing field is going to be used for the Flow field even though it has a different casing.
**Notes for …

materializer: do not try to re-create columns that are case insensitive which already exist

---

materialize-snowflake/snowflake.go
materialize-snowflake/stream.go
materialize-snowflake/stream_test.go

The table name and table schema are separate inputs to the Snowpipe streaming API. Previously if there was an alternate schema for a binding, the fully qualified identifier was being used as the table name, which would cause "table not found" errors.
This fix uses only the table name part for the table name.
I tested this manually using a materialization config with several bindings, where some of them have an alternate schema specified. …

materialize-snowflake: use correct table identifier in stream manager

---

source-kinesis/main.go

Applies an identical change as was made to source-dynamodb to improve connection re-use and minimize DNS resolution requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3048)

source-kinesis: bump allowed idle connections to avoid excessive re-creation

---

materialize-snowflake/bdec.go
materialize-snowflake/bdec_test.go
materialize-snowflake/snowflake.go
materialize-snowflake/snowflake_test.go
materialize-snowflake/stream.go
materialize-snowflake/stream_test.go

The Snowflake behavior change 2025_03 bundle allows VARIANT columns to be extremely large, up to 128 MB. If this bundle is enabled we don't need to check that VARIANT values are too large.
It could still technically be disabled if the user has opted their account out of the bundle. In a couple of months this is slated to be enabled everywhere all the time no matter what, and we can remove most of this code then.
Closes https://github.com/estuary/connectors/issues/3060 …

materialize-snowflake: do not enforce VARIANT max length if account supports it

---

go.mod
go.sum
materialize-boilerplate/materializer.go

If the feature flag `allow_existing_tables_for_new_bindings` is set, disable the load key optimization to prevent conflicts with data in pre-existing tables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3062)

materializer: disable load key optimization if using pre-existing tables

---

estuary-cdk/estuary_cdk/http.py

It's a good idea to retry connection timeouts a few times in case of intermittent errors from flaky APIs. This is safe to do in the `request()` method since it consumes the entire response body before returning, unlike `request_lines()` and `request_stream()` which yield chunks that may have already been processed before a timeout occurs.
Tested the behavior with a small script. Confirmed a request is …

estuary-cdk: retry connection timeouts

---

estuary-cdk/estuary_cdk/http.py

My earlier attempt at retrying connection timeout errors in https://github.com/estuary/connectors/pull/3065 wasn't thorough enough. Connectors still encountered `ConnectionTimeoutError`s when establishing the connection in `request_stream` and `request_lines`, and `asyncio.TimeoutError`s when reading the response body in `request`. After digging into the specific errors further, I learned that:
- `aiohttp.client_exceptions.ConnectionTimeoutError` is raised when [_establishing_ the connection](https://github.com/aio-libs/aiohttp/blob/815901f6afb2c460650ccb0b6f0bfa5b55fe5cd9/aiohttp/client.py#L665-L672). It is not raised after the connection is established and we've begun receiving chunks from the server.
- `asyncio.TimeoutError` is raised when the `aiohttp` client timeout …

estuary-cdk: improve HTTP connection timeout retry logic

---

estuary-cdk/estuary_cdk/capture/common.py
estuary-cdk/estuary_cdk/utils.py
source-monday/source_monday/api.py
source-monday/source_monday/graphql/__init__.py
source-monday/source_monday/graphql/boards.py
source-monday/source_monday/graphql/items.py
source-monday/source_monday/models.py

See #3047 (https://github.com/estuary/connectors/pull/3047#discussion_r2210885256) for more context.
This pull request introduces enhancements to cursor handling, backfill logic, and JSON merge patch functionality in the Estuary CDK and Source Monday integrations. The changes aim to improve efficiency, scalability, and fault tolerance, particularly in handling paginated data and structured cursors for the `items` stream. This PR also simplified the `items.py` `BoardItemIterator` by removing the unnecessary class that wrapped the functions. Below is a categorized summary of the most important changes:
* Added a new `CURSOR_MARKER` constant and utility functions (`is_cursor_dict`, `make_cursor_dict`, `pop_cursor_marker`) to support dict-based cursors for structured and …

source monday: use dict page cursor for items backfill

---

estuary-cdk/estuary_cdk/capture/common.py
source-stripe-native/source_stripe_native/resources.py

- Create deep copies of the `initial_state` when initializing a binding's state in `estuary-cdk`. This prevents unintended mutations to `initial_state` via `state`.
- Generate `initial_state` and `all_account_ids` once in `source-stripe-native`. Instead of generating these potentially large objects for _each_ binding and holding it in memory, it makes sense to only generate them once since they're calculated to the same value.
See individual commits for more details.
The memory unlocked by these improvements can be used to concurrently capture from more connected accounts. But before changing those settings, I'd like to observe and note how much these improvements affect actual production captures' memory usages. After noting how much these …

source-stripe-native: memory usage improvements for connected accounts

---

source-postgres/database.go
source-postgres/discovery.go
source-postgres/main.go
source-postgres/replication.go

It's not uncommon in production for the query connection to be disconnected, especially if it's idle for more than a minute when replication gets busy.
Previously when that happened we would just propagate the error until it resulted in the capture failing, and then the task would be automatically restarted again after 5-10 minutes.
But that's dumb and inefficient when we could simply reconnect and continue operation as normal, the only reason we don't currently do that is that it's more work to implement. Except really it's not, we can just swap in pgxpool throughout and fix up a couple fiddly bits and there we go, now any time we go to use the connection after it's been idle for longer than 1 second (hard-coded pgxpool threshold) it will be pinged and recreated first if …

source-postgres: Use pgxpool.Pool for query connection

---

source-monday/source_monday/graphql/query_executor.py
source-monday/source_monday/models.py

This change improves error handling for the Monday.com GraphQL API client by explicitly addressing the **list of errors** that may be returned in a single GraphQL response. When a query results in multiple errors (e.g., due to partial failures, field-level issues, or concurrent problems), the system now **analyzes all errors, determines their status codes, and surfaces the most actionable (highest priority) status code** to the caller. This approach also clearly marks which errors are non-retriable (e.g., permission, validation, or schema issues), which should be retried (e.g., rate limits, server errors which are typically transient), and which require special handling (e.g., cursor expiry).
Note: the cursor expiry is not handled as a special case currently. The code …

source-monday: improved error handling

---

source-sage-intacct/source_sage_intacct/api.py
source-sage-intacct/source_sage_intacct/models.py
source-sage-intacct/source_sage_intacct/sage.py

* Accept "float" values for Sage fields that are typed as INTEGER, since that is apparently a thing that can happen. Sooner or later I'd imagine we'll just need to accept "any" for all of these column types, but I'm just keeping them       strictly typed now out of morbid curiosity.
* Some fixups for deletion handling, since that hadn't been able to be properly tested until now.
(anything that might help …

source-sage-intacct: updates to fix capture

---

source-salesforce-native/source_salesforce_native/models.py

Turns out that sometimes Salesforce says a standard field is `xsd:int`/`xsd:long` but the field actually contains float values. The REST API keeps the type Salesforce sends these fields to us, but the Bulk API returns everything as strings since we're reading from CSVs & we convert them to the appropriate type. Our previous handling choked on supposedly integer type fields containing values like `"47.0"`, but the existing `_str_to_number` function handles this fine. …

source-salesforce-native: improve integer conversion handling for Bulk API records

---

.github/workflows/python.yaml
source-google-play/source_google_play/gcs.py

I forgot to add the new `source-google-play` connector to the CI workflow in https://github.com/estuary/connectors/pull/3091. This PR fixes that so the package will be built and published.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connecto …

source-google-play: add to ci

---

materialize-postgres/VARIANTS

Adds Supabase as a PostgreSQL materialization variant for better Supabase discoverability.
The Postgres connector appears to already handle Supabase use cases (specifically, forbidding connection poolers), and I was successfully able to set up a Postgres materialization using a Supabase instance.
I will add new reference docs for the Supabase variant.
Thanks for reviewing!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3088)

materialize-postgres: Add Supabase variant

---

source-mongodb/change_stream.go
source-mongodb/test_util.go

Clean revert of the commits from #3097 and #3096.
This change had a bad interaction with captures using batch modes of capture, where there are change streams running concurrently with backfill tasks and there is a period where the change streams get priority over the backfill tasks until they are caught up. The change as-implemented would have these never signal that they were caught up, since `stopWhenCaughtUp` is actually false in this case, as they run continuously.
I'll have to think about this implementation more. I think the immediate need for it is resolved so it is fine to revert for now until I can come up with something better. …

mongo revert

---

source-postgres/backfill.go
source-postgres/change.go
source-postgres/datatypes.go
source-postgres/replication.go

We only use discovery info in a couple of limited spots during result value processing (and arguably we should try to remove those), mostly driving it based on the PostgreSQL datatype OID and the Go values that result from using those.
Previously we were perfectly happy for that data to be missing, just carrying on as best we could without the discovery-type special cases. This was broken as part of the big optimization refactoring, so here I'm streamlining the relevant code to just the values we actually use and then making it not an error if the discovered type is unknown.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3113)

source-postgres: Handle missing discovery info for column

---

source-google-play/source_google_play/models.py
source-google-play/tests/snapshots/snapshots__spec__capture.stdout.json

It turns out the Google Play docs aren't completely accurate. They say the bucket will start with `pubsite_prod_rev_<some_identifier>`, but it's possible for buckets to look like `pubsite_prod_<some_identifier>`. I'm removing the bucket name validation entirely for now; once the connector gets some use, we can add this validation back in if entering an incorrect bucket name is a frequent failure point during setup.
**Notes for …

source-google-play: remove bucket name validation

---

source-mongodb/change_stream.go
source-mongodb/test_util.go

Commit 45884eb was an initial, but flawed attempt to accomplish this, which was reverted while I thought harder about how to do it correctly.
The general idea is that we have observed MongoDB change streams actually returning no results from `TryNext` even if there are more results, so we can't reliably treat the lack of results as a positive indication that the stream is caught up. Retrying a few times over the course of ~seconds seems to reliably get records if there are any though, so when a stream is being "caught up", it needs to be retried a few times if it gets no results, but has not yet observed an event timestamp later than the cluster op time watermark. This is almost exclusively relevant to databases with large existing tables that are backfilling, but no …

source-mongodb: retries on empty change stream results during catch-up take 2

---

source-azure-blob-storage/main.go

We need to reset the index back to 0 when we start reading files on a new page, otherwise the connector will try to use the index from the previous page and panic with an `index out of range` error.
- - - …

source-azure-blob-storage: reset index after fetching the next page

---

source-sage-intacct/source_sage_intacct/resources.py

There isn't really a way to capture deletion records for PROJECT objects since the audit history for these doesn't include the RECORDNO primary key, but we can infer deletions by using a snapshot binding.
I don't expect the PROJECT list to be very large, so a snapshot binding should work fine for it.
- - - …

source-sage-intacct: make PROJECT a snapshot binding

---

source-postgres/replication.go

Honestly we might just ignore them outright (like we do when they arrive during the initial stream opening), but this is pretty rare and we've never seen notices _in the replication stream_ before, so I'd like to have logging tell us what it is. Might lower it to debug level after I see what the relevant production capture is telling us.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3138)

source-postgres: Log and ignore NoticeResponse during replication

---

source-monday/source_monday/models.py

Adds `BOARD_VIEW_DELETED` event to ActivityLogEvents and updates ActivityLog to accept string events in the model so that the default `case` in `get_event_result` is reached. Before, we would see a Pydantic validation error. The match-case still works as before, but now the default case is reachable with a custom validation error thrown that is easier to read in logs.
Tested with `flowctl preview` to …

source-monday: handle new activity log event

---

source-mongodb/.snapshots/TestSpec
source-mongodb/change_stream.go
source-mongodb/change_stream_test.go
source-mongodb/main.go
source-mongodb/pull.go

Adds a couple of advanced configuration options for change streams, to set a larger maxAwaitTime and to completely disable pre-images.
These options may be useful for high-volume change streams, where the server takes longer to respond with ready change events, and pre-images are not needed but cannot be disabled for collections on the database side.
The source-mongodb documentation will need updated to reflect these options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connect …

source-mongodb: advanced options for change streams

---

source-monday/source_monday/models.py

Adding `BOARD_DISCONNECT` activity log event. I don't understand this event as much; However, the `board_id` is part of the `activity_log.data` field and it appears we should treat this event as a normal `board` refresh event.
- - - …

source-monday: add `board_disconnect` activity log

---

go.mod
go.sum
source-mongodb/main.go

Use snappy compression exclusively, since it is supported by all MongoDB
databases of interest and is quite a bit faster than zlib.
Upgrades the MongoDB driver to the latest, since I was testing if the memory
issues with zstd compression were fixed. They weren't, but it doesn't seem like
a bad idea to upgrade the driver version anyway.
- - -
This change …

source-mongodb: use snappy compression

---

source-salesforce-native/source_salesforce_native/supported_standard_objects.py

Users are requesting the addition of the `Knowledge__ka` and `Knowledge__kav` standard objects. They both have a `SystemModstamp` field and can be queried via the REST and Bulk APIs, so simply adding them to `supported_standard_objects.py` should let these objects be discovered.
I verified that both `Knowledge__ka` and `Knowledge__kav` are standard objects, have a valid cursor field (`SystemModstamp`), …

source-salesforce-native: add two more standard objects

---

materialize-snowflake/.snapshots/TestSQLGeneration
materialize-snowflake/sqlgen.go

Querying the VARIANT document column directly was actually returning results through the Go driver as pretty-printed JSON, which has a lot of extra whitespace. In extreme cases, this could cause the documents to exceed gRPC message size limits. In more common cases it is just wasteful.
Using the TO_JSON function causes these documents to be returned in their compact JSON representation instead.
(anything …

materialize-snowflake: load documents as compact JSON

---

source-mongodb/change_stream.go
source-mongodb/change_stream_test.go
source-mongodb/coordinator.go
source-mongodb/coordinator_test.go
source-mongodb/test_util.go

Operation times can be extracted from change stream resume tokens, even if the resume token doesn't correspond to a document event.
This ensures that the operation time will always be known when polling a change stream, which provides better observability for how caught up the connector is in reading the change stream (it won't artificially appear stalled when there are no document events for a while), and also a confirmation of when the change stream is caught up with the latest cluster time watermark.
Using these extracted operation times allows for removal of the clunky catch-up retry mechanism, which was a work-around for handling change streams that would return no events even when they were not caught up. It will now be known from the extracted timestamp that the …

source-mongodb: use latest op time decoded from resume tokens

---

source-monday/source_monday/models.py

Add handling for event types:
- `BOARD_VIEW_DISABLED` - board-level event. Handled by fetching the board; similar to `BOARD_VIEW_ENABLED`
- `UPDATE_BOARD_PERMISSIONS` - board-level event. Handled by fetching the board.
- `UPDATE_GROUP_COLOR` - board-level event. Handled by fetching the board. Note: the boards documents contain the group `id` and `name`, so this really doesn't change anything in the data from what I can tell. However, this event is seldom seen and causes minimal requests since it is board-level fetches.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, …

source-monday: add more activity log events

---

materialize-snowflake/stream.go

Log failed blob metadata if a streaming blob fails to be written.
We try to rename a blob if it errors on a "malformed request" because that is usually just that the blob is too old and needs a new file name generated, but if it still fails after that we need to know more about the metadata for debugging.
- - - …

materialize-snowflake: log failed blob metadata if a streaming blob fails to be written

---

source-salesforce-native/poetry.lock
source-salesforce-native/pyproject.toml
source-salesforce-native/source_salesforce_native/__init__.py
source-salesforce-native/source_salesforce_native/auth.py
source-salesforce-native/source_salesforce_native/models.py
source-salesforce-native/source_salesforce_native/resources.py
source-salesforce-native/tests/snapshots/snapshots__spec__capture.stdout.json

Some users are unable to authenticate with OAuth to their production Salesforce instance. One such case is when their Salesforce uses Okta SSO. Users have requested an option to authenticate with a service account (non-SSO) with username, password, and security token as an alternative to OAuth.
By using the [SOAP `login()` call](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login.htm) to retrieve an access token and the instance domain, we can support authentication via username, password, and security token. Instead of making SOAP calls ourselves, the `simple-salesforce` package has a handy `SalesforceLogin` function that handles this for us.
**Documentation …

source-salesforce-native: add `UserPass` authentication option

---

source-pendo/source_pendo/api.py
source-pendo/source_pendo/models.py
source-pendo/source_pendo/resources.py
source-pendo/tests/snapshots/snapshots__discover__capture.stdout.json

`source-pendo` was the first native connector I built, and it doesn't follow a lot of the more standard conventions more recently built connectors follow. It also occasionally has OOM failures when backfilling the various event & event aggregates bindings.
- Refactoring `source-pendo` to bring it more in line with the conventions followed by other native connectors & to make maintaining the connector easier.
- The refactors are all in the first three commits. No functional changes were made in these commits.
- Using the `IncrementalJSONProcessor` to reduce memory usage & avoid OOMs.
I'd recommend reviewing commit-by-commit. It looks like there's a lot of changes, but most of it is re-organization of the existing code. The only functional change …

source-pendo: refactor & use IncrementalJSONProcessor

---

materialize-postgres/.snapshots/TestSpecification
materialize-postgres/driver.go

Make `credentials` required so it's unfolded in the UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3200)

materialize-postgres: mark `credentials` as required

---

source-pendo/source_pendo/models.py
source-pendo/source_pendo/resources.py
source-pendo/tests/snapshots/snapshots__discover__capture.stdout.json

The collection keys for the events and event aggregates resources were insufficient to uniquely identify records, causing de-duplication through the platform on non-duplicate data. This PR fixes the collection keys for events and event aggregates.
The change in collection keys will cause collections to be re-versioned and to be backfilled for all existing captures.
Tested on a local stack. Confirmed …

source-pendo: fix collection keys for events and event aggregates

---

source-hubspot-native/source_hubspot_native/models.py
source-hubspot-native/tests/snapshots/snapshots__capture__stdout.json
source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json

Production `source-hubspot-native` captures are hitting this error:
```
runTransactions: readMessage: Task capture.engagements.incremental: 2 validation errors for BatchResult[Association]
requestedAt
Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
links
Extra inputs are not permitted [type=extra_forbidden, input_value={}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
```
It looks like Hubspot added a `requestedAt` and `links` field to the `BatchResult` response. The connector doesn't like these extra fields being present due to the `extra="forbid"` in the model, but it's fine to allow extra …

source-hubspot-native: allow extra fields in the BatchResult response

---

source-jira-native/source_jira_native/api.py
source-jira-native/source_jira_native/models.py
source-jira-native/source_jira_native/resources.py

Users have noticed `source-jira-native` is missing epics that aren't associated with any boards. The current strategy of only fetching epics associated with boards obviously won't capture these board-less epics.
Epics can be retrieved using two different approaches:
1. Via boards associated with epics
2. Via an issue search (Jira treats epics as a special type of issue)
We should use both approaches for a few reasons:
- Issue searches find epics that aren't associated with any boards.
- Board-based retrieval handles next-gen issues/epics that can't be fetched via the `/rest/agile/1.0/epic/:epicId` endpoint.
- Board-based retrieval is more API request-efficient than individual epic fetches after an issue search. Multiple epics are returned in a single response when …

source-jira-native: fetch epics not associated with boards

---

source-klaviyo-native/source_klaviyo_native/models.py

In events associated with campaigns, the `$message` field contains the campaign id. The imported `source-klaviyo` connector lifted that campaign id up to the top level, and the native `source-klaviyo-native` connector continues to do that. However, events associated with deleted campaigns do _not_ have a `$message` field at all; this is likely because the campaign has been deleted in Klaviyo and its id no longer exists. This PR updates the native connector to handle events for deleted campaigns.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that …

source-klaviyo-native: handle events for deleted campaigns

---

estuary-cdk/estuary_cdk/gunzip_stream.py
estuary-cdk/estuary_cdk/http.py
estuary-cdk/tests/test_gunzip_stream.py
source-apple-app-store/acmeCo/app_crashes.schema.yaml
source-apple-app-store/acmeCo/app_downloads_detailed.schema.yaml
source-apple-app-store/acmeCo/app_sessions_detailed.schema.yaml
source-apple-app-store/acmeCo/app_store_discovery_and_engagement_detailed.schema.yaml
source-apple-app-store/acmeCo/app_store_installs_and_deletions_detailed.schema.yaml
source-apple-app-store/acmeCo/flow.yaml
source-apple-app-store/source_apple_app_store/api.py
source-apple-app-store/source_apple_app_store/client.py
source-apple-app-store/source_apple_app_store/models.py
source-apple-app-store/source_apple_app_store/resources.py
source-apple-app-store/source_apple_app_store/utils.py
source-apple-app-store/test.flow.yaml
source-apple-app-store/tests/snapshots/snapshots__discover__stdout.json

This PR finalizes the implementation of the Apple App store capture connector after seeing it used and finding out more about the quirks in Apple's API and asynchronous Analytics Report endpoints.
Introduces a `GunzipStream` class in the CDK for streaming uncompressed bytes from a Gzip encoded file returned from APIs with the `Content-Type` header set to `application/gzip`. This is not automatically decompressed by `aiohttp` and requires manual decompression, which this class will do via the built in `zlib` Python library.
Additionally, this PR simplifies the analytics report incremental streams page and log cursors to only change when we process a report. I.e., We assume (and have observed this behavior thus far) the analytics reports are processed and provided via the …

source-apple-app-store: finalize implementation

---

source-klaviyo-native/source_klaviyo_native/api/events.py

I noticed a production capture was deadlocked in the `events` backfill with no progress for ~8 hours. Injecting a SIGQUIT showed that the subdivision worker, shutdown monitor, and 4 out of 5 chunk worker tasks were still running. One chunk worker task was not included in the logs after the SIGQUIT, meaning it was no longer running. I suspect the deadlock occurred from this chunk worker exiting without decrementing the active worker count, and this prevented the shutdown monitor from detecting that all work was done.
I'm still investigating _how_ that chunk worker could have exited without decrementing the active worker count or raising an exception that propagates through the `TaskGroup`. In the meantime, implementing a health check that fails if any workers exit before …

source-klaviyo-native: add worker health check to prevent deadlocks

---

source-salesforce-native/source_salesforce_native/supported_standard_objects.py

This PR contains a lot of additions to and two removals from `supported_standard_objects.py`.
The additions were generated by checking which standard objects with cursor fields we've seen returned in `/describe` and `/describe/:sobject/sobject` API calls now. I scripted the generation of these, but I also spot checked a handful of them to confirm the cursor fields are correct & we can query them via the REST API.
The removals were driven by users trying to capture these objects but getting an error stating that we have to add a `WHERE ParentId = 'some_parent_id'` clause. The connector doesn't support capturing child objects yet, so removing these from the list of supported standard objects will help avoid these errors. We can look into adding these objects back once the …

source-salesforce-native: add more supported standard objects

---

go/materialize/logging.go
materialize-cratedb/driver.go
materialize-mysql/driver.go
materialize-postgres/driver.go
materialize-redshift/driver.go
materialize-snowflake/stream.go
materialize-sqlserver/driver.go

We have seen expirations using the 30 minute window, so refresh every 15 minutes. There is very little cost to doing this more frequently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3232)

materialize-snowflake: refresh bucket credentials more frequently 

---

estuary-cdk/common.Dockerfile

Some Python connectors have started failing due to the absence of the `tzdata` and `tzdata-legacy` packages (similar to https://github.com/estuary/connectors/pull/3169). Adding those packages into the `common.Dockerfile` makes them available.
Tested on a local stack & confirmed a capture that was getting errors for a missing `tzdata` package now works fine.
- - - …

estuary-cdk: add `tzdata` and `tzdata-legacy` to `common.Dockerfile`

---

go.mod
go.sum
go/writer/parquet.go
materialize-snowflake/bdec.go
materialize-snowflake/stream_http.go

Adds some additional logging about bdec file metadata as it is generated and bdec files are registered with the Snowflake streaming API. This includes a comparison with the written metadata from the parquet file itself.
It is somewhat verbose and may not be necessary long-term, but it is hoped that it will be useful to help diagnose any reported inconsistencies. …

materialize-snowflake: logging for bdec file stats

---

source-monday/source_monday/models.py

Adds support for an Activity log event that we have not seen in production captures until recent.
- `board_view_duplicated` - as the name suggests; it occurs when a user duplicates a view within a board. This event contains the `board_id` and should be treated as a board-level incremental update and does require a sync for the items stream.
- - -
This …

source-monday: handle new board_view_duplicated activity log event

---

estuary-cdk/estuary_cdk/capture/base_capture_connector.py
estuary-cdk/estuary_cdk/http.py
estuary-cdk/estuary_cdk/utils.py
source-klaviyo-native/source_klaviyo_native/api/events.py

This PR prevents the `events` backfill from deadlocking when a worker task is cancelled. Workers should never be cancelled during normal operation (the shutdown monitor and shutdown event coordinate when tasks should exit naturally), and a non-`TaskGroup` initiated cancellation is an exceptional condition that should stop processing and crash the connector. This PR does that by implementing `CancelledError` handling for workers.
I observed `source-klaviyo-native` captures getting deadlocked in the `events` backfill. Previous PRs to troubleshoot/address the deadlock were:
- https://github.com/estuary/connectors/pull/3221
- https://github.com/estuary/connectors/pull/3238
- https://github.com/estuary/connectors/pull/3253
After the last PR, I saw a log like "Task …

source-klaviyo-native: handle worker cancellation to avoid deadlocks

---

source-salesforce-native/source_salesforce_native/supported_standard_objects.py

Users have asked for `SurveyQuestion` and `SurveyQuestionResponse` standard object to be added to the list of supported standard objects. I confirmed they both have the `SystemModstamp` field and can be queried via the REST API without using a `WHERE` or `LIMIT` clause (i.e. the connector can currently support capturing these objects).

source-salesforce-native: add `SurveyQuestion` and `SurveyQuestionResponse` standard objects

---

source-jira-native/source_jira_native/models.py

If the `SERVICEDESK_AGENT` permission doesn't exist for the user's Jira instance or the user doesn't have that permission granted, we shouldn't discover any of the Service Management API streams since they'll fail with a 403 Forbidden error.
Confirmed that if a user doesn't have the `SERVICEDESK_AGENT` permission granted or that permission doesn't exist in their Jira instance, the Service Management API …

source-jira-native: check permissions for streams using the Service Management API

---

filesink/store.go
go/auth/iam/config.go
materialize-postgres/.snapshots/TestSpecification
materialize-postgres/driver.go
materialize-s3-csv/.snapshots/TestSpec
materialize-s3-parquet/.snapshots/TestSpec
source-postgres/.snapshots/TestGeneric-SpecResponse
source-postgres/main.go

This adds support for AWS IAM to materialize-s3-parquet and materialize-s3-csv.  Users who wish to use IAM authentication will need to configure a Role according to our [documentation][1].
related: https://github.com/estuary/flow/issues/2123
[1]: https://docs.estuary.dev/guides/iam-auth/aws/
NA
- https://github.com/estuary/flow/pull/2403

filesink: add IAM support for S3

---

materialize-snowflake/.snapshots/TestConfigURI-Optional_Parameters
materialize-snowflake/.snapshots/TestConfigURI-User_&_Password_Authentication
materialize-snowflake/config.go

We don't use the Go Snowflake driver's Config struct to build a DSN anymore since we have the "account" as an optional input, but that Config will automatically add a `maxRetryCount` parameter with a default value of 7 to connection strings.
There is some observational evidence that transient errors are not getting retried for basic queries, although somehow PUT queries do seem to get retried internally by the driver.
This adds `maxRetryCount=10` to our connection strings to ensure that retryable failures are retried in general.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that …

materialize-snowflake: add maxRetryCount parameter to connection string

---

estuary-cdk/estuary_cdk/http.py
source-hubspot/tests/snapshots/snapshots__capture__capture.stdout.json

We've observed more errors beyond `asyncio.TimeoutError` that crash connectors when trying to establish an HTTP connection. As long as these errors occur before any data is consumed by the connector, these connection-related errors are safe to retry.
What's tricky is some error types could be raised when establishing the connection _or_ reading the response body. To ensure we only retry errors when establishing the connection, I refactored the retry logic to live in `HTTPMixin._request_stream` and only apply when establishing the connection instead of for the entirety of `HTTPMixin._request_stream`.
Note: the GH workflow that builds CDK connectors doesn't run if there's _only_ CDK changes, so I updated `source-hubspot`'s failing capture snapshot to trigger a rebuild of …

estuary-cdk: retry more HTTP connection errors

---

estuary-cdk/estuary_cdk/http.py
source-shopify-native/source_shopify_native/graphql/README.md

I missed adding `aiohttp.ServerDisconnectedError` to the list of new errors to retry in https://github.com/estuary/connectors/pull/3329. `aiohttp.ServerDisconnectedError` can be raised both when establishing the connection and when streaming the response body, but the CDK only retries when establishing a connection so it's safe to retry them.
Note: like in that earlier PR, I included a small update to a CDK connector to trigger GH workflow that runs Python connector tests & build images. …

estuary-cdk: retry one more connection error

---

materialize-mongodb/driver.go

Set `NoTruncateResources` for MongoDB materialization.  This materialization has not supported TruncateResource since it was added in [#3090](https://github.com/estuary/connectors/pull/3090/files#diff-40f53bb4e4160d9b7be44c3cbb9f76824c1cda2b3e0931d0bcb86ff4ce102468R204).
The connector will do a drop table and recreate on backfill.
NA

materialize-mongodb: disable support for truncating resources

---

materialize-boilerplate/materializer.go

We allow a resource action to be nil and skip their execution, but when we run delete/create together we didn't handle the case where one or both are nil.  These must be ran together in a single action so provide ordering in case concurrency is enabled.
NA
NA

materialize-boilerplate: skip nil actions during delete/create

---

source-jira-native/source_jira_native/api.py
source-jira-native/source_jira_native/models.py
source-jira-native/source_jira_native/resources.py
source-jira-native/tests/snapshots/snapshots__discover__capture.stdout.json

`sprint_issues`'s sole purpose is to serve as a join table between sprints and issues. `issues` already contains data for each issue, and `sprints` already contains data for each sprint, so we don't need to nor want to duplicate that data across multiple streams.
Jira does not expose a way to reliably detect when an issue is associated with a sprint, so we're not able to incrementally replicate `sprint_issues` and have to make it a full refresh stream instead.
The connector's docs should be updated to reflect the newly added `sprint_issues` stream that hits the [`/rest/agile/1.0/sprint/{sprintId}/issue` endpoint](https://developer.atlassian.com/cloud/jira/software/ …

source-jira-native: add `sprint_issues` stream

---

source-datadog/source_datadog/api.py
source-datadog/source_datadog/models.py
source-datadog/source_datadog/resources.py
source-datadog/tests/snapshots/snapshots__spec__stdout.json

Often, users have a significant amount of logs in Datadog and they don't want to capture all of them. The `advanced.logs_query` config option lets users filter out which logs the connector captures.
The connector's documentation should be updated to reflect the new config option.
Tested on a local stack. Confirmed the `advanced.logs_query` field is used when fetching `logs`.

source-datadog: support filtering logs with a user-provided query
