estuary/connectors

- source-s3/main.go
Resolves points 2 and 3 in #181
> update source-s3 spec to make keys optional

- go.mod
- go.sum
- materialize-bigquery/bigquery.go
- materialize-bigquery/transactor.go
- materialize-boilerplate/boilerplate.go
- materialize-postgres/driver.go
- materialize-s3-parquet/driver.go
- materialize-s3-parquet/driver_test.go
- materialize-snowflake/snowflake.go
- materialize-webhook/driver.go
Transactor adds Acknowledge, passes through contexts,
tweaks the Prepare interface, and introduces a new Load signal
for acknowledgements.
> bump protocols & update for Transactor changes

- parser/src/format/character_separated/mod.rs
Fixes #97
Adds an explicit check for the number of columns in each CSV row instead
of relying on the underlying parser to fail if a row has too many
columns. This allows us to consistently and correctly check the number
of columns in each row, even when headers are provided in the config
instead of being inline at the top of the file.
**Workflow steps:** no change
Adds the short link: https://go.estuary.dev/QRKf3x as a placeholder for documentation on parser configuration. This link currently only appears in the error message, but is intended to point users to an (advanced) "parser configuration" doc.
**Notes for reviewers:** none
> CSV missing columns with configured headers

- sqlcapture/discovery.go
When performing discovery, the existence of any table with an unhandled column type can break the entire process. It would be nice if we could simply note the failure and continue, especially since the user may not even care about capturing that table, or about that column of that table at least.
It might be cleanest eventually to just log a warning and not include the troublesome column in the generated schema at all. Sadly, flowctl swallows any warnings we produce, so to get it to the user we have to embed the error into the JSON schema output.
Currently the easiest way to hit this is to perform discovery when there exists a table with a column of an array type that hasn't been special-cased in.
> sqlcapture: don't error out on type translation failure

- source-postgres/capture_test.go
- source-postgres/discovery.go
Fixes https://github.com/estuary/flow/issues/365
Neither views nor materialized views can be captured by our connector because neither of them actually show up in the WAL. This makes sense, the only problem is that our discovery logic actually _would_ list views as acceptable streams.
The fix is to tweak the table-discovery query SQL to only return information about tables of type `'BASE TABLE'`. Strictly speaking this does more than just exclude views, but from [the documentation](https://www.postgresql.org/docs/current/infoschema-tables.html) it appears that the other table types we might see are `'FOREIGN'` and `'LOCAL TEMPORARY'`, and I don't think we want discovery to return those either.
Use `flowctl discover` on a PostgreSQL database, and you …
> source-postgres: exclude views from discovery

- source-postgres/discovery.go
The portion of the column-discovery query that reads column descriptions can fail in some cases, such as when the capture user doesn't have the `USAGE` permission on some schema. In many cases we didn't even want to capture these tables, so it makes little sense for this to be a fatal error for the entire discovery process.
This commit removes the column description from the main column discovery query, and then after the main query completes runs a loop over every discovered column individually requesting the description. Errors are ignored during this step, because the worst that should happen is that our generated JSON schema will not have useful descriptions.
Outside of the specific edge case of schemas which we don't have the `USAGE` permission on this should be a …
> source-postgres: Factor out column descriptions from discovery

- go.mod
- go.sum
Updates the Flow version to the latest master commit.
> bump flow dependency to latest master

- sqlcapture/main.go
It's basically never useful to capture this table, so we shouldn't be implicitly suggesting that by including it in the `flowctl discover` generated catalog.
This is a simple check performed right before emitting the discovered catalog, so it shouldn't have any impact on other uses of the discovery logic.
Our test coverage doesn't extend to the `sqlcapture.AirbyteMain` subcommands, so this was tested manually by running `flowctl discover` against a local PostgreSQL instance.
This fixes https://github.com/estuary/connectors/issues/190
Perform discovery (via `flowctl discover` or the new UI) using the `source-mysql` or `source-postgres` connectors, and the watermarks table should no longer be included in the resulting catalog.
> sqlcapture: Exclude watermarks table from discovery results

- sqlcapture/main.go
Not sure how exactly I screwed that up in https://github.com/estuary/connectors/pull/193, but somewhere between the version that I tested locally and the actual PR that I uploaded, I managed to screw up the `<namespace>.<name>` ordering, so the watermarks table comparison wasn't working correctly. Whoops :frowning_face:
This commit fixes that, and also adds some debug logging in case the table-filtering ever confuses somebody.
> sqlcapture: Fix watermark-filtering logic to actually work

- go.mod
- go.sum
This updates the go flow package to include latest changes for the sqlDriver.
> Flow: Update go package for sqlDriver

- go.mod
- go.sum
> Flow: Update go package

- source-gcs/main.go
- tests/source-gcs/setup.sh
> source-gcs: service account is a string, not JSON object

- source-gcs/Dockerfile
- source-hello-world/Dockerfile
- source-kafka/Dockerfile
- source-kinesis/Dockerfile
- source-mysql/Dockerfile
- source-postgres/Dockerfile
- source-s3/Dockerfile
- source-test/Dockerfile
- Add `sh` to source images so we can merge https://github.com/estuary/flow/pull/519
N/A
N/A
> source-*: add /bin/sh to source images

- materialize-firebolt/driver.go
- ApplyDelete must be idempotent, so if the table is already dropped, just log a warn message and exit gracefully.
> materialize-firebolt: warn if table doesn't exist and exit w/o err

- source-kinesis/main.go
Fixes #217 (a crash when performing discovery from flow)
N/A
N/A
N/A
> Wrap discovered catalog in airbyte message

- go.mod
- go.sum
> flow: update flow dependency to latest dfafc46

- source-mysql/replication.go
The `binlog_format=ROW` system variable can theoretically [1] be overridden on a per-session basis, and if this happens but only modifies tables that we don't care about capturing, then ideally we should just ignore those query events.
This PR modifies the handling of `INSERT` and `DELETE` statements in the binlog to only be an error if they impact tables that are currently active. It would be nice to also handle `UPDATE`s the same way, but those are more complicated and will require some additional work to make sure the logic is correct, so I wanted to handle the easy cases immediately and see if that helps with the specific failure we're observing.
[1] We have some weak evidence that this may be happening on Amazon RDS MySQL for updates to the `mysql.rds_heartbeat2` …
> source-mysql: Ignore INSERT/DELETE events from inactive tables

- source-mysql/main.go
This adds a query of the `mysql.rds_configuration` table where `name = 'binlog retention hours'`. If the query succeeds then this parameter takes priority over the standard MySQL system variables when doing the binlog retention sanity-check.
> source-mysql: Sanity-check RDS binlog retention too

- materialize-bigquery/endpoint.go
- materialize-bigquery/query.go
- materialize-bigquery/transactor.go
Bigquery frequently errors out due to concurrent updates against the
same table. This commit adds retry behavior around query execution so
that the connector does not fail. Unfortunately, there doesn't seem to
be a great way to identify errors due to concurrent updates, and so we
might also retry other types of errors. So we limit the number of retries,
to avoid continuously retrying queries that may never succeed.
**Workflow steps:** n/a
**Documentation links affected:** n/a
Originally, I'd hoped to also include a change here to have individual shards each use a distinct partition in the `flow_checkpoints_v1` table. While I still think that's beneficial, it seems like it'll take a while to handle migrating live materializations to the new table …
> Retry failed queries in materialize-bigquery

- source-http-file/main.go
- Add description to config JSONSchema of source-http-file. Thanks @oliviamiannone for writing them https://github.com/estuary/flow/pull/589
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/299)
> source-http-file: add description to config JSONSchema

- materialize-firebolt/firebolt/firebolt.go
- I had assumed that connector processes will not be long-running, but we do actually end up having long-running connector processes which means the access token will eventually expire.
- This PR introduces access token refreshing when it's about to expire (30 minutes before)
N/A, you just won't get more errors about expired tokens.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/300)
> materialize-firebolt: refresh access token when it's about to expire

- source-test/main.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/284)
> source-test: add OAuth2 annotation to endpoint spec schema

- source-test/main.go
- Remove required fields from OAuth2 section
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/304)
> source-test: remove required fields from OAuth2

- source-test/main.go
- Add OAuth2 credentials to config for testing purposes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/309)
> source-test: add OAuth credentials to config

- source-test/main.go
- update mapping to reflect Google's response better
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/311)
> source-test: update mapping

- source-test/main.go
- prompt=consent to get refresh token
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/312)
> source-test: prompt=consent for OAuth + refresh token

- source-postgres/replication.go
If the user creates two captures from the same Postgres database (and doesn't customize the replication slot name in the advanced settings) the second capture will fail because slot `flow_slot` is already in use.
This makes the error message a bit nicer in this situation, from:
error starting replication: unable to start replication: ERROR:
replication slot "flow_slot" is active for PID 9967 (SQLSTATE 55006)
To the slightly more user-friendly:
error starting replication: another capture is already running against
this database: replication slot "flow_slot" is active for PID 9967
We might want to add some text to https://docs.estuary.dev/reference/Connectors/capture-connectors/PostgreSQL/ discussing this situation and probably clarifying …
> source-postgres: Provide a more useful 'slot in use' error

- materialize-snowflake/.snapshots/TestSpecification
- materialize-snowflake/snowflake.go
The field ordering that was added to the snowflake materialization is causing issues with the JSON schema. This reverts that ordering until these issues can be resolved.
- - - …
> materialize-snowflake: remove field ordering

- materialize-bigquery/.snapshots/TestSpecification
- materialize-bigquery/bigquery.go
- materialize-elasticsearch/.snapshots/TestDriverSpec
- materialize-elasticsearch/driver.go
- materialize-firebolt/.snapshots/TestDriverSpec
- materialize-firebolt/config.go
- materialize-firebolt/config_test.go
- materialize-postgres/.snapshots/TestSpecification
- materialize-postgres/driver.go
- materialize-s3-parquet/.snapshots/TestS3ParquetDriverSpec
- materialize-s3-parquet/driver.go
- materialize-snowflake/.snapshots/TestSpecification
- materialize-snowflake/snowflake.go
- source-gcs/main.go
- source-kinesis/connection.go
- source-kinesis/main.go
- source-mysql/main.go
- source-postgres/main.go
- source-s3/main.go
This is a cherry-pick of https://github.com/estuary/connectors/pull/361, and then the changes to the test snapshots to reflect that ordering values are integers (see 88f299bff9defa7dce29dbd9fd01424ba3a68c86).
Refer to the documentation notes in https://github.com/estuary/connectors/pull/361
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/372)
> better field ordering for connectors (take 2)

- source-firestore/pull.go
I believe that the 'OrderBy' part of the Listen query is not necessary, and there is (very weak) evidence that it may cause ResourceExhausted errors to occur more frequently. This would make sense, if those errors indicate something like "you're using up too much server-side CPU/RAM" and the ordering requires extra work.
Retrying temporary failures seems like a good idea in general as well, since it allows the capture to make forward progress in some cases where immediately failing the capture wouldn't. I'm torn on whether there should be a maximum retry count or other safeguards, but since failing the entire capture will just result in Flow restarting it after 5 minutes or so, this should be an unambiguous improvement and we can think about improving on this in the …
> source-firestore: Remove 'OrderBy' and retry temporary failures

- materialize-boilerplate/boilerplate.go
- source-boilerplate/boilerplate.go
- Set a timeout for our listening on connector side for a connection to be initiated, otherwise connector processes can be stuck even when sent a SIGTERM, as was observed by @dhammika 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3 …
> *-boilerplate: set a deadline for listener.Accept

- source-mysql/main.go
- source-mysql/replication.go
When connecting for backfills and replication, we first try to connect with TLS, and if that fails for any reason we try again without TLS before erroring out.
This shouldn't change anything except that some MySQL databases which we previously failed to connect to should now be usable.
None, we didn't mention that TLS was required in our current docs anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/398)
> source-mysql: Attempt fallback to non-TLS connections

- source-firestore/pull.go
See https://github.com/estuary/connectors/issues/450 for a complete summary of the problem, but TL;DR: if replication fails to catch up within 10 minutes Firestore will cut us off, but if we fail the capture then we'll just retry again when the connector gets relaunched in a few minutes. And on monitoring that sure looks like a connector making progress!
So if we instead ignore the issue, that's also not ideal but at least it's not busy-looping and racking up massive read traffic the whole time.
I'm in the process of verifying this locally (it's fairly simple to test, just takes a while since we have to wait 10 minutes for Firestore to cut us off). Once that's done this should be good to go.
- - - …
> source-firestore: Don't error out if catchup streaming fails

- sqlcapture/capture.go
This is a new safety check added as part of https://github.com/estuary/connectors/pull/468 but which breaks the rollout of said PR in at least one case.
That case is when the scan key of an ongoing MySQL backfill contains a `DATETIME` column, which previously was serialized as an RFC3339 timestamp (with 'T' instead of ' ' separator and with the hour offset to UTC) and after the aforementioned PR these values are now serialized as the raw text format that MySQL prefers. The problem arises when we compare the old scan key (coming from the initial state checkpoint after the connector restarted) to a new one (the first key of the next backfill chunk after the restart).
In general we double-check the key ordering to help maintain the invariant that bytewise scan-key ordering …
> sqlcapture: Disable scan key ordering check as a temporary hack

- .github/workflows/ci.yaml
- Trigger a refresh of connector_tags when a new connector image is published
- Merge a change to master
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/486)
> ci: refresh connector tag after publishing new image

- config_schema_guidelines.md
Adding discriminator stuff to the docs
N/A
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/445)
> Adding discriminator section to the docs

- .github/workflows/ci.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/491)
> materialize-snowflake: temporarily disable pushing built docker image

- filesource/filesource.go
- add infer schema annotation to cloud storage connectors
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/504)
> source-{s3,gcs}: add infer schema annotation

- source-mysql/replication.go
* Ignore DROP PROCEDURE queries in replication handling.
* Make ignored queries case-insensitive.
None
Any easy ways to improve test coverage?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/511)
> source-mysql: add `DROP PROCEDURE` to set of ignored queries

- source-mysql/discovery.go
The `DATETIME` value `"0000-00-00 00:00:00"` is used by MySQL to indicate invalid data. However we can't process it into a RFC3339 timestamp through the normal parse-then-format machinery because month/day 0 doesn't exist. So we hard-code the replacement `"0000-00-00 00:00:00" -> "0001-01-01T00:00:00Z"` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/512)
> source-mysql: Replace the all-zeroes `DATETIME` with a valid RFC3339 placeholder

- source-firestore/discovery.go
- The discovery logic stays in place to discover collections, but we no longer run schema inference on the documents and instead just provide a minimal schema, along with the `x-infer-schema: true` annotation to let Flow handle the schema inference.
- see #496
- `flowctl-go discover --image source-firestore:local`
- - - …
> source-firestore: use minimal schema for firestore collections

- source-firestore/pull.go
Previously we needed to consume Acknowledge messages to avoid them blocking up stdin, but https://github.com/estuary/flow/pull/818 makes these opt-in so that's no longer necessary.
I'm not sure how long it'll take before the Flow changes are fully deployed, but this also isn't remotely a high-priority cleanup. I figure I'll just forget about this immediately and at some point in the future we'll merge it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/436)
> source-firestore: Remove Ack-discarding logic

- sqlcapture/main.go
- At `Validate` and `ApplyUpsert` RPC, make sure we have access to the binding tables
- I'm reusing our Discover logic for finding accessible tables here to be consistent. The code path that I have is probably not the most efficient if user is not choosing all the discovered bindings, but it is _simple_ and means we don't need some new logic.
- Create a capture to a sql endpoint (e.g. `source-postgres`) and add a binding to a nonexistant (or non-accessible) table. You should see an error like this:
```
could not find or access table estuary_test_cfngjj
```
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones …
> sqlcapture: validate existance and accessibility of table

- materialize-google-sheets/transactor.go
Adds a per-binding limit of 1,000,000 cells that can be part of the materialized view. This will prevent the connector from using an excessive amount of memory when reading from a high cardinality collection. We can fail fast in this case rather than letting the connector run out of memory and be OOM-killed.
Google sheets can actually hold more cells than this (up to 10,000,000 in a workbook). But based on some simple tests with wikipedia recent changes data, 1,000,000 cells of that collection uses about 200mb of data, so this seems like a more reasonable limit.
With this change it is still possible for a materialization to be specified with many bindings that would each stay under the limit, but cumulatively could use more memory. Rather than handling that complicated …
> materialize-google-sheets: limits for maximum number of materialized cells

- materialize-s3-parquet/parquet_file_processor.go
Adds a limit to the number of times that the connector will attempt to retry a file upload if the upload fails. This is a relatively quick-fix as opposed to a more comprehensive refactoring of the connector to use V2 of the AWS Go SDK which includes retrying retry-able errors. I've added a TODO that we can evaluate at some point if it makes sense to go down that path. For now this will fix the case where, for example, the service account credentials are invalidated on the AWS side and the connector keeps retrying forever while still showing an OK shard status while never writing any data.
The max retry attempts is pretty arbitrary but should be generous enough to allow for occasional occurrences of actual retry-able errors without getting hung up for too long on terminal …
> materialize-s3-parquet: limit the maximum number of attempts for retrying a file upload

- materialize-s3-parquet/parquet_file_processor.go
Quick fix to actually error out the connector if the retry attempts are exhausted
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/559)
> materialize-s3-parquet: exit with error with retry attempts exhausted

- .github/workflows/ci.yaml
`apt update` before `apt install`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/568)
> ci: apt update before install

- source-alpaca/worker.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/570)
> source-alpaca: temporary fix for long, empty backfills

- source-alpaca/worker.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/572)
> source-alpaca: temporary fix for long, empty backfills (take 2)

- source-mongodb/main.go
- Resolves #577 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/578)
> source-mongodb: check database exists

- materialize-postgres/pipeline.go
- debug log of the query being run by roundTrip
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/583)
> materialize-postgres: debug log query run by roundTrip

- materialize-postgres/pipeline.go
Reverts estuary/connectors#583
> Revert "materialize-postgres: debug log query run by roundTrip"

- materialize-sql/templating.go
- add debug level logs to `materialize-sql` connectors regarding their templates to allow troubleshooting template bugs / errors easier
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/587)
> materialize-postgres: debug log rendered templates

- materialize-mongodb/driver.go
- source-mongodb/discovery.go
- source-mongodb/pull.go
- Resolves #550 
- Delete a document from your capture, in the materialization you should end up with `_meta: { deleted: true }`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/591)
> source-mongodb: emit "_meta/deleted: true" for delete events

- materialize-sqlite/sqlite.go
- see https://github.com/estuary/connectors/issues/582
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/598)
> materialize-sqlite: fix documentation link

- .github/workflows/ci.yaml
Fixes an issue with determining the version for "variants" in the CI pipeline.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/602)
> ci: fix variant image version calculation

- .github/workflows/ci.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/603)
> ci: fix base connector path for version determination

- .github/workflows/ci.yaml
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/604)
> ci: fix BASE_CONNECTOR build-arg

- materialize-redshift/sqlgen.go
Redshift supports timestamps to microsecond precision. I found that if a value like `2022-12-01T14:40:56.999999951Z` where precision beyond the microsecond level is significant is materialized, Redshift will error out when inserting it into a table.
This sets an element converter for timestamps that will truncate their values to have at most microsecond precision.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/597)
> materialize-redshift: truncate timestamps to microsecond precision

- materialize-sql/driver.go
- materialize-sql/validate.go
- Allow migration to remove a field, this will lead to the column being marked as nullable and left in the database. Does not allow removing of key fields.
- Remove a non-key field from your collection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/607)
> materialize-sql: allow migration to remove a field (mark nullable)

- materialize-sql/driver.go
- If a binding has been removed, drop its corresponding table
- Delete a binding from an existing materialization, and the table should be dropped
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/614)
> materialize-sql: drop table if binding is removed

- materialize-sql/driver.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/624)
> materialize-sql: use `dialect.Identifier` on AlterInput field

- materialize-sqlite/sqlite.go
The `materialize-sql` framework expects a CheckPrerequisites function from its Endpoints, and the sqlite materialization didn't have one which was causing a nil pointer panic.
The sqlite materialization doesn't have any prerequisites to check so this adds a noop function for that.
- - - …
> materialize-sqlite: add CheckPrerequisites placeholder function

- go.mod
- go.sum
- materialize-firebolt/driver.go
- materialize-firebolt/schemalate/run.go
- materialize-firebolt/transactor.go
- Delete table when the corresponding binding is deleted
- Also fixed a bug with empty prefixes causing data not to be committed properly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/623)
> materialize-firebolt: delete table when binding is removed

- materialize-sql/validate.go
- better error for the case of incompatible projections
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/633)
> materialize-sql: better error for incompatible projections

- source-mysql/datatype_test.go
- source-mysql/discovery.go
- source-mysql/prerequisites.go
This PR includes a few fixes/enhancements to `source-mysql`.
Closes https://github.com/estuary/connectors/issues/537
With this change we'll try to create the database for the watermarks table if it doesn't exist prior to creating the watermarks table itself if it doesn't exist. This will work for cases where the user configured for the capture has the ability to create databases, which is probably most common for testing setups running with an admin account or similar.
If the database and watermarks table is able to be created the watermarks part of the setup can be completed and the capture run with no other prior database actions.
Closes https://github.com/estuary/connectors/issues/538
Currently, if the timezone can't be determined from the system `'time_zone'` variable …
> source-mysql: a few fixes/enhancements

- .github/workflows/ci.yaml
- infra/docker-compose.yaml
- tests/source-kafka/setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/678)
> source-kafka: fix integration test

- materialize-mongodb/.snapshots/TestSpecification
- materialize-mongodb/config.go
- source-mongodb/main.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/693)
> mongo: recommend pasting the full URL

- materialize-mongodb/config.go
- source-mongodb/main.go
- Fixes the failing mongodb jobs in CI pipeline
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/702)
> mongodb: fix jsonschema description

- source-mysql/replication.go
This fixes https://github.com/estuary/connectors/issues/703 by requesting heartbeat events from the server every 30s and setting a message read timeout of 5 minutes.
The heartbeats should ensure that the TCP connection remains open under normal conditions even when no other activity is occurring, and the read timeout ensures that we will detect otherwise-silent link failures within minutes rather than hours.
This would be tricky to test automatically in CI, but I have tested manually that this change works as expected, and also verified that without this change a default-configured MySQL instance doesn't send any heartbeat or similar traffic when no changes are occurring, which is entirely consistent with the failures we observed in production.
- - - …
> source-mysql: Request heartbeats and set read timeout

- source-postgres/prerequisites.go
This was previously disabled because it broke captures from Amazon RDS, due to how they use the `rds_replication` role instead of `REPLICATION` (and don't bother to also tweak the `rolreplication` column of `pg_roles` accordingly).
The fix is to add an explicit fallback check for membership in the `rds_replication` role.
As far as I know the new logic should work on all major managed SQL providers, but I haven't actually tested that. We can either spend several hours on some manual testing to make sure this works, which I'm not prepared to do right this moment but will get to sometime soon, or we could just YOLO merge it and then if we see any unexpected task failure notifications revert it again.
- - - …
> source-postgres: Re-enable 'user has REPLICATION' check

- source-mongodb/main.go
If ReplicaSet is not enabled a MongoDB deployment, the backfill operation will work but then the connector will fail when trying to create a change stream. This adds verification that a change stream can be created during the `Validate` RPC.
The only way I could find to make sure that a change stream can be created is to actually try to create a change stream, so this validation involves creating one and then immediately closing it for each captured mongodb collection. This will add a little bit of overhead to each `Validate` call but it seems pretty insignificant in my testing.
Closes https://github.com/estuary/connectors/issues/749
If you try to set up a capture on a mongodb instance without ReplicaSet enabled (cannot create a change stream), you'll …
> source-mongodb: validate change stream creation

- materialize-google-sheets/util.go
Expand the request retry logic of `materialize-google-sheets` to cover 502 / 503 errors as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/760)
> materialize-google-sheets: expand retries to cover 502/503

- materialize-pinecone/client/client.go
Increases the number of retry attempts that will be made for retryable errors before erroring out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/763)
> materialize-pinecone: increase retry attempts for retryable errors

- source-sqlserver/discovery.go
A user ran into a situation where the `CONSTRAINT_NAME` column was the same for distinct rows in `INFORMATION_SCHEMA.TABLE_CONSTRAINTS`, so the join with `INFORMATION_SCHEMA.KEY_COLUMN_USAGE` on that column resulted in multiple rows when we need there to just be one.
I'm pretty sure that the 6-tuple `{CONSTRAINT,TABLE}_{CATALOG,SCHEMA,NAME}` is properly unique, so screw moderation we'll join on all six columns.
I have not added a unit test for this because I'm not sure how the colliding constraint names came to exist. In my attempt to write a test reproducing this I observed that constraint names are normally something like `PK__TestTabl__3213E83FFF1774D4` with a unique ID, so I suspect that either some sort of explicit primary key setup is required or this only occurs on …
> source-sqlserver: Improve primary-key discovery query

- source-postgres/prerequisites.go
Sometimes a replication slot with the name the capture is configured with already exists, but not in the database that the capture is using. This will currently cause the connector to fail after publication with a Postgres error like `replication slot “flow_slot” was not created in this database`. This can happen if a publication is attempted and is able to create the slot but fails for some other reason, and then the user changes their configured database and publishes it again.
With this change we will return a validation error describing this fact when the desired slot name already exists but in another database. The solution is to use a different slot name, or remove the existing slot. …
> source-postgres: verify that replication slot exists in the configured database

- source-postgres/discovery.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/782)
> source-postgres: fix infinity timestamp

- source-mysql/prerequisites.go
There are a couple of reports that this check may be producing false positives in some setups that should otherwise work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/793)
> source-mysql: Disable REPLICATION SLAVE permission check

- source-mongodb/pull.go
- handle an additional error signifying a missing resume token
- handle replace events
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/795)
> source-mongodb: additional resume token error, listen on replace events

- materialize-pinecone/transactor.go
- tests/materialize/materialize-pinecone/setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/798)
> materialize-pinecone: handle precomputed JSON bytes for optional fields

- source-firestore/discovery.go
This commit fiddles with several Firestore discovery details in ways that I hope will make it less likely to OOM on large datasets. This includes:
- A hard limit on the total number of collection-scanning worker threads that will ever be spawned (currently set to 10k). This should help guard against the theoretical failure mode where a document has a million nested collections under it and we run out of memory simply because of goroutines waiting to run.
- A new limit on the number of nested collections which will be scanned under any single document. This also helps guard against the 'lots of nested collections' failure mode while making sure we don't rabbit-hole all our discovery work into one small part of the overall tree.
- Checking the `maxDocumentsPerResource` …
> source-firestore: Tweak discovery limits

- source-mysql/prerequisites.go
Followup to https://github.com/estuary/connectors/pull/816 which adds even more detailed logging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/817)
> source-mysql: More binlog retention debug logging

- source-firestore/pull.go
We have value-sanitization logic (which currently just replaces NaN values with the string "NaN") which is applied to backfilled documents, but previously it wouldn't recurse into lists which made it of limited usefulness.
This rewrite replaces `sanitizeDocument` with `sanitizeValue` (because it makes the logic cleaner once we're handling lists- of-values and maps-of-values both) but other than recursing into lists there should be no functional change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/824)
> source-firestore: Recursively sanitize arrays via backfill

- source-firestore/pull.go
Adds a semaphore which should ensure that only 2 (at current setting) `BackfillAsync` worker threads can be holding onto chunks of backfilled documents at any given moment. Hopefully this will make memory usage more controllable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/825)
> source-firestore: Limit number of concurrent backfill queries

- materialize-redshift/driver.go
All indications are that obtaining an exclusive lock on the potentially concurrently accessed checkpoints table should cause other transactions to "wait" until they can get the lock. In practice I have seen this not be the case when the lock statement was part of a statement batch, so hopefully a more direct lock statement execution will do the trick.
I was able to manually test this somewhat by simply opening two sessions in a Redshift cluster and getting a lock on a table with the first session. Then when I tried to get a lock with the second session, it blocked (no error) until the first session's transaction committed.
Redshift materializations with more than one shard operating in the same metadata schema should work without error.
**Documentation …
> materialize-redshift: explicitly lock table at start of commit

- materialize-redshift/driver.go
Hotfix to https://github.com/estuary/connectors/pull/832 - this handling is necessary for nullable strings, where the received value can be `nil`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/833)
> materialize-redshift: handle nullable strings for alter column lengths

- materialize-redshift/sqlgen.go
Redshift will terminate values going into `VARCHAR` columns where the null escape sequence occurs. This is especially a problem when it is the first thing in the string and is followed by other characters, as this results in the load error "Invalid null byte - field longer than 1 byte". Adding an additional escape to the beginning of the string allows the value to be loaded with the initial `"\u0000"` as a regular string.
Load options like `ESCAPE` and `NULL AS` seem somewhat promising for better configuration of this behavior, but these options are not supported when copying from JSON files, see [aws docs](https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-format.html#copy-json-data-file).
If the null escape sequence occurs elsewhere in a string value …
> materialize-redshift: escape leading null escape sequences

- source-mongodb/pull.go
- See the comment in code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/845)
> source-mongodb: consider change events with fullDocument=null

- source-http-ingest/src/server.rs
Adds some debug logging to help troubleshoot an issue with a production task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/853)
> source-http-ingest: add debug logging

- sqlcapture/capture.go
* On a failure to serialize a row, capture the applicable table
* Extend the `backfilling streams` log with the selected table for the next backfill
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/861)
> sqlcapture: minor logging extensions

- source-http-ingest/src/server.rs
Updates the source-http-ingest connector to accept arrays of JSON objects.  If the body of a request is a JSON array, then each item in the array must be an object that conforms to the write schema of the collection.
In the case that `idFromHeader` is set in the resource config, arrays are dealt with by suffixing the header value with the index of each array element.
This commit does _not_ update the openapi spec. Doing so may be desirable, but it's totally necessary right now, and I'd prefer to do it in a subsequent commit.
start sending http requests with array bodies ;)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/862)
> source-http-ingest: accept array bodies

- materialize-pinecone/client/client.go
The Pinecone API returns errors as JSON in the response body with useful information for diagnosing the problem, and we can return the error message with the connector error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/866)
> materialize-pinecone: decode vector upsert errors

- source-postgres-batch/.snapshots/TestSpec
- source-postgres-batch/Dockerfile
- source-postgres-batch/driver.go
- source-postgres-batch/main.go
- source-postgres-batch/main_test.go
Tweaks some `jsonschema` annotations so things look nicer in the UI (mostly by making the query template properly multiline). Also adds the first test of this connector, a snapshot test of the spec response.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/878)
> source-postgres-batch: Fix schemas to look nicer in the UI

- tests/materialize/materialize-elasticsearch/snapshot.json
- tests/materialize/materialize-google-sheets/snapshot.json
- tests/materialize/materialize-pinecone/snapshot.json
Trivial fixes of changes to test snapshots for recent modifications.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/882)
> tests: update materialization test snapshots

- source-mysql/discovery.go
It's kind of gross to have to do this, but if the user's source database is so badly broken that their JSON columns contain non-empty but invalid JSON then we should still try and do _something_ with those values other than failing the capture.
Since the fault lies in the source data and our generated for a JSON column is `{}` we are both morally and practically able to do whatever we like with these values, so I have chosen to wrap them in an object as `{"invalidJSON": "<stringifiedValue>"}` so that at least such values are clearly identifiable.
This is completely untested because I still don't actually know how to get invalid non-empty values into JSON columns. I figure as long as CI still passes we merge this and see if it fixes the production capture that's currently …
> source-mysql: Stringify malformed JSON column values

- source-dynamodb/discovery.go
Produce an error for a discovery yielding no discovered bindings. This is most likely a user configuration error, either by not having DynamoDB streams enabled on any tables or configuring the capture with a different region than their tables are in.
With this change, a discover resulting in no capture tables will display an error like this from discovery:
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/899)
> source-dynamodb: respond with an error if no bindings are produced from discovery

- materialize-mysql/.snapshots/TestConfigURI-IncorrectSSL
- materialize-mysql/.snapshots/TestConfigURI-RequireSSL
- materialize-mysql/.snapshots/TestSpecification
- materialize-mysql/config_test.go
- materialize-mysql/driver.go
- Tested these new value mappings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/911)
> materialize-mysql: ssl config

- sqlcapture/capture.go
Previously the diagnostics were run only when it's determined that the replication stream is idle, but there's another possible failure mode where we observe a low rate of changes (and thus the idle timeout never triggers) but still never see the watermark.
A flat 5-minute timeout (cancelled once we reach the watermark) more closely models the situations where diagnostics are likely to be needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/913)
> sqlcapture: Tweak replication diagnostics trigger logic

- source-mysql/replication.go
Adds support for `DROP DATABASE` queries when they're dropping a schema which none of the active bindings are part of. Note that we'll still error out and halt the capture if a schema is dropped while we're actively capturing tables from it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/920)
> source-mysql: Support 'DROP DATABASE' queries for unbound schemas

- materialize-redshift/driver.go
If the COPY error is because the target table doesn't exist, we'll get a decent error message back from Redshift like `"ERROR: Cannot COPY into nonexistent table some_table (SQLSTATE XX000)"`, and there won't be any information in the `sys_load_error_detail` table. We should return this error message directly instead of trying and failing to query `sys_load_error_detail`.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/918)
> materialize-redshift: return errors from non-existant COPY INTO errors as-is

- source-firestore/pull.go
Fixes a couple of things I overlooked in https://github.com/estuary/connectors/pull/936. Specifically, the handling of a streaming catchup failure used to return from the function, so after my changes that branch continued on to the more general "report an error" handling when it was supposed to continue the loop instead. Also there was a null pointer dereference in the backfill initialization logic which could only occur on a preexisting capture from before that PR.
I'm still out today, just happened to be around for a few minutes and figured I'd throw this together since I have the context to see exactly what's wrong.
> source-firestore: Fix a couple dumb oversights

- materialize-elasticsearch/transactor.go
Fixes a potential deadlock in sending load batches on the batches channel if the worker has
failed between when it was checked at the start of the loop and when the batch is actually sent.
Also removes a bit of complexity around waiting for the runtime's acknowledgement before evaluating
loads, which was an extremely small optimization at best that doesn't seem like it's worth it
anymore.
(anything that …
> materialize-elasticsearch: fix possible load deadlock

- source-s3/main.go
Invalid credentials is a common error case, and currently this returns the "raw" AWS S3 client error that talks about a request signature mismatch. This won't make any sense to a user who tried to publish the capture, so we can handle that error (and some others) and produce a more understandable error message.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/969)
> source-s3: more useful error message on invalid credentials or missing bucket

- materialize-bigquery/bigquery.go
Return a clear error message if the configured dataset or project ID can't be found.
Under certain circumstances BigQuery will return a useless error message like "Request could not be served" when the project ID or dataset is malformed in a certain way, but the 404 response code always means that one of the two could not be found.
There is a bit of code for `if googleErr.Message != ""` which is sort of peculiar and I think a leftover from prior refactoring and debugging which is being removed. We'll just pass through the error as-is if its not a 404, since other cases are pretty well described as far as I can tell.
N/A
(anything that …
> materialize-bigquery: better error message on prereq check for dataset or project not found

- materialize-dynamodb/type_mapping.go
- materialize-elasticsearch/client.go
- source-dynamodb/backfill.go
- source-dynamodb/capture.go
- source-dynamodb/pull.go
- source-sftp/main.go
Trivial fixes to typos in code comments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/986)
> chore: fix various typos in code comments

- source-mysql-batch/main.go
When originally writing this code I accidentally looked at the latest version of the client library DSN parsing logic, however this has been changed since the version (v1.5.0) we're currently using.
The old version we're using has the dumbest possible "parsing" logic and just splits the string on some separators without any encoding/decoding of special characters, and so we need to use an equally dumb string-splatting behavior when constructing the connection string.
If/when we upgrade the client library version this logic should be changed back to using `url.URL{}.String()` for symmetry with the newer parsing logic.
- - - …
> source-mysql-batch: Make (Config).ToDSN() match client library

- source-mongodb/pull.go
- reverting the decoding changes from #985 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1000)
> source-mongodb: revert changes related to document decoding

- source-postgres/backfill.go
Sets `max_parallel_workers_per_gather = 0` before running any backfill queries and resets it to the default afterwards. This avoids an edge case in which the query planner decides to use parallel sequential scans to satisfy the `WHERE ctid > $1` query, which breaks our ordering assumptions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1031)
> source-postgres: Disable parallel workers for keyless backfills

- materialize-mysql/driver.go
- MySQL has a 64 character limit on column names, and some of our source connectors inevitably trip up this limit. This is an attempt to give a better error message to users in these scenarios.
- Tested manually, results:
- Try materializing a hubspot collection such as `engagement_emails` or a facebook collection such as `ad_creatives` which have long column names
- - - …
> materialize-mysql: instructions in case of long field names

- source-dynamodb/stream.go
Quick follow-up to #1045: Semaphore acquisition is done in a loop, so deferring its release won't work. It can be released after the serialized data is emitted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1048)
> source-dynamodb: don't defer release of the semaphore

- sqlcapture/capture.go
Previously after ensuring that we're caught up and all tables are fully backfilled the connector would enter a "stream forever" state in which it just processes changes indefinitely as they come in from the source database. This was implemented by simply running the "stream to watermark" function with a nonexistent watermark value, which would never be observed and so streaming would never end.
There were two reasons this behavior might be suboptimal:
1. We're not actively confirming that the connection remains alive. In the past we've seen the occasional case (usually involving an SSH bastion intermediary) where the DB is fully idle, the underlying TCP stream gets silently disconnected, and it takes hours before TCP-level keepalives cause this to be detected by the …
> sqlcapture: Use 'Heartbeats' when streaming indefinitely

- sqlcapture/capture.go
Resets the replication cursor when there are no bindings.
This should allow the user to get things working again after WAL deletion events by disabling and then re-enabling all bindings, rather than having to use the Flow CLI to download their task spec, rename it, and publish that.
If I understand correctly that disabled bindings simply aren't sent to the connector in the bindings list at all (which I'm fairly sure is the case, since otherwise that wouldn't work at all?), then disabling all bindings in the UI should allow a capture task to recover after WAL deletion renders the old restart checkpoint no longer usable.
- - - …
> sqlcapture: Reset replication cursor when no bindings

- materialize-google-pubsub/transactor.go
If there is an error publishing a document for a binding, report the binding number with the error message to aid in troubleshooting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1060)
> materialize-google-pubsub: show binding number with publish error

- source-postgres/replication.go
- sqlcapture/capture.go
Adds a few queries to be run as part of the "automated replication diagnostics" triggered when watermark streaming takes unexpectedly long to complete.
Also adds some additional logging calls in the deferred watermark- writing worker spawned by `streamForever`, so that:
1. There is no way for the worker to exit without logging why it did so.
2. At debug level, we can see when the watermark write actually succeeded, since it's theoretically possible that this could be some time after we dispatched the write query.
No user action is required, this is all internal debug logging stuff.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/10 …
> source-postgres: Replication diagnostics and watermark logging

- source-mysql/replication.go
It is rare but possible (observed once ever in production) for the MySQL capture to deadlock while shutting down, because the event channel buffer is full and the replication worker is attempting to send another event, while the top-level capture loop has already stopped processing events and is waiting for the final error result from shutting down the replication worker.
The fix for this is to allow context cancellation to unblock these sends, which means that the replication worker will finish shutting down, which means it will send the final error result, which allows the top level shutdown to finish.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors …
> source-mysql: Fix a rare shutdown deadlock

- source-mysql/prerequisites.go
Fixes the `SHOW MASTER STATUS` prerequisite check to error out when the result is empty, and adds a new check which explicitly queries whether the `log_bin` system variable is set to `ON`.
As a result, when running against a database without binary logs enabled the error will now look like:
the capture cannot run due to the following error(s):
- binary logging is not enabled: system variable 'log_bin' = "OFF"
- unable to query latest binlog position (is binary logging enabled?)
This is slightly redundant in this case, but there are some cases where we could theoretically see an empty `SHOW MASTER STATUS` result even if binary logging is enabled (for instance, if the destination for binlog files is full or incorrectly permissioned so they can't actually be opened on disk), …
> source-mysql: Validate that binary logging is enabled

- materialize-bigquery/bigquery.go
- materialize-sql/driver.go
This is a temporary fix for allowing materialize-bigquery to use a parameterized query instead of a potentially large SQL string when inserting or updating its materialization spec.
BigQuery does not allow for SQL strings to be larger than 1 MiB in size, which is not outside the realm of possibility for complex Flow materialization specs. The size of the parameters in a parameterized query is not included in this size limit, so running the query as a parameterized query works much better for these large specs.
A more permanent fix will be rolled into #1086 shortly, but this will be able to unblock any current publications which are hitting the size limit.
I tested this with a huge materialization spec containing about 50,000 fields (100 bindings with 500 fields each). The …
> materialize-bigquery: use parameterized query for persisting the materialization spec

- python/flow_sdk/shim_singer_sdk.py
Whoops, I forgot how to python 😬
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1097)
> source-criteo: fix syntax error

- materialize-postgres/sqlgen.go
The values for strings can be `nil` if the field is not required, so handle that via the `StringCastConverter` instead of erroring on string fields that are `nil`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1104)
> materialize-postgres: handle `nil` values for string fields in converter

- python/flow_sdk/shim_airbyte_cdk.py
Updates `shim_airbyte_cdk` to handle state messages and emit checkpoints at the proper time. There is still a piece of work to do here wrt handling state keys properly, but AFAIK that's behind some runtime work that's not out yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1105)
> Emit Airbyte checkpoints

- tests/materialize/materialize-databricks/setup.sh
- Disable update delay in integration test so the test can run properly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1126)
> materialize-databricks: disable updateDelay in integration test

- python/README.md
I realized while writing this that there is a _lot_ of possible detail to include, and I may have gone too deep in certain areas and not deep enough in others. But I think this is at least a useful start. Thoughts?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1124)
> Add detailed docs for how to write OAuth configs

- source-kafka/Cargo.lock
- source-kafka/Cargo.toml
- source-kafka/README.md
- source-kafka/src/configuration.rs
- source-kafka/src/kafka.rs
- source-kafka/src/lib.rs
- source-kafka/src/msk_oauthbearer.rs
- source-kafka/tests/it/snapshots/it__spec_test.snap
- source-kafka/tests/test-config.json
- Introduce a new authentication method: AWS Credentials used to generate an OAuth Bearer token
- Renamed `authentication` to `credentials` since we have a convention for this, and we have no customers using this connector yet, so it is better to rename it now as it will be very hard later on
- Tested the `UserPassword` authentication method as well with a confluent instance and it works 👍🏽 
- I couldn't get the integration tests to work unfortunately, so I resorted to manual testing. The process for testing the AWS MSK setup is outlined below
- Create an AWS Managed Streaming Kafka (MSK) cluster, then enable [public access](https://docs.aws.amazon.com/msk/latest/developerguide/public-access.html)
- Once you have public access, then set up the …
> source-kafka: authenticating with AWS credentials

- .github/workflows/ci.yaml
- source-kafka/src/configuration.rs
- source-kafka/tests/it/snapshots/it__spec_test.snap
- tests/source-kafka/setup.sh
- fix integration tests that were failing, passing job: https://github.com/estuary/connectors/actions/runs/7267684250/job/19802036834?pr=1140
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1140)
> source-kafka: fix integration tests

- tests/run.sh
Integration tests were failing because the directories used for builds were too long, so this uses a shorter directory.
Soon we should switch to using `flowctl preview`-based snapshot tests instead of running a temporary data plane, so this is not intended to be a long-term fix.
- - - …
> tests: use shorter tmp dir

- sqlcapture/discovery.go
These are all things which should not result in the user being shown scary messages. The excluded view/table logic is totally normal and not an issue at all, and while the unhandled datatype stuff often indicates something we could improve in our connector or test coverage, we're not systematically collecting this info and showing it to the user as a warning is basically never going to be helpful.
(In fact if we wanted to make a list of column types which encounter issues in production, the obvious approach would be to query the live_specs table in Supabase and look for those `"using catch-all schema"` description strings, so the log message part of this is really not helpful at all)
- - - …
> sqlcapture: Downgrade scary discovery warnings

- source-mongodb/oplog.go
- update error to include link to docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1155)
> source-mongodb: add link to docs in error

- source-postgres/replication.go
Ignores the `Origin` message type when decoding postgres logical replication messages.  This message is used to indicate the original source of a transaction in cases where we're capturing from a postgres instance that is itself replicating from another instance.
I'm not entirely certain that this change will be sufficient to allow capturing from a postgres read replica, which seems to be the actual goal. But it seems like maybe it will, and so it's worth a try, given that it's low risk. If this does work, then it might be good to follow up and update our documentation to at least mention that this is supported.
- - - …
> source-postgres ignore Origin messages

- python/pyproject.toml
makes digging through the source more challenging without this
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1133)
> docs: add homepage link to flow_sdk

- source-airtable/source_airtable/source_airtable/schema_helpers.py
- source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__discover__capture.stdout.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1190)
> Fix: Make `_airtable_id` not nullable, since it's a primary key

- source-airtable/source_airtable/source_airtable/schema_helpers.py
- source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__discover__capture.stdout.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1191)
> fix: Also need to make `_airtable_id` required

- source-mongodb/main.go
Mongodb has an "online archive" service, which looks a lot like mongodb but doesn't work with our connector.  This adds an explicit check for URLs that appear to be for that service, and returns a clearer error message in case someone uses such a URL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1185)
> source-mongodb: better error message when url is for online-archive

- source-airtable/source_airtable/source_airtable/spec.json
- source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__spec__capture.stdout.json
- source-asana/source_asana/source_asana/spec.json
- source-asana/tests/snapshots/source_asana_tests_test_snapshots__spec__capture.stdout.json
They were still missing a couple of fields causing the UI to error when authenticating with OAuth
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1196)
> Update `source-asana` and `source-airtable`'s endpoint config schemas

- materialize-databricks/driver.go
Changes materialize-databricks to emit an updated checkpoint after a successful ack, as a best-effort attempt at zero'ing the checkpoint from the successfully applied queries.
The primary motivator for this is to make it easier to migrate to using state keys for bindings. The hope is that this can avoid the need to do a state migration, since there will almost never be any state to migrate. The current structure of the checkpoints would make it difficult to correlate the persisted queries with which binding they came from, so avoiding a migration would be nice.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu …
> materialize-databricks: post-ack updated checkpoint

- materialize-mongodb/.snapshots/TestSpecification
- materialize-mongodb/Dockerfile
- materialize-mongodb/config.go
- materialize-mongodb/driver.go
- source-mongodb/.snapshots/TestSpec
- source-mongodb/Dockerfile
- source-mongodb/main.go
Adds support for ssh tunneling for the mongodb capture and materialization.
Manually tested by running an SSH tunnel and connecting both through that do capture and materialize data.
Closes #1246
- - - …
> mongodb ssh tunnel

- materialize-starburst/starburst.go
Fix typo in the recently merged `materialize-starburst` connector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1235)
> `materialize-starburst`: Fix typo

- materialize-redshift/driver.go
If no information exists in `sys_load_error_detail` for a failed COPY INTO job, the original error message from the COPY INTO command is the best thing to return, since in all known cases it is quite clear and what went wrong.
- - - …
> materialize-redshift: return original error if unable to query sys_load_error_detail

- materialize-redshift/client.go
The VARBYTE column type we are using to store specs has a maximum size of 1MB. This is not big enough to store some of the larger specs that we have seen in the wild for materializations with fairly reasonable numbers of bindings. This change stores those specs with compression, which in some quick tests I did with large specs reduces the their size by 5x or more.
This is fairly simple change and with a small scope, compared to something more involved like using a VARIANT column with multiple fields to chunk up the spec. But it is pretty low risk and I'm hoping it will push off larger changes until we start providing the "last validated" spec in `Validate` calls, and don't need to persist a spec at all.
Tested by running the unit & integration tests which exercise spec …
> materialize-redshift: compress persisted spec bytes

- source-airtable/source_airtable/source_airtable/schema_helpers.py
- source-airtable/source_airtable/source_airtable/streams.py
- source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__capture__capture.stdout.json
- source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__discover__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1264)
> Fix: Airtable nan error from some streams

- materialize-firebolt/firebolt/firebolt.go
- Fix error reporting in our Firebolt client
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1275)
> materialize-firebolt: report error in case of client error

- materialize-databricks/.snapshots/TestSQLGeneration
- source-mongodb/pull.go
Log some basic information about the database that is being connected to, including its version and maximum object size setting, if we are able to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1277)
> source-mongodb: log buildInfo on startup

- source-mongodb/pull.go
Rather than including all available fields in change stream documents, apply filtering based on projections to get only the fields we need. The prevents issues such as the `updateDescription` of a document re-stating a huge field that is also in the `fullDocument` and causing errors because the change stream document is over the 16MB limit with the doubly enumerated field.
A slightly more thorough solution would also involve the `$changeStreamSplitLargeEvent` pipeline filter, although that option has some limitations: It is only supported on relatively new versions of MongoDB, and it is not completely bulletproof in that it does not traverse and split nested fields. So we would almost certainly want to use these projections to select only the necessary fields even if we …
> source-mongodb: select projections of change stream documents

- source-hubspot/spec.yaml
- source-hubspot/tests/snapshots/source_hubspot_tests_test_snapshots__spec__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1315)
> secret tag for client_id

- source-mysql/.snapshots/TestGeneric-SpecResponse
- source-sqlserver/.snapshots/TestGeneric-SpecResponse
- sqlcapture/main.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1333)
> Stream name in ResourceConfig set to read only

- materialize-snowflake/.snapshots/TestSpecification
- materialize-snowflake/snowflake.go
- A hint in the resource spec so users know how to enable Snowpipe
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1338)
> materialize-snowflake: hint for enabling snowpipe for delta updates

- materialize-sql/apply.go
Table creation will sometimes fail for a variety of reasons and it is hard to tell which table it is for, or what SQL was attempted to create the table. This adds logging to allow for troubleshooting, and a slightly improved error message.
- - - …
> materialize-sql: log table creation failure statements

- materialize-databricks/driver.go
- active sessions prevent the warehouse from shutting down using the auto-delay configuration
- reproduced the original issue and noticed the warehouse would consider our active session as a reason not to turn off after the configured auto-stop period.
- by closing database connections as soon as we are done with them, we minimise the time the warehouse is awake
- tested by running the integration test and checking active session afterwards in the databricks dashboard …
> materialize-databricks: don't keep an active session

- source-airtable/source_airtable/spec.json
- source-airtable/tests/snapshots/snapshots__spec__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1357)
> source-airtable: re-add removed `auth_method` property

- materialize-snowflake/client.go
- materialize-snowflake/config.go
- materialize-snowflake/pipe.go
- materialize-snowflake/snowflake.go
- materialize-snowflake/snowflake_test.go
- tests/materialize/materialize-snowflake/snapshot.json
- If the user-specified schema does not exist, attempt to create it automatically
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1348)
> materialize-snowflake: create schema if doesn't exist

- materialize-databricks/driver.go
- this log was missing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1375)
> materialize-databricks: log when finished committing changes

- estuary-cdk/estuary_cdk/capture/common.py
This was a hot fix last night to unblock Netsuite, but AFAICT it's the right change to make anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1385)
> CDK: Set a default for `next_page`

- source-boilerplate/boilerplate.go
This change is fairly small but impactful. Johnny's profiling earlier today apparently found that we're spending a lot of time blocked on write syscalls, which makes sense since we currently output every document to Flow as a separate message send.
This commit wraps a 1MiB `bufio.Writer` around stdout at the very base level, and adds flush logic to the `Send()` method so that anything *except* a document flushes that buffer. The end result should be that our behavior is mostly unchanged except that we'll accumulate capture documents into batches which get flushed only when the buffer fills up or we reach the next checkpoint.
This should hopefully improve connector throughput, though I can't say by how much.
This is a very low-level change, so it isn't exercised by most of …
> source-boilerplate: Buffer documents to amortize write overhead

- source-redshift-batch/driver.go
The parallel execution is done using a fairly clunky and verbose pattern (running each discovery query in a separate `errgroup` worker thread, using a single-element buffered channel for each thread's result) because it was what I could confidently bang out in 15 minutes.
We should consider replacing the whole mess with a suitable 'promise' abstraction helper package if one exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1401)
> source-redshift-batch: Run discovery queries in parallel

- source-mysql/replication.go
Turns out that in https://github.com/estuary/connectors/pull/1412 I was overly optimistic about the rarity of certain non-DDL query events in the binlogs.
The two most egregiously spammy forms are:
"BEGIN"
"# Dummy event replacing event type 160 that slave cannot handle.             "
But I'm still skeptical about the `ignoreQueriesRe` in general and suspect that one or more of those query event regexps is responsible for us missing out on DDL operations we care about.
So I'm introducing a quick-and-dirty third tier here, a regexp for only the most spammy of query events which uses more conservative patterns so we're *really* sure anything matching that can be ignored without even logging it (at `INFO` level).
- - - …
> source-mysql: Silently ignore a couple of query events after all

- source-mysql/prerequisites.go
This fixes https://github.com/estuary/connectors/issues/1340
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1413)
> source-mysql: Check for `--binlog-do-db` not including `"flow"`

- source-http-ingest/VARIANTS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1364)
> Added webhook variants

- source-firestore/pull.go
We fairly often see a fatal error message from `source-firestore` which reads simply:
unexpected TargetChange.REMOVE: The datastore operation timed out, or the data was temporarily unavailable
And we should really be mentioning the name of the collection on which this error occurred. This commit should fix that, and also makes sure that we mention the collection name on backfill errors as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1440)
> source-firestore: Error message improvements

- source-firestore/pull.go
Firestore's data model is kind of insane, internally. In order to cope with the arbitrarily-nested nature of things they have a concept of a "Collection Group" which is the set of all documents with the same final (non-ID) path element, so for instance `users/123/messages` and `groups/456/messages` are both found in the `messages` collection group.
We use this in our backfills (and then process the document path ourselves to figure out which binding, if any, a document should be captured under). This means that multiple bindings for distinct resource paths may actually be combined in a single backfill, so we have logic to recombine the per-resource backfill states into a single backfill state and update all impacted resource states as one.
In general this works, but there …
> source-firestore: Restart backfills on state mismatch

- materialize-snowflake/snowflake.go
- Instead of retrying 5 minutes for each binding before moving on to the next binding, retry in a round-robin fashion across bindings by looping through bindings for each retry attempt. Reduce the time between retry attempts and reduce the total time spent retrying
- - - …
> materialize-snowflake: round-robin try pipes

- source-http-ingest/VARIANTS
New webhook ingest variant for Jira
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1461)
> Added Jira Webhook Variant

- source-asana/tests/snapshots/snapshots__capture__capture.stdout.json
New data was added to our Asana project causing a mismatch in the snapshot output 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1489)
> Updating asana snapshot tests

- source-hubspot/tests/snapshots/snapshots__capture__capture.stdout.json
- source-hubspot/tests/snapshots/snapshots__discover__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1490)
> Update hubspot snapshot tests

- estuary-cdk/estuary_cdk/flow.py
- source-google-sheets-native/tests/snapshots/source_google_sheets_native_tests_test_snapshots__spec__stdout.json
- source-hubspot-native/source_hubspot_native/api.py
- source-hubspot-native/tests/snapshots/source_hubspot_native_tests_test_snapshots__capture__stdout.json
- source-hubspot-native/tests/snapshots/source_hubspot_native_tests_test_snapshots__spec__stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1487)
> Adding default value to credentials_title hubspot-native settings

- source-mysql/discovery.go
It's possible that the enum edge-case we've been seeing (where we see replicated enum values one greater than any valid option) is caused by us parsing the original enum type definition wrong. To figure out if that's the case we need to be able to see what the raw enum definition says before we parse it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1494)
> source-mysql: Log raw column type definition for enums

- materialize-postgres/sqlgen.go
We can validate a pre-existing column of type "character varying" for "text" columns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1498)
> materialize-postgres: validate columns of type "character varying"

- source-google-sheets-native/source_google_sheets_native/models.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1504)
> Allow extra fields for Pydantic Sheet model

- materialize-elasticsearch/type_mapping.go
We store object types as "flattened" index mappings, and strings with byte-lengths larger than 32766 cause errors when trying insert into those mappings, which is primarily a problem for the `flow_document` field.
There is an option `ignore_above` for this which can be configured on mappings to not index or store these long string fields in Lucene (which is what has the length limit), but still have them available in the `_source` field when retrieving documents. This allows objects with very large strings to be materialized and have the values of those strings retrieved via the `_source` field, which is what we use for querying load documents.
(list any …
> materialize-elasticsearch: don't index long strings in flattened mappings

- materialize-snowflake/snowflake.go
We have been seeing errors of "390112: Your session has expired. Please login again." consistently for a while now, and they arise as the result of calling `r.RowsAffected()` from an async query result.
I haven't been able to get a reproduction of this issue and can't yet propose a coherent mechanism for why it might be happening. For now it seems like a reasonable workaround / diagnostic to always get a fresh connection every time we run these async queries in acknowledge. This may not work to resolve the issue, but has very little risk and if we see that the errors stop we will have learned something about why they might be happening. …
> materialize-snowflake: use a new connection when running async queries

- estuary-cdk/importing_airbyte_source_connectors.md
Documents the requirements for importing Airbyte source connectors to use the Estuary CDK.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1415)
> docs: requirements for importing airbyte source connectors

- source-facebook-marketing/source_facebook_marketing/schemas/custom_conversions.json
- source-facebook-marketing/tests/snapshots/snapshots__discover__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1535)
> Facebook Marketing missing required primary key

- source-facebook-marketing/source_facebook_marketing/schemas/activities.json
- source-facebook-marketing/tests/snapshots/snapshots__discover__capture.stdout.json
Made application_id required
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1537)
> Updated primary keys for activities

- sqlcapture/discovery.go
Don't discover materialized tables, since that is almost never what is intended, and causes problems with synthetic projection names. A column of "flow_published_at" is used as a sentinel for guessing if the table is from a materialization or not. Although not 100% accurate (the user could exclude this field), it will work in the vast majority of cases.
Manually tested this by materializing a table to a Postgres database and trying to capture from that same database. On the current connector, we'd discover the materialized table and have no easy way to exclude it and avoid getting collection spec errors. With this change, we won't discover the materialized table, but will discover all other non-materialized tables like before.
(How does one use this …
> sqlcapture: don't discover materialized tables

- source-sqlserver/replication.go
More queries that might tell us something about replication failures in SQL Server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1544)
> source-sqlserver: Yet more diagnostic queries

- materialize-redshift/driver.go
Logs the detected value for [`enable_case_sensitive_identifier`](https://docs.aws.amazon.com/redshift/latest/dg/r_enable_case_sensitive_identifier.html), as some pre-work to https://github.com/estuary/connectors/pull/1551.
The assumption is that any pre-existing materializations that had this parameter enabled would be currently broken and that all others would have it disabled (the default), but I'd like to double check that first with this logging before implementing the change that handles cases where it is enabled.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, …
> materialize-redshift: log detected value of `enable_case_sensitive_identifier`

- materialize-postgres/driver.go
The default 5432 port gets appended when not using a network tunnel address currently. But when using a network tunnel address, we don't handle cases where the port is missing.
This change allows us to use the default 5432 port when using a network tunnel also.
Closes https://github.com/estuary/connectors/issues/1026
- - - …
> materialize-postgres: append default port when using network tunnel

- go.mod
- go.sum
This latest driver version is supposed to fix the panics with async queries we frequently see, so hopefully it does that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1568)
> snowflake: update to the latest driver version

- source-postgres/backfill.go
If the backfill query is interrupted due to a statement timeout but yielded at least one row, then it's not very helpful to fail the capture task and require a restart. Much more useful to keep on going with what we've got so that we can make partial progress.
Without this, we would be forced to fiddle with the backfill chunk size if/when this happened again, but after this change we should not need to do any of that, instead the connector will just read as many rows as it can before getting killed and consider whatever it gets back to be a complete backfill chunk.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1593)
> source-postgres: Add a special case for backfill statement timeouts

- source-google-ads/source_google_ads/schemas/ad_group_ad_report.json
- source-google-ads/source_google_ads/schemas/ad_groups.json
- source-google-ads/source_google_ads/schemas/display_keyword_performance_report.json
- source-google-ads/source_google_ads/schemas/display_topics_performance_report.json
- source-google-ads/source_google_ads/schemas/geographic_report.json
- source-google-ads/source_google_ads/schemas/keyword_report.json
- source-google-ads/source_google_ads/schemas/shopping_performance_report.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1594)
> Updating schemas, non-nullable primary keys

- materialize-postgres/.snapshots/TestSQLGeneration
- materialize-postgres/.snapshots/TestSpecification
- materialize-postgres/driver.go
- materialize-postgres/sqlgen.go
- materialize-postgres/sqlgen_test.go
- tests/materialize/materialize-postgres/fetch.sh
- tests/materialize/materialize-postgres/setup.sh
- tests/materialize/materialize-postgres/snapshot.json
- Support hard deletes in materialize-postgres
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1611)
> materialize-postgres: support hard deletes

- materialize-snowflake/snowflake.go
There are a couple of problems with the Go Snowflake driver's WithAsyncMode option so instead of continuing to use that, we'll just run the Store queries concurrently on our end.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1610)
> materialize-snowflake: use separate goroutines for store queries instead of WithAsyncMode

- source-google-sheets-native/source_google_sheets_native/models.py
Adding missing grid properties to model from [google sheets official docs](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets?hl=pt-br#GridProperties)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1612)
> source-google-sheets-native: adding missing grid properties to model

- source-hubspot-native/source_hubspot_native/api.py
We are seeing intermittent errors where incremental email events are yielded without a final log cursor. This is some temporary logging to help troubleshoot that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1619)
> source-hubspot-native: temporary logging for yielded email events without a log cursor

- materialize-elasticsearch/.snapshots/TestDriverSpec
- materialize-elasticsearch/driver.go
- materialize-elasticsearch/transactor.go
- tests/materialize/materialize-elasticsearch/fetch.sh
- tests/materialize/materialize-elasticsearch/setup.sh
- tests/materialize/materialize-elasticsearch/snapshot.json
- Implement hard deletions for materialize-elasticsearch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1624)
> materialize-elasticsearch: implement hard deletes

- source-dynamodb/.snapshots/TestDiscovery-additional_table_without_stream_enabled
- source-dynamodb/.snapshots/TestDiscovery-multiple_tables_with_various_types
- source-dynamodb/.snapshots/TestDiscovery-single_table_with_a_partition_key
- source-dynamodb/discovery.go
- Add deletion annotation to discovered schemas of source-dynamodb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1630)
> source-dynamodb: deletion annotation in discovered schemas

- materialize-mongodb/transactor.go
Certain Flow reduction strategies can result in identical documents being stored, and MongoDB does not report an attempted "replace" with an identical document as an update when it's part of a bulk write operation.
- - - …
> materialize-mongodb: fix store count checks for unchanged documents

- source-google-ads/acmeCo/account_performance_report.schema.yaml
- source-google-ads/acmeCo/accounts.schema.yaml
- source-google-ads/acmeCo/ad_group_ad_report.schema.yaml
- source-google-ads/acmeCo/ad_group_ads.schema.yaml
- source-google-ads/acmeCo/ad_groups.schema.yaml
- source-google-ads/acmeCo/campaigns.schema.yaml
- source-google-ads/acmeCo/click_view.schema.yaml
- source-google-ads/acmeCo/display_keyword_performance_report.schema.yaml
- source-google-ads/acmeCo/display_topics_performance_report.schema.yaml
- source-google-ads/acmeCo/flow.yaml
- source-google-ads/acmeCo/geographic_report.schema.yaml
- source-google-ads/acmeCo/keyword_report.schema.yaml
- source-google-ads/acmeCo/shopping_performance_report.schema.yaml
- source-google-ads/source_google_ads/schemas/ad_group_ad_report.json
- source-google-ads/source_google_ads/schemas/ad_groups.json
- source-google-ads/test.flow.yaml
- source-google-ads/tests/snapshots/snapshots__discover__capture.stdout.json
updating google-ads schema
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1648)
> source-google-ads: updating google-ads schema

- source-google-ads/acmeCo/ad_group_ad_report.schema.yaml
- source-google-ads/acmeCo/ad_groups.schema.yaml
- source-google-ads/source_google_ads/schemas/ad_group_ad_report.json
- source-google-ads/source_google_ads/schemas/ad_groups.json
- source-google-ads/tests/snapshots/snapshots__discover__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1650)
> source-google-ads: reverting nullable primary key

- estuary-cdk/estuary_cdk/capture/__init__.py
Pydantic automatically serializes Decimals as strings, but orjson doesn't know about that. In order to handle this, we must tell `orjson` how to handle Decimals. [Their docs on this](https://github.com/ijl/orjson?tab=readme-ov-file#default)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1641)
> fix: orjson serialization of `decimal.Decimal`

- source-asana/source_asana/schemas/attachments.json
- source-asana/source_asana/schemas/attachments_compact.json
- source-asana/source_asana/schemas/custom_fields.json
- source-asana/source_asana/schemas/events.json
- source-asana/source_asana/schemas/organization_exports.json
- source-asana/source_asana/schemas/portfolios.json
- source-asana/source_asana/schemas/portfolios_compact.json
- source-asana/source_asana/schemas/portfolios_memberships.json
- source-asana/source_asana/schemas/projects.json
- source-asana/source_asana/schemas/sections.json
- source-asana/source_asana/schemas/sections_compact.json
- source-asana/source_asana/schemas/stories.json
- source-asana/source_asana/schemas/stories_compact.json
- source-asana/source_asana/schemas/tags.json
- source-asana/source_asana/schemas/tasks.json
- source-asana/source_asana/schemas/team_memberships.json
- source-asana/source_asana/schemas/teams.json
- source-asana/source_asana/schemas/users.json
- source-asana/source_asana/schemas/workspaces.json
- source-asana/tests/snapshots/snapshots__capture__capture.stdout.json
- source-asana/tests/snapshots/snapshots__discover__capture.stdout.json
- source-asana/tests/test_import_schemas.py
fixing schema primary keys and snapshots
Changes tested with a local flow setup and a supabase DB instance
All streams were tested and materialized
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1663)
> source-asana: fixing schema and snapshots

- source-kafka/src/kafka.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1667)
> source-kafka: strip schema registry magic byte & schema ID

- materialize-bigquery/transactor.go
Adds logging for commit queries that fail, so we can see what the query is that failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1673)
> materialize-bigquery: log queries that fail

- source-klaviyo/source_klaviyo/schemas/events.json
- source-klaviyo/source_klaviyo/streams.py
- source-klaviyo/tests/snapshots/source_klaviyo_tests_test_snapshots__discover__capture.stdout.json
Changed Events stream API to stable version
And added new field called campaign_id
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1717)
> source-klaviyo: changing Events stream API && new field

- source-google-sheets-native/source_google_sheets_native/models.py
Updates the source-google-sheets-native connector to handle rows with missing `values` when trimming blank rows from the end of the sheet. This was observed on a production capture, which is now making progress after this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1723)
> WIP: try filtering rows with no values

- source-klaviyo/source_klaviyo/streams.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1726)
> source-klaviyo: changing campaign_id extraction

- source-klaviyo/source_klaviyo/streams.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1730)
> source-klaviyo: removing unused field

- source-mysql/main.go
This is a fairly large log message, but our debug-level logs are already pretty spammy these days so this shouldn't be a big deal, and it's useful to be able to go and check the complete settings of any capture on demand.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1729)
> source-mysql: Log 'SHOW VARIABLES' at `DEBUG` on startup

- materialize-sqlite/sqlite.go
SQLite has no pre-reqs, so this is a no-op function that will avoid a null pointer panic.
At some point I will create a test for materialize-sqlite
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1800)
> materialize-sqlite: fix connector

- materialize-s3-iceberg/transactor.go
If a binding has no data for a transaction, its table will not be appended to and the "checkpoint" property of that table will not be updated.
The "PreviousCheckpoint" for that binding must also not be advanced in this case, otherwise the next append to the table will fail since the "PreviousCheckpoint" persisted in the state will not match the "checkpoint" property of the table.
By leaving the "PreviousCheckpoint" unchanged in the persisted connector state for bindings with no data, the next append files operation for that table will be able to transition the table from its last applied checkpoint to the current checkpoint.
This also includes a change that will update the persisted connector state after `Acknowledge` is complete to clear out the list of files that need …
> materialize-s3-iceberg: don't advance checkpoints in persisted state for bindings with no data

- source-bigquery-batch/driver.go
- source-mysql-batch/driver.go
- source-postgres-batch/driver.go
- source-redshift-batch/driver.go
If the connector gets restarted partway through a table poll we want it to retry immediately, which means that we shouldn't have updated the 'Last Polled' timestamp state yet.
This commit changes that for all four batch SQL connectors, so now we'll have an unconditional checkpoint after the result set processing ends (where previously we only had that if there were still uncommitted documents) and before that checkpoint we update the 'Last Polled' timestamp to the time at which we *started* the query.
I also tweaked a bit of logging that I thought could be better and added a couple of missing error checks for Postgres, since I'm already touching that part of the code and I noticed the after-query check on `rows.Err()` was missing.
- - - …
> source-*-batch: Improve poll scheduling around interruption

- source-postgres-batch/driver.go
It's somewhat debatable how useful partial-progress checkpoints are nowadays since there are no hard limits on Flow transaction sizing or anything, but every other Batch SQL capture has them, so it's probably good for `source-postgres-batch` to have them as well for consistency if nothing else.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1806)
> source-postgres-batch: Emit partial-progress checkpoints

- source-postgres/.snapshots/TestDiscoveryComplex
- source-postgres/.snapshots/TestGeneric-KeylessDiscovery
- source-postgres/.snapshots/TestGeneric-SimpleDiscovery
- source-postgres/datatype_test.go
- source-postgres/datatypes.go
- source-postgres/discovery.go
Reverts estuary/connectors#1812
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1813)
> Revert "source-postgres: Support NaN values in float4/float8 columns"

- source-klaviyo/source_klaviyo/__main__.py
- source-klaviyo/source_klaviyo/streams.py
- source-klaviyo/tests/snapshots/source_klaviyo_tests_test_snapshots__discover__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1761)
> source-klaviyo: capturing campaign_id via  message field

- go/dbt/trigger.go
- materialize-bigquery/.snapshots/TestSpecification
- materialize-bigquery/bigquery.go
- materialize-bigquery/transactor.go
- materialize-databricks/.snapshots/TestSpecification
- materialize-databricks/config.go
- materialize-databricks/driver.go
- materialize-mysql/.snapshots/TestSpecification
- materialize-mysql/driver.go
- materialize-postgres/.snapshots/TestSpecification
- materialize-postgres/driver.go
- materialize-redshift/.snapshots/TestSpecification
- materialize-redshift/driver.go
- materialize-snowflake/.snapshots/TestSpecification
- materialize-snowflake/config.go
- materialize-snowflake/snowflake.go
- materialize-sqlserver/.snapshots/TestSpecification
- materialize-sqlserver/driver.go
- Trigger DBT jobs after transactions which materialize data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1829)
> dbt: DBT job trigger in warehouse materializations

- go/dbt/trigger.go
- materialize-bigquery/.snapshots/TestSpecification
- materialize-databricks/.snapshots/TestSpecification
- materialize-mysql/.snapshots/TestSpecification
- materialize-postgres/.snapshots/TestSpecification
- materialize-redshift/.snapshots/TestSpecification
- materialize-snowflake/.snapshots/TestSpecification
- materialize-sqlserver/.snapshots/TestSpecification
I tried not to make this mistake again, but here we are 😁 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1833)
> dbt: fix "cause" field's jsonschema description

- source-mixpanel-native/acmeCo/flow.yaml
- source-mixpanel-native/source_mixpanel_native/streams/engage.py
- source-mixpanel-native/tests/snapshots/source_mixpanel_native_tests_test_snapshots__discover__capture.stdout.json
#1426 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1869)
> source-mixpanel: updating engage stream primary key

- source-mysql/replication.go
It turns out that the MySQL replication client library we use has an internal event buffer in addition to the one we maintain. We try to keep buffers small so that we never run out of memory, so this commit reduces the size of that buffer from 10,240 events to 256 events.
This should put us at a significantly smaller risk of OOMing, and should still be plenty high enough to keep everything running smoothly without unnecessary blocking on send/receives.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1870)
> source-mysql: Reduce binlog event cache from 10240 to 256

- source-jira-native/acmeCo/issue_navigator_settings.schema.yaml
- source-jira-native/acmeCo/issue_type_screen_schemes.schema.yaml
- source-jira-native/acmeCo/permissions.schema.yaml
- source-jira-native/acmeCo/screen_tabs.schema.yaml
- source-jira-native/source_jira_native/schemas/projects.json
- source-jira-native/source_jira_native/streams.py
- source-jira-native/test.flow.yaml
- source-jira-native/tests/snapshots/source_jira_native_tests_test_snapshots__discover__capture.stdout.json
Updated Project Types stream Primary Key to `Key` field
Updated Projects stream schema to remove ENUM limitations
Tested using local flow instance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1876)
> source-jira-native: updating project_types pk & projects schema

- source-mixpanel-native/source_mixpanel_native/schemas/annotations.json
- source-mixpanel-native/source_mixpanel_native/schemas/cohort_members.json
- source-mixpanel-native/source_mixpanel_native/schemas/cohorts.json
- source-mixpanel-native/source_mixpanel_native/schemas/engage.json
- source-mixpanel-native/source_mixpanel_native/schemas/export.json
- source-mixpanel-native/source_mixpanel_native/schemas/funnels.json
- source-mixpanel-native/source_mixpanel_native/schemas/revenue.json
- source-mixpanel-native/tests/snapshots/source_mixpanel_native_tests_test_snapshots__discover__capture.stdout.json
The primary keys in the write schema must be required and non-nullable to allow compatibility with SQL materializations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1879)
> source-mixpanel-native: require primary keys in schema

- materialize-bigquery/transactor.go
It may be useful to see what the query that resulted in the failure was in the logs, so it will be logged in case of an error creating the query job, getting the results iterator from the job, or reading the results iterator.
- - - …
> materialize-bigquery: log failed load queries

- go/schema-gen/generate.go
- materialize-bigquery/.snapshots/TestSpecification
- materialize-bigquery/bigquery.go
- materialize-databricks/.snapshots/TestSpecification
- materialize-databricks/driver.go
- materialize-dynamodb/.snapshots/TestSpec
- materialize-dynamodb/driver.go
- materialize-elasticsearch/.snapshots/TestDriverSpec
- materialize-elasticsearch/driver.go
- materialize-mongodb/.snapshots/TestSpecification
- materialize-mongodb/config.go
- materialize-motherduck/.snapshots/TestSpecification
- materialize-motherduck/driver.go
- materialize-mysql/.snapshots/TestSpecification
- materialize-mysql/driver.go
- materialize-postgres/.snapshots/TestSpecification
- materialize-postgres/driver.go
- materialize-redshift/.snapshots/TestSpecification
- materialize-redshift/driver.go
- materialize-snowflake/.snapshots/TestSpecification
- materialize-snowflake/snowflake.go
- materialize-sqlserver/.snapshots/TestSpecification
- materialize-sqlserver/driver.go
- materialize-starburst/.snapshots/TestSpecification
- materialize-starburst/starburst.go
- Add `x-schema-name` and `x-delta-updates` annotations to all materializations connectors that support them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1892)
> materialize-*: x-schema-name and x-delta-updates annotations

- materialize-postgres/driver.go
Copies over similar logic that the source-postgres connector uses, since connection poolers will not work well with either connector.
The docs link technically links to the `source-postgres` docs, but I think it's still a fine reference for the materialization since it communicates the important points of getting a direct database connection.
- - - …
> materialize-postgres: don't allow supabase connection pooler addresses

- source-hubspot-native/source_hubspot_native/api.py
A few enhancements to `source-hubspot-native` to resolve production issues. See commit messages for more detail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1901)
> source-hubspot-native: a few enhancements

- source-hubspot-native/source_hubspot_native/api.py
Adding some debug logging to help troubleshoot failures with the search API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1902)
> source-hubspot-native: debug logging for fetching search objects

- sqlcapture/main.go
As described in the comment, this is an ugly but functional solution to the problem of "sometimes it would be really useful to just adjust the replication cursor value instead of backfilling an entire multi-terabyte dataset".
Replacements are scoped to only take effect for a capture task with a specific name and specific cursor value, so unless I've made a very dumb error in the implementation this should have zero impact on any tasks other than the one we're trying to fix. The task name is hashed so that entries in this table don't leak any information about the customer. In theory we might want to obscure the binlog filename as well, but in practice everyone seems to have a default of `binlog` or `mysql-bin` and we're adding entries manually so it's not actually a big …
> sqlcapture: Implement an ugly but functional replication cursor replacement mechanism

- source-hubspot-native/source_hubspot_native/api.py
The search API fails if you try to get more than 10,000 records from a single search, so these large search results need to be split up and handled as separate searches.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1906)
> source-hubspot-native: handle search API results larger than 10,000 records

- source-mysql-batch/VARIANTS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1925)
> docs: Add variant for SingleStore batch

- source-http-ingest/Cargo.lock
- source-http-ingest/Cargo.toml
- source-http-ingest/src/lib.rs
Updates all dependencies. This is hopefully to fix a presumed break in proto-flow JSON deserialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1934)
> source-http-ingest: update dependencies

- sqlcapture/main.go
If the backfill mode changes for a preexisting binding then we ought to see the backfill counter increment at the same time.
Incorrect backfill mode changes are one of the more avoidable user errors we see, so hopefully this will rule out that whole class of failure.
This fixes https://github.com/estuary/connectors/issues/1931
This change is largely untested because our test suite doesn't really make it easy to exercise the "validating a new task spec in the context of its prior state" scenario at present. However the code isn't complicated, CI passes, and it should be a pretty low-risk change since the diff is confined to the `Validate()` method and the worst-case outcome of a completely broken `Validate()` method AFAIK is that it prevents some …
> sqlcapture: Require backfill increment when mode changes

- source-http-ingest/src/transactor.rs
- source-http-ingest/tests/test.rs
The source-http-ingest connector was never updated to account for the fact that the runtime can acknowledge multiple checkpoints with a single Acknowledge request. This manifested as a bug where it would wait for a long time on acknowledgements that would never come, and clients would experience many timeouts waiting for responses.
The fix is to expect a non-zero `checkpoints` as part of each acknowledgement, and acknowledge that number of transactions.
I've tested this by setting up a capture in production and generating load by having multiple shells that each use curl to send requests in a loop. Then killing all but one of those scripts would result in a deadlock of the remaining one. That's no longer happening with this branch. I did observe a different deadlock, …
> source-http-ingest: fix handling of acknowledgements

- source-stripe-native/source_stripe_native/api.py
In the incremental replication functions, the logic for emitting documents and updating the cursor were coupled; whenever we emit a document, the cursor would be updated. This would work if the API returned documents in increasing order, but the Stripe API returns documents in _decreasing_ order. This means that the cursor was being updated to the timestamp for the oldest document we haven't seen, not the most recent document.
The incremental logic for updating the cursor is now decoupled from emitting documents, and the cursor is now updated to be the most recent document's timestamp.
Variable names were also updated to more accurately reflect the associated entities & improve readability (ex: `events` or `resources` instead of `result`).
(How does …
> source-stripe-native: fix incremental logic

- materialize-boilerplate/stream-encode/parquet.go
Values for integer fields can be floats with a 0 fractional part, either as an actual float or as a string-encoded number. Similarly to the element converter used by SQL materializations, the Parquet encoder needs to handle these and appropriately convert them to integers.
- - - …
> stream-encode: parquet encoder handles integers that are floats

- source-linkedin-ads-v2/acmeCo/flow.yaml
- source-linkedin-ads-v2/source_linkedin_ads_v2/schemas/account_users.json
- source-linkedin-ads-v2/source_linkedin_ads_v2/schemas/accounts.json
- source-linkedin-ads-v2/source_linkedin_ads_v2/schemas/campaign_groups.json
- source-linkedin-ads-v2/source_linkedin_ads_v2/schemas/conversions.json
- source-linkedin-ads-v2/source_linkedin_ads_v2/spec.json
- source-linkedin-ads-v2/source_linkedin_ads_v2/streams.py
- source-linkedin-ads-v2/tests/snapshots/source_linkedin_ads_v2_tests_test_snapshots__discover__capture.stdout.json
- source-linkedin-ads-v2/tests/snapshots/source_linkedin_ads_v2_tests_test_snapshots__spec__capture.stdout.json
- source-linkedin-ads-v2/unit_tests/test_source.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1983)
> source-linkedin-ads: cleaning up schemas

- source-stripe-native/source_stripe_native/api.py
Stripe has two billing systems, usage-based and meter-based. Our UsageRecords stream hits the legacy usage-based endpoint. If we try to hit the usage-based endpoint with a subscription item that doesn't actually use usage-based billing, Stripe response with a `400` error and a pretty specific message. Since there are no usage-based usage records for that subscription item, we can safely skip requesting usage records when this happens.
I also fixed the warn level log for my previous commit by passing a `dict` of the error's properties instead of passing the actual `HTTPError`.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4 …
> source-stripe-native: handle UsageRecords 400 response

- materialize-snowflake/client.go
Provide a better error message if the user does not have permission to create a table in the selected schema.
Closes #2003
Regex matching on error strings is always terrible but it's the best I could come up with. Even the error code returned for this kind of error refers to a useless "javascript execution error" category.
- - - …
> materialize-snowflake: better error message for table creation access issue

- materialize-sql/apply.go
Evaluating migrations of all projections for which a column exists runs into an edge case if the projection has had all of its types removed for some reason, because materializations don't know how to map Flow schema fields with no types to their respective endpoint types.
Instead only evaluate migrations for columns that are included in the field selection. Validation ensures that fields with no types are forbidden from being selected. In a scenario where a projection goes from having types + a column created, to having no types and being excluded from migrations and field selection, to having types again at some point in the future, the migration will be evaluated then when the field for the projection is back in the field selection.
(How does one …
> materialize-sql: only evaluate migrations for selected fields

- source-linkedin-ads-v2/source_linkedin_ads_v2/streams.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2030)
> source-linkedin-ads: changing creative_name extraction query

- source-mongodb/backfill.go
The assumption that documents are returned in an ascending insertion order does not appear to be true for non-standard MongoDB deployments. These kinds of deployments don't support change streams and must be captured in a batch mode, so for bindings that use batch mode always require an explicit sort.
- - - …
> source-mongodb: require sorting on `_id` for batch captures

- estuary-cdk/estuary_cdk/shim_airbyte_cdk.py
Previously, imported Airbyte connectors that utilize the `CaptureShim` class ignored the `SIGQUIT` mechanism used to log stack traces containing all of the currently running coroutines. This was because `CaptureShim` was not _actually_ run as a coroutine.
To resolve this, the `Task.spawn_child` method is used to run a `CaptureShim` as a coroutine and an `await asyncio.sleep(0)` was added to provide a safe stopping point when a `SIGQUIT` signal is set. Also, logic was also added to `CaptureShim._run` to allow imported Airbyte connectors to perform graceful exits triggered by the `periodic_stop` coroutine. …
> estuary-cdk: run `CaptureShim` as a coroutine

- source-front/tests/snapshots/snapshots__discover__capture.stdout.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2101)
> source-frontapp: updating snapshots

- materialize-mongodb/transactor.go
A collection with a present field of `_id` in its documents would lose that value when materializing to MongoDB, which has its own field for documents called `_id`.
That's not ideal in general, but it would cause specific problems with a standard updates materialization where the loaded document would be missing the `_id` field value that is required by the source collection schema for reductions.
The fix here is to materialize a present `_id` field from the Flow collection under an alternate field name `_flow_id` in stored documents, and reverse that process when loading documents for standard updates by replacing the loaded document's `_id` with the `_flow_id` and then deleting `_flow_id`.
Did a test on a local stack by trying to materialize a collection captured from …
> materialize-mongodb: preserve collection `_id` field values as `_flow_id` in materialized documents

- materialize-boilerplate/stream-encode/parquet.go
Integer values can be received as floats with 0 fractional part, even if the value is within the range of a 64-bit integer. This updates the parquet encoder to handle that case.
Integer values can also be received as floats if the value is outside the range of 64-bit integer, and that's not being addressed right now since it doesn't seem like an immediate issue. …
> materialize: parquet encoder handles integers encoded as floats

- materialize-firebolt/.snapshots/TestDriverSpec
- materialize-firebolt/config.go
Driver spec test is failing since in an update for Firebolt connector TestDriverSpec snapshot was not updated. Rectifying this.
N/A, test only change.
N/A
This was brought up in #estuary-firebolt-integration in Slack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2168)
> test(materialize-firebolt): Fix driver spec snapshot test

- tests/materialize/materialize-firebolt/config.yaml
- tests/materialize/materialize-firebolt/fetch-data.go
- tests/materialize/materialize-firebolt/setup.sh
- tests/materialize/materialize-firebolt/snapshot.json
Fixes firebolt integration tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2169)
> materialize-firebolt: fix integration tests

- source-oracle-flashback/source_oracle_flashback/api.py
When a query fails, log the failed query for additional diagnostic information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2203)
> source-oracle-flashback: log failed queries

- source-oracle-flashback/source_oracle_flashback/api.py
`VERSIONS BETWEEN SCN` results in any valid rows for the specified SCN range, and rows which have `VERSIONS_STARTSCN < rangeBegin && VERSIONS_ENDSCN >= rangeBegin` are also considered. In our logic however we only consider `VERSIONS_STARTSCN` as the transaction identifying checkpoint that's why we need the extra `VERSIONS_STARTSCN >= {{cursor}}` to avoid results where `VERSIONS_STARTSCN` is smaller than the latest checkpoint we have emitted.
We had seen this with some tasks where the connector would try to emit a checkpoint that was already processed again, and Estuary CDK complains in those cases. In essence we were re-emitting previously emitted documents.
Tested by running our test suite. I'm not sure how to trivially reproduce the scenario where we have two queries …
> source-oracle-flashback: filter out already-processed SCNs

- materialize-bigquery/transactor.go
- materialize-snowflake/snowflake.go
- materialize-sql/templating.go
- materialize-sql/templating_test.go
The assumption that the first Store request is the minimum value for all keys of a composite key was incorrect, and could cause invalid merge query conditions for collections with composite keys.
An explicit comparison needs to be done to determine the minimum and maximum observed keys for a transaction, and that is implemented here.
This will have a bit more overhead, but I'm assuming it will be negligible in the grand schema of things. An alternate strategy would be to only base the merge condition on the first part of a composite key, but using all parts of the key is desirable so that users can include additional fields in their collection key if they know these are valid keys and will provide a benefit in merge conditions, rather than being limited to only the first …
> materialize-{bigquery,snowflake}: fix key comparison for composite keys

- source-hubspot-native/source_hubspot_native/api.py
The search API will return records with a modification time before the requested "since" (the start of the window) if their updatedAt timestamp is within the same millisecond, effectively ignoring the microseconds part of the range criteria. These spurious results can be safely ignored in the rare case that there is a record with a modification time within the same millisecond as requested at the start of the time window, but some smaller fraction of a second earlier. …
> source-hubspot-native: filter search results that are earlier than the requested time range

- materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
Adds a simple retry mechanism for table append transactions, since there can sometimes be intermittent failures with REST catalogs. Bailing out of the entire transaction can be a significant latency increase vs. a short delay before retrying the transaction.
- - - …
> materialize-s3-iceberg: retry failed append transactions

- source-intercom-native/source_intercom_native/api.py
The `/companies/list` limitation mentioned in https://github.com/estuary/connectors/pull/2204 has been reached by a user, and the connector is crashing as a result. It turns out the API returns a specific `400` error when we try to page past that 10k limit. Since the connector does not currently have an option to use the `/companies/scroll` endpoint & avoid that limit, we should handle this specific error to avoid crashing the connector.
If/when support for the `/companies/scroll` endpoint is added, we should re-evaluate whether or not the connector should crash when hitting the `/companies/list` limit (i.e. force users with more than 10k companies to use the `/companies/scroll` endpoint). …
> source-intercom-native: handle error when hitting /companies/list limit

- materialize-bigquery/query.go
Increases the number of times the materialization will retry failed jobs due to concurrent updates on the table or rate limits before failing the connector.
Most often this happens when two materializations share the same checkpoints table, and long-running transactions can "lock" the checkpoints table for extended periods of time.
- - -
This change …
> materialize-bigquery: increase job timeouts due to concurrent updates or rate limits

- source-braintree-native/source_braintree_native/api.py
We've received reports of missing `disputes` documents. The provided missing disputes both had a `received_date` that was one day before their `created_at`, meaning we can't assume that `received_date` is a close approximation of `created_at` when searching Braintree. Examples of missing documents are below.
```json
{"id":"dispute_1","received_date":"2025-01-10","created_at":"2025-01-11T00:50:12Z"}
{"id":"dispute_2","received_date":"2025-01-16","created_at":"2025-01-17T00:09:34Z"}
```
I think we missed these disputes when the following conditions were true:
1. The capture was caught up to the present and replicating incrementally.
2. It was early-ish in the next day. 
3. The window size was small (ex: 1 hour).
For example, if the capture is using a 1 hour date window, …
> source-braintree-native: fix missing `disputes` documents

- materialize-boilerplate/logging.go
- materialize-boilerplate/logging_test.go
This fixes a logic error for materializations that do not stage loads for deferred evaluation & use the extended logging capabilities, either directly or by turning on debug logging. The prior code did not account for the possibility of a load response to be sent prior to reading flush, which is what happens with these kinds of materializations.
- - - …
> materialize-boilerplate: fix logic error when loads are not staged for evaluation

- materialize-mongodb/transactor.go
Use multiple concurrent load workers to maximize throughput when there are a lot of load requests to evaluate. This can be a limiting factor particularly when round-trip latency is high.
The original code was structured to allow for easily adding concurrency to these requests, but I just hadn't seen a need for it until now, when we have an example of a task that seems to be getting limited at this point. …
> materialize-mongodb: use multiple concurrent load workers

- source-sqlserver/discovery.go
So apparently only the `INFORMATION_SCHEMA` tables are officially named in uppercase in SQL Server, and the `sys.foobar` information tables are officially lowercase. Luckily we consult either one or the other data source in specific queries so it's easy enough to just go back to unconditionally using the old lowercased queries for secondary index and computed column listings.
This hasn't been tested against a database running a case-sensitive (or case-insensitive but Turkish) collation, but as it's just stripping out some feature-flagged logic it shouldn't change anything by default so I think it's safe to just YOLO it assuming CI passes.
- - - …
> source-sqlserver: Always lowercase sys.* discovery

- materialize-snowflake/snowflake.go
GitHub diff is a mess because of indentation, so I've commented on actual changes
- Rework the pipe report checking logic. We used to set a number of iterations per pipe to approximate taking 5 minutes, but in cases where users have > 100 pipes we would end up always falling back to `COPY_HISTORY`, and failing because we had tried to get all results from `COPY_HISTORY` on the first iteration (whereas `COPY_HISTORY` is supposed to be a last resort option). It was this way due to some vestigial reasons that no longer apply, we used to paginate through results of reports, etc., which we don't do anymore and we are generally more confident that we will get results from the API in less than a minute.
- The new logic has a time limit across all pipes and instead of iteration …
> materialize-snowflake: check pipe reports without delay unless 0 results

- materialize-kafka/src/apply.rs
Normally we will see that a topic already exists via the admin metadata request and not try to create them again, but there are apparently some more restrictive setups that do not allow the topic to show up in the metadata response, but do allow it to be written to by name.
This change makes it so that the connector won't fail if it tries to create a topic that already exists, even though it can't see that it exists.
**Notes for …
> materialize-kafka: don't fail apply if a topic already exists

- source-oracle/prerequisites.go
- add a prerequisite to Oracle CDC to check for archive log retention period of at least 24 hours, but give a warning if it is less than 7 days
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2317)
> source-oracle: add archive log retention period check

- sqlcapture/capture.go
There's some additional information it might be useful to see here for debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2354)
> sqlcapture: Log all discovery info, not just columns

- tests/materialize/materialize-databricks/cleanup.sh
- tests/materialize/materialize-motherduck/cleanup.sh
- tests/materialize/materialize-motherduck/config.yaml
- tests/materialize/materialize-redshift/cleanup.sh
- tests/materialize/materialize-redshift/config.yaml
- tests/materialize/materialize-s3-iceberg/config.yaml
- tests/materialize/materialize-s3-iceberg/snapshot.json
- tests/materialize/materialize-snowflake/cleanup.sh
- tests/materialize/materialize-snowflake/fetch-data.go
Updates the keys used to authenticate for some integration tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2388)
> tests: update auth for tests

- source-sqlserver/replication.go
This is useful information for debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2404)
> source-sqlserver: Discover CDC instance role_name

- scripts/list-tasks/main.go
This just makes the operation of the list-tasks script a bit less aesthetically unpleasant. Since there is no connector named `ghcr.io/estuary/404: Not Found` and never will be the old code technically "worked" but it bothered me anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2420)
> scripts/list-tasks: Fix VARIANTS file 404

- .github/workflows/ci.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2431)
> source-oracle-batch: add to CI

- scripts/list-tasks/main.go
I'm trying to modify about 700 tasks in production and it would be really convenient when trying to make sure every last one has been updated to just throw everything away and start over with just he tasks that didn't get successfully published.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2428)
> scripts/list-tasks: Flag to list tasks without setting

- source-shopify/pyproject.toml
- source-shopify/source_shopify/tap_shopify/schemas/inventory_item.json
- source-shopify/tests/snapshots/snapshots__discover__capture.stdout.json
Small schema update, and fixes the connector build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2444)
> source-shopify: update schema for inventory_items

- materialize-boilerplate/staged_files.go
In f4a82c4 a partial fix was implemented to prevent attempts to cleanup the same files again when a binding had data for one but not a subsequent transaction.
That change fixed that issue, but it also made it so that staged files just never got cleaned up, because `f.started` is set to `false` by `f.flush()`, which is always called before the cleanup.
A complete fix is here, which clears out the list of uploaded files after sending them off for deletion.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along …
> materialize-boilerplate: fix staged files cleanup again

- source-postgres/replication.go
This should never happen but we observed it once. I still have no idea how it could possibly happen so we need more information in case it happens again someday.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2457)
> source-postgres: Detect tuple/relation mismatch

- scripts/list-tasks/main.go
The main purpose of thise flag is so that when doing a bulk flag flip in production, one can go and re-pull just tasks that still needh to be modified.
And my reasoning is that if I'm going and setting a flag like `no_foobar` in prod, there are three cases:
- A task has no feature flag setting for `foobar`. These are the ones we want to modify.
- A task has setting `no_foobar`. These don't need to be touched since they already have the value we want.
- A task has setting `foobar`. These _really_ shouldn't be touched since somebody has explicitly indicated that they want the opposite of what we're doing.
Previously the 'missing flag' logic was written such that one might go `--missing=no_foobar` to get all tasks without the specific flag setting `no_foobar` in their …
> scripts/list-tasks: Rework missing-flags logic

- source-postgres/replication.go
This adds a connector startup check to verify that the resume LSN is less than or equal to the current server WAL LSN. This should be the case 100% of the time except when we suddenly get pointed at a different database entirely, or if the WAL gets deleted and restarts from zero as happens in a DB version upgrade.
This check is in warn-only mode for now, and I tweaked the wording on the other "is this resume LSN consistent with the current state of the server" check we do so they'll both include the substring `"resume cursor mismatch"`. My plan is to check back in a week to see if either warning triggered when it shouldn't have, and if not we'll (finally) promote these checks to hard failures.
- - - …
> source-postgres: Additional resume cursor check

- go.mod
- go.sum
- materialize-databricks/driver.go
- tests/materialize/materialize-databricks/snapshot.json
Reverts estuary/connectors#2507
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2508)
> Revert "materialize-databricks: use mahdi's fork of databricks driver"

- estuary-cdk/estuary_cdk/capture/common.py
- source-stripe-native/source_stripe_native/resources.py
This PR improves the handling of subtasks and state management in the `estuary-cdk` and `source-stripe-native` connector. The most important changes include adding support for `subtask_id` in various CDK functions and improving the handling of initial state creation in `source-stripe-native`
The main problem that necessitated this change:
* Unassigning a shard (restarting it) for a `source-stripe-native` capture that had `capture_connected_accounts` enabled would potentially cause an assertion error if some of the previous backfill subtasks finished and were set to None, but others were not. The state pulled out of the `state.backfill` dictionary for the `subtask_id` could be `None` and then the assertion would fail. The changes here ensure that a task is only spawned if …
> source-stripe-native: Fix subtask backfill state assertion issue

- source-oracle/replication.go
- Apparently it is possible for the current log file to be at the same time archived, i.e. it is possible to have two log files with the same `SEQUENCE#` and `FIRST_CHANGE#`, one of them with `Status: ARCHIVED` and the other `Status: CURRENT`. In this scenario Logminer complains:
```
adding logfile "/rdsdbdata/db/OOPUAE_A/onlinelog/o1_mf_3_m5ml99to_.log" (CURRENT, 18433725214, NO, NO) to logminer: ORA-01289: cannot add duplicate logfile /rdsdbdata/db/OOPUAE_A/onlinelog/o1_mf_3_m5ml99to_.log
ORA-06512: at "SYS.DBMS_LOGMNR", line 82
ORA-06512: at line 1
```
This pull-request addreses this case by preferring the `CURRENT` file over the archived one (with the presumption that the `CURRENT` file has more recent updates). Added a debug log for this scenario so I can monitor it. …
> source-oracle: skip archived log if it has same sequence as current log

- source-http-ingest/src/server.rs
Resolves #2433
Okta requires the server to respond to a GET request with a special header value before it will start sending webhooks. This implements the GET request handler.
This is enabled universally, since I saw no downside to doing so. So this should allow the connector to just start accepting Okta webhooks, without requiring any extra steps.
I tested this by deploying the PR build of the connector, and having the user configure Okta to start sending webhooks. They were able to successfully verify the endpoint and capture data.
I also manually tested using:
```
curl -k 'https://ca1f4fbcdaac1efc-8080.reactor.flow.localhost:9000/webhook-data' -H 'accept: application/json' -H 'x-okta-verification-challenge: canary'
{"verification":"canary"}
```
and …
> source-http-ingest: support okta verification challenge

- source-mixpanel-native/source_mixpanel_native/streams/cohort_members.py
Mixpanel cohorts can be associated with a data group. If a data group that has cohorts associated with it is deleted, the members of that cohort can't be queried via `/engage` and doing so results in a somewhat specific 404 response. I think this can be fixed by removing the association between the cohort & data group in Mixpanel, but the user has to do that in their own account. Until the user makes that fix, we log a warning & skip to fetching the next cohort's members. …
> source-mixpanel-native: skip fetching members for cohorts associated with deleted data groups

- materialize-snowflake/.snapshots/TestSQLGeneration
- materialize-snowflake/pipe.go
- materialize-snowflake/snowflake.go
- materialize-snowflake/sqlgen.go
- materialize-snowflake/sqlgen_test.go
- tests/materialize/materialize-snowflake/cleanup.sh
- tests/materialize/materialize-snowflake/fetch.sh
- tests/materialize/materialize-snowflake/setup.sh
- tests/materialize/materialize-snowflake/snapshot.json
- Hash pipe names following Iceberg's example with some modification to fit the requirements here
- Add a test case for a table name with special characters to test it out
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2569)
> materialize-snowflake: hash pipe names with special characters

- source-google-ads/source_google_ads/spec.json
- source-google-ads/tests/snapshots/snapshots__spec__capture.stdout.json
Removing references to Airbyte's docs & unsightly raw HTML elements in field descriptions & spec in general.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2497)
> source-google-ads: clean up field descriptions

- source-postgres/discovery.go
Adds logic to source-postgres discovery to query and log the current server XID. This is a hacky place to put that behavior but discovery runs at connector startup and periodically throughout the connector lifecycle, so it should give us the information we need.
The query/log function shouldn't be able to cause task failures since errors are logged but not returned. It first tries `txid_current()` and then if that fails (which should only happen on a read-only standby replica) it tries `pg_last_committed_xact()` (which should give a similar result and work on a standby according to what I've read, but I haven't used that function before so I can't vouch for it firsthand).
- - - …
> source-postgres: Query/log current XID periodically

- materialize-boilerplate/validate.go
- materialize-boilerplate/validate_test.go
Include the collection name in this error from Validate to help with finding a resolution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2578)
> materialize: include the collection name in nullable key error message

- .github/workflows/python.yaml
Add new `source-chargebee-native` to CI pipeline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2585)
> source-chargebee-native: add to ci

- source-mixpanel-native/source_mixpanel_native/streams/export.py
> source-mixpanel-native: handle split `export` records better

- source-chargebee-native/source_chargebee_native/api.py
Modified the date filtering logic in the _fetch_resource_data function to utilize the cursor field specific to IncrementalChargebeeResource.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2593)
> source-chargebee-native: update date filtering logic

- source-sqlserver/prerequisites.go
We only need this prerequisite check when in read-only non-replica mode and it's incorrect to let that break a replica capture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2610)
> source-sqlserver: Skip `cdc_log_scan_sessions` check on replicas

- materialize-mysql/driver.go
It has happened where table creation statements were successfully ran in Apply, but then the connector can't see the table right after in Open. Among other things, this makes it so it can't load the column metadata for the table(s) to enable dynamic resizing of text columns.
Right now this will panic. This changes it so a better user-facing error message is returned instead.
(anything that might help …
> materialize-mysql: more informative error message if a table doesn't exist in Open

- source-intercom-native/source_intercom_native/api.py
The `conversation_parts` stream is very slow since it iterates through a page of conversations and makes an API call to fetch the parts of each conversation one after another.
This process can be sped up significantly by fetching parts for multiple conversations concurrently. The connector now leverages `asyncio.as_completed` to fetch parts of conversations concurrently and yield them in the order that they arrive. The connector caches a list of conversation ids to fetch parts for before the next cursor to checkpoint,
so it's alright for the ordering of `conversation_ids` to not be maintained when yielding conversation parts. The `parts_semaphore` ensures only 15 API requests for parts are in-flight at a time.
The checkpoint strategy for `conversations` was also updated …
> source-intercom-native: fetch parts of separate conversations concurrently

- source-gainsight-nxt/source_gainsight_nxt/api.py
This change modifies the _fetch_object_data function to yield results asynchronously using IncrementalJsonProcessor, improving memory efficiency and performance. The function now returns an AsyncGenerator instead of a list, allowing for better handling of large API responses causing OOM Kills. Additionally, the snapshot_resource and fetch_resource_page functions have been updated to accommodate the new streaming approach, ensuring they yield documents correctly based on the new implementation.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that …
> source-gainsight-nxt: use incremental json processing

- source-braintree-native/source_braintree_native/api.py
- Ensuring searches for all transaction search fields will return fewer than `TRANSACTION_SEARCH_LIMIT` results
- The connector was already checking & raising an exception if any of the searches exceeded `TRANSACTION_SEARCH_LIMIT`, but it wasn't reducing the date window's end if non-`created_at` fields hit the limit. This has never happened (it seems like transactions are created much more frequently than any of the other actions tracked by the other fields), but this should help the connector handle this situation better if it does occur.
- Fetching disbursed transactions in the incremental `fetch_transactions` function.
When a transaction's `disbursement_details/disbursed_date` is updated, none of the `TRANSACTION_SEARCH_FIELDS` or the …
> source-braintree-native: incrementally capture past day(s) disbursed transactions

- source-mongodb/pull.go
The 'hello' command is not present on very old version of MongoDB, but 'isMaster' can be used as a fallback for our purposes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2625)
> source-mongodb: use 'isMaster' as a fallback for fetching cluster op time

- materialize-postgres/driver.go
On numerous occasions we have observed certain queries hanging forever when materializing to postgres, and as far as we know these have always been due to the database running out of disk space.
This adds a conservative timeout to queries that are prone to hang on this condition, so that the connector will fail with an error and restart, rather than hanging indefinitely. …
> materialize-postgres: add timeout for queries that have been known to hang

- source-gainsight-nxt/source_gainsight_nxt/api.py
- source-gainsight-nxt/source_gainsight_nxt/models.py
- Removed unnecessary `has_results` flag in `fetch_resource_changes` function, simplifying the logic for yielding `max_updated_at`.
- Updated cursor value handling in `GainsightResourceWithModifiedDate` model with a new `set_cursor_value` validator to ensure proper datetime conversion.
- Added validation for required class attributes in the model's subclassing to enforce structure and integrity. …
> source-gainsight-nxt: fix bug in incremental capture

- source-postgres-batch/driver.go
The initial backfill query from a CTID+XMIN table shouldn't ever be filtered on base XID because we don't have a meaningful lower XID to filter on.
The upper XID filter will generally be applied, except when this is an initial backfill _and_ the server XID has already wrapped around, because in that case we'd filter out rows with a higher XID-4 from the previous wraparound epoch(s).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2651)
> source-postgres-batch: Backfill XID filtering

- source-postgres-batch/driver.go
This PR improves two things which I noticed while watching some batch Postgres task logs today:
1. When a polling query is interrupted due to statement timeouts or recovery conflicts, we just retry internally rather than letting it take down the entire capture. These errors are a benign and expected thing, and retrying within the worker just avoids a bunch of unnecessary task downtime and impact on other bindings.
2. Some logging tweaks and two sub-second sleeps which should make the initial flurry of startup logging much easier to read without any impact on normal operation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2652)
> source-postgres-batch: Retries and logging tweaks

- materialize-snowflake/snowflake.go
- We have a customer who has pipes that take more than 5 minutes to show up in status...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2660)
> materialize-snowflake: increase waiting time for pipe status to 10m

- materialize-snowflake/snowflake.go
- I realised we were adding old version pipe names to `currentPipes` which would break the `cleanupPipes` process because:
Let's say we have binding X, and it has two checkpoints, one X.v1 and one X.v2
X.v1 has pipe name with version A
X.v2 has pipe name with version B
We clean up X.v1 as we realise this is an older version of the same binding (`item.PipeName != b.pipeName`), but we have added "A" to currentPipes. When we run `cleanupPipes`, we loop over pipes that exist in Snowflake, and we find B, and we compare it against A, the schema and the table name match but the version doesn't, so we clean up B. This is not destructive since we only run cleanup after having finished a commit, but it unnecessarily re-creates pipes constantly.
- Also added more logging to be able …
> materialize-snowflake: only cleanup leftovers if not already cleaned up

- source-kinesis/capture.go
- source-kinesis/connection.go
Some situations necessitate polling shards as fast as we practically can, such as there always being new records available, or trying to catch up to a stream with a long run of empty segments.
There is an internal backoff/retry mechanism in the Kinesis client itself which works most of the time for this, but we still want to always retry on this particular kind of error rather than crashing the connector and possibly losing progress.
For the specific case of shards with a long run of empty data where we have to call GetRecords many times to get to the latest tip, there's probably an additional improvement we could make where we also checkpoint the latest timestamp and use a different kind of resumption shard iterator, but that is a larger change.
(How …
> source-kinesis: always retry throughput exceed errors for GetRecords

- source-salesforce-native/source_salesforce_native/api.py
- source-salesforce-native/source_salesforce_native/bulk_job_manager.py
We've started to see production tasks hit the 24-hour rolling limit for how much data can be queried via the Bulk API 2.0 (1 TB). We should investigate ways to improve the connector's usage of the Bulk API (ex: resume reading bulk jobs that were started in the connector's previous invocation), but a simpler improvement that should be made regardless is falling back to the REST API when we receive this error.
**Notes for …
> source-salesforce-native: fallback to REST when Bulk volume has been exceeded

- source-salesforce-native/source_salesforce_native/api.py
The scope of this PR includes:
- Combating eventual consistency issues with Salesforce's API by not fetching the most recent 5 minutes of updates.
- Improving checkpointing behavior for empty date windows.
I've done some testing to prove that Salesforce's REST API is eventually consistent. Here's the tests' results:
| Test ID   | Number of Delayed IDs | Delay Duration | Test Duration |
|--------|-------------|----------------|----------------|
| 1 | 3           | 2 seconds      | 17 minutes     |
| 2 | 2           | 1 second       | 7 minutes      |
| 3 | 3           | 1 second       | 6 minutes | 
| 4 | 5           | 3 seconds     | 40 seconds |
| 5 | 1           | 1 second      | 5 minutes | 
[Fivetran](https://fivetran.com/docs/connectors/applications/salesforce/trouble …
> source-salesforce-native: address eventual consistency issues with REST API

- source-mysql/main.go
Usually backfill queries are fast. But every so often we'll have a long-running backfill query, and in MySQL land those very often fail after exactly two minutes with error:
io.ReadFull(header) failed. err read tcp <addr>: i/o timeout: connection was bad
The fact that it always seems to be two minutes is what made me start being suspicious. And it turns out I was right to suspect, because that's actually our connector's fault.
Previously, we set connection timeouts of one minute as part of the initial connection-establishment logic so that certain classes of "database is unreachable but there's an SSH tunnel involved and so we can't actually tell that the connection dropped" of error would be reliably detected.
Unfortunately that same timeout is also applied to every …
> source-mysql: Fix mysterious I/O timeouts

- materialize-azure-fabric-warehouse/sqlgen.go
The maximum allowed string byte size in Azure Fabric Warehouse is 1 MiB, which is somewhat restrictive.
In cases where strings are larger than this, we'd like to know which field it is for. The error message from Fabric doesn't tell us that of course, so this is a built-in check of the lengths before we send them to Fabric.
- - - …
> materialize-azure-fabric-warehouse: connector check of maximum string length

- source-klaviyo/source_klaviyo/streams.py
We've observed eventual consistency with the Klaviyo API's `/events` endpoint. To avoid asking for data while Klaviyo is inconsistent, we set an upper bound on how recent the data can be. This limits how "real-time" the connector is, but these Airbyte imports are often relatively slow anyway since streams don't run concurrently, and if we wanted a more real-time solution, we should build a native connector.
I ran a few tests to find how "eventual" Klaviyo's `/events` endpoint is. After testing some possible `LAG` durations, I ended up using 110 minutes of lag to ensure results from Klaviyo are consistent. It's possible even this isn't sufficient, but I couldn't' find any evidence of events appearing after 110 minutes of lag during my (albeit somewhat limited) testing. …
> source-klaviyo: address eventual consistency with `events`

- materialize-redshift/sqlgen.go
These timestamp columns need to be converted to strings in UTC time before they can be cast to SUPER columns.
I manually tested this with a timestamp column with or without nulls and verified it is migrated to a SUPER column as expected. I am not entirely sure how the `jsonQuoteCast` function operates on columns that are already VARCHAR to SUPER, but this seems to work without doing that.
(anything that …
> materialize-redshift: migrate TIMESTAMPTZ columns to SUPER

- go/blob/s3.go
A region is always required to for S3, either via an option or dynamic determination.
This makes that requirement more explicit, and provides a better error message for the fairly common case of a bucket not existing.
- - - …
> blob: make sure a region is available for s3

- materialize-postgres/driver.go
Lazily start a Postgres transaction only when there is at least once key to load.
Previously, we would always start a transaction, even if no load requests were received. In cases such as delta updates bindings, this would cause a transaction to be held open and then be closed out without doing anything for the duration of the runtime's reading of documents to store. …
> materialize-postgres: don't start a postgres transaction if there are no keys to load

- source-zendesk-support-native/source_zendesk_support_native/resources.py
The various `posts` streams and the `topics` stream are parts of a Zendesk Support Help Desk. It looks like some Zendesk accounts don't have help desks, so API calls to these help desk endpoints fail with a 404 error. The connector shouldn't discover these endpoints if the Zendesk account doesn't have a help desk.
Confirmed `posts`, `post_comments`, `post_comment_votes`, `post_votes`, and `topics` are …
> source-zendesk-support-native: conditionally discover help desk streams

- source-monday/source_monday/graphql.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2774)
> source-monday: move log statement into loop

- source-zendesk-support-native/acmeCo/articles.schema.yaml
- source-zendesk-support-native/acmeCo/flow.yaml
- source-zendesk-support-native/source_zendesk_support_native/api.py
- source-zendesk-support-native/source_zendesk_support_native/models.py
- source-zendesk-support-native/test.flow.yaml
- source-zendesk-support-native/tests/snapshots/snapshots__capture__capture.stdout.json
- source-zendesk-support-native/tests/snapshots/snapshots__discover__capture.stdout.json
Adding Articles stream from the Zendesk Help Center API
https://developer.zendesk.com/api-reference/help_center/help-center-api/articles/#list-articles
Tested with customer credentials via flowctl 5/12/25
- - - …
> Adding Help Center Articles Stream

- source-hubspot-native/source_hubspot_native/api.py
Refines the error message and adds some additional logging for when this happens.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2801)
> source-hubspot-native: log query input when search results are out of order

- estuary-cdk/estuary_cdk/http.py
- source-chargebee-native/source_chargebee_native/api.py
Adds retry logic to `asyncio.TimeoutErrors` that happen `source-chargebee-native` and are not easily reproduced.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2807)
> source-chargebee-native: timeouts

- source-stripe-native/source_stripe_native/resources.py
This pull request introduces changes to the `source-stripe-native/source_stripe_native/resources.py` file to improve the initialization logic for resource state handling. The most notable updates include adding type annotations for `all_bindings`, introducing additional validation for state properties, and restructuring the logic for initializing `fetch_changes_fns` and `fetch_page_fns`.
(anything that …
> source-stripe-native: dynamic subtask state initialization

- source-mysql/backfill.go
In general it's not a fatal error to have our backfill query get interrupted by a statement timeout. An interrupted backfill chunk is still a valid backfill chunk, so long as we're making progress through the table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2828)
> source-mysql: Handle backfill query timeouts gracefully

- source-postgres/replication.go
As explained in the comments, it should never be possible for a PostgreSQL CDC deletion event to be empty, because the deletion has to contain the table's REPLICA IDENTITY columns and you can't delete from a published table with an empty replica identity.
And yet, somehow this appears to be happening on a production task, so we need more information about what's going on. This adds a check for the should-be-impossible situation, and if it occurs it logs everything I can think of that might be useful before erroring out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2834)
> source-postgres: Debug logging for empty deletion

- source-facebook-marketing/source_facebook_marketing/streams/async_job.py
When splitting an `InsightAsyncJob` into smaller jobs, the `self._edge_object.get_insights` call is only used to retrieve unique primary keys for future, smaller jobs (_not_ to fetch & yield records). Including the `breakdowns` parameter segments data and can significantly increase the number of rows returned, even though the set of unique primary keys stays the same. This slows down the connector since it ends up paginating through multiple results with the same primary key. I've observed this happen when including the `region` breakdown; it can take over an hour to get ~15 unique primary keys.
Omitting the `breakdowns` param causes only a single row to be returned for each primary key, reducing how much pagination is needed when splitting an `InsightAsyncJob`. …
> source-facebook-marketing: omit `breakdowns` param when splitting async jobs

- source-jira-native/source_jira_native/api.py
We've already observed a single issues response causing the connector to run out of memory and crash. Switching to the `IncrementalJSONProcessor` avoids these OOMs.
I originally didn't use the `IncrementalJSONProcessor` because I anticipated adding streams that are children of issues — i.e., we fetch an issue, then fetch some subresource using that issue's ID. In other connectors with similar child streams where the parent used the `IncrementalJSONProcessor`, reading the HTTP response for the parent stream would time out due to how long it takes to fetch child resources for each parent ID.
I was cautiously optimistic that a single `issues` response wouldn't consume too much memory and that we wouldn't need to worry about parent streams' HTTP responses timing out when …
> source-jira-native: use incremental json processor for `issues`

- source-mysql/replication.go
For MySQL DML query events we normally try to determine whether they modify a table that we actually care about before erroring out, but the MySQL UPDATE query grammar is pretty complicated so previously we just took the conservative approach and assumed that any UPDATE query event was an error.
This commit makes that logic a bit more nuanced, so that the simplest possible `UPDATE <table> SET ...` type of queries should perform the same "does it refer to an active table" check we do for INSERT and DELETE.
More complicated UPDATE queries involving parenthesized lists of tables or joins will still be assumed to be an error.
- - - …
> source-mysql: Improved UPDATE query handling

- source-postgres/backfill.go
In https://github.com/estuary/connectors/pull/2878 the CTID backfill logic was modified so that instead of a LIMIT clause plus ascending-TID-order assumption we'd use an explicit upper bound on each backfill query.
That means this ordering check is no longer required, and removing it was actually the entire point of the previous PR, I just forgot to actually delete the check. Whoops.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2887)
> source-postgres: Remove CTID ordering sanity check

- source-mongodb/main.go
To help with debugging reports of high numbers of connections being created,
this adds some debug logging to see when new connections are being made.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/2895)
> source-mongodb: debug logging for connection pool events

- source-jira-native/source_jira_native/api.py
The bulk `screens/tabs` endpoint is the most request-efficient way to fetch screen tabs, but it returns _all_ screen tabs, including deleted & archived ones. This means we can make requests for fields of screens/tabs that no longer exist in `snapshot_screen_tab_fields` & receive `400` responses from Jira with a message like "Screen with id 12345 does not exist". We should ignore those errors when we hit them.
**Notes for …
> source-jira-native: handle 400 responses when fetching screen tab fields

- source-stripe-native/source_stripe_native/resources.py
This update adds a check to each resource binding to ensure that all connected account IDs are present in both the incremental and backfill state dictionaries. If either state is missing for an account, it is initialized from the initial state, and a checkpoint is triggered to persist the update.
This PR also addresses a legacy issue where, after a connector restart, the incremental state for a subtask might not be initialized even though the backfill state has progressed due to not emitting checkpoints in the prior state initialization logic for connected accounts. In such cases, the subtask is reset to backfill and to ensure state/data consistency. This check is a temporary measure to reconcile state misalignments and prevent data loss or missed updates for affected …
> source-stripe-native: reconcile connector state

- materialize-redshift/Dockerfile
- materialize-redshift/client.go
- materialize-redshift/driver.go
- materialize-redshift/driver_test.go
- materialize-redshift/sqlgen.go
- materialize-redshift/sqlgen_test.go
- tests/materialize/materialize-redshift/config.yaml
Updates the connector to use materialize-sql-v2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3014)
> materialize-redshift: use materialize-sql-v2

- source-jira-native/source_jira_native/resources.py
We've observed that some Jira instances do not support all standard permissions, and Jira returns a 400 response if we check if a user has any of those unsupported permissions.
Instead of checking for all standard permissions by default, we now get the list of available permissions, then only check if the user has the intersection of those support permissions and all standard permissions.
Tested on a …
> source-jira-native: fix permissions validation for instances with limited permission sets

- source-postgres/change.go
In general row keys don't contain nil values, but it is possible in certain corner cases (mainly involving overriding the row key selection to something other than the primary key). In that case, we should always translate a nil byte slice to the nil tuple element 0x00.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3038)
> source-postgres: Nil values in FDB tuples

- source-stripe-native/source_stripe_native/priority_capture.py
I've observed a slow memory leak in production captures where memory usage would increase ~30% over a few hours. I suspect the memory leak is due to improper cleanup of pending tasks when a work item is cancelled.
In `_binding_incremental_task_with_work_item()`, the code created `asyncio` tasks for monitoring stopping conditions:
```python
global_stop = asyncio.create_task(task.stopping.event.wait())
work_cancelled = asyncio.create_task(work_item.cancellation_event.wait())
done, pending = await asyncio.wait([global_stop, work_cancelled], ...)
for p in pending:
p.cancel()  # ❌ Cancelled but not awaited
```
When `asyncio.wait()` completed with the `global_stop` task still pending, that task was cancelled with `p.cancel()` but never awaited. This left the cancelled task …
> source-stripe-native: fix memory leak from not awaiting cancelled tasks

- source-mongodb/change_stream.go
We'll require 10 _consecutive_ empty result sets to be considered caught-up when there is no event timestamp available for positive confirmation.
This should only happen when we're really at the "end" of the change stream and there are no more events.
It mitigates a scenario where many reads of the change stream are needed, and they have intermittent empty results. …
> source-mongodb: adjust catch-up stream retry logic

- source-shopify-native/source_shopify_native/graphql/bulk_job_manager.py
This query to check a bulk job status is cheap, so we shouldn't run into rate limits by querying more frequently. This should help reduce how much time the connector is sleeping & potentially waiting when a bulk job has completed. This isn't a huge throughput improvement, but it could help a little bit.
- - - …
> source-shopify-native: reduce the maximum sleep duration between checking bulk job status

- source-monday/source_monday/api.py
Boards can be deleted between invocation of `fetch_items_page` after we initially found the board in non-deleted state and checkpointed the board ID in the `PageCursor`. This causes the `fetch_items_page` to continuously fail when querying items for that board and the backfill never makes progress.
This PR introduces a check for all boards again on each invocation and marks boards as deleted and emits a checkpoint for boards that were deleted so that we do not try to process their items anymore. Additionally, while we haven not observed this, there is a check to mark boards as complete if the query no longer returns a board that was originally in the `PageCursor` which could happen if:
- User started a capture
- made some progress on backfill
- paused capture for 30+ days …
> source-monday: handle boards deleted between `fetch_items_page` invocation

- source-mongodb/change_stream.go
Adds an experimental routine for extracting timestamps from MongoDB resume tokens. I'm fairly confident it will work across all MongoDB versions, but right now I am adding it along with logging that can be enabled by `LOG_LEVEL=debug`. I would like to ensure it works across a sampling of tasks in production before using it for anything else.
The intended uses for this are to eventually:
* Provide a positive indication that a change stream is "caught up", even if it yields no events that have a cluster timestamp with them. We can extract a timestamp even from a post-bast resume token, which represents a time relative to the position of the change stream. This would replace the rather janky retry-based mechanism implement in 13c89ec.
* Similarly, give a better indication of …
> source-mongodb: experimental timestamp extraction from resume tokens

- materialize-kafka/Cargo.lock
- materialize-kafka/Cargo.toml
- materialize-kafka/Dockerfile
- materialize-kafka/src/lib.rs
- materialize-kafka/src/transactor.rs
- materialize-kafka/src/validate.rs
- source-kafka/Cargo.lock
- source-kafka/Cargo.toml
- source-kafka/Dockerfile
- source-kafka/src/lib.rs
similar to #3133 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3145)
> fix rust connectors: read requests until EOF

- base-image/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3167)
> base-image: add `tzdata` package

- base-image/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3169)
> base-image: add `tzdata-legacy` package

- source-klaviyo-native/source_klaviyo_native/api/common.py
When the connector hits an error and is attempting to gracefully exit, a `backfill_incremental_resources` invocation can significantly delay that graceful exit since the function does not yield control back to the CDK & check the stopping event until the backfill is complete. fetch_page functions like `backfill_incremental_resources` should yield control back to the CDK every so often to avoid blocking like that.
In other connectors, I've used a date window to prevent the fetch_page function from trying to complete the entire backfill in a single invocation. However, not all of Klaviyo's endpoints support a less than operator on the cursor field - we _can't_ use date windows for every endpoint. Instead, I've implemented a simple timer to exit …
> source-klaviyo-native: update backfills to check the stopping event after 5 minutes

- source-sqlserver/replication.go
Apparently the throughput optimization PR broke watermark fences about a month ago, but it took a while to notice because:
1. Very few people are still using watermark fences
2. If we fail to identify the watermark fence, the initial catchup streaming phase just continues forever, and that still works fine as long as you just need to stay caught up on replication. Things only actually break if you need to backfill or add a table.
The root of this bug is that I accidentally used a list of column names which is in _serialized document order_ as though it were in _database column order_ leading us to consult the wrong column value for the actual check. This should fix it.
- - - …
> source-sqlserver: Fix watermark fencing

- source-azure-blob-storage/main.go
Sometimes, Azure returns empty pages as part of a listing _despite_ there being non-empty pages left to list. I'm not 100% sure what causes this, but Claude suspects it's related to how Azure indexes blobs in large containers.
We can easily handle this by just skipping empty pages & fetching the next one. Whether or not a page contains results doesn't impact pagination; the pager's `More` method uses a `NextMarker` page cursor under the hood to determine whether or not more pages exist. …
> source-azure-blob-storage: skip empty pages in listing

- materialize-google-pubsub/driver.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/3205)
> materialize-google-pubsub: key fields should be OPTIONAL

- source-http-file/main.go
Automatically reconnect when Wikimedia streams are cancelled by the server. Only retries on specific "stream ID $NUMBER; CANCEL; received from peer" errors.
This is a carve out that only works with the Wikimedia stream for `source-http-file`; the connector is being used to capture from a stream, not a file of finite length. If we want to support resuming streams (or said another way, files that never end), we'll need to investigate other options further.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along …
> source-http-file: reconnect after HTTP connections are cancelled

- source-shopify-native/acmeCo/flow.yaml
- source-shopify-native/acmeCo/product_variant_metafields.schema.yaml
- source-shopify-native/source_shopify_native/graphql/__init__.py
- source-shopify-native/source_shopify_native/graphql/collections/metafields.py
- source-shopify-native/source_shopify_native/graphql/customers/metafields.py
- source-shopify-native/source_shopify_native/graphql/locations/metafields.py
- source-shopify-native/source_shopify_native/graphql/metafields.py
- source-shopify-native/source_shopify_native/graphql/orders/metafields.py
- source-shopify-native/source_shopify_native/graphql/products/metafields.py
- source-shopify-native/source_shopify_native/resources.py
- source-shopify-native/test.flow.yaml
- source-shopify-native/tests/snapshots/snapshots__capture__capture.stdout.json
- source-shopify-native/tests/snapshots/snapshots__discover__capture.stdout.json
This pull request introduces support for capturing and processing Shopify product variant metafields, alongside a refactor to fix the handling of metafield results across multiple resource types. The main changes include the addition of a new `ProductVariantMetafields` resource and improvements/refactors to the metafield result processing logic so that the `process_results` method actually uses the proper `PARENT_ID_KEY` variable set by the sub-class and not the `MetafieldsResource` class. …
> source-shopify-native: add product variant metafields

- source-jira-native/source_jira_native/api.py
I had assumed sprints could only be associated with a single board. Turns out, I was wrong and sprints can be associated with multiple boards and the connector should be deduplicating sprints that are associated with more than one board.
Tested on a local stack. Confirmed sprints are de-duplicated based on their id.
- - - …
> source-jira-native: de-dupe sprints

- materialize-motherduck/driver.go
Motherduck has occasional issues where queries hang forever, never completing but also never erroring out. A 4 hour timeout is quite generous but should allow the connector to restart rather than getting stuck indefinitely, while still allowing any reasonable query to complete. Hopefully MD will fix this eventually and we can remove this timeout.
> materialize-motherduck: add timeout for stuck queries

- materialize-sqlserver/.snapshots/TestSQLGeneration
- materialize-sqlserver/driver.go
- materialize-sqlserver/sqlgen.go
> materialize-sqlserver: switch to _flow_delete in merge queries

- materialize-azure-fabric-warehouse/.snapshots/TestSQLGeneration
- materialize-azure-fabric-warehouse/sqlgen.go
- materialize-azure-fabric-warehouse/transactor.go
> materialize-azure-fabric-warehouse: use _flow_delete for deletions

- source-azure-blob-storage/main.go
The Azure Blob Storage connector was ignoring the `query.Prefix` parameter in its `List()` method, causing all bindings to capture from the container root instead of their specified subpaths. This meant that bindings configured with different paths (e.g., "container/dir1", "container/dir2") would all see the same files from the entire container.
This brings the Azure connector in line with other `filesource` connectors (S3, GCS) which correctly handle prefix filtering. Each binding now only captures files under its configured subpath, enabling proper multi-binding usage patterns.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HX …
> source-azure-blob-storage: fix prefix filtering for multiple bindings
