estuary/connectors

Makefile, go-types/airbyte/catalog.go, go-types/airbyte/json_test.go, go-types/shardrange/partition_range.go, source-kinesis/capture.go, source-kinesis/capture_test.go, source-kinesis/connection.go, source-kinesis/main.go, source-s3/capture.go, source-s3/connection.go, source-s3/main.go
This PR addresses a few different issues:
- Add `projections` to `ConfiguredStream` and pass them through to the parser configuration in the S3 connector
- Namespace `ConfiguredStream.projections` and `ConfiguredCatalog.tail | range` with `estuary.dev/` prefix, but still accept the un-prefixed field names as well. The intent will be to do away with the prefix if and when these are merged into the airbyte spec.
- Fixes a few issues I found with the `spec` subcommands panicing due to invalid json.
- Add missing pre-requisites to connector build makefile tasks
=> Connector configuration cleanups

Makefile, go-types/filesource/filesource.go, source-s3/main.go
- Use AnonymousCredentials when no credentials are provided in the config. This allows ingestion of data from public buckets.
- Include the object Path in the error message when parsing fails, so that it's easier to track down parse errors.
=> Minor fixes to source-s3

parser/src/format/csv.rs, parser/src/format/projection.rs, parser/src/format/snapshots/parser__format__projection__test__projections_are_built.snap, parser/src/input/mod.rs, parser/tests/examples/valid-big-nums.csv, parser/tests/examples/valid-mixed-types.csv
- Parser now will refuse to parse numberic values that overflow the
common 64bit numberic types.
- Parser no longer defaults inferred type information to allow any type,
and instead returns `types::INVALID` when no type information is known.
=> Fix parser handling of overflowing numberic values

.github/workflows/ci.yaml
It looks like we're running into intermittent problems with concurrent jobs all writing to the same cache entry. The recommended advice for now appears to be "parameterize the scope with your matrix name". I don't know if this is going to be fixed upstream at some point, but I'm curious if this fixes it for us.
I've tested this with `johnny/materializations` merged in. It seems to fix the issue, at least anecdotally. More runs will be the real test. I've had 3 successive, successful builds.
=> Explicitly scope Docker layer caching

tests/run.sh
The rationale for not automatically deleting the directory makes
good sense, but giving actionable instructions and identifying the
specific path that needs to be deleted makes it less painful for
interactive use.
=> Make run.sh failure less cryptic when running a second time

parser/Cargo.lock, parser/Cargo.toml, parser/src/format/csv.rs, parser/src/format/projection.rs, parser/src/format/snapshots/parser__format__projection__test__projections_are_built.snap
Collate projection fields in the same way that Flow does,
using caseless and Unicode-normalized equality.
Tweak variants which are produced from document locations automatically
drawn from the JSON Schema for /foo/bar
- foo_bar (joined with underscores)
- foobar (matches camelCase and TitleCase)
- "foo bar" (joined with spaces)
For top-level properties like /foo_bar, also allow these to
match "foo bar", where underscore components are joined with spaces.
Finally, in addition to "" also match "NULL", "null", and "nil" to JSON
null.
Issue #32
=> parser: refine projection field collation and variants

.github/workflows/ci.yaml
This has proved to be less reliable than initially hoped. Let's see how long the builds are now that they are parallelized. The job parallelism may prove to be fast enough in practice.
=> Remove Docker layer caching

parser/Cargo.lock, parser/src/config/mod.rs, parser/src/config/snapshots/parser__config__test__config_schema_is_generated.snap, parser/src/format/csv.rs, parser/src/format/mod.rs, parser/src/format/projection.rs, parser/src/lib.rs, parser/src/main.rs, parser/tests/csv_error_absorption_test.rs, parser/tests/happy_path_test.rs, parser/tests/testutil.rs
Adds the ability to configure an `errorThreshold` as part of the Parser's configuration. This allows it to be threaded through from the Capture's configuration within the Flow catalog. The Parser will absorb the parsing errors it encounters until the threshold is exceeded, at which point it returns all the errors it as seen thus far.
=> Skip Malformed CSV Rows

parser/src/config/csv.rs, parser/src/config/mod.rs, parser/src/config/snapshots/parser__config__test__config_schema_is_generated.snap, parser/src/format/csv.rs, parser/tests/csv_error_absorption_test.rs
The `errorThreshold` was previously defined at the top level of the
parser config, which made it seem like it would apply to all file types.
But it really only applies to csv files at the moment, and it's not
really clear that it even could be applied to many other file formats.
This could be confusing for users who set the top-level `errorThreshold`
and then wonder why their JSON file fails and doesn't respect the
threshold. This moves the `errorThreshold` under the character separated
configuration, so that it's clear that it only applies to that format.
This also renames the `line_ending` config to `lineEnding` to be
consistent with the rest of the naming.
=> Move parser errorThreshold under csv config

parser/Cargo.lock, parser/Cargo.toml, parser/run.go, parser/run_test.go, parser/src/format/mod.rs, parser/src/main.rs
Changes the code for invoking the parser from Go so that the parser logs
will be printed to the stderr of the connector. This allows the
logs from both the connector and the parser to appear in the logs
collections of captures.
This also updates the parser to log with flattened fields, so that log
the forwarded logs will look a little nicer in Flow.
=> Log all parser output to connector stderr

materialize-snowflake/snowflake.go
If the JSON schema specifies a string `format` of `"date-time"`, then
create a column with type `TIMESTAMP` in Snowflake materializations.
This is a minimal change to support only timestamps in snowflake.
Handling of additional string `format`s, and timestamps in other
databases, is being deferred until after we have some end-to-end testing
that can verify the behavior.
=> Materialize date-time strings as snowflake timestamps

.github/workflows/ci.yaml
This is a hackish copy-paste so now there are two build-push-action instances, but it's still the most elegant way I could figure out to express "always upload with the SHA tag (including for PRs), but only use 'dev' tag when `main` has a new build".
If the "push SHA-tagged version for PRs" behavior isn't intentional the two actions could be combined instead.
GitHub Actions are confusing and terrible though, so I have no idea if this will actually work.
=> connectors: push to ghcr.io with 'dev' tag

.github/workflows/ci.yaml, go.mod, go.sum, materialize-elasticsearch/.snapshots/TestDriverSpec, materialize-elasticsearch/Dockerfile, materialize-elasticsearch/driver.go, materialize-elasticsearch/driver_test.go, materialize-elasticsearch/elasticsearch.go, materialize-elasticsearch/schemabuilder/.snapshots/TestRunSchemaBuilder_NullOverrides, materialize-elasticsearch/schemabuilder/Cargo.lock, materialize-elasticsearch/schemabuilder/run.go, materialize-elasticsearch/schemabuilder/run_test.go, materialize-elasticsearch/schemabuilder/src/elastic_search_data_types.rs, materialize-elasticsearch/schemabuilder/src/elastic_search_schema_builder.rs, materialize-elasticsearch/schemabuilder/src/errors.rs
related issue: #57 
The PR creates the elastic search materialize connector.
The connector focuses on materializing raw flow documents into elastic search service.
The document schema of  elastic search is constructed from flow schema using the existing [schema builder](https://github.com/estuary/connectors/tree/main/materialize-elasticsearch/schemabuilder). 
Some TODOs of the work including 1. manual testing of the driver on different versions and managed services, and see the performances when data load is very heavy. 2. Add integration tests to it, which depends on the testing framework to be switched to work with the new Flow.
--- …
=> elasticsearch materialization connector

.github/workflows/ci.yaml, materialize-elasticsearch/.snapshots/TestDriverSpec, materialize-elasticsearch/driver.go, materialize-elasticsearch/schemabuilder/run.go, tests/materialize/datasets/duplicated-keys.jsonl, tests/materialize/datasets/ingest.go, tests/materialize/flow.json.template, tests/materialize/flowctl/build-and-activate.sh, tests/materialize/flowctl/combine.sh, tests/materialize/flowctl/delete.sh, tests/materialize/flowctl/temp-data-plane.sh, tests/materialize/materialize-elasticsearch/cleanup.sh, tests/materialize/materialize-elasticsearch/expected/duplicated-keys-delta.jsonl, tests/materialize/materialize-elasticsearch/expected/duplicated-keys-non-delta.jsonl, tests/materialize/materialize-elasticsearch/expected/multiple-data-types.jsonl, tests/materialize/materialize-elasticsearch/fetch-materialize-results.sh, tests/materialize/materialize-elasticsearch/ingest-data.sh, tests/materialize/materialize-elasticsearch/setup.sh, tests/materialize/materialize-s3-parquet/cleanup.sh, tests/materialize/materialize-s3-parquet/fetch-materialize-results.sh, tests/materialize/materialize-s3-parquet/ingest-data.sh, tests/materialize/materialize-s3-parquet/setup.sh, tests/materialize/run.sh
The PR improved the materialization elastic search connector.
1. it exports the descriptions of the connect specifications in the spec responses.
2. it adds integration tests to it. As the ingest to flow mechanism has been changed recently, the change also involves changes to the materialization testing infrastructure, and the existing integration test for `s3-parquet.`
The changes are structured roughly in a sequence of commits.
- `data ingest script` adds a new script to ingest data to Flow captures via `Push` mechnism.
- `test infra change and s3-parquet` changes the testing infrastructure to use the new ingest script and switched the existing test to work with the new infra.
- `elasticsearch tests` adds the integration test for elastic search.
- `hook with github workflow` enables the …
=> Improvements to Materializations ElasticSearch

materialize-bigquery/bigquery.go
Adds another case to the BigQuery SQL generator so that date-formatted strings (`{"type": "string", "format": "date"}`) will be translated to the BigQuery `DATE` type rather than `STRING`.
Specify `"format": "date"` in your JSON schema.
None
=> materialize-bigquery: Add support for 'date' formatted strings

go.mod, go.sum, materialize-bigquery/binding.go, materialize-bigquery/transactor.go
Subsequent to https://github.com/estuary/protocols/pull/22 (which relaxes the requirement so that a binding for the root document is only `RECOMMENDED` in delta-updates mode), we still need to modify the actual connectors to work with this configuration.
This PR tweaks the BigQuery materialization so that it doesn't assume the existence of a binding for the root document when in
delta-updates mode.
Once this all works, a catalog entry like:
```yaml
materializations:
wgd/example/to-bigquery:
endpoint:
connector:
image: ghcr.io/estuary/materialize-bigquery:dev
config: wgd-materialize-bigquery.config.yaml
bindings:
- source: wgd/example/data
resource: 
table: "example_table"
delta_updates: true
fields:
recommended: true
exclude: ["flow_document"]
``` …
=> materialize-bigquery: Don't assume the root document exists

materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go
This change adds a new `billing_project_id` configuration parameter (optional, defaults to `project_id` if unset) which will be given to BigQuery (via `bigquery.NewClient`) for billing purposes.
However once we do this, all queries will "conveniently" use that project ID as the default for their own name resolution. To fix that and make the two concepts properly decoupled I had to change a couple places where table names are assembled from "dataset.table" to a fully-qualified "project_id.dataset.table".
I have verified that this works well enough to get through the previously-failing validation step during a catalog build, but haven't tried running the full catalog with this change yet.
Specify `billing_project_id` in a BigQuery materialization config.
=> materialize-bigquery: Allow setting billing_project_id separately

materialize-bigquery/bigquery.go
Allow hyphens to occur in table identifiers. Otherwise `project-name.dataset.table` gets sanitized to `project_name.dataset.table` and merge queries fail because that doesn't exist.
=> materialize-bigquery: Don't sanitize hyphens, they're allowed

source-mysql/docker-compose.yaml, source-mysql/docker-entrypoint-initdb.d/init-user-db.sh
Using `source-mysql/docker-compose.yaml` should ideally result in a test DB set up automatically so that the `source-mysql` unit tests will pass without further manual tweaking.
```
$ cd connectors/source-mysql
$ docker-compose rm
$ docker volume rm source-mysql_myqsl_data
$ docker-compose up
$ go test -v
```
=> source-mysql: Set up test DB user, watermarks table, etc

.github/workflows/ci.yaml, tests/source-mysql/setup.sh
Adds the `source-mysql` connector to the CI build matrix and integration test. This should mean both that changes to `source-mysql` will actually be tested on new PRs going forward, and also that `ghcr.io/estuary/source-mysql:dev` will actually work to run the CI-built connector.
=> source-mysql: Add to the CI build matrix

network-proxy-service/sshforwarding/test_sshd_configs/docker-compose.yaml
A quick fix to make the build green. More work is needed to understand the exact reason that fails the SSH test in CI.
=> pin down openssh-server docker image version

source-mysql/main.go, source-postgres/fdbutils.go, source-postgres/fdbutils_test.go, source-postgres/main.go, sqlcapture/capture.go, sqlcapture/interface.go, sqlcapture/resultset.go, sqlcapture/tests/tests.go, sqlcapture/tuples.go
Per discussions, adding the logic to transform the numeric fields in keys in to a tuple, to make sure 1. the tuple conforms to the FoundationDB tuple format. 2. The fdb-encoded byte slice preserve the order of the original numeric value.
**Documentation links affected:*
=> encode pgtype.numeric ids

source-mysql/replication.go
When connecting to a read replica where `log_bin = OFF` the query `SHOW MASTER STATUS` will return an empty result set (but no error), which currently panics the connector.
This setup won't actually work, so it's correct to fail here, but the failure should be clean, with an error message that suggests the solution.
=> source-mysql: Fail cleanly when `SHOW MASTER STATUS` is empty

source-kinesis/README.md, source-kinesis/connection.go
Just adds a readme, and sets the AWS credential fields to `secret`.
**Workflow steps:** n/a
**Documentation links affected:** nope
**Notes for reviewers:** nope
=> Add Kinesis readme, specify AWS credentials as secret

source-mysql/replication.go
This event appears to be related to binlog segment rotation, and is used to establish an understanding of "what came before" a given file. Since we're not currently using/supporting GTID-based cursors, it is safe to ignore these events.
This change is untested (other than verifying that it doesn't break any existing test cases), because it would take nontrivial work to trigger binlog segment rotation and the fix itself is simple enough that it didn't seem worth the effort to set that up.
=> source-mysql: Ignore PreviousGTIDsEvent

materialize-rockset/driver.go, materialize-rockset/driver_test.go
Rockset allows underscores, but our validation regex was disallowing
them. This just updates the validation regex to match underscores.
**Workflow steps:** n/a
**Documentation links affected:** n/a
**Notes for reviewers:** n/a
=> Allow underscores in Rockset names

go.mod, go.sum, source-mysql/main.go, source-mysql/replication.go, sqlcapture/capture.go
The go-mysql library uses a separate logging framework, with some pretty
terrible defaults. This adds explicit configuration of that logger so
that it logs to stderr instead of stdout, and so that the log level
matches the level that's used by logrus.
Also adds a few log statements to aid in debugging.
**Workflow steps:** n/a
**Documentation links affected:** n/a
**Notes for reviewers:** n/a
=> Various logging improvements to source-mysql

source-hello-world/main.go, source-kafka/src/configuration.rs, source-kafka/tests/it/snapshots/it__spec_test.snap
Schemars will render "title" attributes if you use a Markdown heading in the doc comment. This should make it easier to render UI for some of these elements.
N/A
N/A
The snapshot of the spec output is probably the main thing to look at. Otherwise it's just tweaking comments.
=> Add titles to generated Kafka spec schema

.github/workflows/ci.yaml, materialize-bigquery/Dockerfile, materialize-postgres/Dockerfile, materialize-snowflake/Dockerfile, network-proxy-service/networkproxy.go, network-proxy-service/networkproxy_test.go, network-proxy-service/sshforwarding/sshforwarding.go, network-proxy-service/sshforwarding/sshforwarding_test.go, network-proxy-service/testutil.go, tests/materialize/run.sh, tests/run.sh, tests/source-postgres/setup.sh
Switch the source-postgresql connector to work with the new network-connector API.
Two small fixes are made to enable the tests working again, detailed in the PR comments.
The SSH config in this doc(https://github.com/estuary/flow/blob/master/site/docs/concepts/connectors.md) and related needs to be updated, in which
- rename `sshUser` to `user`,
- rename `remoteHost` to `forwardHost`
- rename `remotePort` to `forwardPort`
- rename `sshPrivateKeyBase64` to `privateKey`, and the content of the field no longer need to be `based64-encoded`. It should be the plain-text of multi-line private key formatted in `yaml`. …
=> sshproxy naming change

source-postgres/datatype_test.go, source-postgres/discovery.go
This fixes https://github.com/estuary/connectors/issues/54
PostgreSQL array types are inherently multidimensional, and according to the documentation:
> [The] current implementation ignores any supplied array size limits, i.e., the behavior is the same as for arrays of unspecified length.
> 
> The current implementation does not enforce the declared number of dimensions either. Arrays of a particular element type are all considered to be of the same type, regardless of size or number of dimensions. So, declaring the array size or number of dimensions in CREATE TABLE is simply documentation; it does not affect run-time behavior.
This means that however we translate array values will need to handle varying sizes and dimensionality on a per-row basis. There are basically …
=> source-postgres: Add support for array types

filesource/filesource.go
Without the json-field annotation, the `Data` field in the struct `State`  of `filesource.go`  is serialized as `Data` with capitalized `D`. This is inconsistent with the [specification](https://github.com/estuary/flow/blob/master/go/protocols/airbyte/catalog.go#L199) in the protocol, which requires an uninitialized `d`.    
Go  is flexible to handle the inconsistency during deserialization, but Rust has more strict checking imposed, and the work to allow `case_insensitive` checking is still [on-going](https://github.com/serde-rs/serde/pull/1902). So it might be easier to fix the json annotation here, unless there is any other considerations.
(list any …
=> adding json annotation

.github/workflows/ci.yaml
See https://github.com/google-github-actions/setup-gcloud/issues/539
GitHub workflows are complaining and failing at the moment because of this: https://github.com/estuary/connectors/runs/5642539364?check_suite_focus=true#step:6:17
=> github workflows: fix gcloud branch pinning to @v0

materialize-firebolt/schemalate/run.go, materialize-firebolt/transactor.go
- ~Allows for document keys with `/` to be stored by replacing the `/` with `_` to be compatible with Firebolt~
- In case of JSON objects, marshals them into a string and then stores them as a string to compensate for Firebolt's lack of support for actual JSON objects
See the other PR https://github.com/estuary/flow/pull/423
N/A
See the other PR https://github.com/estuary/flow/pull/423
=> materialize-firebolt: store JSON as marshalled string, allow nested keys

materialize-firebolt/transactor.go
- Changes the way the files are uploaded to use pipes instead of `append(bytes)`
- See the discussion [here](https://github.com/estuary/connectors/pull/146#discussion_r834665869) for the motivation behind this PR
N/A
N/A
See https://github.com/estuary/connectors/pull/146#discussion_r834665869
=> firebolt: upload files using pipes instead of bytes

materialize-postgres/sqlgen.go, materialize-postgres/sqlgen_test.go
- If a field is `format: date-time` but also nullable, our current code panics
- Also adding a better error which helps with troubleshooting
N/A
N/A
N/A
=> materialize-postgres: check for nil in date-time conversion

materialize-postgres/sqlgen.go, materialize-postgres/sqlgen_test.go
- PostgreSQL can handle ISO8601 datetimes itself, so we can instead of parsing the datetime ourselves, just pass it in directly with type: `TIMESTAMPZ` and let postgres handle the conversion.
Solves #184 
- Use `format: date-time` on a date-time value formatted as ISO8601
N/A
=> materialize-postgres: do not convert timestamp values, insert as is

source-mysql/main.go, source-postgres/main.go
Adds the field `.spec.connectionSpecification.title` to the `spec` subcommand output for `source-postgres` and `source-mysql`, since apparently that's being used for something in the UI.
This should fix https://github.com/estuary/connectors/issues/186
=> source-{mysql,postgres}: Add 'title' field to specs

.github/workflows/ci.yaml, source-hello-world/main.go, source-test/Dockerfile, source-test/main.go
- I copied `source-hello-world` to `source-test` to have a source we can use for our internal testing by implementing weird behaviours in it
- Add an option to `source-test` which would allow us to skip the state message to test this end-to-end.
N/A
=> source-test: option to skip the state message

materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go
The UI depends on values provided to the connector to show information
and create the actual form.
Also made a change to the CredentialsJSON field to be a string instead of a byte[] slice because a byte slice would get encoded in JSONSchema differently that is incompatible with how flow deals with the data: https://github.com/invopop/jsonschema/blob/297bb072302c4423669838e04bb7705277e50224/reflect.go#L417-L419
I believe the changes here are backward compatible since string and byte slice can be cast to each type in any direction.
This should fix some issues with the UI showing an error message trying to get test the BQ materialization:
```json
{
"error": "SchemaBuild",
"description": "failed to build json schema: at keyword 'media' of schema …
```
=> BigQuery: Add support for JSON Form

config_schema_guidelines.md
This is just some basic documentation related to connector endpoint
configuation schemas, and how they are rendered as forms in the UI.
=> Add docs on connector config schemas

materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go, materialize-bigquery/bigquery_test.go
JSONSchema needs to include some extra attributes to be presented to the
UI so the forms are properly built.
The added logic will have the test failed until
https://github.com/estuary/flow/pull/496 merges and the connector is
rebased to include the new version of the sqlDriver.
The reason for this is because the the DoNotReference needs to be enable
otherwise the test fails and the Schema is formulated in a different
way.
This should be a safe backward compatible fix.
Close #206
=> BigQuery: Add JSONSchema attribute in annotation for UI Form

source-mysql/main.go, source-postgres/main.go
Adds `"documentationUrl"` to the `spec` output for `source-mysql` and `source-postgres`.
=> source-{mysql,postgres}: Add 'DocumentationURL' to spec output

source-mysql/discovery.go
The MySQL connector will not discover tables in the system schemas `information_schema`, `mysql`, `performance_schema`,
or `sys`. This could be confusing to the user, especially since the lack of any 'default user schema' makes it kind of tempting to put tables in the 'mysql' schema if one doesn't know any better. Or it could happen by accident, if you just give `--database=mysql` to the MySQL CLI and then forget to `USE <schema>` or give a fully-qualified name.
For now let's do the simplest possible fix, and emit a warning when the discovery result is empty. After this change, running discovery on an empty MySQL instance gives the following output:
INFO[0000] initializing connector                        addr="207.148.12.34:3306" dbName=mysql serverID=1198288759 …
=> source-mysql: Warn about system schemas on empty discovery

materialize-firebolt/config.go, materialize-firebolt/firebolt/firebolt.go
- Mark `password` and `aws_secret` as secrets in JSONSchema
- Give a better error message in case of 503: make sure the engine is up and running
=> materialize-firebolt: mark config secrets in jsonschema

materialize-firebolt/config.go, materialize-firebolt/spec.go, materialize-firebolt/transactor.go
- If a `prefix` was given without a trailing slash, it would cause issues such as:
```
{"timestamp":"2022-05-12T18:55:50.509439286Z","level":"INFO","message":"invoke connector /connector/connector, [\\"apply-upsert\\"]"}
running external table creation query: response error code 500, Could not access the data source. Please make sure the engine and bucket are on the same AWS region.
```
- This will fix that case as it ensures there is a slash between the prefix and the spec filename. This is consistent with how we handle the prefix in other places of the connector. I also added a note to the JSON schema that the value must now be without a trailing slash.
(list …
=> materialize-firebolt: fix prefix without trailing slash causing issues

source-postgres/replication.go
Empirically this makes the connector more able to tolerate large spikes of changes without failing, and to recover better when the cursor LSN is very far behind the latest WAL entries.
However the exact reason that this *needs* to be so large is still unknown. Ideally the buffer should be unnecessary, the only reason it exists at all was to help keep the data rate smoother from the perspective of the source DB, and larger spikes should be handled just fine by ordinary TCP pushback to the walsender.
But in at least one scenario (Google Cloud SQL instance, being hammered at thousands of QPS using `sysbench-tpcc`, and captured by a connector with access via SSH forwarding) some part of that backpressure chain is breaking down and leading to persistent failures, so we should …
=> source-postgres: Increase replication event buffer size

source-kafka/src/configuration.rs, source-kafka/tests/it/snapshots/it__spec_test.snap, source-kafka/tests/test-config.json, tests/source-kafka/setup.sh
Explicitly spells out the schema, rather than relying on schema.rs to generate it. When schema.rs supports extension annotations, we can go back to using the generated schema. For now, we need to at least mark
the credentials as `secret: true`.
1. Update the Kafka connector_tag record to use this tag in Supabase.
2. Wait for the agent to finish updating the connector.
3. Create a new Capture.
4. Select Kafka source.
n/a
n/a
=> Improve Kafka Schema Even More

source-mysql/main.go
Just to make configuring `source-mysql` a bit more foolproof, it should accept a bare hostname (or IP address) and assume the `:3306` suffix if not otherwise specified.
Nothing changes except that you can omit the `:3306` suffix on the `"address"` property now.
=> source-mysql: Accept bare hostname/IPs without port number

.github/workflows/ci.yaml
- Publish images with a version _IF NOT ALREADY EXISTING_. This is important to avoid accidentally overriding the last version. Version must always be bumped if we want to publish a new version. The `dev` tag will continue to be overriden every time we push.
Run main branch github action
N/A
=> ci: push image with version if not already exists

materialize-google-sheets/main.go, materialize-google-sheets/util.go, materialize-google-sheets/util_test.go, tests/materialize/materialize-google-sheets/setup.sh
Switch to using a spreadsheet URL instead of a spreadsheet ID.
=> materialize-google-sheets: use spreadsheet URL and not ID

source-postgres/README.md, source-postgres/backfill.go, source-postgres/helpers_test.go, source-postgres/main.go, source-postgres/replication.go, tests/source-postgres/setup.sh
This PR moves several settings (watermarks table, replication slot, publication) into an 'Advanced' subsection, and merges the `host` and `port` properties into a single `address` field for simplicity. This should make creating PostgreSQL captures much more pleasant in the web UI.
Merging this will require a bit of care to not break existing captures, but to my knowledge there's only one of those that's really important to not break.
The names and locations of various configuration values have changed, but the actual information is the same.
I'll send out a PR for https://docs.estuary.dev/reference/Connectors/capture-connectors/PostgreSQL/ once this is merged.
=> source-postgres: Refactor configuration schema

source-mysql/main.go, source-postgres/main.go
In almost every case the user should be forced to fill this in, so having an incorrect default is just a bit of unnecessary friction.
=> source-{mysql,postgres}: Remove default address from spec

.github/workflows/ci.yaml, base-image/Dockerfile, materialize-bigquery/Dockerfile, materialize-elasticsearch/Dockerfile, materialize-firebolt/Dockerfile, materialize-google-sheets/Dockerfile, materialize-postgres/Dockerfile, materialize-rockset/Dockerfile, materialize-s3-parquet/Dockerfile, materialize-snowflake/Dockerfile, materialize-webhook/Dockerfile, source-gcs/Dockerfile, source-hello-world/Dockerfile, source-kafka/Dockerfile, source-kinesis/Dockerfile, source-mysql/Dockerfile, source-postgres/Dockerfile, source-s3/Dockerfile, source-test/Dockerfile
- Added a new `base-image` which sets up OpenSSH and nonroot user, and I'm using that as the base of runtime stage for all other connector images.
=> materialize-postgres: use debian image and install openssh

source-hello-world/main.go, source-test/main.go
- Add an option to make the source fail after sending N messages
=> source-test: add option to fail after N messages

source-mysql/replication.go
Most simple operations don't produce these, but it's been observed at least once and they should be ignored rather than halting the capture.
=> source-mysql: Ignore 'COMMIT' query events in the binlog

source-mysql/main.go, source-mysql/replication.go
This commit modifies `source-mysql` to use SSL for its connections to the MySQL database. I kind of figured that was the default, but apparently not.
This is done for both the normal/backfill connection and the replication connection. I'm not sure if there needs to be some sort of fallback to not-SSL if SSL connections fail, but my inclination is to just require SSL if possible, and if we see that approach failing in the future we can add fallback logic.
Currently the 'InsecureSkipVerify' TLS configuration is set to true, which means that there's no specific server name which the
SSL certificate is required to match. This means that an active MitM could theoretically intercept the connection (which is why it's called "Insecure" in the option name), but in many cases (such …
=> source-mysql: Use SSL when connecting to MySQL

.github/workflows/ci.yaml
This is to be consistent with the rest of Flow, which now ascribes
special meaning to the image tag `:local`.
This came from discussion on estuary/animated-carnival#29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/279)
=> Use :local tag for testing connectors

source-test/main.go
- Adds auth_specification to source-test for google OAuth2
- To be tested with https://github.com/estuary/flow/pull/570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/281)
=> source-test: add authSpec for google

filesource/discovery.go, filesource/filesource.go, go.mod, go.sum, schema_inference/inference.go, source-gcs/Dockerfile, source-http-file/Dockerfile, source-kinesis/Dockerfile, source-kinesis/discovery.go, source-kinesis/main.go, source-s3/Dockerfile, tests/run.sh, tests/source-gcs/bindings.json, tests/source-gcs/setup.sh, tests/source-kinesis/bindings.json, tests/source-kinesis/setup.sh, tests/source-s3/setup.sh
Kinesis, S3, and GCS do not provide any facilities to introspect on the data in its streams/files. This leads to a lackluster user experience, as the discovered bindings all have an empty json schema. This means to get the most value out of Flow, the user needs to author a json schema from scratch. This is less than ideal.
Instead, we'll have these connectors use the `flow-schema-inference` tool to generate simple schemas from the data we read from the streams themselves. Not all of these will be maximally useful, but it's a great start for a user just trying the system. A more advanced user can always edit these schemas with more useful annotations.
**Workflow steps:** (Kinesis example)
1. Login to the AWS CLI.
1. Create a Kinesis stream
1. Seed that stream with some …
=> Add Schema Inference to Kinesis, S3, and GCS Connectors

materialize-elasticsearch/.snapshots/TestDriverSpec, materialize-elasticsearch/driver.go
- Field overrides are not actually required, they can be omitted
- `flowctl api spec --image ghcr.io/estuary/materialize-elasticsearch` and this field should no longer be required.
See: https://github.com/estuary/flow/pull/588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/290)
=> materialize-elasticsearch: mark field overrides as optional

flowsim/testcat/testcat.go, materialize-google-sheets/Dockerfile, materialize-rockset/README.md, materialize-s3-parquet/Dockerfile, materialize-webhook/Dockerfile, source-kafka/README.md, sqlcapture/discovery.go, tests/materialize/flowctl-admin/build-and-activate.sh, tests/materialize/flowctl-admin/combine.sh, tests/materialize/flowctl-admin/delete.sh, tests/materialize/flowctl-admin/temp-data-plane.sh, tests/materialize/run.sh, tests/run.sh, testsupport/build_catalog.go
We recently split out a new `flowctl` tool which interacts with the control plane, rather than the data plane directly. Instead, the old `flowctl` was renamed `flowctl-admin`. This updates the connector tests and docs to use `flowctl-admin` as it still contains the commands and behavior they expect.
--- …
=> Update references `flowctl` -> `flowctl-admin`

filesource/discovery.go
Try increasing the maximum number of documents that we use for schema inference, to hopefully result in more accurate schemas.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/302)
=> increase schema inference sampling limit to 40k

source-postgres/helpers_test.go, source-postgres/main.go, source-postgres/replication.go
In the absence of this setting the connection will keep trying indefinitely, which in practice means "until the OS TCP connect timeout expires after 4 minutes". This in turn means that even when the target database is completely unreachable and Flow is running the connector in a crash loop, the majority of the time it will look like it's "working" in the UI because the most recent connector run has not yet failed.
I suspect 30 seconds is plenty of time for any non-pathological database setup to connect (and supporting this assertion: the MySQL client-library has a hard-coded 10s deadline already), but this could be made configurable if it ever becomes an issue.
--- …
=> source-postgres: Timeout DB connection after 30 seconds

filesource/filesource.go, source-gcs/main.go, source-http-file/main.go, source-s3/main.go
The filesource library uses an upper bound on the `Last-Modified`
timestamp during each sweep. This prevented the source-http-file
connector from ingesting files that are updated very frequently because
the `Last-Modified` timestamp would end up falling outside of the
`maxBound`. Additionally, the failure scenario that the `maxBound` is
meant to address in the first place isn't possible with source-http-file
since it only ever ingests a single file.
This commit updates `filesource.Source` to include the delta that's
applied to the current time in order to determine the `maxBound` for
each sweep. This lets source-s3 and source-gcs retain the existing
behavior, while allowing source-http-file to use a positive value so
that frequently updated files can be captured. …
=> source-http-file uses a maxBound in the future

filesource/discovery.go, filesource/filesource.go, go.mod, go.sum, materialize-bigquery/.snapshots/TestSpecification, materialize-postgres/.snapshots/TestSpecification, materialize-snowflake/.snapshots/TestSpecification, source-http-file/main.go
Make `filesource` connector discover work _better_, though still not _great_.
source-http-file supports unbounded real-time streams, such as wikipedia recent changes.
* (Optional) Use the new "Headers" tab of source-http-file to provide additional headers to be sent with the request.
* Start using source-http-file with streaming data sources, like wikimedia's recent changes, that previously did not work.
- - - …
=> filesource schema discovery & source-http-file streaming

go.sum, source-mysql/backfill.go, source-mysql/main_test.go, source-mysql/throughput_test.go, source-postgres/backfill.go, source-postgres/capture_test.go, source-postgres/discovery.go, source-postgres/helpers_test.go, source-postgres/throughput_test.go, sqlcapture/capture.go, sqlcapture/resultset.go, sqlcapture/tests/helpers.go, sqlcapture/tests/interface.go, sqlcapture/tests/tests.go
This PR adds `go test`-able benchmarks `BenchmarkBackfill` and `BenchmarkReplication` to `source-postgres` and `source-mysql`. These benchmarks take care of initializing the test database with a bunch of rows of synthetic data and then time a capture of that data. They do their best to exclude all of the necessary setup and teardown work from the actual benchmark timing, so that the reported `ns/op` measurements should accurately reflect the marginal cost of capturing a certain amount of data. See "Workflow steps" for more details on how to run those.
In addition, this PR includes several changes motivated by running these benchmarks in a setup with significant (~45ms) DB<->Capture latency:
- Optimizes the `source-postgres` handling of column descriptions during …
=> SQL capture benchmarks and some throughput improvements

build-local.sh, schema_inference/inference.go, source-boilerplate/boilerplate.go, source-firestore/Dockerfile, source-firestore/apply.go, source-firestore/discovery.go, source-firestore/helpers.go, source-firestore/main.go, source-firestore/pull.go, source-firestore/validate.go, source-nativehello/Dockerfile, source-nativehello/main.go
- Support nested collectons for source-firestore by discovering them using a wildcard notation:
```
captures:
acmeCo/source-firestore:
endpoint:
connector:
image: source-firestore:local
config: source-firestore.config.yaml
bindings:
- resource:
path: orgs/*/runs/*/runResults/*/queryResults
target: acmeCo/orgs_runs_runResults_queryResults
- resource:
path: orgs/*/runs/*/runResults
target: acmeCo/orgs_runs_runResults
- resource:
path: orgs/*/runs
target: acmeCo/orgs_runs
- resource:
path: orgs
target: acmeCo/orgs
```
- I realised while working on this PR that actually it is not possible for us to not fully scan Firestore whenever we boot up. The process of listening on changes of a query always includes a copy of all documents upfront: …
=> source-firestore: support nested collections, use flow protocol

materialize-boilerplate/boilerplate.go, materialize-boilerplate/boilerplate_test.go, source-boilerplate/boilerplate.go, source-boilerplate/boilerplate_test.go
Previously the check was for `io.ErrShortBuffer`, which is not actually the error we get when the incoming message is too large for the buffered reader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/325)
=> boilerplate: Check for bufio.ErrBufferFull correctly

source-firestore/discovery.go
With this change discovery on a realistic dataset takes about 8x longer (going from 15s to 2m), but is also much more likely to encounter rare nested sub-collections.
This commit also adds calls to `docs.Stop()` to tell the Firestore client when we're done with a particular DocumentIterator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/328)
=> source-firestore: Tweak discovery limit constants

source-postgres/backfill.go, source-postgres/capture_test.go, source-postgres/testdata/TestTrickyColumnNames_backfill.snapshot, source-postgres/testdata/TestTrickyColumnNames_discovery_a.snapshot, source-postgres/testdata/TestTrickyColumnNames_discovery_b.snapshot, source-postgres/testdata/TestTrickyColumnNames_replication.snapshot
This change adds a test of several difficult column names which require quoting in PostgreSQL:
* A primary key column named `table`, which is a reserved word and thus an error if not quoted.
* A primary key column named `Meta/"wtf"/ID`, which contains two different special characters (and double quotes in particular, which require special handling) as well as capital letters.
The tricky column names are made primary keys, because we need to be able to give them *back* to Postgres when performing backfill queries, but the test also exercises discovery, and captures via backfill and replication, just to make sure the names are handled correctly throughout the capture.
This should fix https://github.com/estuary/connectors/issues/314
Column names …
=> source-postgres: Quote all column names in backfill queries

source-firestore/discovery.go
Previously this was `/__name__`, which is basically just the final path element and thus is frequently something like `27` which is not unique, and this caused the obvious sorts of issues now that the whole nested collections thing is live.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/329)
=> source-firestore: The discovered key should be /__path__

materialize-google-sheets/main.go, materialize-google-sheets/util.go
This PR tweaks the startup behavior of the Google Sheets materialization in ways that I think make it more user-friendly, and in the process fixes the issues that led to materializations crashing when run with >26 fields or when they reached >1000 rows.
The row count limit was a weird one, because our use of `InsertRange` requests in the transactor _should have_ resulted in every new output row adding itself to the sheet. But in practice there's some trickery going on, and somehow it's still possible to hit row count limits when appending a new row to the very end of a full sheet. To fix this, we now maintain a "sentinel" row after all our data rows, identified by the value `{}` in the `flow_document` column.
The column limit was much simpler: by default a sheet has 26 …
=> materialize-google-sheets: Fix row/column limitations

materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/snowflake.go
This fixes the issues seen in #334 when materializing into snowflake on AWS providers. The host for AWS providers is not consistently any combination of account/region/provider for AWS (see [list](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#non-vps-account-locator-formats-by-cloud-platform-and-region)), so we can't reliably build a URL just from those values.
Fortunately, the snowflake client allows explicitly specifying a "host" value, which bypasses all of the idiosyncrasies of building the host from account/region/provider. This also allows for connecting with the [preferred account identifier format](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#format-1-preferred-account-name-in-your-organization), which uses the …
=> materialize-snowflake: add host to config & remove region

filesource/state_test.go
This unit test shows that files do not get re-processed by the filesource state machine when sweeps are alternatively completed in monotonic and non-monotonic modes. Although the `MinBound` is not updated when finishing a sweep in monotonic mode, the `Path` is tracked which results in lexicographically "older" files being skipped. In non-monotonic mode, the `MinBound` is updated when finishing a sweep which precludes files older than what has already been seen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/337)
=> filesource: add test for switching between monotonic and non-monotonic sweeps

materialize-google-pubsub/.snapshots/TestSpec, materialize-google-pubsub/driver.go, materialize-google-pubsub/transactor.go
Related to https://github.com/estuary/flow/issues/673, specific to the PubSub materialization
Adds an additional optional field `identifier` to the resource config. This allows for configurations that can materialize multiple collections into the same topic. The `ResourcePath` for each binding must be unique, and providing unique `identifier`s per resource allows for `ResourcePath`s like `mytopic.identifier1`, `mytopic.identifier2` etc.
Configurations like this will now be possible, where two collections are materialized into the same PubSub topic:
```yaml
materializations:
bobCo/multi-pubsub:
endpoint:
connector:
image: "materialize-google-pubsub:local"
config: ../flow/pubsub.config.yaml
bindings:
- resource:
identifier: one
topic: multiplex-topic …
```
=> materialize-google-pubsub: enable multiple bindings to multiplex on topics

source-s3/main.go
Uses the passed-in context for `source-s3` `(*s3Store).Read`. This way the retrieving of objects can respect context timeouts.
Most notably, there is a timeout specified for [schema discovery](https://github.com/estuary/connectors/blob/353d119f03a004c6777fae7df67ffdd5b8f33c22/filesource/discovery.go#L111-L119), and without this timeout, it is possible that a single extremely large file will take an excessive amount of time to process. …
=> source-s3: get object with context

go.mod, go.sum, source-mysql/backfill.go, source-mysql/datatype_test.go, source-mysql/discovery.go, source-mysql/replication.go, source-postgres/discovery.go, sqlcapture/interface.go
This change required some tweaks to the plumbing around column types. Previously the `DataType` of a column was represented as a string with values like `"int"` or `"text"`, but representing the possible values of an enum column required richer metadata. This was accomplished in a backwards-compatible way by turning the string into an `interface{}` value, and leaving the majority
of column types as a string. Thus the JSON-serialized type names included in state checkpoints are unchanged for other types.
Then a new `mysqlColumnType` struct was defined with an `EnumValues` array and a `Type` property. Currently this is only used for enum and set, but if any other types required richer metadata in the future the same struct can be extended. After deserializing table metadata …
=> source-mysql: Add support for ENUM and SET column types

source-s3/main.go
Closes https://github.com/estuary/connectors/issues/345
Threads the context through to the `source-s3` connector `List` operation. https://github.com/estuary/connectors/pull/344 accomplished the same thing for `Read`. This will allow for better handling of context cancellations or timeouts.
Should be minimal observable impact. This will eliminate the potential for very large and/or slow file listings to lock up schema discovery indefinitely.
N/A
I had initially thought this would take more work to get done, but it turned out to be pretty simple with the `filesource.ListingFunc` adapter already available. There wasn't much possible improvement I could see from refactoring the existing iterator …
=> source-s3: use context for file listing

schema_inference/inference.go
Closes https://github.com/estuary/connectors/issues/341
This fixes a race condition in handling the stdin/out pipes from running schema inference. It has been consistently causing the `source-kinesis` test to fail in an intermittent way. See [recent example](https://github.com/estuary/connectors/actions/runs/3094509636/jobs/5008268197).
Why is only the kinesis test failing? Apparently only `source-firestore` and `source-kinesis` use this code path, and `source-firestore` doesn't have an integration test that verifies bindings like the `source-kinesis` test. Although this change is primarily motivated by the desire to stop the test from flaking, I would imagine this could cause intermittent issues with discovery for both of these connectors in production.
The relevant line …
=> schema-inference: fix race condition

materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go, materialize-elasticsearch/.snapshots/TestDriverSpec, materialize-elasticsearch/driver.go, materialize-firebolt/.snapshots/TestDriverSpec, materialize-firebolt/config.go, materialize-firebolt/config_test.go, materialize-postgres/.snapshots/TestSpecification, materialize-postgres/driver.go, materialize-s3-parquet/.snapshots/TestS3ParquetDriverSpec, materialize-s3-parquet/driver.go, materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/snowflake.go, source-gcs/main.go, source-kinesis/connection.go, source-kinesis/main.go, source-mysql/main.go, source-postgres/main.go, source-s3/main.go
Closes https://github.com/estuary/connectors/issues/360
Adds ordering properties to fields in various connectors. The specific ordering is what seemed reasonable to me, and I'd be open to alternative suggestions. My general thought process for ordering things was to put them in this order:
1. Basic connection information, like a database URL
2. Authentication, in the form of user/password or service account credentials
3. The remaining connector configurations, ordered logically where possible, with "optional" fields generally coming last
The poster child for this algorithm is the configuration for the Postgres connector, which will appear in the order of:
```
address
user
password
database
```
The configs don't always map to that baseline perfectly, so I tried to get as …
=> better field ordering for connectors

tests/source-s3/cleanup.sh
Simple change to use the correct exported variable for the source-s3 end-to-end test bucket name, so that it gets correctly cleaned up.
- - - …
=> source-s3: fix bucket cleanup

.github/workflows/ci.yaml, tests/materialize/datasets/ingest.go, tests/materialize/materialize-elasticsearch/ingest-data.sh, tests/materialize/materialize-google-sheets/fetch-materialize-results.sh, tests/materialize/materialize-google-sheets/ingest-data.sh, tests/materialize/materialize-postgres-rc/ingest-data.sh, tests/materialize/materialize-s3-parquet/ingest-data.sh, tests/materialize/run.sh, tests/run.sh
Some adjustments to the end-to-end tests that allow them to more easily be run on non-linux systems (mac):
- Instead of the test script itself specifically downloading `flow` binaries, the test environment must make them available on `$PATH`. As long as the runner has `flowctl-admin` via `$PATH`, the tests can be run.
- The materialization tests were adjusted to use the `flow` binaries directly instead of running the temp data plane inside of container. This seemed to make things much simpler, and is consistent with how the capture tests run. I'm not 100% sure that the tests couldn't be run on mac with this docker container strategy, but I found it much easier to just run the binaries directly.
These tests should now be runnable on linux and mac, by …
=> improve end-to-end test compatibility

go-schema-gen/.snapshots/TestGenerateSchema, go-schema-gen/generate.go, go-schema-gen/generate_test.go
This will map our generated schema to use integer types for "order" fields. It is necessary because of the handling of "order" fields in flow: https://github.com/estuary/flow/blob/b2f26e1435f37a1cb7d71055381a1f8faf4d0940/crates/doc/src/annotation.rs#L65-L68
As part of merging this, I will also update the mirrored code in the flow repository: https://github.com/estuary/flow/blob/master/go/protocols/materialize/go-schema-gen/generate.go
`jsonschema_extras` can include values like `order=0` and have the generated schema correctly represent the order value as an integer.
N/A
- - - …
=> schema-gen: use integers for ordering values

go.mod, go.sum, materialize-rockset/driver_test.go, materialize-sql/type_mapping.go
Updates the pin for flow. One item of note is that the protocol field "user_provided" was renamed to "explicit" in https://github.com/estuary/flow/pull/672.
- - - …
=> go.mod: bump flow pin

schema_inference/inference.go, source-firestore/discovery.go
Downgrades several spammy `INFO` level logs during discovery to `DEBUG` level, including the ones that come from the schema inference package.
Also adds a new `INFO` level message at the end of discovery to positively confirm when it terminates successfully.
Nothing changes, except that in the case of failures we might actually get to see the error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/373)
=> source-firestore: Logging tweaks

source-firestore/discovery.go, source-firestore/helpers.go
This adds a check for "retryable" status code errors when discovery fetches documents from Firestore, and retries them using a very simple exponential-backoff+jitter strategy up to a maximum of 5 retries. Hopefully this makes discovery a lot more robust.
This **doesn't** add retrying to the subcollection-checking part of discovery, or to the actual pull operation, but I expect to add at least the pull RPC retries in the near future.
Also I haven't tested the new backoff code to make sure it works as intended, although I have run the existing test suite and verified that it doesn't obviously break things.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors …
=> source-firestore: Retry temporary failures during discovery

source-firestore/discovery.go
Adding a bit of retry logic seemed to help a little, but we're still seeing discovery fail half the time. The maximum backoff after 5 retries was only 1.6s though, so let's try just making the number bigger.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/375)
=> source-firestore: Increase discovery retries from 5 to 9

source-firestore/pull.go
The Firestore data model is not quite JSON (for instance it has distinct types for timestamps, document references, and lat/long points), so we already do some conversion before serializing to JSON for output.
It turns out there's another subtle difference: Firestore documents can contain NaN floats, but NaN isn't a valid JSON value. In order to avoid losing data we just convert it into the string `"NaN"` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/379)
=> source-firestore: Translate NaNs to the string "NaN"

materialize-postgres/.snapshots/TestSpecification, materialize-postgres/Dockerfile, materialize-postgres/driver.go
- Add standalone network-tunnel to `materialize-postgres`
```
address: "999.290.265.259:5432"
database: "postgres"
networkTunnel:
sshForwarding:
privateKey: <YOUR KEY>
sshEndpoint: "ssh://user@endpoint"
password: "password"
user: "postgres"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connecto …
=> materialize-postgres: use standalone network-tunnel

source-boilerplate/boilerplate.go
This is a reduced version of https://github.com/estuary/connectors/pull/388 with everything not absolutely required to fix the immediate `source-firestore` breakage trimmed out so that I feel confident merging it without review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/389)
=> source-boilerplate: Minimal change to ignore log.level flag

materialize-s3-parquet/parquet_file_processor.go
When a new binding is added to an already-running s3-parquet materialization, we may have cases where the checkpoint's `nextSeqNumList` is shorter than the binding list of the new RPCs. In these cases we can just set `nextSeqNumList` of these additional bindings to start at 0.
This is based on my understanding of [this comment](https://github.com/estuary/connectors/blob/main/materialize-s3-parquet/checkpoint/driver_checkpoint.go#L12-L16) about `NextSeqNumList`:
```
// The sequence number used to name the next files to be uploaded to the cloud.
// To be specific, the next parquet file from the i-th binding is named using the deterministic pattern of
// "<KeyBegin>_<KeyEnd>_<NextSeqNumList[i]>.parquet".
// The NextSeqNumList[i] is increased by 1 after each successful upload …
```
=> materialize-s3-parquet: avoid index out of bound errors

materialize-bigquery/Dockerfile, materialize-boilerplate/boilerplate.go, materialize-elasticsearch/Dockerfile, materialize-firebolt/Dockerfile, materialize-google-pubsub/Dockerfile, materialize-google-sheets/Dockerfile, materialize-postgres-rc/Dockerfile, materialize-postgres/Dockerfile, materialize-rockset/Dockerfile, materialize-s3-parquet/Dockerfile, materialize-snowflake/Dockerfile, materialize-webhook/Dockerfile, source-boilerplate/boilerplate.go, source-firestore/Dockerfile, source-gcs/Dockerfile, source-hello-world/Dockerfile, source-http-file/Dockerfile, source-kinesis/Dockerfile, source-mysql/Dockerfile, source-nativehello/Dockerfile, source-postgres/Dockerfile, source-s3/Dockerfile, tests/source-gcs/bindings.json, tests/source-kinesis/bindings.json
This commit removes the `FLOW_TCP_PORT=2222` label from all Dockerfiles, removes the bit of code that opened a TCP port from source-boilerplate and materialize-boilerplate, and instead goes back to using os.Stdin and os.Stdout for those.
Unfortunately the logic changes to the boilerplate packages have to be made for all connectors at once, so this change has a fairly large blast radius if something is overlooked, but I don't think that can be helped.
In theory everything keeps working, and some of the current connector breakage is fixed for the moment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/396)
=> Revert TCP connectors back to stdio

materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go
Allows for service account credentials for `materialize-bigquery` to be provided as non-base64 encoded JSON, which is consistent with how all the other google cloud (etc.) connectors work. The spec descriptions are updated to indicate that the credentials don't need to be base64 encoded.
I made this change backwards compatible so that we don't need to bump the version of the connector for this. It will continue to work with base64 encoded JSON, but the spec & docs should direct users to create materializations with unencoded JSON.
Closes https://github.com/estuary/connectors/issues/401
A bigquery materialization can be created or updated with either base64 encoded JSON, or regular JSON. This also works when adding the JSON file to the config via the …
=> materialize-bigquery: support non-base64 credentials

source-gcs/Dockerfile, source-hello-world/Dockerfile, source-http-file/Dockerfile, source-kafka/Dockerfile, source-kinesis/Dockerfile, source-mysql/Dockerfile, source-postgres/Dockerfile, source-s3/Dockerfile, source-test/Dockerfile, tests/source-gcs/bindings.json, tests/source-kinesis/bindings.json
- Switches connectors that use airbyte protocol to use latest version of airbyte-to-flow which communicates over stdio
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/405)
=> source-*: switch airbyte protocol connectors to use airbyte-to-flow

source-firestore/.snapshots/TestDiscovery, source-firestore/discovery.go
I thought this had been fixed previously, but apparently we're still generating collection schemas which forbid additional properties of the `/_meta` object, which then immediately breaks because Flow adds `/_meta/uuid`.
Doing a simple "create capture via discovery then materialize it" setup in the UI should actually work without any manual schema editing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/407)
=> source-firestore: Stop setting `additionalProperties: false`

source-firestore/discovery.go
This is the *fourth* rewrite of Firestore discovery, and I'm really hoping it will be the last one. The new logic keeps the decently high throughput of the previous attempt (currently it peaks at 16MBps running on my laptop) but applies harder limits to the number of documents fetched.
The new approach is roughly:
- Separate 'scan workers' and 'inference workers' into separate errgroups. This allows the shutdown logic to be made a bit more centralized at the top level: first wait until all scanners are done, then close all inference channels, then wait until all inference workers are done. And doing that means that we can be a bit more disorganized about spawning workers as described in the next bullet.
- Spawn a 'scan worker' for each distinct *collection* we observe, …
=> source-firestore: Limit amount of data fetched during discovery

source-firestore/.snapshots/TestSpec, source-firestore/main.go
Provides enum options for the `backfillMode` resource property, and tweaks the description to be a bit more user-friendly.
This fixes https://github.com/estuary/connectors/issues/408
The resource editing part of the "Create a Capture" flow in the UI should be a bit friendlier now.
I added go.estuary.dev/source-firestore pointing to https://docs.estuary.dev/reference/Connectors/capture-connectors/google-firestore/
We need to update the docs sometime soon to describe the current state of the connector. At a minimum that means describing the `backfillMode` setting, but it might be good to have some discussion of how the Firestore data model maps to Flow collections, like what I wrote in [the …
=> source-firestore: Provide enum options for `backfillMode`

go.mod, go.sum
This picks up the recent protocols/airbyte change which allows the `--log.level` flag to occur at any position in the command line (https://github.com/estuary/flow/pull/780).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/412)
=> go.mod: Upgrade Flow dependency to latest

source-mysql/discovery.go
Somebody (who might be past me) left this log message at `INFO` level, which means that we're getting one spam message per enum value translated. For a table using enums this means at least one message per row, and that's terrible.
Downgrade it to `TRACE` level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/416)
=> source-mysql: Downgrade spammy log message from INFO to TRACE

source-mysql/backfill.go, source-mysql/main.go, source-mysql/main_test.go, source-mysql/testdata/TestConfigSchema.snapshot
There's a plausible argument and some (very limited) evidence that large chunk sizes could have an adverse performance impact on the target database, especially if individual rows are large. This change adds a new advanced property to control the number of rows per backfill chunk directly, defaulting to the current setting of 131,072 if unspecified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/417)
=> source-mysql: Allow adjusting backfill chunk size

materialize-boilerplate/boilerplate.go, source-boilerplate/boilerplate.go
This commit adds support for specifying log level and format in the same way as our Airbyte captures and various other portions of the Flow codebase work. This lack is currently breaking `source-firestore` after some of the recent "connect over TCP" and "don't put the connector proxy in the execution path" changes caused it to get run directly with a `--log.level` argument.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/388)
=> {source,materialize}-boilerplate: Support log.level and log.format

source-mysql/backfill.go, sqlcapture/resultset.go
Adds a couple more debug log messages. We're observing one backfill in production which appears to hang for **a very very long time** on each backfill query, and it would be useful to know for certain that the query itself is the part taking all that time (as opposed to the result value processing).
And happily, now that the final couple of "make log levels work" PRs have landed, we can actually turn on debug logging in production via `flowctl-admin shards edit`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/420)
=> source-mysql: Add a couple of debug log messages

source-mysql/backfill.go, source-mysql/main.go, source-postgres/backfill.go, source-postgres/main.go
Once per connector restart (per backfilling table), before actually running the backfill query we ask the database to EXPLAIN the query and then log the response.
This should help us diagnose some conditions where backfill queries aren't performing as expected. Any errors which occur during the EXPLAIN process will be logged but not treated as fatal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/421)
=> source-{mysql,postgres}: EXPLAIN backfill queries and log result

source-firestore/.snapshots/TestSpec, source-firestore/main.go, source-firestore/pull.go
This is vaguely analagous to how we've used path regexes on filesource captures in the past, as a mechanism for kicking a malfunctioning capture back into the state we need it to be in.
In this particular case, what this allows is taking a collection binding for which replication streaming is failing and removing it from the catalog, and then at a later date we can either re- add it with *the same* timestamp that it used to have, or we can add it with some later timestamp if we need to fiddle around with things manually.
Nothing should change by default, but now it's possible to manually tweak the initial replication cursor timestamp when adding a capture binding (and **only** when first adding it, the state is authoritative and this new property just …
=> source-firestore: Add 'initTimestamp' resource property

source-test/main.go
- Remove use of `catalog.Tail` option
- Introduce `exit_after` option to ask connector to exit after N rows
- This makes the `greetings` option pretty much useless. I'm still keeping it around so we don't break things but we can remove that option once we know no one is using it.
- - - …
=> source-test: "exit_after" instead of tail

source-mysql/datatype_test.go, source-mysql/discovery.go, source-mysql/main.go, source-mysql/replication.go
Previously they were captured as strings in MySQL's preferred timestamp format (`YYYY-MM-DD HH:MM:SS`). This commit changes things so that they are instead (`YYYY-MM-DDTHH:MM:SSZ`).
Note that MySQL TIMESTAMP / DATETIME columns don't actually store any useful time zone information. A TIMESTAMP is defined as being converted to UTC for storage, so we rely on the DB to get that right and just request that it give us the values in UTC as well. For the DATETIME column type we don't even have that assurance, so treating them as UTC is probably wrong but it's still the best we can do.
I'm torn on whether this change requires a version bump. All we previously said was "it's a string" so changing the format is _technically legal_, I think? It would make things a lot easier if we …
=> source-mysql: Translate TIMESTAMP/DATETIME to RFC3339 strings

source-test/main.go
- For some reason (I still don't understand) this condition is necessary for this connector to exit when we want it to
- This replaces the old condition of `if catalog.Tail`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/432)
=> source-test: fix loop logic

source-firestore/pull.go, source-hello-world/main.go, source-kinesis/capture.go, source-kinesis/discovery.go, source-kinesis/main.go, sqlcapture/capture.go, sqlcapture/main.go, tests/run.sh
- Remove use of `tail` when running e2e tests, and instead periodically check lines of output against expected lines, and once we reach the same number of lines we compare them one final time to see if the test passes or not
- Remove code that handled non-tailing mode from various connectors
N/A, supposed to be seamless, unless you were using `--poll`, which now connectors won't handle
- - -
This change …
=> Remove `tail`

source-boilerplate/testing/testing.go, source-mysql/backfill.go, source-mysql/datatype_test.go, source-mysql/discovery.go, source-mysql/main.go, source-mysql/replication.go
The DATETIME column type is just a raw 'YYYY-MM-DD HH:MM:SS' value with no explicit frame of reference. In general there's an implicit reference of "the user's local time zone", but we don't necessarily know what that is. And we'd really like to emit captured values as RFC3339 timestamps, so we need to interpret the values *somewhere*.
After this PR we assume that if the database's `time_zone` system variable is set to a IANA zone name or a numeric time offset then that is the location/offset in which a DATETIME should be parsed.
If the `time_zone` variable is set to its default value of `'SYSTEM'` we refuse to translate DATETIMEs, because for some reason the MySQL `system_time_zone` variable only contains the current time offset [1] and not a valid zone name which could …
=> source-mysql: Use DB `time_zone` for DATETIME parsing

source-mysql/replication.go
This commit modifies `source-myqsl` to ignore events that the client library represents as `replication.GenericEvent` messages. These are a grab-bag of rare edge cases that we don't care about, with the most common being `SHUTDOWN_EVENT` (which indicates that the MySQL server shut down at some point in the past and then presumably either restarted or failed over to a replica or something).
I've skimmed the code to see what events are classified as `replication.GenericEvent` and I'm fairly sure we can safely ignore all of them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/437)
=> source-mysql: Ignore 'GenericEvent' replication events

materialize-rockset/.snapshots/TestRocksetDriverSpec-TestEndpointSpecSchema, materialize-rockset/.snapshots/TestRocksetDriverSpec-TestResourceSpecSchema, materialize-rockset/driver.go, materialize-rockset/driver_test.go
This updates the connector spec for the API key field to clarify that it must have admin or member roles. A read-only key won't work.
The `materialize-rockset` docs should be updated along these same lines.
I updated the spec snapshots to be pretty-printed. The first commit does only that, and the second commit makes the actual change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/442)
=> materialize-rockset: spec update indicating api key requirements

go-schema-gen/generate.go, materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go, materialize-elasticsearch/.snapshots/TestDriverSpec, materialize-elasticsearch/driver.go, materialize-firebolt/.snapshots/TestDriverSpec, materialize-firebolt/config.go, materialize-google-pubsub/.snapshots/TestSpec, materialize-google-pubsub/driver.go, materialize-google-sheets/.snapshots/TestSpec, materialize-google-sheets/main.go, materialize-postgres/.snapshots/TestSpecification, materialize-postgres/driver.go, materialize-rockset/.snapshots/TestRocksetDriverSpec-TestResourceSpecSchema, materialize-rockset/driver.go, materialize-s3-parquet/.snapshots/TestS3ParquetDriverSpec, materialize-s3-parquet/driver.go, materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/snowflake.go
- Add `x-collection-name` annotation to materialization resource spec schemas, which will be used by the UI to fill in the collection name automatically
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/441)
=> materialize-*: add x-collection-name to resource spec schemas

source-mysql/.snapshots/TestGeneric-SimpleDiscovery, source-postgres/.snapshots/TestDiscoveryComplex, source-postgres/.snapshots/TestGeneric-SimpleDiscovery, source-postgres/.snapshots/TestTrickyColumnNames-discover, sqlcapture/discovery.go
In the transition to the Flow gRPC protocol the recommended stream name got changed from `table_name` to `schema.table_name` so this reverts that.
Also the resource config schema now describes a property for the primary key, but this has two issues:
1. A `[]string` property looks kind of ugly in the UI.
2. It defaults to empty, which makes it a lot more confusing to the user.
So this commit fills that in. Thus in the common case of a single primary key column the UI will at least show a single text box with the name of that column, so hopefully the user will get the idea.
Nothing changes for the user except hopefully the dashboard UI is less confusing once we upgrade to the v3 connector.
- - - …
=> sqlcapture: Tweak discovery logic so it works nicer in the UI

source-mysql/.snapshots/TestGeneric-SpecResponse, source-mysql/main.go, source-postgres/.snapshots/TestGeneric-SpecResponse, source-postgres/backfill.go, source-postgres/main.go, source-postgres/main_test.go, source-postgres/replication.go, sqlcapture/capture.go
This PR lowers various buffer-size tuning constants in `source-mysql` and `source-postgres` so that we can expect captures to actually work properly within the 1GiB connector memory limits. This comes at the cost of lowered throughput in some possible setups, but in the common case the hit shouldn't be too terrible.
Also this PR makes the backfill chunk size an advanced config property of `source-postgres` the same way we already did for MySQL, just for consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/446)
=> source-{mysql,postgres}: Lower buffer-size constants

source-mysql/discovery.go, source-postgres/discovery.go, sqlcapture/discovery.go
This PR tweaks `source-postgres` discovery logic to ignore tables in the `cron` schema, which is added by the `pg_cron` extension and generally isn't something the user actually intends to capture.
Also moves the warning when no tables are discovered from the source-mysql discovery code into the generic sqlcapture discovery code so that source-postgres will warn as well.
It will now be safe to blindly click through the discover-and-publish workflow in the UI when `pg_cron` is installed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/455)
=> source-postgres: Ignore the 'cron' schema

source-mysql/main.go, source-mysql/main_test.go, source-postgres/main.go, sqlcapture/main.go
This PR changes `source-mysql` to derive its default value for `/advanced/node_id` by hashing the task name, where previously it just hard-coded `u32("Flow")` as the default value.
The issue with a hard-coded default is/was that if a user naively creates two captures from the same MySQL host (which may be required if they want to capture from distinct logical databases) the captures will fight each other for the same ID and crash a lot.
But we don't want to just use pure randomization because some DB admins might want us to use a stable ID even if the user doesn't care to specify one. So instead of being truly random this changes the default behavior to use the upper 32 bits of the SHA-256 hash of the capture task name, which is effectively random but also stable for any …
=> source-mysql: Derive default 'node_id' from capture task name

materialize-bigquery/.snapshots/TestSQLGeneration, materialize-postgres/.snapshots/TestSQLGeneration, materialize-postgres/sqlgen_test.go, materialize-sql/.snapshots/TestTableTemplate, materialize-sql/table_mapping.go, materialize-sql/type_mapping.go
- All columns except primary keys are made as nullable. this is to allow fields to be made nullable from a collection without causing issues. Once we support automatic schema migration of tables to mark fields as nullable after creation, we can revert back to the more strict behaviour, see: https://github.com/estuary/connectors/issues/447
- Create a new SQL materialization with non-pk fields that are not marked as nullable, but they will still be created as nullable
**Notes for …
=> materialize-sql: create all non-pks as nullable

source-firestore/pull.go
We're seeing Firestore captures failing in production due to excessive memory usage, and this is the dumbest hammer that we have to potentially reduce memory usage so it's worth trying.
In general our backfills tend to be constrained by journal append rate limits and RTTs to Firestore are fairly low, so this isn't expected to have a large impact on throughput in general.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/463)
=> source-firestore: Reduce backfill chunk size

go-auth/google/spec.go, materialize-google-pubsub/.snapshots/TestSpec, materialize-google-sheets/.snapshots/TestSpec
- Migrate OAuth templates to the new mustache format, this connector was left behind when we did the migration in https://github.com/estuary/flow/pull/841
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/465)
=> go-auth: update oauth templates to mustache

go.mod, go.sum
This updates to the latest Rockset client, which includes a fix for retrying rate limit errors. With this updated client, retryable rate limit errors will be automatically handled by the client, rather than returning a terminal error which would crash the connector and cause re-trying of the transaction in a potentially infinite loop.
Closes https://github.com/estuary/connectors/issues/459
n/a
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/466)
=> materialize-rockset: update rockset client to v0.15.4

sqlcapture/capture.go
This reverts commit 830a94ac7506cdd75773cb00550090d29b46cd6a.
This PR is the inverse of https://github.com/estuary/connectors/pull/473, to be merged once everything is running smoothly again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/474)
=> Revert "sqlcapture: Temporary hack to roll out #468"

source-alpaca/.snapshots/TestSpec, source-alpaca/main.go, source-alpaca/worker.go
This will prevent pulling in unstable data if the historical API is queried at a time very close to
the current instant. I have seen reports that this can result in inconsistent results in rare cases,
due to delays or inconsistent ordering in tick records that stream into the database on the Alpaca
side. This small delay should eliminate that possibility.
Closes https://github.com/estuary/connectors/issues/480
No user-facing changes.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/482)
=> source-alpaca: add small delay on backfiller recency

go-auth/google/.snapshots/TestConfigSchema, go-auth/google/config.go, materialize-google-pubsub/.snapshots/TestSpec, materialize-google-sheets/.snapshots/TestSpec, source-http-file/main.go
Part of https://github.com/estuary/connectors/issues/467
Recent changes to UI rendering to be more strict about not rendering invalid specs have illuminated the fact that on a few connectors the `credentials`-type of configs don't have the required `type: object` key/value. This fixes that so they render properly in the UI again.
Applies to `materialize-google-pubsub`, `materialize-google-sheets`, and `source-http-file`. `source-http-file` still has some rendering problems with the parser config that will need to be handled in the flow repo.
`source-kafka` also has rendering problems, but this PR is not addressing those.
N/A
(anything that …
=> add missing "type" property to credentials configurations

.github/workflows/ci.yaml
This is a CI change that will allow for easily pushing an image with a different tag from a single dockerfile build. This will allow us to have a specific tag for `source-mariadb`, `materialize-timescaledb`, etc. The images themselves are identical (they have the same digests) as their root `source-mysql` and `materialize-postgres`, they just have a different tag.
The variant images will be published on merges to `main` with the same version tag as their root connector.
Closes https://github.com/estuary/connectors/issues/422
Additional tags for any image can be configured in `ci.yaml` in a similar way. Multiple additional tags can be specified to be built from a single connector.
This PR will end up creating two new …
=> build: update CI to allow pushing multiple tags from the same dockerfile

materialize-bigquery/bigquery.go, materialize-postgres/.snapshots/TestSpecification, materialize-postgres/driver.go, materialize-sql/driver.go, materialize-sql/endpoint.go, materialize-sql/table_mapping.go
Adds an optional resource-level configuration for the user to provide additional SQL statements to be executed when creating a table as part of `ApplyUpsert`. This could be used for things like converting a table to a TimescaleDB hypertable before any data is written to it, creating additional indexes, etc.
Closes #476
As an example for materializing to TimescaleDB where you want the table that the materialization is going to create to be created as a hypertable, you would add this SQL statement to the config:
```sql
SELECT create_hypertable('flow_created_table_name', 'timestamp_column');
```
The postgres materialization docs will need updated with this new configuration. An example for creating a hypertable would be …
=> materialize-postgres: add config to run additional sql on table creation

materialize-google-sheets/transactor.go, materialize-google-sheets/util.go
- Improve error message for the case when `PrevRound > loadRound`
- Some tiny comment improvements
- Solves https://github.com/estuary/connectors/issues/485
- Materialize to a sheet, disable that materialization, then create another materialization
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/conn …
=> materialize-google-sheet: better error message for PrevRound mismatch

materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/Dockerfile, materialize-snowflake/snowflake.go, materialize-snowflake/snowflake_test.go, materialize-snowflake/sqlgen.go, materialize-sql/templating.go
- Switch materialize-snowflake to use the new `materialize-sql` library instead of the deprecated library in flow repository.
- Same as before
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/469)
=> materialize-snowflake: switch to materialize-sql

.github/workflows/ci.yaml, materialize-snowflake/snowflake_test.go, materialize-snowflake/sqlgen.go
Makes the snowflake materialization use historical quoting.
This is important because of how snowflake handles identifier quoting: https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html
The "newer" `sql.IsSimpleIdentifier` would quote anything that had uppercase letters. Previously the snowflake materialization would not quote these things. Snowflake itself resolves unquoted identifiers as UPPERCASE, so with the new materialization quoting rules a field like `someField` would be resolved as `someField`, vs previous it being resolved as `SOMEFIELD`. This was causing existing materializations to fail when using the new code when the had fields with uppercase letters, as many of them do.
I tested this out using a problematic field name like `someField` in the …
=> materialize-snowflake: use historical quoting rules

source-gcs/main.go, source-s3/main.go
Adds a check to `source-s3` & `source-gcs` to make sure the bucket is connectable when creating the "store object". This happens during the airbyte protocol `Check` command, so an error connecting to the bucket will be surfaced during validation, rather than at runtime. This is particularly important now that we aren't doing any kind of discovery with the cloud storage connectors, since at no point during the setup does it actually connect to the bucket.
Errors that will be returned during validation will look like this for a non-existent bucket:
- `source-s3`: `connecting to store: validating connection to bucket "not-a-real-bucket-as8djf98": NotFound: Not Found`
- `source-gcs`: `connecting to store: validating connection to bucket "not-a-real-bucket-as8djf98": storage: …
=> source-{gcs,s3}: validate bucket is connectable when creating store

materialize-bigquery/bigquery.go
This adds a check to make sure the project, dataset, and cloud storage bucket exist with creation of the client. This prevents the materialization from being saved if any of these are invalid.
In the case of an invalid cloud storage bucket previously the materialization could be saved but then a runtime error would occur. With this change, an error will be returned when trying to save the materialization:
```
driver error while validating materialization bobCo/bq-test-1 Caused by: invocation failed: connector failed (exit status: 1) with stderr: building endpoint: creating client: validating connection to bucket "bucket-that-does-not-exist-12341234asdf": storage: bucket doesn't exist
```
An invalid project ID or dataset previously would not be able to be saved, but the …
=> materialize-bigquery: verify dataset, project, and cloud storage bucket

materialize-google-pubsub/.snapshots/TestSpec, materialize-google-pubsub/driver.go, materialize-google-pubsub/transactor.go
Two improvements to pubsub in this PR:
- The first commit provides a config option to create a default subscription when `ApplyUpsert` creates a topic. This is almost always going to be what should happen, otherwise the initially published messages will be dropped since there is no subscription. It is by default `true`. This closes https://github.com/estuary/connectors/issues/497
- The second commit sets the underlying PubSub client to block if its message queue is full. The default behavior was to never block, and this meant that if the store iterator could be read from faster than publish messages could be completed (network bound), unbounded in-memory buffering could occur. The PubSub client handles concurrently sending requests already, with a batch size of 100 and a …
=> materialize-google-pubsub: improve memory & create default subscription

source-gcs/main.go, source-s3/main.go
…equired permissions
This is a follow-up to #494 which added validation checks for cloud storage connectors to check for the existence of a bucket.
I originally had those checks get metadata for the bucket to confirm it exists, but that requires a separate permission from what is otherwise needed. These connectors only need permissions to list and read objects in a bucket and don't necessarily need permission to read metadata about buckets.
The change here is a bit more complicated than before, but produces similar validation results. It only requires list & get objects permissions.
N/A
- - …
=> source-{s3,gcs}: verify bucket existence & permissions with minimal required permissions

source-kinesis/capture.go, source-kinesis/discovery.go, tests/source-kinesis/bindings.json
- source-kinesis: remove local schema inference, use `x-infer-schema: true` instead
- Added `sequence_number` and `partition_key` to form a key for each record received from Kinesis, this is based on the docs: "SequenceNumber is the unique identifier of the record within its shard." and "PartitionKey identifies which shard in the stream the data record is assigned to.", which I take to mean a combination of two forms a unique identifier of each record.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along …
=> source-kinesis: remove local schema inference, use x-infer-schema: true

source-mysql/backfill.go, sqlcapture/resultset.go
Instead of using "(key_one, key_two) > (123, 'bar')" constructions, use "key_one > 123 OR (key_one = 123 AND key_two > 'bar')". MySQL and MariaDB's optimizer is able to make better use of this form.
Also:
* Lower a spammy log to trace level.
* Attempt to use ANALYZE rather than EXPLAIN for the backfill query, as its output is more accurate. …
=> source-mysql: decompose range query to make it easier to optimize

materialize-rockset/.snapshots/TestRocksetDriverSpec-TestResourceSpecSchema, materialize-rockset/README.md, materialize-rockset/driver.go, materialize-rockset/driver_test.go, materialize-rockset/rockset.go, materialize-rockset/transactor.go
This removes the s3 integration option from the Rockset materialization. It was not functional in its current state, difficult to use, and likely to result in corrupt Rockset collections since Rockset's S3 integration does not guarantee ordering.
There was also some refactoring & simplification possible since the newer Rockset client we are now using provides a built-in method for waiting for a Rockset collection to be ready to accept writes, so that bit of code was removed from our connector.
I tested this locally with some test data sets and everything still worked like before.
Closes https://github.com/estuary/connectors/issues/506
Use the connector like before, but now you won't see the S3 integration configuration. …
=> materialize-rockset: remove s3 integration option

materialize-bigquery/Dockerfile, materialize-elasticsearch/Dockerfile, materialize-firebolt/Dockerfile, materialize-google-pubsub/Dockerfile, materialize-google-sheets/Dockerfile, materialize-postgres/Dockerfile, materialize-rockset/Dockerfile, materialize-s3-parquet/Dockerfile, materialize-snowflake/Dockerfile, materialize-webhook/Dockerfile, source-alpaca/Dockerfile, source-firestore/Dockerfile, source-gcs/Dockerfile, source-hello-world/Dockerfile, source-http-file/Dockerfile, source-kafka/Dockerfile, source-kinesis/Dockerfile, source-mysql/Dockerfile, source-nativehello/Dockerfile, source-postgres/Dockerfile, source-s3/Dockerfile, source-test/Dockerfile
All we get from our current OOM-kill monitoring is the name of the process that got killed, so having them all be named "connector" is *rather unhelpful*. This should make OOM-kill events marginally easier to track down.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/519)
=> Rename all connector binaries in their Dockerfiles

materialize-bigquery/.snapshots/TestSQLGeneration, materialize-bigquery/bigquery.go, materialize-bigquery/sqlgen.go, materialize-postgres/.snapshots/TestSQLGeneration, materialize-postgres/driver.go, materialize-postgres/sqlgen.go, materialize-postgres/sqlgen_test.go, materialize-snowflake/snowflake.go, materialize-snowflake/sqlgen.go, materialize-sql/.snapshots/TestAlterColumnNullableTemplate, materialize-sql/driver.go, materialize-sql/endpoint.go, materialize-sql/templating.go, materialize-sql/templating_test.go, materialize-sql/type_mapping.go, materialize-sql/validate.go
- Allow updating a collection to make a field nullable in `materialize-sql` connectors
- Create a materialization with non-nullable fields
- Update those fields to make them nullable
- The connector should update your destination database to mark those columns as nullable
- - - …
=> materialize-sql: allow updating fields to make them nullable

.github/workflows/ci.yaml
Creates these new connectors:
- `source-alloydb` which is a re-tag of `source-postgres`
- `materialize-alloydb`which is a re-tag of `materialize-postgres`
Needs new docs for `source-alloydb` and `materialize-alloydb`, which will be pretty much the same as `source-postgres` and `materialize-postgres`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/525)
=> source-alloydb & materialize-alloydb: new connector

source-boilerplate/testing/testing.go, source-postgres/.snapshots/TestCapitalizedTables-Capture, source-postgres/.snapshots/TestCapitalizedTables-Capture-Replication, source-postgres/.snapshots/TestCapitalizedTables-Discover, source-postgres/backfill.go, source-postgres/discovery.go, source-postgres/main_test.go, source-postgres/replication.go, sqlcapture/main.go, sqlcapture/tests/helpers.go, sqlcapture/tests/tests.go
This fixes a couple of bugs when interacting with tables whose names explicity capitalized, for example the one you get by running `CREATE TABLE "USERS" (id INTEGER PRIMARY KEY, name TEXT);`.
It also adds a new test 'TestCapitalizedTables' which exercises discovery, validation, and capturing from a table named `"USERS"` (with quotes, meaning that it will actually be capitalized on the PostgreSQL side).
Also adds a bonus commit which I _think_ fixes CI build flakiness around the final `DROP_REPLICATION_SLOT` performed during tests. (Added in this PR because its CI builds were consistently failing, and either adding that change fixed it or it's just random and I got lucky)
- - - …
=> source-postgres: Fix handling of capitalized table names

source-postgres/.snapshots/TestUserTypes-Domain-Capture, source-postgres/.snapshots/TestUserTypes-Domain-Capture-Replication, source-postgres/.snapshots/TestUserTypes-Domain-Discovery, source-postgres/.snapshots/TestUserTypes-Enum-Capture, source-postgres/.snapshots/TestUserTypes-Enum-Capture-Replication, source-postgres/.snapshots/TestUserTypes-Enum-Discovery, source-postgres/.snapshots/TestUserTypes-Tuple-Capture, source-postgres/.snapshots/TestUserTypes-Tuple-Capture-Replication, source-postgres/.snapshots/TestUserTypes-Tuple-Discovery, source-postgres/capture_test.go, source-postgres/replication.go
This PR represents the bare minimum we can do to make the use of user-defined types not fail a capture. Concretely, this changes `Type` messages from logical replication to no longer be an error, and adds some tests verifying correct-ish behavior on domain, enum, and tuple types.
There are still a lot of rough edges:
1. Discovery only "works" to the extent that it doesn't crash. The discovered JSON type for a column of user- defined type is `{description: "<error>"}`, meaning that it accepts anything but complains about it if you look at the schema.
2. Tuple types aren't serialized especially well as JSON. Rather than becoming a JSON array or object, they are just emitted as a JSON string whose contents is the Postgres text-form representation of the value.
3. There are …
=> source-postgres: Bare minimum of user type support

source-postgres/main_test.go, sqlcapture/tests/helpers.go
This bit of helper logic is supposed to run a capture over and over in a loop, killing and restarting it after every new state checkpoint, in order to exercise checkpoint resuming in the most stressful way possible.
However there may be a timing bug around how it shuts down captures. I haven't been able to reproduce it locally, it only pops up during CI builds, but I'm reasonably certain that if a capture could emit multiple new state checkpoints in rapid succession, the restart would only take place after the final one rather than the first one like we want. And similarly documents from that entire span of time would be combined into a single run. This matches the sort of failure we're seeing in CI builds, so hopefully this commit will fix that.
Now includes a second …
=> sqlcapture: Fix 'RestartingBackfillCapture' race condition

source-mysql/replication.go, source-postgres/replication.go, source-sqlserver/docker-initdb.sh, source-sqlserver/main_test.go, source-sqlserver/replication.go, source-sqlserver/watermarks.go, sqlcapture/capture.go, sqlcapture/interface.go
This involved a multitude of little tweaks, including:
- Editing the database initialization script to create a new 'flow_capture' user with the necessary permissions.
- Modifying the test suite setup code to use a different user for test manipulations and captures, so that we can create tables and enable CDC as the sysadmin and then use the restricted 'flow_capture' user for captures.
- Modifying the test suite to enable CDC for newly created tables, so that the 'flow_capture' user doesn't require that permission.
- Modifying the connector "ensure watermarks table exists" process to use a simple `SELECT * FROM watermarks` to tell if the table exists, because the complex "check if it exists and if not create it" query requires create permissions even when the table …
=> source-sqlserver: Support captures as non-sysadmin user

source-mysql/replication.go
Ignores `ALTER USER` queries in the MySQL binlog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/546)
=> source-mysql: Ignore 'ALTER USER' queries

source-mysql/replication.go
Ignores `REVOKE` statements during source-mysql replication
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/547)
=> source-mysql: ignore REVOKE statements

materialize-bigquery/bigquery.go, materialize-bigquery/transactor.go
We've seen a couple of instances of an apparent deadlock with bigquery materializations, where the materialization will apparently start up and not write out any data, even though it does not exit with an error.
The cause of this is not immediately clear, so I am adding some logging for the startup the connector. We currently only see "opening bigquery" if everything works perfectly which is not very useful. The logs added here might be leaning a little towards overkill in the other direction, but they will only be logged when the connector restarts and should be useful for making sure the connector is able to initialize successfully. …
=> materialize-bigquery: add logging for connector initialization

source-mongodb/main.go
- Turns out working out the network tunnel is not as trivial for MongoDB, given that they usually use SRV DNS records and they have some cluster discovery logic that we need to dive into and understand so we can tunnel properly. For now I'm removing network tunnelling since we don't have a request for it.
- On the other hand, when using SRV MongoDB URIs in the format `mongodb+srv://`, the user should be able to specify this custom schema if they want to. This PR covers that. …
=> source-mongodb: remove tunnel, allow custom schema

source-mongodb/main.go
- Apparently if you give a URL with no scheme to `url.Parse`, it actually parses successfully but gives a URL which has `Scheme` equal to the whole address, with an empty `Host` 😁 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/560)
=> source-mongodb: fix address without schema throwing error

source-mongodb/main.go
- Validate `mongodb+srv://` addresses to ensure no port is specified, since port values are not supported on this scheme.
- This leads to a better UX by giving a better error message when users specify the port by mistake
- - - …
=> source-mongodb: validate mongodb+srv:// address to ensure no port

.github/workflows/ci.yaml
- Fix CI by installing `postgresql` instead of `postgresql-client` which seems to have been removed from the repositories
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/567)
=> ci: install postgresql instead of postgresql-client

source-alpaca/worker.go
This reverts a couple of commits for `source-alpaca` that were used to unblock a capture that was doing a long backfill over a time period that was not generating data.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/573)
=> source-alpaca: revert temporary fix for long, empty backfills

source-alpaca/.snapshots/TestSpec, source-alpaca/driver_test.go, source-alpaca/main.go, source-alpaca/main_test.go
Data is not available from the historical Alpaca APIs until 01-01-2016. If somebody puts in a start time way before that, the connector will churn through a potentially large amount of empty time ranges while backfilling and take a long time to actually start producing data. This adds a constraint to the configuration that a start date no earlier than 01-01-2016 can be used.
See https://github.com/estuary/flow/pull/964
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/574 …
=> source-alpaca: set a minimum start date

materialize-bigquery/bigquery.go, materialize-bigquery/sqlgen.go, materialize-postgres/driver.go, materialize-postgres/sqlgen.go, materialize-snowflake/snowflake.go, materialize-snowflake/sqlgen.go, materialize-sql/.snapshots/TestAlterTableAddColumnTemplate, materialize-sql/driver.go, materialize-sql/endpoint.go, materialize-sql/templating.go, materialize-sql/templating_test.go, materialize-sql/validate.go, materialize-sqlite/sqlgen.go, materialize-sqlite/sqlite.go
- Allow new fields to be added to bindings, and in turn add new columns to existing tables for `materialize-sql` connectors. I've tested `materialize-postgres` so far.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/581)
=> materialize-sql: schema migration to alter table and add new column

materialize-postgres/.snapshots/TestSQLGeneration, materialize-postgres/sqlgen.go, materialize-postgres/sqlgen_test.go, materialize-postgres/testdata/flow.yaml
Fixes an invalid query that could occur when a load query is done if no value fields are materialized. This is possible if all the fields materialized by a collection are keys and only the `flow_document` is updated.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/588)
=> materialize-postgres: handle materializations with no values materialized

materialize-snowflake/.snapshots/TestSQLGeneration, materialize-snowflake/snowflake.go, materialize-snowflake/snowflake_test.go, materialize-snowflake/sqlgen.go, materialize-snowflake/sqlgen_test.go, materialize-snowflake/testdata/flow.yaml, materialize-sql/templating.go
Fixes a couple of edge cases for the generated sql queries in `materialize-snowflake`:
- When a binding is configured with `delta_updates` and `flow_document` is excluded as a field
- When there are no non-key fields selected, AKA there are no value fields being materialized
Both of these are uncommon but can happen, and we've seen examples of them with other connectors.
Closes https://github.com/estuary/connectors/issues/589
N/A
The first commit is purely a refactoring of the sql generation tests to make it easier to see the diffs from the next couple of changes which are what actually modify the generated queries.
- - -
This change …
=> materialize-snowflake: sql fixes for delta_updates and no selected values

source-postgres/.snapshots/TestScanKeyTypes-UUID, source-postgres/datatype_test.go, source-postgres/main.go, sqlcapture/tests/helpers.go
Adds support for Postgres captures with UUID columns in the primary key.
The UUID is represented as a `[16]uint8` when we receive it from the Postgres client library, but can be sliced into a `[]uint8` and the client library will accept that later on when we use it as a resume cursor value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/593)
=> source-postgres: Support UUIDs as primary keys

source-postgres/.snapshots/TestScanKeyTypes-UUID
The new `TestScanKeyTypes/UUID` test snapshot is incorrect after the name-capitalization fix (for test tables) which was rolled into the prerequisites checking PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/594)
=> source-postgres: Update test snapshot

materialize-redshift/driver.go
Resolves a conflict that was created by merging the new Redshift connector PR out of order with some changes in the materialize-sql package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/596)
=> materialize-redshift: fix build

.github/workflows/ci.yaml, connector-variant.Dockerfile, materialize-sql/driver.go, sqlcapture/main.go
We re-tag a few connector images as identical variants of their base image. They are exactly the same other than the image tag. Currently these variants produce the same documentation URL in their spec response as the base image, resulting in a somewhat confusing experience when the docs link is followed in the web app, or when the sidebar displays the connector docs.
This PR provides a way for setting an alternative documentation URL for these variants.
It is mostly handled by `connector-variant.Dockerfile` which is a very simple extension of the base dockerfile that allows for a build arg to set the documentation URL. This is made available to the connector code through an environment variable. I've updated the SQL capture & SQL materialization packages to use this …
=> allow extending connector images as variants with alternate docs links

.github/workflows/ci.yaml
Fixes an error in the connector tag refresh script.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/600)
=> ci: fix syntax error in connector tag refresh

materialize-postgres/driver.go, materialize-redshift/driver.go, source-mysql/main.go, source-postgres/main.go, source-sqlserver/main.go
Previously this would just be logged and then execution would continue onwards and attempt to connect to localhost, which is confusing and results in sub-optimal error messages for the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/601)
=> return the error when network tunnel Start() fails

source-postgres/prerequisites.go
This may be failing in some setups, which would imply that the method we're using to check that permission is insufficiently nuanced.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/605)
=> source-postgres: Disable 'user has REPLICATION' startup check

source-mysql/Dockerfile, source-mysql/datatype_test.go, source-postgres/Dockerfile, source-postgres/datatype_test.go, source-sqlserver/Dockerfile
I still have never been able to reproduce this locally, but the 'TestScanKeyTypes' test will intermittently fail when running in CI, and this is troublesome for our push-on-green model, so out it goes for the moment.
It will still be run locally by default, it's only skipped when the CI_BUILD environment variable is set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/606)
=> source-{mysql,postgres}: Skip 'TestScanKeyTypes' in CI builds

source-mongodb/pull.go
- Look for one document in each collection during discover to infer type of `_id`, currently supporting `integer` and `number` (I doubt anyone uses this). We previously had a customer who had numerical IDs.
- Resolves #592 
- Create a collection with integer `_id` and run discover
- - - …
=> source-mongodb: use one document to infer type of _id

materialize-sql/driver.go
- collection projections are not semantically the same as field selections, so we should be comparing field selection, not projection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/627)
=> materialize-sql: fix deleted columns migration

source-http-ingest/src/lib.rs, source-http-ingest/src/server.rs, source-http-ingest/tests/snapshots/test__discover.snap, source-http-ingest/tests/test.rs
Updates the discovered binding in source-http-ingest to add the `x-infer-schema` annotation to the discovered 'webhook-data' collection. This just seemed like an obvious omission, since the json schema permits almost any valid json object.
Just setup a new capture using the source-http-ingest connector, and bask in the joy of automatically inferred json schemas.
@oliviamiannone is this something we should document explicitly for each connector? I'm a little uncertain. Happy to update the docs if you think we should.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/622)
=> Infer schema for source-http-ingest collections

materialize-redshift/.snapshots/TestSpecification, materialize-redshift/driver.go, materialize-redshift/staged_file.go
Adds an optional configuration for `bucketPath`  for storing temp objects in a bucket under a path. This is an identical option as `materialize-bigquery` and was something I overlooked when initially developing the connector.
Closes https://github.com/estuary/connectors/issues/611
See https://github.com/estuary/flow/pull/978
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/615)
=> materialize-redshift: configuration for setting a bucket path

materialize-bigquery/bigquery.go, materialize-bigquery/query.go
If the dataset is found in the project, it still may not be in the same region as the configuration states, even though it can perform the trivial query I had previously used to check this. The trivial query was really just checking that the configured region was actually a region, and not that it was the _correct_ region.
This adds a check specifically for the dataset region. It must be the same as the one in the configuration or a clear error message is returned.
I also tweaked the error messaging and logging when querying the meta tables. They would previously log warnings that things couldn't be found. With this change there will be the typical "info" log when applying the materialization if this is the first time the tables are being created.
(How …
=> materialize-bigquery: validate region metadata of dataset

materialize-mongodb/driver.go, materialize-mongodb/spec.go
- persist last materialization spec in `flow_materializations` collection
- when a binding is removed, remove its corresponding collection
- add a binding, then remove it. the collection will be dropped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/628)
=> materialize-mongodb: delete collection when a binding is removed

materialize-sql/driver.go
- we were using the collection projection to determine if a field is new, however if a field was not previously selected for this materialization, but now it is, it still counts as a new column.
- - - …
=> materialize-sql: check fieldSelection to determine new field additions

source-sqlserver/main.go
When performing backfills we alternate reading chunks from the database tables, performing a watermark write, and then waiting for that write to show up via CDC. This means that backfill throughput is capped at <ChunkSize> / <WatermarkLatency>.
This is true of all SQL captures, but in general the latency from watermark write to CDC event is milliseconds on other databases. SQL Server is special and uses a separate agent process which polls the WAL every 5s by default. This means that we can backfill at most <ChunkSize>/5 rows per second from any one table.
Let's stop the immediate pain by increasing the chunk size 8x, taking us from ~816 docs/sec to ~6.5k docs/sec.
- - - …
=> source-sqlserver: Increase backfill chunk size to 32k

source-sqlserver/.snapshots/TestColumnNameQuoting, source-sqlserver/backfill.go, source-sqlserver/main_test.go
Per the documentation it's pretty much always safe to wrap a column name in `[brackets]` when constructing a query, so now we will.
It is possible that there are undocumented edge cases of column names which require further character-level escaping, but if such names exist the documentation doesn't mention the possibility, so this should be adequate until/unless we discover that such a name exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/639)
=> source-sqlserver: Properly quote column names in backfill query

source-mongodb/pull.go
Adds a bit of additional logging when encountering a server error while reading the change stream. This is to help diagnose an issue with a capture running in production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/641)
=> source-mongodb: log change stream error details

source-sqlserver/.snapshots/TestScanKeyTypes-DateTimeOffset, source-sqlserver/.snapshots/TestScanKeyTypes-Integer, source-sqlserver/datatypes.go, source-sqlserver/datatypes_test.go
This copies the 'TestScanKeyTypes' test to `source-sqlserver` with a test case for `datetimeoffset` columns.
Then the `encodeKeyFDB` function is modified to make this pass by serializing `time.Time` values coming from the database driver using the `sortableRFC3339Nano` format string. No decoding is required, as the string format can be used directly as an input to subsequent backfill queries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/640)
=> source-sqlserver: Add support for datetimes as keys

source-mongodb/pull.go
When a mongodb oplog does not contain enough history to resume from the last resumption checkpoint, the connector attempts to zero out its state and re-start backfilling the collections. The logic to detect this condition didn't seem to be working. The logs showed that the error message did match, but that the error code did not. So this removes the error code check from the condition, to hopefully allow the broken capture to re-start backfilling.
- have a mongo capture that stops emitting state checkpoints at some point
- wait until the last observed change event falls off the back of the mongo server's oplog 
- start the capture
- Previously, this would cause the capture to repeatedly fail. Now, it should fail once and then re-start backfilling the …
=> source-mongodb: fix restarting backfill

source-gcs/Dockerfile, source-hello-world/Dockerfile, source-http-file/Dockerfile, source-kafka/Dockerfile, source-kinesis/Dockerfile, source-s3/Dockerfile
We had this temporarily pinned to a specific build to ease the transition to the new flow protocols, but that's done now so we can move back to the dev image for airbyte-to-flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/646)
=> airbyte-to-flow: use airbyte-to-flow:dev for all connectors that use airbyte-to-flow

source-postgres/backfill.go
This removes the parens from around the column names in the `ORDER BY` of the backfill queries for source-postgres. I ran `EXPLAIN` on some backfill queries and found that, at least in this circumstance, postgres would refuse to use an index when the column names were surrounded with parens, while it would use them as expected if the parens were left off. In this case, we were querying by `(a, b)`, where `a` had a primary key index, and `b` had a secondary btree index. The parens in the `WHERE` clause did not seem to have any effect, though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/648)
=> source-postgres: remove parens from ORDER BY

sqlcapture/capture.go
Previously we would backfill one chunk of rows from *every* table (in the backfill state) at once, and this policy put us in a tricky spot where we'd have to either size the backfill chunk size *really conservatively* or we'd risk instantly running out of memory if a new capture added, say, eight new tables all at once which needed backfills.
In theory nothing should change except large backfills won't cause OOMs as easily.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/649)
=> sqlcapture: Backfill a randomly selected table per loop

source-postgres/replication.go, sqlcapture/capture.go
The previous change which made only one table get a chunk backfilled at a time didn't impact memory usage nearly as much as expected, so while that's still probably a good move in general it implies that we're gobbling up memory somewhere else instead.
There are two other notable "buffers" inside of a SQL capture, so let's try reducing the size of both of those buffers and see if that makes any difference.
Both of these are sized primarily for performance -- connector operation remains correct even if the channels were unbuffered, so it should be entirely safe to make them smaller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/650)
=> source-postgres: Lower a couple of buffer-size tuning constants

source-mysql/Dockerfile, source-postgres/Dockerfile, source-sqlserver/Dockerfile
New in Go 1.19, the `GOMEMLIMIT` environment variable is added for use-cases such as "the deployment of a web service into containers with a fixed amount of available memory".
I suspect that in at least some cases we OOM during large backfills not because we have >1GiB of *live* data, but rather because the Go GC correctly deduces that we'd get better throughput if we used >1GiB of heap before running a GC cycle. And really, if we don't inform it about our 1GiB memory limit that's a choice it is correct in making.
So, uh, maybe let's try asking it to pretty please keep the Go heap below 900MiB if it can?
In theory we might want to move this into the base connector image at some point in the future, but I figured limiting it to just SQL captures …
=> source-{mysql,postgres,sqlserver}: Ask nicely to use less RAM

source-boilerplate/testing/testing.go, source-sqlserver/.snapshots/TestTextCollation, source-sqlserver/backfill.go, source-sqlserver/main_test.go
This PR is intended to fix text collation ordering in backfill queries, by explicitly specifying the `Latin1_General_100_BIN2_UTF8` collation order on primary keys whose column type is `{n}{var}char(N)`.
The aforementioned collation basically means "just shut up and sort lexicographically on Unicode code-points" as far as I can tell, and since UTF-8 is designed such that bytewise lexicographic ordering matches Unicode code-point ordering this _should_ mean that backfill query row ordering will exactly match our internal scan key ordering as intended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/655)
=> source-sqlserver: Fix primary key text collation

source-mysql/.snapshots/TestGeneric-DuplicatedScanKey, source-postgres/.snapshots/TestGeneric-DuplicatedScanKey, source-sqlserver/.snapshots/TestGeneric-DuplicatedScanKey, sqlcapture/capture.go, sqlcapture/resultset.go, sqlcapture/tests/tests.go
In the past we required that successive row keys be strictly greater than previous rows. But since it's possible to capture from tables without a primary key or any other form of uniqueness constraint on the backfill key columns, there are legitimate situations where we might observe successive keys being exactly equal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/657)
=> sqlcapture: Allow successive row keys to be equal

materialize-bigquery/.snapshots/TestSQLGeneration, materialize-bigquery/sqlgen.go
Uses direct equality for loads, rather than "is not distinct from".
We've been observing poor load query performance on even modestly sized data sets, making the
connector essentially unusable for these cases. Some quick testing has revealed that using `=` for
comparision in the load query instead of "is not distinct from" makes a tremendous difference in the
performance of the load query join.
This change means that we will not be able to use nullable keys with the connector. For the moment
this is acceptable since it is only very recently that nullable keys were allowed in the runtime and
there are no current bigquery materializations using nullable keys. We will likely be pursuing a
different path for nullable keys involving default values in the future, so long term …
=> materialize-bigquery: use direct equality for load query

materialize-postgres/.snapshots/TestSpecification, materialize-postgres/config_test.go, materialize-postgres/driver.go
If no port is specified with the host, the connector will currently use 5432. This is buried in the [inner workings of pgx](https://github.com/jackc/pgconn/blob/1e1135688ea919f66b9425b5bfe06f14ef1e5285/defaults.go#L16) and not made clear to the user. This changes the messaging that the user sees and makes setting the port explicit in our connector code so that it is stable going forward.
Use a postgres materialization as before with no port specified and observe that it still works. No behavior is actually changed with this PR.
N/A
- - - …
=> materialize-postgres: be more explicit about the default port

.github/workflows/ci.yaml, source-s3/main.go, tests/source-gcs/expected.txt, tests/source-s3/cleanup.sh, tests/source-s3/expected.txt, tests/source-s3/setup.sh
Updates the `source-s3` integration tests to use localstack instead of an actual S3 bucket so they can run reliably.
Also adjusts some test output ordering for `source-s3` and `source-gcs`. Apparently the new sqlite materialization has a slightly different idea of what order these are output in.
N/A
There was a small adjustment needed to the `source-s3` connector to get non-AWS endpoints to work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/663)
=> source-s3: use localstack for integration tests

source-mysql/.snapshots/TestSecondaryIndexDiscovery-index_only, source-mysql/.snapshots/TestSecondaryIndexDiscovery-nonunique_index, source-mysql/.snapshots/TestSecondaryIndexDiscovery-nothing, source-mysql/.snapshots/TestSecondaryIndexDiscovery-nullable_index, source-mysql/.snapshots/TestSecondaryIndexDiscovery-pk_and_index, source-mysql/discovery.go, source-mysql/discovery_test.go, source-postgres/.snapshots/TestSecondaryIndexDiscovery-index_only, source-postgres/.snapshots/TestSecondaryIndexDiscovery-nonunique_index, source-postgres/.snapshots/TestSecondaryIndexDiscovery-nothing, source-postgres/.snapshots/TestSecondaryIndexDiscovery-nullable_index, source-postgres/.snapshots/TestSecondaryIndexDiscovery-pk_and_index, source-postgres/discovery.go, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-index_only, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-nonunique_index, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-nothing, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-nullable_index, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-pk_and_index, source-sqlserver/discovery.go, source-sqlserver/discovery_test.go, source-sqlserver/main_test.go
This PR extends the stream discovery logic for SQL database captures to autoselect a secondary index as the collection/backfill key under the specific circumstances where the table has no primary key, but it _does_ have a unique index made up of non-nullable columns.
This is useful because it means that in some setups things will "just work" where previously they required manual intervention, and it may be an easier request in some cases to ask the user to create another index on a table as opposed to defining a primary key.
Create a table which has no primary key (but has some `NOT NULL` columns), and define a secondary index on those columns using `CREATE UNIQUE INDEX`. Discovery will now identify the existence of a suitable index and use that as the …
=> source-{mysql,postgres,sqlserver}: Implement secondary index discovery

source-postgres/.snapshots/TestUserTypes-Enum-Discovery, source-postgres/.snapshots/TestUserTypes-Tuple-Discovery, source-postgres/discovery.go, sqlcapture/discovery.go
Rewords the "unknown column type" discovery failure messaging. Previously this message was a very scary `"ERROR: could not ..."` message which could mislead users into thinking the situation was a lot worse than it really is. After this change the message will look something like:
"columnName": {
"description": "using catch-all schema: unable to translate PostgreSQL type \"userenum\" into JSON schema"
}
Which should hopefully give them the (correct) impression that they can just continue onwards and things will work so long as they don't need a more precise schema for that column.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/670)
=> source-postgres: Reword "unknown column type" discovery warning

source-mysql/.snapshots/TestAlterTable_AddColumnBasic-at_middle, source-mysql/.snapshots/TestAlterTable_AddColumnBasic-at_middle_restart, source-mysql/.snapshots/TestTrickyColumnNames-backfill, source-mysql/.snapshots/TestTrickyColumnNames-discover, source-mysql/.snapshots/TestTrickyColumnNames-replication, source-mysql/.snapshots/TestTrickyTableNames-Capture, source-mysql/.snapshots/TestTrickyTableNames-Capture-Replication, source-mysql/.snapshots/TestTrickyTableNames-Discover, source-mysql/backfill.go, source-mysql/capture_test.go, source-mysql/main_test.go, source-mysql/prerequisites.go, source-postgres/.snapshots/TestTrickyColumnNames-backfill, source-postgres/.snapshots/TestTrickyColumnNames-discover, source-postgres/.snapshots/TestTrickyColumnNames-replication, source-postgres/capture_test.go, sqlcapture/capture.go, sqlcapture/discovery.go, sqlcapture/discovery_test.go
This set of changes improves handling for unusually named tables and primary key columns.
The cross-cutting change to `sqlcapture` for unusual table names is related to recommended Flow collection names on discovery. Flow collection names are allowed only a specific set of characters and have certain requirements for "path-like" sequences like `/../` due to their inclusion in Gazette journal paths. A database like Postgres can have just about any character in a table name (if it is quoted) which can lead to invalid recommended collection names if these table names are used as-is in collection names. The change here applies a simple sanitization where the disallowed characters and any occurrences of a `/` character are replaced with `_`. This closes …
=> sqlcapture: enhanced handling for unusual identifiers

source-http-file/http_file_test.go, source-http-file/main.go
Add a test over validation behavior and discovered name extraction.
Tested via local stack.
Fixes estuary/flow#1017
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/674)
=> source-http-file: additional validation and name extraction from URL

source-postgres/.snapshots/TestUserTypes-Range-Capture, source-postgres/.snapshots/TestUserTypes-Range-Capture-Replication, source-postgres/.snapshots/TestUserTypes-Range-Discovery, source-postgres/capture_test.go, source-postgres/datatype_test.go, source-postgres/discovery.go, source-postgres/main_test.go
This changes discovery for range (user-defined and built-in) and enum (which are always user-defined) columns to output a JSON schema with `string` fields for these columns. They will continue to be output in their text form.
Postgres enum type values are represented as string labels. There is an underlying integer value corresponding to the string label values, but that seems less useful to capture. The enum type in Postgres restricts inputs to just its set of labels, and JSON schema supports a similar concept with the `enum` keyword. However I am opting to _not_ attempt to cast the Postgres enum values into a corresponding JSON schema enum. This is mostly because it would make dealing with additions to the Postgres enum difficult: We would need a mechanism for …
=> source-postgres: discover enum & range types as strings

source-postgres/replication.go
In automated tests the new LSN acknowledgement code seems to work, but in production our capture from our own Supabase instance is not advancing the replication slot LSN. We need more visibility here to narrow down the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/685)
=> source-postgres: Add DEBUG logs for a production issue

sqlcapture/capture.go
This was the original meaning of the message and there's at least one place within Flow that hasn't been updated to set the count yet, so we should continue to treat it as a count of 1 if unset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/686)
=> sqlcapture: Treat Acknowledge with empty count as count=1

source-postgres/datatype_test.go, source-postgres/discovery.go
A captured table column may be an array type and be nullable, in which case the column might contain arrays or `null`. We would previously discover these columns as `{"type":["object"]}` which would disallow any `null` values to be captured from the table. We were also applying the column nullability to the items in the array. But it is not possible for a column array to be declared with non-nullable items in Postgres in a way that we can currently check for, as it requires additional constraints on the table.
This changes discovers for nullable array columns to have a type like `{"type":["object","null"]}` which will allow nullable array columns to be captured when the columns contain `null`.
Closes https://github.com/estuary/connectors/issues/684 …
=> source-postgres: handle nullable columns with array types

source-mysql/.snapshots/TestGeneric-SpecResponse, source-mysql/main.go, source-postgres/.snapshots/TestGeneric-SpecResponse, source-postgres/main.go
Previous work to get RAM consumption under control was wildly successful and now SQL captures are very stable around 20-50MiB during an active backfill.
This means we should have plenty of headroom to take larger bites from the source database, which generally is expected to give us much better throughput. This is especially true if there's substantial round-trip query latency to the database, but even fairly close databases should benefit for various other "getting fully spun up to maximum throughput" reasons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/689)
=> source-{mysql,postgres}: Increase backfill chunk size 8x

source-postgres/prerequisites.go
Up until now `source-postgres` has tried to create a "FOR ALL TABLES" publication if the configured publication did not exist. Creating this publication can cause problems for non-captured tables if those tables do not have a primary key and also do not have a replica identity. In this case the tables can no longer process updates and deletes, since they are included in the FOR ALL TABLES publication and these actions require a table that is part of a publication to have a replica identity. In short, we do not want our capture to have any side effects on non-captured tables.
With this change we'll instead create an "empty" publication at first if one doesn't already exist and ensure all required tables are part of it (including both captured tables and the watermarks …
=> source-postgres: don't create FOR ALL TABLES publication

source-mongodb/discovery.go, source-mongodb/pull.go
- Views cannot be used with `ChangeStream`, so we should exclude them from discovery process
- When sanitizing documents, we were not matching against `primitive.M` for nested objects (although `primitive.M` is a type alias for `map[string]interface{}` but it requires matching explicitly), so nested objects were not being sanitized, leading to `NaN` errors
- `ChangeStream` errors were not being surfaced properly, which lead to confusion when a `ChangeStream` would fail …
=> MongoDB: assortment of issues

source-mysql/main.go
Passwords used as part of replication in MySQL can't be longer than 32 characters in length, so this adds a validation check explaining that if the user has supplied a password that is too long.
This impacts both MySQL and MariaDB since they use the same connector. MariaDB doesn't actually have this limitation, but unless we did a lot more work to differentiate between MySQL and MariaDB this is the best we can do for now.
Closes https://github.com/estuary/connectors/issues/691
We should update the docs for MySQL and MariaDB.
- - - …
=> source-mysql: require passwords be no longer that 32 characters in length

source-mysql/replication.go
Apparently if the SSH tunnel breaks it's possible for the capture to get stuck trying to reconnect indefinitely, which will never work because the SSH process has shut down and won't be restarted.
Conveniently there's an option 'MaxReconnectAttempts' which places a finite limit on the number of connection retries the MySQL client library will perform, so that connection attempts failing will eventually become task failures and get retried at a higher level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/700)
=> source-mysql: Limit number of connection retry attempts

materialize-snowflake/snowflake.go, materialize-snowflake/sqlgen.go, materialize-snowflake/sqlgen_test.go, materialize-snowflake/staged_file.go, tests/materialize/materialize-snowflake/cleanup.sh, tests/materialize/materialize-snowflake/fetch-data.go, tests/materialize/materialize-snowflake/fetch.sh, tests/materialize/materialize-snowflake/setup.sh, tests/materialize/materialize-snowflake/snapshot.json
We've been uploading data as one large file per binding to Snowflake for staging data, and that has resulted in a few problems:
- Most significantly, the `gosnowflake` driver seems to get bogged down encrypting these files when they are multiple gigabytes in size, which is typical for a non-trivial transaction duration.
- The upload for large files apparently fails entirely if they are too large under some circumstances, resulting in an endless loop of extremely long encryption followed by failed uploads.
- Snowflake can process many small files in parallel, which should offer performance improvement vs. a single large file
This changes the file staging to split the data up into a series of smaller files which are then collectively queried together. The PUTs to Snowflake …
=> materialize-snowflake: split internal stage PUTs into smaller files

base-image/Dockerfile, source-mysql/Dockerfile, source-postgres/Dockerfile, source-sqlserver/Dockerfile
Sets an advisory limit via environment variable in the `materialize-snowflake` dockerfile as a workaround to the memory issues documented in https://github.com/estuary/connectors/issues/709.
This actually seems to work very well in practice and will keep the connector memory right at 900mb when reading load query results for the datasets I have tried it with. This is certainly not an ideal amount of memory to use (we'd like it to use a lot less), and for that I have some initial thoughts in the previously linked issue.
~I'm opting not to make this a global setting via the base image at the moment, since I'd generally prefer to know about high memory use from other connectors via our OOM kill alerts, even if they are something that could be remedied by more active GC, so …
=> materialize-snowflake: set GOMEMLIMIT=900mb

source-mysql/replication.go, source-mysql/replication_test.go
Modifies `source-mysql` to ignore `/* comments like this */` when they're reported as query events via replication.
Also adds a test because this regex is getting long enough to need one even if each individual case is fairly simple.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/710)
=> source-mysql: Ignore /* comments like this */

source-mysql/.snapshots/TestGeneric-SpecResponse, source-mysql/discovery.go, source-mysql/main.go, source-mysql/prerequisites.go
There are some MySQL-based setups where it is difficult to set the `'time_zone'` system variable. This adds a configuration value to allow for configuring a timezone as part of the capture that will be used for `datetime` columns when the the `'time_zone'` system variable cannot be set on the database by the user.
Closes https://github.com/estuary/connectors/issues/714
Will need to update the mysql capture docs to reflect this new configuration parameter and describe its usage.
- - - …
=> source-mysql: add timezone configuration

source-kafka/src/kafka.rs
- this is a leftover from when we used to emit the message as a separate object, but now it is flattened (following suite of all other connectors)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/720)
=> source-kafka: remove leftover `message` from document schema

materialize-sql/validate.go
Reverts estuary/connectors#719
This ended up breaking materializations that use `recommended: true` in their field selections. The problem is that it now recommends fields that are `type: object` or `type: array`. So I'm reverting for now, and we can revisit the original problem later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/724)
=> Revert "materialize-sql: recommend string field locations that are formatted as numeric"

materialize-sql/type_mapping.go, materialize-sql/type_mapping_test.go, materialize-sql/validate.go
This PR accomplishes 2 things:
- Originally in 9e6b387 there was a change intended to make string fields formatted as numeric (integer or number) be included in the "recommended" fields. That change inadvertently also cause object and array fields, or indeed ANY field with a single type, to also be recommended. This new version of that change will only recommend fields that map to a `FlatType` of `INTEGER` or `NUMBER` to accomplish the original goal without including other unintended single-type fields.
- Updates the `effectiveJsonTypes` mapping to handle nullable strings formatted as numeric in addition to non-nullable fields of this kind, which closes https://github.com/estuary/connectors/issues/723. These fields will also be recommended by default now.
**Workflow …
=> materialize-sql: fix numeric format strings as recommended and handle nullable

.github/workflows/ci.yaml, materialize-mongodb/VARIANTS, materialize-mongodb/docker-compose.yaml, materialize-postgres/VARIANTS, source-mongodb/VARIANTS, source-mysql/VARIANTS, source-postgres/VARIANTS, source-sqlserver/VARIANTS, tests/materialize/materialize-mongodb/setup.sh
This PR modifies the CI workflow configuration to remove the `build_variants` step and instead merges the variant building-and-pushing steps into the main `build_connectors` matrix build. This means that flake in one connector (say, `source-kafka`) should no longer impact our ability to build and push another connector variant (such as `source-amazon-aurora-mysql`).
The new process for building and pushing variants is just a shell command featuring a `for VARIANT in ${...}` loop, with the list of variant names coming from the file `${CONNECTOR}/VARIANTS`. Because of the looping we can no longer use `docker/build-push-action` to manage this, but honestly I think just running `docker build` / `docker tag` / `docker push` is more comprehensible anyway.
For simplicity the …
=> Move connector variant building/pushing into `build_connectors` matrix build

.github/workflows/ci.yaml
Apparently you can only specify one image/tag to push per invocation of that command, for some reason.
This is a fast-follow bugfix for the untestable portion of https://github.com/estuary/connectors/pull/729
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/731)
=> ci: Fix 'docker image push' arguments

materialize-snowflake/sqlgen.go
Handle strings with format `date` as Snowflake [`DATE` type](https://docs.snowflake.com/en/sql-reference/data-types-datetime#date) columns.
Fortunately this is a very simple change since the text encoding that Snowflake accepts for `DATE` types matches Flow's `date` format, so it is fully backward-compatible. 
I tested backward-compatibility for this by:
1. creating a materialization with `date`s on the current connector (`date` column(s) created as  in Snowflake with type `STRING`)
2. materializing some `date`-formatted string values
3. changing the image of the connector to the new one, built with this change
4. materializing some more `date`-formatted string values and observing that the materialization still worked (values still materialized into `STRING` columns)
A …
=> materialize-snowflake: handle "date" formatted strings

filesource/filesource.go, source-boilerplate/boilerplate.go, source-kinesis/Dockerfile, source-kinesis/capture.go, source-kinesis/connection.go, source-kinesis/discovery.go, source-kinesis/main.go, source-kinesis/shard_range.go, source-kinesis/shard_range_test.go
- Switch `source-kinesis` to flow protocol and use `source-boilerplate`
- Pull-request is based on #726 
- Create a capture for Kinesis and generate data to be sent to it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/728)
=> source-kinesis: switch to flow protocol

build-local.sh, filesource/filesource.go, filesource/state.go, source-boilerplate/boilerplate.go, source-gcs/Dockerfile, source-gcs/main.go, source-http-file/Dockerfile, source-http-file/main.go, source-kinesis/Dockerfile, source-kinesis/capture.go, source-kinesis/connection.go, source-kinesis/discovery.go, source-kinesis/main.go, source-kinesis/shard_range.go, source-kinesis/shard_range_test.go, source-s3/Dockerfile, source-s3/main.go, source-sftp/Dockerfile, source-sftp/main.go
- Switch `filesource` and the connectors that use it `source-gcs`, `source-s3`, `source-http-file` and `source-sftp` to flow protocol
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/726)
=> filesource: switch to flow protocol

materialize-snowflake/snowflake.go, materialize-snowflake/staged_file.go
For standard updates materializations Flow uses load queries to determine which keys already exist in the database, and this information is available to the connector during the store phase.
COPY INTO queries are much more efficient than MERGE queries, and we can use the knowledge of which keys already exist when storing new records to issue separate COPY INTO vs. MERGE queries within the same transaction for files staged as new records vs. updates.
The hope is that for cases where a standard updates materialization is storing mostly new rows with relatively few updates in each transaction that this will reduce the time for store phases to complete. On such materializations of large data sets we have observed that the MERGE queries take a long time to complete, and the …
=> materialize-snowflake: separate MERGE and COPY INTO queries for stores

source-kafka/src/kafka.rs, source-kafka/src/lib.rs
- include the broker servers connecting to in the error message of `fetch_metadata`, since this error is commonly caused by the wrong broker being configured
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/741)
=> source-kafka: include servers connecting to in error message

materialize-bigquery/query.go
The retry duration was previously limited to just a few seconds, which was causing frequent task failures when more than one materialization shard operate in the same dataset (either because of a split shard, or separate materializations).
It's pretty gross, but the only way to determine if an error is a result of one of these concurrent update failures is to substring match the error message itself, since the googleapi package doesn't break things down enough to match them in any other way.
This extends the retry duration out to several minutes with a decent amount of backoff between attempts to give the shard a chance to complete its operations when running concurrently with other shards in the same dataset, but limits retrying only to errors related to concurrent …
=> materialize-bigquery: extend retry duration

materialize-sql/endpoint.go, materialize-sql/validate.go
- validate that required fields are marked as `Exists.MUST` in projections during `Validate` and `Apply`
- Validate a capture with a key that's optional according to document schema of the collection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/739)
=> materialize-sql: validate required fields in collection projections

materialize-snowflake/snowflake.go, materialize-snowflake/staged_file.go
This reverts commit 0bea66d44d84a5dfe787fe53a1c9f1e3407419f4.
The change did not end up making any actual improvements when observed with actual tasks in production. Reverting this to return the code to its original, simpler form.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/744)
=> Revert "materialize-snowflake: separate MERGE and COPY INTO queries"

materialize-snowflake/snowflake.go
The default behavior of the Snowflake driver is to load & parse query results as arrow batches. This causes relatively high memory usage since they are loaded in large chunks and processed as a batch of columns.
This commit changes the connector to use row-oriented JSON results instead. This is accomplished with the parameter `"GO_QUERY_RESULT_FORMAT": "json"`. Furthermore, the Snowflake driver allows for the use of a "stream downloader" with JSON results which enables streaming load results back to the runtime in a memory-efficient way.
The main caveat when using JSON instead of arrow is (alleged) reduced performance. Although worse performance is plausible, this should not have any meaningful impact on our materialization throughput overall. We run loads in parallel …
=> materialize-snowflake: use streaming json downloader for loads

materialize-sql/table_mapping.go
Adds an escape hatch for materializations sourcing from collections that have string formats where the materialization was created before support for materializing the string formats as specific SQL types was added. This can be used for backwards compatibility. I only know of a single field in a single materialization that needs this in order to run on the latest image of its materialization.
There is a broader concept of our SQL materializations providing backwards compatibility for dialect changes, and this is certainly not that. That will be a hard thing to do and there is not sufficient motivation for figuring out how to do it well right now. This solution is a bit ugly, but is the most minimal change I could come up with that would accomplish the immediate need and …
=> materialize-sql: option for ignoring string formatting via field config

source-mysql/datatype_test.go, source-postgres/datatype_test.go, sqlcapture/main.go, sqlcapture/tests/helpers.go
Skips tests using the `RestartingBackfillCapture` helper function in CI builds, because after several attempts they're still flaky due to some sort of nondeterminism.
Also I threw in a minor error-message tweak that came up earlier today while helping a user get a capture going.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/752)
=> Skip some SQL Capture tests in CI builds to reduce flakiness

source-postgres/.snapshots/TestConfigURI-Basic, source-postgres/.snapshots/TestConfigURI-IncorrectSSL, source-postgres/.snapshots/TestConfigURI-RequireSSL, source-postgres/.snapshots/TestGeneric-SpecResponse, source-postgres/main.go, source-postgres/main_test.go
Adds a new 'SSL Mode' advanced config option. This is an enumeration which gets directly plumbed through into a libpq connection URI 'sslmode' parameter, which should have the appropriate effect when set.
When this option is left unset the connector behavior should be unchanged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/753)
=> source-postgres: Add 'SSL Mode' advanced config option

materialize-bigquery/bigquery.go, materialize-bigquery/transactor.go
This makes materialize-bigquery provide its config to the endpoint as a pointer, to be consistent with the other sql materializations.
Automated tests pass (ran manually) and also I am able to create a materialization through the UI with this change, whereas before it would error.
- - - …
=> materialize-bigquery: config from endpoint is a pointer

filesource/filesource.go, go/connector-errors/errors.go, materialize-boilerplate/boilerplate.go, source-boilerplate/boilerplate.go
When a `filesource` capture is running the parser and the parser fails, the parser logs an error message and exits with status 1. Currently we log something like `"parser failed: exited with status 1"` from the connector as the last log line when this happens.
This changes the connector to not log anything extra when the parser process exits with an error. The responsibility is on the parser to log the details of the error, and the connector shouldn't clobber that will a less useful generic log. This allows the relevant parser error to be picked up as the shard failure reason and shown in the UI.
See also https://github.com/estuary/flow/pull/1084 for a change in the parser to make the message logged on failure include the details of the error.
Observe …
=> filesource: log errors from parser as last logged line

source-kafka/Dockerfile
We need to copy in a couple more shared library files into the runtime docker stage for the connector to be able to run.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/765)
=> source-kafka: fix build

materialize-pinecone/Dockerfile, materialize-pinecone/client/client.go
When a 429 "Too Many Requests" response is received from the OpenAI API, we retry since this is usually a rate limit error that exponential backoff while remedy. It is also possible for this response code to be received if a quota is exceed.
Either way, the API response contains some useful information in its JSON body, and we can extract that and return the API error message in the connector error.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/764)
=> materialize-pinecone: return error message from rate limit error message response

materialize-s3-parquet/parquet_data_converter.go, materialize-s3-parquet/parquet_data_converter_test.go
Properly handle integer instances destined for float (`type: number`) fields.
Integers will be sent / preferred by the runtime if the location parses cleanly as an integer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/766)
=> materialize-s3-parquet: proper handling for integer->float

materialize-bigquery/query.go
Bigquery sometimes responds with a 400 status error and provides no specific reason for the error, but the error response suggests that retrying might solve the problem. We have seen that retrying does indeed solve the problem when the connector is restarted via the shard supervisor. This change makes these errors be automatically retried.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/768)
=> materialize-bigquery: retry errors when response suggests retrying

source-sqlserver/.snapshots/TestIndexIncludedDiscovery, source-sqlserver/discovery.go, source-sqlserver/discovery_test.go
When we query the system tables to list potential secondary unique indices for discovery, we need to filter out included non-key columns.
This fixes https://github.com/estuary/connectors/issues/773
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/776)
=> source-sqlserver: Filter included columns from index enumeration

source-mysql/main.go, source-sqlserver/.snapshots/TestGeneric-SpecResponse, source-sqlserver/datatypes.go, source-sqlserver/datatypes_test.go, source-sqlserver/discovery.go, source-sqlserver/main.go, sqlcapture/timezone.go
Support for the `DATETIME`, `DATETIME2`, and `SMALLDATETIME` columns is added by introducing a new configuration property 'Time Zone' whose value should be an IANA Time Zone name or `-HH:MM` numeric offset, and using that location to interpret the contents of `DATETIME` and friends.
This is basically the same as how we do things in MySQL, except here we're not even trying to autodetect a time zone from the server configuration.
The new time zone property is added at the top level of the configuration so all new users should see it. The default value according to the JSON schema should be `"UTC"` and likewise if the property is empty (as it will be for existing captures) it will default to `"UTC"`.
This fixes https://github.com/estuary/connectors/issues/772
**Workflow …
=> source-sqlserver: Fully support `DATETIME` columns

source-sqlserver/datatypes_test.go, source-sqlserver/discovery.go
The `hierarchyid` column type is a weird one. It's an ultra- compact representation of an arbitrary node position within a tree, encoded using an undocumented variable-length binary code of some sort.
When we receive these values from the SQL Server client library they're still in their `[]byte` form, and given that (as far as I can determine) there is no publically available documentation [1] of this binary representation I don't think we should be in the business of decoding them.
So this change amounts to telling our discovery logic that a `hierarchyid` column will be serialized into a base64 string and calling it a day.
This fixes https://github.com/estuary/connectors/issues/771
[1] The best documentation I could find about the actual encoding of this data was …
=> source-sqlserver: Support `hierarchyid` column type

source-postgres/datatype_test.go, source-postgres/discovery.go
Convert infinity and negative infinity to their best equivalent RFC3339 timestamp fields of `"9999-12-31T23:59:59"` and `"0000-01-01T00:00:00Z"`, respectively. Previously these were output from the connector as the integer values `1` and `-1`.
Closes https://github.com/estuary/connectors/issues/780
Capture from a table with `infinity` or `-infinity` and it will work without a schema violation.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/781)
=> source-postgres: handle infinity values for timestamp fields

go/pkg/slices/slices.go, materialize-bigquery/sqlgen.go, materialize-firebolt/.snapshots/TestDriverSpec, materialize-firebolt/config.go, materialize-firebolt/driver.go, materialize-mongodb/driver.go, materialize-postgres/driver.go, materialize-postgres/sqlgen.go, materialize-redshift/sqlgen.go, materialize-snowflake/sqlgen.go, materialize-sql/driver.go, materialize-sql/validate.go, materialize-sqlite/sqlgen.go, source-kinesis/connection.go, source-kinesis/discovery.go, source-kinesis/main.go, source-mongodb/main.go, source-postgres/main.go
We have a similar function for determining if a slice contains an element copied in many connectors. This consolidates that into a common function that can be used amongst all connectors.
There are also a few minor cleanups that I noticed while updating these function call sites.
I changed the function signature of our previous standard "slice contains" function to take the slice first and then the element to look for, which is the reverse of how it was. This seems more in line with similar functions, like the one in [golang.org/x/exp](https://pkg.go.dev/golang.org/x/exp/slices#Contains).
N/A
(anything that might help someone review this …
=> refactor: consolidate "slice contains" logic

source-sqlserver/.snapshots/TestScanKeyTypes-UniqueIdentifier, source-sqlserver/.snapshots/TestUUIDCaptureOrder, source-sqlserver/datatypes.go, source-sqlserver/datatypes_test.go, source-sqlserver/main_test.go
The way that SQL Server orders `uniqueidentifier` columns is completely insane (see also: https://devblogs.microsoft.com/oldnewthing/20190426-00/?p=102450). But by adding some logic to reorder the byte representation we can produce a serialized form that sorts lexicographically, and then invert that shuffle when decoding the key for the next backfill query.
Note that this shuffling is _different_ from what we do to serialize them as JSON UUIDs, because the way in which SQL Server screws up comparisons ordering is _entirely different_ from how we already knew that it screws up endianness between a human-readable `"00112233-4455-6677-8899-AABBCCDDEEFF"` input and the resulting partially-endian-swapped `33 22 11 00 55 44 77 66 88 99 AA BB CC DD EE FF` bytes we get back later …
=> source-sqlserver: Encode UUID row keys for correct sorting

source-mysql/replication.go
I'm unsure why/how `SAVEPOINT` would show up as a query event at all, but it's not inherently a problem. Now a `ROLLBACK` might be a bigger concern, but we'll deal with that if it comes up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/787)
=> source-mysql: Ignore SAVEPOINT query events as benign

materialize-sql/validate.go
Captures often produce collections with various `_meta/` fields. We have received feedback that these are usually not desirable to materialize by default, so this PR changes them to be optional rather than recommended.
A couple of notes:
- Existing materializations that included these fields will not be affected, since locations that are part of an existing materialization spec are validated as [recommended](https://github.com/estuary/connectors/blob/7a4dc720eb292418c3ab3e319e0e85a86eea3ba4/materialize-sql/validate.go#L154-L157)
- Some captures use part of `_meta` for the collection key, like filesource captures. This change does not affect that either, since collection keys will still be validated as "required" preferentially.
I manually tested this by creating a new …
=> materialize-sql: make `_meta/` fields optional instead of recommended

materialize-pinecone/.snapshots/TestSpecification, materialize-pinecone/client/client.go, materialize-pinecone/driver.go, materialize-pinecone/transactor.go, tests/materialize/materialize-pinecone/setup.sh, tests/materialize/materialize-pinecone/snapshot.json
We previously required a single string field as input for the embedding with the idea that it may
already exist in a collection, or be produced by a derivation.
This changes the connector to build an input from the selected fields of the materialization. The
input is arranged as "key: value" pairs on newlines with the value being the stringified
JSON-encoded of the field value. Since only scalar types are permitted this results in a reasonable
representation of the input data.
The embedding input or any other fields are no longer included as metadata, and only flow_document
is included as metadata so that it may be obtained from the results of a vector query.
Materializing to pinecone without needing a field called `input`, or explicitly setting one. …
=> materialize-pinecone: build input from selected fields

materialize-pinecone/client/client.go
Try to decode the error message from any OpenAI API response that isn't OK. We've observed a couple of non-OK response codes now and they seem to follow the same structure for the error message.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/800)
=> materialize-pinecone: decode openai api response error messages

source-postgres/replication.go
These are rare but I believe they might be able to cause the capture to fail just because we don't expect to see that message. They're irrelevant to us, so ignore them.
Also tweaks the 'unexpected message' error to use '%#v' which will hopefully tell us the actual type name so next time I won't have to simply guess what the offending message was.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/803)
=> source-postgres: Ignore 'ParameterStatus' messages

materialize-redshift/driver.go
If the connection attempt times out, we don't want to have the context cancelled for all remaining validation tasks.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/807)
=> materialize-redshift: use separate ping context for testing database connectivity

source-mysql/prerequisites.go
As requested in https://github.com/estuary/connectors/issues/797 this commit disables the "minimum supported version" check until we have a better idea what database versions we can actually support capturing from.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/812)
=> source-mysql: Disable database version prerequisite

source-mysql/datatype_test.go, source-mysql/discovery.go
These values occur if you have a column with a type such as `timestamp(6)` and insert the all-zeroes time into them.
We can handle this by just doing a prefix match for the zero `YYYY-MM-DD HH:mm:SS` part, since MySQL won't allow you to insert a value like `0000-00-00 00:00:00.123456` anyway -- the zero month/day are only allowed if it's the zero timestamp, so no information is lost by just doing a simple prefix match and replacing with a constant `0001-01-01T00:00:00Z` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/811)
=> source-mysql: Handle zero timestamps with fractional seconds

source-mysql/prerequisites.go
Adds a couple of log messages. These should be useful in general, but I'm adding them right now in order to debug a capture for which the sanity check appears to have not worked as it should.
I believe this change should be very safe, so I intend to YOLO merge it in order to get results that much faster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/816)
=> source-mysql: Additional logging on binlog expiry check

source-mysql/prerequisites.go
Previously we assumed that an error when querying the table `mysql.rds_configuration` must be "No Such Table" and would proceed to query the vanilla MySQL config variables next.
But apparently it's possible for the capture user to simply not have permission to access `rds_configuration` on an RDS MySQL database. In that case our binlog expiry sanity check will misbehave and basically fail-open. This is bad for the user, since we need to ensure that binlog segments won't be instantly deleted in the event of an error.
(Note that they can still enable the 'skip binlog retention sanity check' config option in lieu of granting permissions to this table, if that's a problem)
After this change, users running RDS MySQL with a setup where the `flow_capture` …
=> source-mysql: Handle RDS binlog configuration query errors

source-mysql/datatype_test.go, source-mysql/discovery.go
Apparently MySQL will never actually guarantee that your ENUM column doesn't contain illegal values. Note that this is distinct from nullability, an `ENUM(...) NOT NULL` column can still contain error values which will be represented by the empty string when you retrieve them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/821)
=> source-mysql: Always include `""` as possible ENUM value

source-firestore/pull.go
This makes it 4x harder for a collection of massive documents to make the connector get OOM killed. Though it can always still happen so long as we're using `(*DocumentIterator).GetAll()` so we might want to reconsider that in the future.
Going to YOLO merge this because it's just tweaking an integer constant and I'm doing a bit of debugging-in-production here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/827)
=> source-firestore: Lower backfill chunk size to 1024->256

go.mod, go.sum, source-postgres/datatype_test.go, source-postgres/discovery.go, source-postgres/replication.go
- Normalize `format: time` values to be RFC3339 times (specifically the timezone needs to be normalized). This pull-request only works when we have https://github.com/estuary/flow/pull/1114 also merged since we currently do not support timezone offsets in `format: time` in our jsonschema validation logic
- - - …
=> sqlcapture: normalize time values to be RFC3339

materialize-redshift/driver.go, materialize-redshift/staged_file.go
This configures the S3 uploader to use a single goroutine for uploading a file in attempts to minimize memory usage of the connector.
We already have a fairly high degree of concurrency for uploads just from the fact that many materializations have more than 1 binding - sometimes many more. And each binding actually gets a separate upload thread for both loads and stores.
I am not totally confident that for the kinds of uploads we are doing (with an `io.Reader` and not an `io.ReadSeeker`) that multiple goroutines are used for uploads, but there is some sparse documentation suggesting that memory usage is directly related to the concurrency factor so this seems like it is worth a try. …
=> materialize-redshift: minimize concurrency for upload workers

materialize-redshift/.snapshots/TestSQLGeneration, materialize-redshift/driver.go, materialize-redshift/sqlgen.go
Setting these configuration options enables automatic truncation of strings too long to fit in a `VARCHAR(MAX)` column or `VARCHAR` field of a `SUPER` column. This, it would seem, is preferable to the connector being unable to materialize collections containing these strings at all.
See AWS documentation for [TRUNCATECOLUMNS](https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-conversion.html#copy-truncatecolumns) and [parsing options for SUPER](https://docs.aws.amazon.com/redshift/latest/dg/super-configurations.html#parsing-options-super).
Materialize collections with very long strings directly, though in a truncated state, per Redshift's limits.
The `materialize-redshift` documentation will need …
=> materialize-redshift: truncate strings longer than VARCHAR limits

source-mysql/replication.go
All `FLUSH FOO` queries should be entirely irrelevant to our capture connector.
Also fixes the logging of these benign queries so that they'll be visible at DEBUG level if we need to see them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/842)
=> source-mysql: Ignore all 'FLUSH' query events in replication

materialize-snowflake/sqlgen.go, materialize-snowflake/sqlgen_test.go, materialize-sql/type_mapping.go, materialize-sql/type_mapping_test.go
Strings ending in a 0 decimal part like "1.0" or "3.00" are considered valid as integers per JSON specification (see https://github.com/estuary/flow/pull/1069) so we must handle that possibility in SQL materializations that convert these string values to integers. Anything after the decimal is discarded on the assumption that Flow has validated the data and verified that the decimal component is all 0's. …
=> materialize-sql: handle strings formatted as integers with decimals of 0

materialize-sql/endpoint.go, materialize-sql/validate.go
The schema inference system currently indicates that all collection fields are nullable, including collection keys. SQL materializations have been enforcing that collection key fields be not-nullable, which results in additional complexity when trying to set up a SQL materialization for a collection with an inferred schema.
This change allows SQL materializations to validate even if the collection keys are nullable. Practically speaking, we do not expect the connector to see a null value for a key, as the minimal write schemas for inferred collections are generated with non-nullable keys.
In the future we would like to enforce this in a more refined way, by allowing nullable keys only if they have a default value. This would ensure that SQL materializations would not see …
=> materialize-sql: allow materializing nullable collection keys

materialize-bigquery/bigquery.go, materialize-bigquery/bigquery_test.go
Verify that the configured credentials are valid JSON, to provide a more instructive error message than `bigquery.NewClient` provides if given credentials that are not formatted as JSON.
Closes https://github.com/estuary/connectors/issues/822
- - - …
=> materialize-bigquery: verify that credentials are valid JSON

materialize-bigquery/bigquery.go
Hotfix to https://github.com/estuary/connectors/pull/847 - we do have some legacy tasks that were setup with base64-encoded credentials, and already have a compatibility layer for these.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors …
=> materialize-bigquery: allow base64 credentials to validate if valid json

materialize-bigquery/.snapshots/TestSQLGeneration, materialize-bigquery/sqlgen.go
- FLOAT64 can represent a larger range of values than BIGNUMERIC, and although BIGNUMERIC is better suited to loss-less numerics, in case of `format: number`, they will be processed using a double representation, which means we don't gain anything from using BIGNUMERIC here.
- - - …
=> materialize-bigquery: use FLOAT64 for format: number

source-mysql/replication.go, source-postgres/.snapshots/TestTruncatedTables-capture2, source-postgres/.snapshots/TestTruncatedTables-capture2-fails, source-postgres/capture_test.go, source-postgres/replication.go
Table truncation is a bit of a weird middle ground, where its formal semantic meaning is something like "delete all existing rows" but in practice it's often used as a way of expunging old data simply to keep tables small.
In Postgres and MySQL, table truncation is reported as its own event type, distinct from row deletions. And we don't have any good way to convert a truncate event into a sequence of deletions because that would require keeping track of every single row in a table as part of our persistent capture state, which obviously doesn't scale.
So for now the best thing we can do within our data model is to ignore them. The good news is that this is often what the user would like to have happen, but we may need to revisit whether there's any way to model the …
=> source-{mysql,postgres}: Ignore TRUNCATE events

materialize-bigquery/.snapshots/TestSQLGeneration, materialize-bigquery/sqlgen.go
Clean revert of commit d50650d60ba08e42eff1bcfdc623f6841067bf36.
There is actually a compatibility issue with this change, since BigQuery does loads via an external file, which itself is defined with a strict schema that prevents values typed as float64 from being added to existing bignumeric columns, even though the JSON encoding is compatible.
- - - …
=> Revert "materialize-bigquery: use FLOAT64 for format: number"

source-http-ingest/src/server.rs
This is kind of a quick and dirty fix to make sure we log request errors due to invalid JSON. These were not previously logged because parsing failed in the axum json extractor, so axum sends the response automatically. The normal request logging only logs the status, though, and we want to log the whole body, at least for now. So we'll probably end up doing some more refactoring of this soon, but for now this ought to get us what we need.
One other potentially unrelated fix here is upping the request body limit from the default of 2MiB to 64MiB, which matches the maximum document size allowed by Flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/8 …
=> source-http-ingest: log json parse errors

source-http-ingest/Cargo.lock, source-http-ingest/Cargo.toml, source-http-ingest/src/server.rs
The previous commit seems to have broken request decompression.  This commit fixes it. TBH, I don't actually see why decompression ever would have worked in the first place, which makes me suspicious that there was some sort of issue in my earlier test setup. In other words, this might just be implementing request decompression for the first time, rather than fixing a regression.
In either case, this explicitly adds a request decompression middleware.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/858)
=> source-http-ingest: handle request decompression

source-mysql/discovery.go
The empty string is not valid JSON and so if we somehow got an empty string from a `json` column and made it a `json.RawMessage` it would fail later on when we tried to serialize it.
We have reason to believe that this can happen, and if it does in fact happen it seems reasonable to translate the empty string into JSON `null`.
(See https://bugs.mysql.com/bug.php?id=98496 for one way that this sort of situation could arise)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/860)
=> source-mysql: Translate empty `json` columns as `null`

source-mysql/datatype_test.go, source-mysql/discovery.go, source-mysql/main_test.go
Tweaks value translation logic to normalize invalid enum values to `""`. This happened automatically via backfills, but replication will give us the enum values as an integer and we have to translate `0` as `""` ourselves.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/867)
=> source-mysql: Normalize invalid enum values to ""

sqlcapture/capture.go
If the selected primary key for a binding changes (most likely because the binding has been changed to point at a new collection whose key is different) then we shouldn't really care so long as we're not in the middle of an ongoing backfill.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/868)
=> sqlcapture: No error if primary key changes after backfill

source-mysql/.snapshots/TestAlterTable_Unsupported-capture2-fails, source-mysql/.snapshots/TestAlterTable_Unsupported-capture3-fails, source-mysql/replication.go
I have examined the parser AST structs and have added explicit failure cases for the types of table alteration which I believe might possibly be an error, then changed the default to ignore any of the other 14 alteration types that we don't need to care about because they're totally irrelevant to our capture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/870)
=> source-mysql: Ignore many benign table alterations

source-mysql/replication.go
We don't care about non-primary key constraints at all, and I think it's safe to allow dropping the primary key constraint too, since we do support capturing from tables without a primary key in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/871)
=> source-mysql: Allow ALTER TABLE to drop key constraints

materialize-pinecone/client/client.go, materialize-pinecone/driver.go
Users may specify their own embeddings model to use, and currently if it does not exist the connector will fail when it first runs and tries to create an embedding for a document.
This change allows the connector to validate that the embedding model is one recognized by OpenAI.
Closes https://github.com/estuary/connectors/issues/801
- - -
This change …
=> materialize-pinecone: verify that embeddings model exists during validate

materialize-bigquery/.snapshots/TestSQLGeneration, materialize-bigquery/bigquery.go, materialize-bigquery/sqlgen.go, materialize-bigquery/transactor.go, tests/materialize/materialize-bigquery/cleanup.sh, tests/materialize/materialize-bigquery/fetch-data.go, tests/materialize/materialize-bigquery/snapshot.json
Instead of defining the external file schema from our current dialect definitions, introspect the exist table columns to build a schema that is ensured to be compatible with the table. This way we can change the dialect and as long as the JSON encoding of the values is the same, the loads from the external file will still work.
This allows for changing the materialized column for JSON type `number` to be a `FLOAT64`, and for it to be backward-compatible with existing `BIGNUMERIC` columns.
This was tested by setting up a materialization on the old connector with a `number` type in the schema, materializing a bit of data, switching to the version of the connector from this PR, and then materializing some more data. Also, for the column introspection to EDC schema part, I …
=> materialize-bigquery: use schema from table for edc file

materialize-bigquery/transactor.go
If an alternate billing project ID has been set, we need to use the configured project ID for querying table metadata.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/874)
=> materialize-bigquery: use DatasetInProject for table metadata

materialize-boilerplate/boilerplate.go, source-boilerplate/boilerplate.go
Runs an HTTP server with `pprof` for go-based materialization and capture connectors.
It runs on port `6060` and is accessible via localhost. So to access the server, you need to be able to exec into the reactor pod running the connector container, and then exec into the container itself. The ergonomics of this are not great but it is still very useful to be able to access the endpoints for pprof.
For example, you can get a stack trace for the connector using a command like this:
```
kubectl exec -it <REACTOR_POD> -- docker exec -it <CONTAINER_NAME> curl http://localhost:9000/debug/pprof/goroutine?debug=1
```
As a next step, we can `EXPOSE` a port in the dockerfiles of these connectors, so that they can be accessed via connector networking. Prior to this we should make …
=> connectors: run pprof for go connectors

source-postgres-batch/main.go
This makes naive postgres-to-postgres sync workflows Just Work without complaining about `xmin` being a forbidden column name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/884)
=> source-postgres-batch: Select `xmin` as `txid`

source-postgres-batch/driver.go
This change should make it much clearer whether a particular update query is taking a long time or if the connector is just waiting until the next scheduled polling time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/885)
=> source-postgres-batch: Improve task logging

source-postgres-batch/main.go
During the rewriting I guess I accidentally removed the query clause `ORDER BY xmin::text::bigint`. But we still need that, since the `WHERE xmin > $1` part only works if we can assume that the last value of the previous iteration was also the largest `xmin` value. Which I think is generally true by default, but we shouldn't assume that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/879)
=> source-postgres-batch: Order query results by xmin

source-mysql/.snapshots/TestAlterTable_Unsupported-capture2-fails, source-mysql/.snapshots/TestAlterTable_Unsupported-capture3-fails, source-mysql/.snapshots/TestAlterTable_Unsupported-capture5, source-mysql/.snapshots/TestAlterTable_Unsupported-capture6, source-mysql/discovery.go, source-mysql/main_test.go, source-mysql/replication.go
This commit adds support for `ALTER TABLE foo CHANGE COLUMN` and `ALTER TABLE foo MODIFY COLUMN` queries in cases which don't actually rename or reposition the columns. It's possible in theory to add support for renaming/repositioning (since the effects are basically the equivalent of a DROP / ADD sequence) but I have opted to omit that part in order to get a quick fix together for the simple case.
I also factored out the datatype parsing in discovery into a separate function, because I thought it was the same logic as we use in replication event processing. It turns out the two functions are subtly different but I think the code looks nicer factored-out so I'm hesitant to revert it even though it's a completely unrelated change.
- - - …
=> source-mysql: Support `ALTER TABLE foo CHANGE ...` sometimes

source-postgres-batch/driver.go
When a table has a primary key the connector will add corresponding properties to the collection schema with one of the Flow scalar key types `"integer"`, `"string"`, or `"boolean"` and mark them as required. The column names will be escaped as JSON pointers and recommended as the collection key.
The key types are translated according to a very sophisticated algorithm of looking at the `data_type` column of `information_schema.columns` and translating `"integer"` / `"bigint"` / `"smallint"` to JSON `"integer"`, `"boolean"` to `"boolean"`, and everything else to a JSON schema `"string"`.
If there's no primary key the fallback collection key of `["/_meta/polled", "/_meta/index"]` will be recommended.
- - - …
=> source-postgres-batch: Suggest collection keys

source-dynamodb/.snapshots/TestDiscovery-additional_table_without_stream_enabled, source-dynamodb/.snapshots/TestDiscovery-multiple_tables_with_various_types, source-dynamodb/.snapshots/TestDiscovery-single_table_with_a_partition_key, source-dynamodb/discovery.go
`x-infer-schema` needs to be a "top level" property in the schema, rather than being nested within the `allOf`.
Discovered collections from this connector will have the schema inference button enabled in the UI.
N/A
Tested with a local stack to make sure the button appears after this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/889)
=> source-dynamodb: fix x-infer-schema annotation for discovered schemas

materialize-snowflake/snowflake.go
Adds the name of the table to the error message for a failed copy or merge operation during the Store phase.
One way this operation can fail is if the size of a single JSON document exceeds the maximum allowable by Snowflake. It is currently difficult to tell which collection a very large document is coming from, since Snowflake does not return the name of the table with its error message.
(anything that …
=> materialize-snowflake: report table names on store errors for copy & merge

materialize-redshift/.snapshots/TestSQLGeneration, materialize-redshift/driver.go, materialize-redshift/sqlgen.go, materialize-redshift/sqlgen_test.go
It's possible for collection keys that are strings to be longer than the 255 bytes permitted in a Redshift TEXT column. In this case the load table needs to be created with wider VARCHAR columns to hold the full string value.
We'll keep track of the longest string key values seen for a load transaction, and if it ends up being longer than 255 bytes the load table will be created with all VARCHAR columns wide enough for the longest value seen. Also we will explicitly disable truncation of column values for the load tables, since this could lead to data inconsistency for very long string keys with identical leading 65,535 bytes. That brings along the limitation that string fields used as keys can't be any longer than 65,535 bytes, which doesn't seem totally unreasonable. …
=> materialize-redshift: handling for long strings as load keys

sqlcapture/capture.go
The hope is that the Go format `%#v` will produce a reasonable rendering of the value that's failing JSON marshalling so we can figure out how exactly things are going wrong in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/894)
=> sqlcapture: Log document contents when JSON serialization fails

source-mysql/.snapshots/TestGeneric-SpecResponse, source-mysql/main.go, source-postgres/.snapshots/TestGeneric-SpecResponse, source-postgres/main.go, source-sqlserver/.snapshots/TestGeneric-SpecResponse, source-sqlserver/main.go
Subsequent to https://github.com/estuary/connectors/pull/898 which removed the large in-memory buffer of backfill results (and thus made connector memory usage independent of backfill chunk size) and some Slack discussion about why we still don't want to set this to 1M or something absurd, we decided to bump this up to "something greater than 32,768 but less than 65,536"
Despite the fact that we've been using powers of two for this in the past there's no actual technical requirement or performance related reason that it be a power of two, and a sum of powers such as `48*1024 = 49,152` isn't as instantly recognizable anyway, so I figure we might as well make it look nice to less technical users and have instead increased the default to 50,000 here.
- - -
This change …
=> source-{mysql,postgres,sqlserver}: Backfill chunk size 50,000

materialize-snowflake/snowflake.go, materialize-sql/driver.go
Creating hundreds of tables in a single apply operation takes quite a while when run using a single statement. This change creates batches of table creation statements and runs them with concurrent workers.
Snowflake does not support DDL statements in transactions, so there's no reason to run them as part of a transaction. We just need to make sure the materialization spec update happens only after all of the table alterations are complete.
With this strategy, we can create several hundred tables within the 5 minute timeout period allowed for an Apply RPC.
Create a materialization with up to ~300 bound collections. For testing purposes I used 400 tables. The Apply action takes 1-2 minutes with this many tables. I was also able to materialize documents …
=> materialize-snowflake: batch table creation and run batches concurrently

source-mysql/replication.go, source-postgres/replication.go, source-sqlserver/replication.go, sqlcapture/capture.go, sqlcapture/interface.go
When no replication events have been processed for over a minute but we're expecting to observe a watermark that we wrote, something has gone badly wrong between the database and the connector. Let's make this sort of failure a bit more debuggable by running a database-specific 'ReplicationDiagnostics' hook which executes various diagnostic queries and logs the results.
Currently only implements diagnostic queries for MySQL. For other databases this is a no-op and leaves us no worse off than before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/904)
=> sqlcapture: Run replication diagnostics on unexpected idle

source-mysql/replication.go
Adds `SHOW BINARY LOGS` to the MySQL replication diagnostics hook.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/906)
=> source-mysql: Another replication diagnostic

source-firestore/discovery.go, source-firestore/pull.go
This PR makes several changes which I hope should all contribute to making change streaming more reliable.
To recap: The fundamental challenge that `source-firestore` grapples with frequently is that when we first open a `Listen` RPC for some stream, **we must catch up to the present time within 10 minutes at most** or else Firestore will cut us off and we won't even have an updated resume cursor for our trouble.
This PR does several things which should hopefully make it more likely that we'll get and remain caught up:
- A `WaitGroup` is added which keeps track of the number of replication workers which are _not_ currently caught up. Backfill workers consult this wait group before requesting any data and block unless/until it reaches zero. This should avoid situations …
=> source-firestore: Improve change streaming reliability (hopefully)

source-firestore/pull.go
I believe something screwy may be occurring in at least some of these cases and we're failing to catch up because Firestore is not actually sending us anything. But it's hard to be sure just from reading the debug-level logs because there's still plenty of change events from other collections, so logging the actual counter value on catchup failure should make this more blatantly obvious if it happens.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/912)
=> source-firestore: Log number of docs read before catchup failure

source-mysql/backfill.go
When performing a keyless backfill query, we essentially just want to paginate the table according to *some* stable ordering but we don't care what that ordering is. In the past we've done this by explicitly saying `ORDER BY <table columns>` to get a specific consistent ordering which we *hoped* would correspond with something the database could actually index on.
This seemed like a reasonable thing to hope for because the DB actually does index rows by their literal primary-key values for a keyed table, and one obvious way to extend that system to tables with no primary key would be to treat the entire row as the key.
However the way that MySQL actually handles this is by assigning every row in a keyless table a secret row ID value (which is actually taken from a global …
=> source-mysql: Assume `SELECT *` has stable result ordering

source-mysql/discovery.go, source-postgres/discovery.go, source-sqlserver/discovery.go, sqlcapture/capture.go, sqlcapture/discovery.go, sqlcapture/interface.go
Postgres discovery logic has long ignored views and other entities whose type is not `BASE TABLE`. Unfortunately it looks like MySQL and SQL Server discovery omitted that bit and would happily produce bindings for views, which will never really work properly since they don't have replication events.
This commit changes things so that MySQL and SQL Server discovery should correctly filter these entities, but in such a way that they do not produce an error at capture time for any preexisting captures. Instead views will be silently auto-ignored at capture time.
Hopefully we can unwind some of that logic later on once nobody has any views in their catalogs.
- - - …
=> sqlcapture: Ignore views and other non-BASE TABLE entities

source-boilerplate/testing/testing.go, source-postgres/.snapshots/TestDiscoveryExcludesSystemSchemas, source-postgres/.snapshots/TestPartitionedTableDiscovery, source-postgres/discovery.go, source-postgres/discovery_test.go
This partially addresses https://github.com/estuary/connectors/issues/751 (specifically point #2) but the other bits of polish (documentation updates and better error messages) are still needed at some point.
This commit factors out table-enumeration from column-listing for simplicity (because the query was starting to get hard to follow) and to match what we did for MySQL and SQL Server just yesterday.
The new table-enumeration query is completely different from the old one but I believe it returns the same set of tables as before, minus child partitions. I ran a couple of the discovery tests to spot-check the results and added a couple new ones, so I think it is correct.
As with the other connectors, the column-listing query no longer tries to also filter for table …
=> source-postgres: Exclude child partitions from discovery

source-sqlserver/discovery.go, sqlcapture/main.go
Just fixing a race between my collations work PR and Will Baker's update to Go 1.21
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/926)
=> sqlcapture: Replace our slices package with the standard one

source-sqlserver/Dockerfile
We run a lot of tests in CI and they should all pass most of the time, but if a single one fails then it can take a while before we actually learn this and there's really no reason to be waiting that long. So if one fails, stop the test run immediately so we get quicker feedback and/or an opportunity to retry if it looks like flakiness.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/927)
=> source-sqlserver: Stop CI tests on first failure

source-mysql/replication.go
Since we don't capture from views in the first place we should be fine to just unconditionally ignore these.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/931)
=> source-mysql: Ignore `(CREATE|ALTER|DROP) VIEW` statements

source-postgres/datatype_test.go, source-postgres/discovery.go, source-postgres/replication.go
Postgres permits timestamps with years from 4713 BC to 294276 AD, but we serialize timestamps to RFC3339 strings, which can only go from the year 0 AD to 9999 AD.
In general timestamps with years >9999 aren't actually real data, they're typos like `20231`. So instead of trying to get clever, we'll normalize any out-of-range values to `0000-01-01T00:00:00Z`.
An exception is currently made for the special `infinity` timestamp value, which is still translated as `9999-12-31T23:59:59Z`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/933)
=> source-postgres: Normalize unrepresentable timestamps to zero

materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go, materialize-bigquery/transactor.go, materialize-redshift/.snapshots/TestSpecification, materialize-redshift/driver.go, materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/snowflake.go, materialize-sql/driver.go, materialize-sql/update_delay.go, tests/materialize/materialize-bigquery/setup.sh, tests/materialize/materialize-redshift/setup.sh, tests/materialize/materialize-snowflake/setup.sh
Adds an "update delay" configuration to BigQuery and Redshift, identical to the one Snowflake has (see https://github.com/estuary/connectors/commit/66a370c84b27e3f64fa4f83662d1fa5d23b86e59).
Also sets a default delay of 30 minutes unless otherwise configured, and lowers the store threshold for skipping the delay to 1 million documents.
Docs will need updated for both connectors to reflect the additional configuration option
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connector …
=> materialize-{redshift,bigquery}: add "update delay" advanced configuration

source-mysql/replication.go
These don't parse successfully (at least in some cases) but we also don't care about them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/934)
=> source-mysql: Ignore `DROP TRIGGER` query events via regex

source-firestore/.snapshots/TestAddedBindingSameGroup-one, source-firestore/.snapshots/TestAddedBindingSameGroup-two, source-firestore/.snapshots/TestBindingDeletion-one, source-firestore/.snapshots/TestBindingDeletion-three, source-firestore/.snapshots/TestBindingDeletion-two, source-firestore/.snapshots/TestDeletions-one, source-firestore/.snapshots/TestDeletions-two, source-firestore/.snapshots/TestManySmallWrites-one, source-firestore/.snapshots/TestManySmallWrites-two, source-firestore/.snapshots/TestMultipleWatches-one, source-firestore/.snapshots/TestMultipleWatches-two, source-firestore/.snapshots/TestSimpleCapture-one, source-firestore/.snapshots/TestSimpleCapture-two, source-firestore/main_test.go, source-firestore/pull.go
Modifies `source-firestore` so that when a change stream fails to catch up in time it will:
1. Immediately skip ahead to the current time and continue streaming changes from there.
2. Set a new 'Inconsistent' flag on the resource state, indicating that the output is no longer guaranteed to be perfectly consistent with the source dataset.
3. Fire off a sneaky timer in the background which will force a connector restart after a good long while, which gives the connector an opportunity to re-establish consistency at startup (and avoids the complexity of cancelling and restarting backfills at arbitrary times).
In addition, the connector will now trigger a new backfill of any inconsistent bindings the next time the connector restarts, while also skipping the change stream …
=> source-firestore: Restart failed streams, skipping ahead to the current time

materialize-snowflake/snowflake.go
Fixes an apparent bug where the connector was not using a transaction to actually merge or copy new documents into the target table. The history of code changes does not indicate that this bug is due to a recent change, and with the way operations are ordered it was unlikely to ever cause a problem, especially if materializations were run using only a single shard.
Tested by running the integration tests locally.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/947)
=> materialize-snowflake: store documents in transaction

source-mysql/replication.go
Just a small error-reporting tweak: Adds the name of the unhandled statement-node type to the resulting error message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/948)
=> source-mysql: Log unhandled replication statement types

source-mysql/replication.go
Apparently `ANALYZE TABLE` queries show up in the binlog and then get parsed into a `*sqlparser.OtherRead`. These should be entirely ignorable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/950)
=> source-mysql: Ignore 'OtherRead' statements

materialize-pinecone/.snapshots/TestSpecification, materialize-pinecone/client/client.go, materialize-pinecone/driver.go, tests/materialize/materialize-pinecone/fetch-data.go
Pinecone free tier starter pods can't use namespaces, we need to not use a namespace when the target index pod is a "starter". This means that an index on a starter pod can also only have a single binding.
Do a materialization on a Pinecone free tier account with a starter plan pod. This will succeed if you have a single binding with an empty (empty string) for the namespace.
Pinecone materialization docs should be updated with this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/951)
=> materialize-pinecone: allow empty namespaces and enforce a single binding with empty namespace for starter plans

materialize-dynamodb/transactor.go, materialize-mongodb/driver.go, materialize-mongodb/spec.go, materialize-mongodb/transactor.go, tests/materialize/materialize-mongodb/fetch.sh, tests/materialize/materialize-mongodb/setup.sh, tests/materialize/materialize-mongodb/snapshot.json
In practice we have seen problems with using MongoDB transactions for storing documents related to a
low default transaction timeout on MongoDB servers, and high memory usage on the server for large
transactions, which is probably why there is a fairly low default transaction timeout.
This converts the connector to an "at least once" style of materialization, forgoing the use of
transactions. With these changes, the materialization will work with unbounded Flow transaction
sizes, and be able to achieve "at least once" semantics in the general case, and "effectively once"
when idempotent reductions are used.
This PR also updates the connector to use bulk operations for loads and stores, which is a significant
performance improvement. Loads are done using the `find` …
=> materialize-mongodb: don't use transactions

source-mysql/replication.go
A while back I made a list of all the table alterations which seemed like they could possibly be an issue, and made those all explicit errors so the default could be to ignore unhandled alterations (since there are a ton of benign ones).
This list was a little bit over-broad, and as far as I can see there is no way for an `ALTER COLUMN` clause to ever be a problem (since they just modify column defaults and a couple of other properties we don't care about) so these should be ignored as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/958)
=> source-mysql: Ignore ALTER COLUMN table alterations

source-mongodb/pull.go
- Instead of a global condition for starting backfill (this was never intentional AFAIK), check whether that specific binding has state or not
- Key the checkpoint with collection name and resource config, so that by changing the collection name it is possible to trigger a re-backfill
- - - …
=> source-mongodb: backfill when binding has no state

materialize-mysql/sqlgen.go, materialize-postgres/sqlgen.go, materialize-redshift/sqlgen.go, materialize-snowflake/sqlgen.go, materialize-sql/type_mapping.go, materialize-sqlite/sqlgen.go, materialize-sqlserver/sqlgen.go
Fixes an oversight from #946: We historically have not converted strings with integer or number format to their equivalent numeric type if they are collection keys, and need to continue to not do that. This is mostly because "number" types are usually converted to floats, which cannot be used as table primary keys.
It could possibly be argued that strings formatted as integers should be able to be materialized as integer primary keys. There's an option for that for (new) connectors going forward, but for now we need to keep the behavior the same to maintain compatibility. It may also be possible to change this later with some kind of table introspection, where the connector is able to convert types based on the actual table columns, but that would take significantly more …
=> materialize-sql: don't use numeric types for numeric formatted strings that are primary keys

source-postgres/.snapshots/TestGeneric-SpecResponse, source-postgres/discovery.go, source-postgres/main.go
This commit adds a new advanced config option containing a list of strings. If unset the connector will continue to operate as always, but if this list is non-empty then discovery will only return tables in schemas which are part of that list.
I have confirmed that this doesn't break any of our existing test suite and also verified manually that the filtering logic works as expected.
I'm not entirely happy with the field title/description text, I just wrote the first thing that came to mind so we could get this out. I'm also not entirely sure if this array of strings will look good in the UI form or if a single text input for a comma-separated list of schema names might be better.
Nothing should change by default, but users can now explicitly select …
=> source-postgres: Advanced config option for discovery schemas

source-postgres/discovery.go, sqlcapture/discovery.go, sqlcapture/interface.go
We use the same table-discovery logic inside of a capture in order to get various table metadata, and it's possible for a table to be a configured binding even if it's excluded from discovery. Likewise the watermarks table may be accessible and in use even if it's in a schema which has been filtered out, and that shouldn't be an error.
I've verified that this doesn't break the discovery filtering logic or normal captures, however I haven't actually gone to the effort of reproducing a capture which fails because of the old way it worked. I'm fairly confident this will fix it nonetheless.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/963)
=> source-postgres: Only apply schema filtering to catalog discovery

materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/snowflake.go
If the Snowflake user does not have a default warehouse set for their account and there are multiple possible warehouses, there will be no active warehouse if one is not set in the endpoint configuration.
Currently we pass validation in this case and later fail during apply. This change verifies that there is an active warehouse for the endpoint configuration during validation.
Closes https://github.com/estuary/connectors/issues/942 …
=> materialize-snowflake: fail validation if there is no active warehouse

.github/workflows/ci.yaml, source-boilerplate/testing/testing.go, source-kinesis/.snapshots/TestKinesisCapture, source-kinesis/.snapshots/TestSpec, source-kinesis/Dockerfile, source-kinesis/capture.go, source-kinesis/capture_test.go, source-kinesis/connection.go, source-kinesis/docker-compose.yaml, source-kinesis/main_test.go, source-kinesis/shard_range_test.go, source-kinesis/testdata/kinesis-config.json, tests/source-kinesis/cleanup.sh, tests/source-kinesis/setup.sh
- Uses `localstack` docker containers for Kinesis integration tests instead of actually calling to the real AWS API.
- Moves the "endpoint" configuration to an advanced option, which is consistent to other AWS captures
and materializations. This is not a field that a user is ever likely to use. There aren't any
existing kinesis captures that use this field, so this is not a breaking change.
- Also cleans up and fixes the set of capture tests for Kinesis, which had gotten into quite a state
of disarray.
Closes https://github.com/estuary/connectors/issues/864
N/A
- - - …
=> source-kinesis: use localstack for integration tests 

materialize-sql/type_mapping.go
This field represents "soft deletes" and people usually want it to be materialized, even if they don't know about it when initially creating their materialization, so include it in the list of "recommended" fields.
- - - …
=> materialize-sql: recommend `_meta/op` field for materialization

materialize-elasticsearch/driver.go, materialize-elasticsearch/driver_test.go
We have a pretty long retry duration setup for allowing extended retries of retryable errors for data-related operations, but this does not work well when performing connectivity checks.
A prime example is if the server is using a self-signed certificate, which we currently do not support. This will return a 5xx error that is currently retried, and will result in a timeout cancellation and mask the real error.
We could theoretically try to discriminate errors even further to decide which ones to retry, but for now it seems generally safer to fail fast when doing validation connectivity checks and allow the user to be the retry mechanism. …
=> materialize-elasticsearch: don't retry errors during Validate

source-boilerplate/boilerplate.go, source-mongodb/.snapshots/TestCapture, source-mongodb/main.go, source-mongodb/main_test.go, source-mongodb/oplog.go, source-mongodb/pull.go, source-mongodb/test_util.go
- A new checkpoint structure which allows distinguishing between Backfill and Streaming states, and tracks last backfilled item, timestamp of backfill start, and resume token for streaming
- Converts old checkpoints to the new model
- Use `RawValue` for storing `BackfillLastId` so that we can be sure that we are not losing the original value of the `_id` during decoding and encoding processes of mongodb driver and/or checkpoint …
=> source-mongodb: incremental backfill

source-postgres/backfill.go
Explicitly sorting on CTID is more strictly correct, but in practice can cause backfill queries to take minutes or even hours to execute. There are two ways we could fix this:
1. Write some additional logic to issue CTID-range queries (for which there *is* a fast path in the Postgres query planner, compared to `ORDER BY ctid LIMIT n OFFSET m` which has no such special casing).
2. Just assume that results will actually be in order if we omit the `ORDER BY` clause entirely.
Since it's so much simpler, we're opting for option (2) here.
Note that it's not even strictly necessary that the results be in CTID order so long as they're in a *stable* order between backfill queries. And while there's no explicit guarantee of that, in practice it appears to be the case.
**Workflow …
=> source-postgres: Assume keyless backfills are ordered by CTID

source-postgres/.snapshots/TestDiscoveryWithoutPermissions, source-postgres/discovery.go, source-postgres/discovery_test.go
This commit replaces the old column-discovery query with a drop-in replacement which uses various `pg_catalog` tables instead of `information_schema.columns` and thereby avoids the `has_column_privilege()` check which is part of that view.
Previously it was possible for the capture user to have sufficient permissions to discover a table and its primary key, but the column-discovery query would return no information. This would result in a generated schema like:
```
{
"schema": {
"$defs": {
"foobar": {
"type": "object",
"required": [ "id" ],
"$anchor": "foobar",
"properties": {}
}
},
"allOf": [
{ ...the usual _meta portion of the schema... },
{ "$ref": "#foobar" }
]
},
"key": [ "/id" ]
}
```
And because that schema doesn't constrain the primary-key types in any way this …
=> source-postgres: Fix column discovery when lacking permissions

source-postgres/backfill.go
Previously our keyless backfill queries worked by going
SELECT * FROM table ORDER BY ctid LIMIT n OFFSET m;
This worked in a theoretical sense, but on large tables it forced the database to sort the entire dataset on every query because the query planner doesn't recognize that `ORDER BY ctid` can be done more efficiently than that.
After this change our keyless backfill queries will look like:
SELECT ctid, * FROM table WHERE ctid > $1 LIMIT n;
This should be considerably more efficient because the Postgres query planner has a special case for this (see tidpath.c):
> EXPLAIN SELECT ctid, * FROM \"test\".\"foobar\" WHERE ctid > $1 LIMIT 100;
QUERY PLAN=Limit  (cost=0.00..1.97 rows=100 width=42)
QUERY PLAN=  ->  Tid Range Scan on foobar  (cost=0.00..32.51 rows=1651 width=42) …
=> source-postgres: Use `WHERE ctid > $1` in keyless backfills

materialize-mysql/VARIANTS
Adding Aurora and MariaDB variants for MySQL materialization connector.
Standard addition of 2 new variants for our MySQL materialization connector
We need docs for the following connectors (including these) which I will add separately:
- MariaDB
- Aurora for MySQL
- Gitlab
- Confluence
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/930)
=> Create VARIANTS for MySQL

source-mongodb/oplog.go
there are no indexes defined on the oplog.rs collection, and the recommendation is to use the $natural order (the order by which records are written to disk) in order to read from this collection. This works for oplog.rs since there are only insertions, and never updates, so the $natural order is the order in which records have been inserted. There are performance implications for using any sort other than $natural since all documents must be scanned for those sorts. …
=> source-mongodb: order on $natural instead of ts

source-mongodb/.snapshots/TestCapture, source-mongodb/discovery.go, source-mongodb/main_test.go, source-mongodb/pull.go, source-mongodb/test_util.go
- Add `_meta/op` to source-mongodb documents
- The tests helped find another issue, when emitting deleted documents we were not stringifying the `_id` the same way we do for other events, so there was a discrepancy there, fixed it.
- - - …
=> source-mongodb: _meta/op

materialize-snowflake/.snapshots/TestSQLGeneration, materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/snowflake.go, materialize-snowflake/sqlgen.go, materialize-snowflake/sqlgen_test.go
Snowflake sessions & transactions can span across different schemas. This change allows for resource-level schema configuration, similar to other SQL materializations like materialize-postgres.
Particular attention is given to making the change compatible with existing materializations: If no schema is set for a resource OR the resource schema is the same as the endpoint configuration schema (as will be the case for all existing tasks), the resource path is still just the name of the target table.
Manual testing was done to confirm that tables with alternate schemas than the endpoint configuration get updated & materialized to correctly and can co-exist with tables in other alternate schemas and/or the endpoint configuration schema. Also the "migration" scenario was …
=> materialize-snowflake: allow per-resource schema configuration

materialize-mysql/.snapshots/TestConfigURI-IncorrectSSL, materialize-mysql/driver.go, materialize-mysql/driver_test.go, materialize-sqlserver/driver_test.go
The MySQL driver didn't work with passwords containing special characters because of the URL escaping coming from `uri.String()`. Notably, this was causing Oracle HeatWave materializations to fail with an authentication error because these passwords require special characters. Using the `mysql.Config` to construct the DSN fixes that.
- - -
This change …
=> materialize-mysql: fix escaping issue with DSN

source-postgres/README.md, source-postgres/docker-entrypoint-initdb.d/init-user-db.sh, source-postgres/prerequisites.go
This fixes https://github.com/estuary/connectors/issues/751 (in combination with a Flow docs PR which I'll be merging around the same time)
This commit sets the `publish_via_partition_root` flag everywhere that `source-postgres` executes or documents a `CREATE PUBLICATION` query:
- When, during prerequisite validation, the connector autocreates a publication it will now also attempt to set the flag. It does this in a followup `ALTER PUBLICATION` query because versions of Postgres <13 don't have this option and we don't want the create query to fail in those cases.
- The example queries in the README now show it being set.
- The `init-user-db.sh` script which initializes the CI database for tests will now set it as documented in the README.
- - - …
=> source-postgres: Set `publish_via_partition_root` option

source-mysql/backfill.go
The failure of our `EXPLAIN ...` queries is entirely benign. That whole piece of logic is just to help us with debugging backfill query behavior, and if the explain queries all fail we will just shrug and keep going.
So in my opinion `WARN` severity is more appropriate than `ERROR` here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/892)
=> source-mysql: Downgrade EXPLAIN error logging to WARN

materialize-mongodb/docker-compose.yaml, tests/materialize/materialize-mongodb/cleanup.sh, tests/materialize/materialize-mongodb/fetch.sh, tests/materialize/materialize-mongodb/setup.sh
Since it turns out we can't actually use MongoDB transactions, we don't need to use a MongoDB cluster with a replica set, and can instead use a single node for our test setup. This removes some flakiness from the automated tests, and should make it easier to get a local MongoDB running with the compose file.
- - - …
=> materialize-mongodb: simplify test setup

source-postgres-batch/driver.go
Allocating outside the loop means that the first polling iteration on an empty table will transform a cursor `nil` into `[]any{nil}` (of appropriate length) which is counted as "not the first query" the next time we try polling.
We'd prefer to instead keep running the "start" query until the first time it produces data, so that allocation is moved inside the loop where it will only be executed the first time it's actually needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/987)
=> source-postgres-batch: Only allocate `cursorValues` if there's data

source-mysql-batch/.snapshots/TestSpec, source-mysql-batch/driver.go
Tweaks a the resource config schema metadata so it should look nicer in the UI, and hopefully with the cursor no longer marked as required the generated bindings from discovery won't fail the form validation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/990)
=> source-mysql-batch: Tweaks to work nicer in the UI

source-dynamodb/discovery.go, source-dynamodb/driver.go, source-dynamodb/main.go, source-dynamodb/pull.go
The DescribeStreams API has an account-wide limit 10 requests per second, which makes it
difficult to efficiently discover large numbers of tables without hitting that limit, or timing out
the discover.
Because of this, don't run DescribeStream for every discovered table's stream - it's just not
practical.
Also run `discoverTable` operations in parallel, since the DescribeTable API has a limit of 2,500
requests per second. And increase the maximum number of retries the clients will use to allow for a
degree of rate limiting from system backpressure during normal operation.
These changes allow a source with 100's of tables to be successfully discovered, at the expense of
only finding issues with disabled streams when the connector runs rather than during the publication …
=> source-dynamodb: parallelize discovery

source-dynamodb/stream.go
Info level logging for pruning a fully read shard is pretty spammy since it is directly redundant with having fully read the shard, so make that a debug log. Also add shard counts to the debug logging for a shard topology change.
- - - …
=> source-dynamodb: adjust debug logging

materialize-bigquery/.snapshots/TestSpecification, materialize-bigquery/bigquery.go, materialize-bigquery/sqlgen_test.go, materialize-bigquery/transactor.go
BigQuery sessions & transactions can span across different BigQuery datasets. This change allows for resource-level dataset configuration, similar to how other SQL materializations allow for resource-level schema configuration.
Resources already inherited the dataset from the endpoint configuration for constructing queries, and this change makes that configurable rather than only inherited.
See also https://github.com/estuary/connectors/pull/980, which did something like this for Snowflake.
Manual testing was done to confirm that separate bindings can co-exist with different datasets configured than each other + different than the endpoint configured dataset with its metadata tables, and also to confirm that the migration scenario of a prior materialization with no …
=> materialize-bigquery: allow per-resource dataset configuration

source-mysql-batch/.snapshots/TestSpec, source-mysql-batch/main.go
The default setting for this property should be leaving it unset, not `"mysql"`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/996)
=> source-mysql-batch: Remove default 'DBName' setting

source-mysql-batch/.snapshots/TestSpec, source-mysql-batch/driver.go, source-mysql-batch/main.go
When writing the initial implementation of `source-mysql-batch` I mistakenly assumed that the `go-mysql-org/go-mysql` implementation of the `database/sql` driver interface probably used streaming queries.
(This was an easy mistake to make since the `database/sql` result rows abstraction implements an iterator protocol which is clearly intended to allow streaming processing, and the MySQL client library does have methods for streaming query execution. I didn't think about it too hard and forgot about the extra steps we had to take to make streaming result processing work for the MySQL CDC connector.)
This PR replaces the use of `*sql.DB` with the lower-level `*client.Conn` representation and then explicitly uses a streaming query execution method when polling a binding.
It …
=> source-mysql-batch: Streaming queries and default polling interval

source-mongodb/.snapshots/TestCapture, source-mongodb/discovery.go, source-mongodb/discovery_test.go, source-mongodb/main_test.go
- Filter out [system collections](https://www.mongodb.com/docs/manual/reference/system-collections/) from discovered output
- Updated snapshots for tests 
- Run a discover on a database which has some of the system collections. The system collections show up when their respective feature is used. For example, `system.views` shows up if there is a view created in that database. `system.profile` shows up if profiling is enabled, etc. These collections should no longer be in the output of discovery.
- Tested both using our existing test suite, and a manual test
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing …
=> source-mongodb: filter out system collections from discovery

go.mod, go.sum, go/encrow/encrow.go, go/encrow/encrow_test.go, source-mysql-batch/driver.go
This adds a new helper package `./go/encrow` for serializing tabular data such as we get from SQL queries, and modifies `source-mysql-batch` to use this new package.
The helper package is more efficient than using the standard library `encoding/json` to serialize a `map[string]any` for two reasons:
1. The top level of document serialization is specialized to only work on objects with a specific arity and list of property names. This is represented with a new `encrow.Shape` abstraction.
2. Serializing the individual values of each document is done with the github.com/segmentio/encoding/json package, which is a micro-optimized JSON encoder/decoder package intended as a faster drop-in replacement for the stdlib one.
The specialization alone resulted in about a 3x speedup …
=> source-mysql-batch: Optimize document serialization

source-mysql-batch/driver.go
Just a minor cleanup pointed out in https://github.com/estuary/connectors/pull/1001, since the `SetDefaults()` logic fills in a default polling interval of `"24h"` we can assume the config property is non-empty later on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1004)
=> source-mysql-batch: Remove redundant 24h default poll interval

source-dynamodb/stream.go
Fixes a defect where a stream worker error would only be detected when the shard topology changes, rather than immediately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/999)
=> source-dynamodb: fail-fast if stream workers error

materialize-sql/encoder.go
The `stagedFile` abstraction used for BigQuery/Snowflake/Redshift materializations uses a `*sql.CountingEncoder` which in turn uses a `json.Encoder` to serialize row contents.
The standard library `encoding/json` package is fairly slow, and the `github.com/segmentio/encoding/json` package is a drop-in replacement which performs 2-3x better in most benchmarks, so swapping out the package used in `materialize-sql/encoder.go` should theoretically give us a noticeable throughput improvement for basically no actual effort.
This change is completely untested, but should be quite safe provided that it builds and passes CI in the first place. I don't have any hard numbers on how much of a bottleneck JSON serialization represents for these …
=> materialize-sql: Use github.com/segmentio/encoding/json for encoding

source-postgres/.snapshots/TestGeneric-SpecResponse, source-postgres/main.go
If an empty schema is provided in the discovery schema selection list, there will be no tables discovered since all of them will be filtered out. This may inadvertently happen if a row is added to the array UI component and then not removed. It is not always obvious to the user in this case that they are actually providing a 0-length string as their schema filter.
Ideally we might have controls that would somehow combine a variable length array of items and the fact that if any of them are there, then they must not be 0 length. I couldn't find an easy way to do this with our use of schema-gen: Newer versions of `github.com/invopop/jsonschema` do allow some control over the format of `items` within an array, but not for setting `minLength` that I could see, and upgrading …
=> source-postgres: don't allow empty schema in discovery schema selection list

materialize-mysql/VARIANTS, materialize-postgres/VARIANTS, materialize-sqlserver/VARIANTS, source-mysql/VARIANTS, source-postgres/VARIANTS, source-sqlserver/VARIANTS
Adding Google Cloud SQL variants for mysql, sqlserver and postgres
This is required for their new partner program.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1016)
=> Adding Google Cloud SQL variants for mysql, sqlserver and postgres

materialize-sqlserver/Dockerfile
- need `curl` to check pprof of the connector
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1024)
=> materialize-sqlserver: add curl to docker so we can inspect pprof

materialize-sqlserver/driver.go
the error in case of directCopy and merge were the same, not allowing us to distinguish between the two cases
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1027)
=> materialize-sqlserver: fix error message for direct copy

.github/workflows/ci.yaml, source-mongodb/.snapshots/TestCapture, source-mongodb/Dockerfile, source-mongodb/docker-compose-init.sh, source-mongodb/docker-compose.yaml, source-mongodb/main.go, source-mongodb/main_test.go, source-mongodb/pull.go, source-mongodb/test_util.go
- Some changes to run the MongoDB integration tests in the CI, this requires us to have a way to disable the `oplogSafetyBuffer` check since we don't want to wait 5 minutes.
- Updated the data we use as fixtures in our tests to include objects, arrays, integers, floats and strings. This would help us spot an issue like the encoding bug we recently faced. …
=> source-mongodb: run tests in CI

materialize-sqlserver/driver.go
- reset `needsMerge` after the transaction over
- tested using integration tests: merging process is still working as expected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1029)
=> materialize-sqlserver: reset needsMerge after transaction

source-mysql/replication.go
This is absolutely the wrong way to handle comments in general, but it's at least consistent with how we're mishandling other comment styles at the moment and will unblock a current production capture that's hitting this issue.
In the longer term we should either:
1. Implement proper comment-stripping logic prior to the whole "should we ignore this query" regexp.
2. Convert query parse failures into a warn-and-ignore rather than the current fatal error, and possibly remove the whole "ignore some benign queries via regexp" thing entirely.
The rationale for (2) here is that being strict about parse failures has never, to my knowledge, actually caught a real issue -- the handful of DDL queries which we actually want to produce task failures are also the ones which reliably …
=> source-mysql: Ignore query events beginning with `--` comments

source-mysql-batch/.snapshots/TestBasicCapture, source-mysql-batch/driver.go
Adds a `LastPolled` property to the per-stream state checkpoints and uses that to implement polling after consistent intervals even across task restarts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1032)
=> source-mysql-batch: Persist `LastPolled` timestamp

source-mongodb/pull.go
- We were using `noTimeout` option on a _backfill_ cursor, which is pretty much useless as backfill cursors are not supposed to be idle at all
- We have realised that `noTimeout` cursors are disabled on free tier: [see here](https://www.mongodb.com/docs/atlas/reference/free-shared-limitations/#operational-limitations)
- So I'm removing this option to allow free tier users to use our connector
- Tested using integration tests …
=> source-mongodb: remove `noTimeout` option from cursor

source-mysql-batch/.snapshots/TestQueryTemplate-SubsequentOneCursor, source-mysql-batch/.snapshots/TestQueryTemplate-SubsequentThreeCursor, source-mysql-batch/.snapshots/TestQueryTemplate-SubsequentTwoCursor, source-mysql-batch/driver.go, source-mysql-batch/main.go, source-mysql-batch/main_test.go
The previous implementation of numbered placeholders used the syntax `:N` which proved to be a dumb design decision since that appears as a substring of every timestamp.
(Note that this isn't *quite* as dumb as it sounds because the garden path for most users has them using the default query template which has no such issue, the only time this comes up is if you customize the query template and hard-code a specific timestamp as part of one of the queries. Unfortunately that's not a super uncommon thing to want to do, as specifying an initial cursor value for the first query is the obvious way to avoid backfilling a bunch of historical data)
The new placeholder syntax added in this PR looks like `@flow_cursor_value[N]` which ought to be substantially less collision prone. …
=> source-mysql-batch: Less collision prone numbered placeholders

.github/workflows/ci.yaml, materialize-bigquery/sqlgen.go, materialize-dynamodb/type_mapping.go, materialize-mysql/sqlgen.go, materialize-redshift/sqlgen.go, materialize-snowflake/sqlgen.go, materialize-sql/type_mapping.go, materialize-sqlserver/sqlgen.go, tests/materialize/fixture.yaml, tests/materialize/materialize-dynamodb/snapshot.json, tests/materialize/materialize-mysql/snapshot.json, tests/materialize/materialize-postgres/snapshot.json, tests/materialize/materialize-snowflake/fetch-data.go, tests/materialize/materialize-snowflake/snapshot.json, tests/materialize/materialize-sqlserver/snapshot.json
Many materializations JSON-encode float64 values, but these special values are prohibited in JSON, and different systems allow for different alternative representations when casting into a floating-point column.
Update the StdStrToFloat() signature to force the connector to think about and provide these special value conversions.
Update individual connectors to provide handling for each, using best judgement and available public documentation. …
=> materializations: StdStrToFloat() takes explicit NaN/Infinity/-Infinity casts

materialize-mysql/VARIANTS, materialize-postgres/VARIANTS, materialize-sqlserver/VARIANTS, source-mysql/VARIANTS, source-postgres/VARIANTS, source-sqlserver/VARIANTS
Amazon RDS Source Connectors:
- MySQL
- PostgreSQL
- SQL Server
- MariaDB
Amazon RDS Materialization Connectors:
- MySQL
- PostgreSQL
- SQL Server
- MariaDB
Docs for all sources/materializations have been created
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1040)
=> Variants of DB connecters for Amazon RDS

source-dynamodb/pull.go, source-dynamodb/stream.go
When streaming from tables with huge numbers of shards where a significant portion of the shards have some non-trivial amount of data available, we can end up buffering an excessive amount of data in memory.
This is because the connector requests data from all shards simultaneously, and must hold on to that data until it can be serialized and drained to the runtime. If data comes in faster than it can be drained, the connector will run out of memory.
Here a semaphore is added, to limit how many workers can simultaneously be processing data.
Tested using the unit tests to ensure no existing functionality is broken. It's not really practical to create a huge dynamodb table to test this with many shards in earnest unfortunately, but it is a pretty straightforward and low …
=> source-dynamodb: limit concurrent stream data requests

source-postgres/backfill.go, source-postgres/prerequisites.go
Previously it was possible in some cases to set up the watermarks table such that the capture user didn't have permission to update the table *and yet those failures weren't reported* which is bad.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1052)
=> source-postgres: Make watermarks permissions error reporting work

source-postgres/.snapshots/TestCaptureOversizedFields, source-postgres/.snapshots/TestCaptureOversizedFields-Replication, source-postgres/capture_test.go, source-postgres/discovery.go
Adds some code to truncate overly large (defined here as >1MiB, an arbitrarily chosen value which should be large enough for most reasonable purposes and small enough that even several such fields is still within the Flow document size limits) string/byte/JSON columns coming from Postgres.
This logic isn't bulletproof: I'm sure there are plenty of other column types which could in theory cause trouble, including array columns. But this handles the four most common column types which could contain megabytes of data, and in practice it will probably be sufficient for now.
In the longer term, this truncation function should be made a part of the common `sqlcapture` logic and should be done as part of the final JSON serialization of a change event, so that it will apply to …
=> source-postgres: Truncate oversize string/byte/JSON columns

.vscode/launch.json, python/flow_sdk/shim_singer_sdk.py, python/poetry.lock, python/pyproject.toml
This updates the Singer shim to work with changes in `singer-sdk` v`0.33`. Specifically, we have to pull `sync_all()` in house because the way it references `write_message()` is not compatible with our "clever" solution to monkey-patching that method to capture its output. My write-up on this from a slack thread:
-   When we import a module in python, it imports the `__init__.py`s above that module first. So importing `singer_sdk._singerlib` will import `singer_sdk/__init__.py`, and `singer_sdk/_singerlib/__init__.py`. See the screenshot for the import tree of `singer_sdk._singerlib.messages`
-   In order to monkeypatch `write_message` we need to get a reference to its containing module `singer_sdk._singerlib.messages` *before* that is used by anything else, …
=> Update Singer `CaptureShim` to work with v`0.33`

materialize-google-pubsub/transactor.go
The packed key can be an arbitrary sequence of bytes, including sequences of non-UTF8 characters when converted to a string. If used as an ordering key, this causes a PubSub error.
Instead, hex-encode the packed key to use as an ordering key, which is always valid UTF8.
This change to the ordering key could hypothetically result in out of order reading of messages with the same packed key from a …
=> materialize-google-pubsub: hex-encode ordering key

materialize-bigquery/.snapshots/TestSQLGeneration, materialize-bigquery/sqlgen.go, materialize-bigquery/transactor.go, materialize-sql/templating.go
BigQuery now supports "Flexible column names", which means column names can include hyphens, among other things.
We were never normalizing hyphens as underscores in column names, so historically collections with field names containing hyphens would cause an apply failure. With BigQuery's support for "Flexible column names", the table will now actually be created, but the external tables we use to load data still don't support these special column names.
This commit replaces the column names in the generated JSON files and SQL queries with generic placeholders, so that column names with dashes aren't a problem for external tables. With this we can create & materialize to tables with hyphens in the column names.
(How does one use this feature, and how …
=> materialize-bigquery: compatibility for fields with hyphens

filesource/filesource.go, source-gcs/main.go, source-google-drive/main.go, source-http-file/main.go, source-s3/main.go, source-sftp/main.go
In 7379829 the `RecommendName` for all filesource-based captures was changed to `"file-data"`, to accommodate the new Google Drive capture which uses generated folder names through its API which are not user-friendly, so the more generic default value is better in this case.
All other connectors are capable of producing a more useful recommended name though, and this change allows for individual capture connectors to determine what their output recommended collection name should be to allow for that.
As a result, Google Drive captures will continue to recommend collection names of `"file-data"`, but others will revert back to their previous behavior of recommending a reasonable collection name based on the user's input.
Create a capture from (for …
=> filesource: use more specific recommended collection names where possible

go.mod, go.sum, go/encrow/encrow.go, materialize-bigquery/staged_file.go, materialize-google-pubsub/transactor.go, materialize-motherduck/driver.go, materialize-motherduck/staged_file.go, materialize-redshift/driver.go, materialize-redshift/staged_file.go, materialize-snowflake/staged_file.go, materialize-sql/encoder.go, materialize-sql/encoder_test.go, materialize-sql/table_mapping.go, tests/materialize/materialize-redshift/snapshot.json
Use the optimized `encrow.Shape` for encoding JSON objects, and also optimizations for encoding an array of values for materializations that do that (currently only `materialize-snowflake`).
This is a significant performance improvement when examining _just_ the serialization aspect of the `CountingEncoder`, and shows a 3x improvement in speed of encoding objects, and a ~1.5x improvement for serializing value arrays.
The benchmark outputs below illustrate this, and were run with `compressionLevel = flate.NoCompression` to turn off compression in `CountingEncoder`. The original pre-change code was tested with a slightly modified version of the benchmark included in this PR for compatibility.
_New optimized code, with `compressionLevel = flate.NoCompression`:_
```
go test …
```
=> materialize-sql: use `encrow.Shape` for encoding

source-mysql/.snapshots/TestAlterTable_ChangeColumn-capture1, source-mysql/.snapshots/TestAlterTable_ChangeColumn-capture2, source-mysql/.snapshots/TestAlterTable_ChangeColumn-capture3, source-mysql/.snapshots/TestAlterTable_ChangeColumn-init, source-mysql/.snapshots/TestAlterTable_ModifyColumn-capture1, source-mysql/.snapshots/TestAlterTable_ModifyColumn-capture2, source-mysql/.snapshots/TestAlterTable_ModifyColumn-capture3, source-mysql/.snapshots/TestAlterTable_ModifyColumn-capture4, source-mysql/.snapshots/TestAlterTable_ModifyColumn-init, source-mysql/.snapshots/TestAlterTable_RenameColumn-capture1, source-mysql/.snapshots/TestAlterTable_RenameColumn-capture2, source-mysql/.snapshots/TestAlterTable_RenameColumn-init, source-mysql/.snapshots/TestAlterTable_Unsupported-capture2-fails, source-mysql/.snapshots/TestAlterTable_Unsupported-capture3-fails, source-mysql/.snapshots/TestAlterTable_Unsupported-capture4, source-mysql/.snapshots/TestAlterTable_Unsupported-capture5, source-mysql/.snapshots/TestAlterTable_Unsupported-capture6, source-mysql/main_test.go, source-mysql/replication.go
Adds (full) support for the `CHANGE COLUMN`, `MODIFY COLUMN`, and `RENAME COLUMN` clauses in an `ALTER TABLE` query, as well as some additional test cases verifying that these work as intended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1069)
=> source-mysql: Support column renaming and repositioning in `ALTER TABLE` queries

source-http-ingest/src/lib.rs, source-http-ingest/tests/snapshots/test__discover.snap
Apparently _someone_ committed a TODO instead of actually returning the resource path as part of discover. It's fixed now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1075)
=> source-http-ingest: return resource_path in discovered for real

materialize-bigquery/transactor.go, materialize-redshift/driver.go, materialize-snowflake/snowflake.go, materialize-sqlserver/driver.go
- add info level logging at boundary of different sections of long-running jobs in bigquery, redshift and snowflake to help us troubleshoot issues when they arise
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1072)
=> materialize-{bigquery,redshift,snowflake}: add INFO level logs for jobs

python/flow_sdk/shim_airbyte_cdk.py, python/flow_sdk/shim_singer_sdk.py
The resource config schemas generated by these connectors seem to be invalid according to the UI. I believe this should fix it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1067)
=> fix: Resource config schemas need a `type`

source-mongodb/.snapshots/TestDiscover, source-mongodb/discovery.go
- we initially did this in order to be consistent in behaviour with our sql captures which emit the full document and `_meta/op: "d"`, however the reduction strategy is problematic when it comes to documents that have one of their columns removed in an update, however because of the reduction strategy they retain that column in the materialization. so we have decided to revert this change to just have mongodb emit a document with id and `_meta/op: "d"` that ends up clearing all other columns in the materialization
- Tested by running tests, and manually ran a test where I deleted a field from a document (using `$unset`) and in the materialization the column was set to null. …
=> source-mongodb: do not set reduce: merge strategy for mongo collections

python/README.md, python/flow_sdk/shim_singer_sdk.py, source-criteo/source_criteo/tap_criteo/schemas/v2020.07/campaign.json, source-criteo/source_criteo/tap_criteo/streams/reports.py, source-criteo/source_criteo/tap_criteo/tap.py, source-shopify/connector_config.yaml, source-shopify/source_shopify/tap_shopify/client.py, source-shopify/source_shopify/tap_shopify/tap.py
We don't have to do any multiplexing of stream-specific state for Singer as far as I can tell because the Meltano SDK manages mapping stream-specific into keys in the `"bookmarks"` state-key under the hood. All we have to do is persist the state values, and provide the latest state to the `Tap()` constructor when restarting.
Also update specs for `source-criteo` and `source-shopify` to make them work better in the UI
**Note:** Airbyte state is more complex and I'm still researching how to handle it, so this just covers Singer state for the moment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1079)
=> Update Singer shim to emit state checkpoints

source-bigquery-batch/driver.go, source-mysql-batch/driver.go
Adds a small check so that resource specs with empty cursor column names will be rejected at startup. Also throws in a couple of logging tweaks inspired by trying to read a capture task's logs yesterday, and moves the polled-at timestamp update so that it occurs _after_ acquiring the "only update one binding at a time" mutex which is obviously more correct.
These changes are made to `source-bigquery-batch` and `source-mysql-batch` for consistency. The analagous changes for batch Postgres have been added to the "bring source-postgres-batch back to feature parity" PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1089)
=> source-bigquery-batch: Minor adjustments

materialize-sqlite/sqlgen.go, materialize-sqlite/sqlite.go
This is a follow-up to #1086 - although materialize-sqlite didn't previously need to do anything in particular with its column alteration methods, it does now need to actually create tables in its client `Apply` method since the materialize-sql framework doesn't do that via `ExecStatements` anymore.
The integration tests for various capture connectors use the `dev` image of `materialize-sqlite`, so those only started failing after #1086 was merged, and will fail until after this PR is merged - including on this PR itself. I did build `materialize-sqlite` with this image locally and verified that the capture integration tests work though. In the future it would probably be a good idea to put together a simple integration test for `materialize-sqlite` since there currently …
=> materialize-sqlite: fix apply

materialize-snowflake/snowflake.go, materialize-snowflake/staged_file.go
- Run load and store operations concurrently for up to 5 bindings at a time
- Also upload files concurrently by having multiple `putWorker`s
- Tested by running the integration tests as well as manually tested on more than 5 bindings at a time to check the limiting logic
- - - …
=> materialize-snowflake: run load and store queries concurrently

.github/workflows/ci.yaml, python/flow_sdk/shim_airbyte_cdk.py, source-mysql/.snapshots/TestGeneric-SpecResponse, source-postgres/.snapshots/TestGeneric-SpecResponse, source-sqlserver/.snapshots/TestGeneric-SpecResponse, sqlcapture/main.go
The `resource_path_pointers` used by the sqlcapture and airbyte connectors didn't match the order of the properties in the `resource_path` that's returned by the Validate RPC.  This doesn't cause any problems, because we never actually compare the two. But we have plans to, and it's just weird if they don't match. There's also little risk of changing the order of `resource_path_pointers` at this stage because they're only used for discover merge. So I'd like to make sure they're all consistent before it becomes difficult to change.
Also rolls up a few commits to update the proto-flow dependency for source-kafka and source-http-ingest. These are Rust connectors, and the Rust JSON deserialization does not allow unrecognized fields. So this update is required in order to …
=> make airbyte and sqlcapture resource_path_pointers match validate

source-mysql/replication.go
Another one that can't be parsed by the Vitess query parser.
I'm just about at the point of recommending we turn query parse failures into a benign log-and-ignore, since this has never once been a real issue -- the queries we actually need to handle or forbid are parsed correctly, and these failures are just a bunch of edge cases we don't care about. But that's more work than just adding another prefix string into the ignores regexp, so it can wait until after the production issue is unblocked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1106)
=> source-mysql: Ignore `DROP FUNCTION` query events

materialize-sql/apply_actions.go
There have been a couple of cases where a table that should exist in the endpoint hasn't been found in the `ExistingTables` struct formed from the `INFORMATION_SCHEMA` query. This adds some logging to hopefully help figure out what is going on, by showing the tables that were found.
- - - …
=> materialize-sql: log tables that were found if a table that should exist isn't found

materialize-databricks/driver.go, materialize-postgres/sqlgen.go, materialize-postgres/sqlgen_test.go
- Adds truncation to the column and table locators for reading data from the `information_schema` view for `materialize-postgres`, since Postgres automatically truncates identifiers over 63 bytes in length.
- Qualifies `information_schema` as `system.information_schema` in `materialize-databricks`, since that is needed for some deployments of Databricks. …
=> materializations: fix a couple of bugs with `information_schema` querying

materialize-redshift/driver.go
This package needs to be imported so that `stdsql.Open("pgx", ...)` works correctly. Currently the connector cannot actually run since this got deleted (presumably by accident) in https://github.com/estuary/connectors/pull/1099
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1113)
=> materialize-redshift: Reinstate pgx/v4/stdlib import

materialize-sql/apply_actions.go, materialize-sql/apply_actions_test.go
If a pre-existing table doesn't have all of the columns in the field selection for a binding, we currently don't error on Apply and also don't add the columns. It then may be necessary to exclude that column from the field selection, which is currently impossible since we try to check if the existing column is nullable when removing it from the field selection.
So instead of erroring, just don't try to drop the nullability constraint on columns that don't exist. …
=> materialize-sql: don't try to drop nullability on columns that don't exist

source-mongodb/pull.go
Same as we do for NaNs, float infinities need to be replaced with a string representation because they have no JSON representation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1115)
=> source-mongodb: Sanitize +/-Infinity values

source-mysql/prerequisites.go
We don't enforce a minimum version for `source-mysql`, and will currently log a warning if the detected version is too low.
We've seen various versions of MySQL work, but don't have an exact limit on what should be supported, and don't fail validation on this error. Logging a warning can be confusing if there are other errors that actually cause the capture to fail validation, so this changes the log level to DEBUG so it doesn't normally show up.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a …
=> source-mysql: lower logging for insufficient database version to debug level

config_schema_guidelines.md
https://github.com/estuary/ui/pull/855 will add a new information section into the UI. This will only key off a single field. So wanting to make sure this special case is documented.
N/A
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1119)
=> Updating schema guidelines for `sshEndpoint`

materialize-databricks/config.go, materialize-databricks/config_test.go, materialize-databricks/driver.go, tests/materialize/materialize-databricks/checks.sh, tests/materialize/materialize-databricks/snapshot.json
- The best practice for Databricks integrations is to check the status of the warehouse and give a human-readable error if the status is not active. I've updated the code to give such error in PreReqs, and I've reduced the timeout so that we don't have jobs waiting a long time for warehouses. Warehouses take around 5 minutes to start, and we don't want to hang the UI for 5 minutes waiting for the warehouse to come online. We still will ping the warehouse, which will initiate its booting up, but we will let the user know that the warehouse is not started yet, so they have to wait.
- Added `SchemName` parameter name to connection string, this ensures that temporary tables created are in that schema. I tested this by changing the schema in config and running the new …
=> materialize-databricks: check status of warehouse in prereqs

python/pyproject.toml
This is so that users of this module can use  Mypy typing. Also bump the version to match the version on pypi: https://pypi.org/project/flow-sdk/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1120)
=> Bump `python/pyproject.toml` to include `py.typed`. 

materialize-bigquery/bigquery.go
Sets the User-Agent header in the bigquery client, to enable GCP to track partner attribution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1118)
=> materialize-bigquery: set user agent in bigquery client

materialize-databricks/.snapshots/TestSpecification, materialize-databricks/config.go, materialize-databricks/driver.go, materialize-databricks/logger.go
- Use `sql.CommitWithDelay` to delay commits as a cost-saving measure.
- Tested by manually running this, and commits are spaced by 30 minutes. It takes about 5 minutes for Pro and Classic type of SQL warehouses to boot up (Serverless SQL Warehouses are supposed to be faster to boot up, but we don't have access to those to test them), but that does not lead to a timeout in our code, as in my tests the connector seems to work fine using this configuration.
- Added logic so that if auto-stop is configured to be more than 15 minutes, we disable Update Delay, since it is not as useful in that scenario.
- Disabled databricks sql and databricks SDK's internal logging facilities so that we can directly control what errors get logged
- Documentation: …
=> materialize-databricks: UpdateDelay

tests/run.sh
- `flowctl-go api spec` has been removed
- replaced it with a call to `flowctl raw spec`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1138)
=> tests: fix run.sh file, flowctl-go api spec deprecated, use flowctl raw

source-kafka/src/configuration.rs, source-kafka/src/kafka.rs
- The JSONSchema and the configuration are not linked by code, and in the JSONSchema the credential keys are `aws_access_key_id` and `aws_secret_access_key`, however in the code the struct has `access_key_id` and `secret_access_key`. I had not hit this issue in my tests since I used a local, manually prepared configuration file, but I noticed the discrepancy when trying this out on the UI
- Also removed `PLAIN` as the default `mechanism`, since when you first open the jsonform, it defaults to `PLAIN`, and if you switch to AWS IAM, the default value stays in somehow and becomes part of the config, which is confusing because the user will see it in their config, but in reality it has no effect when using IAM.
- Exclude `__amazon_msk_canary` from discovered bindings since it …
=> source-kafka: fix config field names

source-dynamodb/.snapshots/TestCaptureOperations, source-dynamodb/capture.go, source-dynamodb/docker-compose.yaml
When reading change stream documents, map an explicit `NULL` for any fields that existed in the prior record but are now absent in the current record. This is to allow a top-level merge reduction strategy in the output documents to appropriately represent deleted fields. We require captured tables to have `NEW_AND_OLD_IMAGES` set on their streams.
- - - …
=> source-dynamodb: map explicit NULL for fields that existed in prior documents

source-mongodb/.snapshots/TestCapture, source-mongodb/discovery.go, source-mongodb/main.go, source-mongodb/oplog.go, source-mongodb/pull.go, source-mongodb/pull_test.go
The current approach to mongodb backfills relies on time-based checks to ensure that we haven't missed any replication events that happen during a backfill. These checks caused problems for captures from shared database servers, like the entry-level instances on MongoDB Atlas.  Such shared servers don't provide unlimited access to the oplog, since the oplog itself is shared by many users. This raises the possibility that querying the oplog can potentially return no events, in the case that it gets filled with events that we aren't authorized to read.
This commit changes the behavior around oplog checks to account for that possibility, with the ultimate goal of being able to robustly capture from the sorts of cheap/free instances that users are likely to test with.
It's no …
=> source-mongodb: enable capturing from shared database instances

filesource/filesource.go, filesource/state.go, filesource/state_test.go, source-bigquery-batch/.snapshots/TestBasicCapture-Capture, source-bigquery-batch/.snapshots/TestBasicCapture-Discovery, source-bigquery-batch/driver.go, source-bigquery-batch/main_test.go, source-mysql-batch/.snapshots/TestBasicCapture, source-mysql-batch/driver.go, source-mysql-batch/main_test.go, source-postgres-batch/.snapshots/TestBasicCapture, source-postgres-batch/driver.go, source-postgres-batch/main_test.go
Updates the 3 SQL batch captures to use state keys: `source-bigquery-batch`, `source-mysql-batch`, and `source-postgres-batch`. These were all pretty straightforward and nearly identical changes.
Also updates the `filesource` framework to use state keys. This was slightly more involved because of that way the previous checkpoint was structured. There are 5 captures that use this framework.
We'll be able to remove the "migration" shims for these captures once all existing captures have migrated, and perhaps after some amount of time has passed where we are confident that no previously disabled captures will start back up that we don't want to be broken.
See issue https://github.com/estuary/connectors/issues/1146
Use `backfill` to re-start any of these …
=> sources: use state keys for `filesource` and batch SQL captures

materialize-mongodb/transactor.go, tests/materialize/materialize-mongodb/snapshot.json
Removes the `_id` property before returning loaded documents. This is to prevent that property from causing schema validation errors for collections that use a top level `reduce: { strategy: merge }`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1156)
=> materialize-mongodb: remove _id property from loaded docs

materialize-databricks/driver.go
- The default timeout for the HTTP client used by the Databricks SDK is one minute. This can trip up when uploading the 128MB files depending on the destination storage's bandwidth. This change updates the timeout to be 5 minutes to allow more time for file uploads.
- - - …
=> materialize-databricks: set http timeout to 5 minutes

source-mysql-batch/.snapshots/TestQueryTemplate-FirstOneCursor, source-mysql-batch/.snapshots/TestQueryTemplate-FirstThreeCursor, source-mysql-batch/.snapshots/TestQueryTemplate-FirstTwoCursor, source-mysql-batch/main.go
Fixing bug in the query template where non null values cursor values were not being captured during first query. Query now appends ORDER BY {{cursors}} clause when a cursor is present, whether or not the current query is the first query.
- - - …
=> Modified default query template to find non null cursor

materialize-bigquery/bigquery.go
The configured project that contains the dataset must be specified when querying the INFORMATION_SCHEMA views if a billing project is configured, otherwise the query defaults to the billing project which will not contain the desired dataset.
- - - …
=> materialize-bigquery: use project containing dataset for querying ORMATION_SCHEMA

sqlcapture/capture.go
Sometimes it would be pretty convenient if we could turn on debug logs in production and see the full list of all tables discovered and their columns and the types of those columns.
Since by default we're only running at INFO level in production this should be fine, although it will make test output noisier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1130)
=> sqlcapture: DEBUG-log the results of startup table discovery

materialize-motherduck/driver.go
Sets the `custom_user_agent` in the duckdb DSN, to enable tracking partner usage with MotherDuck.
Closes #1166
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1175)
=> materialize-motherduck: set user agent in connection string

materialize-s3-parquet/driver.go, tests/materialize/materialize-s3-parquet/fetch.sh, tests/materialize/materialize-s3-parquet/snapshot.json
- Reproduced the issue by running a materialization locally using `flowctl peview`
- Applied this change, and the connector works
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1181)
=> materialize-s3-parquet: fix invalid empty state error

materialize-bigquery/client.go, materialize-boilerplate/apply.go, materialize-boilerplate/info_schema.go, materialize-databricks/client.go, materialize-postgres/sqlgen.go, materialize-sql/std_sql.go
- For `materialize-postgres`, we create columns as "bigint", but pre-created tables may have columns that are just "integers", and we want to support those.
- In general, columns with default values can be NOT NULL even if the Flow collection field is not required, since
the default value will take the place of a null value for the field.
This works for our stats postgres materialization, which uses pre-created tables with `integer` column types (not `bigint`) and also has `NOT NULL` columns with default values where we are materializing nullable fields. I also ran the tests for all other materializations that consider columns with default values.
(list any …
=> materialize-sql: fixes for column validations and nullability

source-airtable/source_airtable/source_airtable/schema_helpers.py, source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__discover__capture.stdout.json
This was being set by the `airbyte-to-flow` override in the old connector, that never got transferred over to the python connector
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1189)
=> fix: Provide primary key `_airtable_id` for `source-airtable`

materialize-databricks/client.go
- This is to allow serverless instances to start up without the user having to re-try. Dedicated warehouses still will timeout as they take more than 5 minutes usually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1188)
=> materialize-databricks: increase Validate RPC timeout to 1 minute

source-airtable/source_airtable/source_airtable/spec.json, source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__spec__capture.stdout.json, source-asana/source_asana/source_asana/spec.json, source-asana/tests/snapshots/source_asana_tests_test_snapshots__spec__capture.stdout.json
This enables the OAuth button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1192)
=> fix: Forgot `x-oauth2-provider` on `source-airtable` and `source-asana`

source-mongodb/pull.go, source-mongodb/pull_test.go
- We were not handling NaN values in arrays. I'm introducing this logic here and also added some tests for `sanitizeDocument`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1193)
=> source-mongodb: handle NaN values in arrays

source-firestore/.snapshots/TestAddedBindingSameGroup-one, source-firestore/.snapshots/TestAddedBindingSameGroup-two, source-firestore/.snapshots/TestBindingDeletion-one, source-firestore/.snapshots/TestBindingDeletion-three, source-firestore/.snapshots/TestBindingDeletion-two, source-firestore/.snapshots/TestDeletions-one, source-firestore/.snapshots/TestDeletions-two, source-firestore/.snapshots/TestManySmallWrites-one, source-firestore/.snapshots/TestManySmallWrites-two, source-firestore/.snapshots/TestMultipleWatches-one, source-firestore/.snapshots/TestMultipleWatches-two, source-firestore/.snapshots/TestSimpleCapture-one, source-firestore/.snapshots/TestSimpleCapture-two, source-firestore/main_test.go, source-firestore/pull.go
Updates the connector to use `stateKey` for each binding to track its state.
This includes a migration for existing captures. Once all existing captures have started up with this new connector and we are confident that no additional old captures will be re-enabled, we can remove the migration code.
I tested this by creating a capture with the "old" connector version, and then switching it to the new version. It picked up where it left off, and incrementing the `backfill` counter could trigger a re-backfill of a binding.
So far I've run all the semi-manual tests and updated the test snapshots. I'm also running the really huge datasynth test just for grins and will update the snapshot for that when it is done, but that will take many hours more than likely. All that should …
=> source-firestore: use stateKey for tracking binding state

source-mongodb/pull.go
`updateResourceStates` may remove bindings from the checkpoint, and these removals won't be reflected in persisted merge patches in future document checkpoints. Because of this, we should always emit a full update to the state checkpoint in `Pull` after `updateResourceStates` has run to persist any changes in the state due to bindings being removed.
- - - …
=> source-mongodb: always emit an updated checkpoint after `updateResourceStates`

materialize-bigquery/sqlgen.go
Clean revert of 24b4fc12934c76258252ac6118dd95db6af8e561. We actually need to do something a little more complicated here, along the lines of allowing the same column type to have multiple validators, rather than one validator using multiple column types.
- - - …
=> Revert "materialize-bigquery: validate "number" columns as either bignumeric or float64"

materialize-bigquery/sqlgen.go
We used to create number columns as "bignumeric" (see https://github.com/estuary/connectors/pull/859.), and now create strings formatted as integer columns as "bignumeric". Allowing "bignumeric" columns to be either integer or number compatible allows both new and old materializations to work.
Manually tested by using a pre-created column with a number field as a "bignumeric" column and verified that it was able to validate on this new image, whereas it fails on the current dev image. …
=> materialize-bigquery: validate bignumeric columns as integer or number

python/flow_sdk/shim_airbyte_cdk.py, python/pyproject.toml, source-airtable/acmeCo/test_base/flow.yaml, source-airtable/acmeCo/test_base/soups/flow.yaml, source-airtable/test.flow.yaml, source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__discover__capture.stdout.json
The consequence of this was that we were not persisting state messages (and crashing instead), so incremental captures would fail to be incremental.
Note, this also adds a more clear exception for a scenario I encountered in a customer's task where it was outputting documents for a binding/stream ID that we didn't know about, and crashing. I _think_ we should still crash in this case, but at least now the message will be more clear and make it easier to track down the problem. 
As a fast-follow I would like to add integration test coverage for incremental captures
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1217)
=> fix: Airbyte shim typo

materialize-bigquery/.snapshots/TestValidateAndApply, materialize-databricks/.snapshots/TestValidateAndApply, materialize-mysql/.snapshots/TestValidateAndApply, materialize-postgres/.snapshots/TestValidateAndApply, materialize-redshift/.snapshots/TestValidateAndApply, materialize-snowflake/.snapshots/TestValidateAndApply, materialize-sql/type_mapping.go, materialize-sqlserver/.snapshots/TestValidateAndApply
Users almost always want arrays and fields with multiple types (materialized as JSON columns) to be materialized by default, so this changes them to be recommended instead of optional.
We will merge this on Monday, Jan 29th, as we have given users a heads-up that this change is coming, and new publications of their tasks will cause these newly recommended fields to be added to their materializations.
Closes #1208
Create SQL materializations and see that array fields and fields with multiple types are included in the recommended fields, and will be materialized by default. Object fields are still optional.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit …
=> materialize-sql: recommend arrays and fields with multiple types

materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/snowflake.go
Adds a regex pattern for the `host` configuration value. Users occasionally include a protocol or a trailing `/`, which the connector will error on during validate, but we could also do some simple pattern matching in the UI to make it even more clear, so this implements that.
The pattern isn't exactly right since the `.`'s are not escaped with a `/`, but I couldn't figure out how to get a `/` to take in a go struct tag and don't feel particularly motivated to have a completely hand-written config schema right now.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or …
=> materialize-snowflake: regex pattern for host configuration

materialize-databricks/driver.go, materialize-snowflake/snowflake.go, tests/materialize/materialize-databricks/snapshot.json
_Related PR: https://github.com/estuary/connectors/pull/1213. This was merged and all active databricks materializations are now running on it and emitting post-ack zero'd checkpoints._
Adds support for state keys to materialize-databricks. The backfill capability more-or-less worked even without this, but the full `stateKey` implementation mitigates certain unlikely edge cases that may occur if the ack state is not persisted, and a table is re-backfilled and then persisted queries for the prior table are run against the re-created table.
I manually tested migrating an existing materialization from the prior image over to this, as well as starting a new materialization from scratch with this image. Also various combinations of multiple bindings with or without data and …
=> materialize-databricks: use stateKey for tracking binding state

materialize-snowflake/snowflake.go, tests/materialize/materialize-snowflake/snapshot.json
- A small change in the format of checkpoint item which will allow us to distinguish between old v2 checkpoints. In case we do find an old v2 checkpoint, we clean up the checkpoint and start anew.
- - - …
=> materialize-snowflake: switch checkpoint format for migration

go/protocols/materialize/lifecycle.go, materialize-postgres/driver.go
This implements batch flushing logic based on the size of documents handled, rather than a simple count of documents.
For loads, it uses the size of the packed key. For stores, it uses the size of packed key, packed values, and raw document JSON. This is just an approximation of the memory used for buffering the queries for these documents in a `pgx.Batch`, but it seemed to work pretty well in a synthetic test case: For documents each around 100kb, this version of the connector will use just a little over 100mb of memory per `docker stats` when doing stores, and have batch sizes of about 50 documents. Each materialized row has all of the fields from the document as well as a field with the entire document, so 50 documents is just about right with a batch size limit of …
=> materialize-postgres: limit batch size based on document size

materialize-sql/driver.go
Some materializations (currently, only materialize-snowflake) need the name of the tenant running the task for partner reporting purposes.
This previously wasn't threaded through correctly and was resulting in incorrect reporting, and this is the fix.
- - - …
=> materialize-sql: fix tenant name extraction

source-sftp/.snapshots/TestSpec, source-sftp/main.go
- I attempted to make a more generalised way of creating `oneOf`s without outputting the schema directly, and I realised we soon end up almost re-implementing jsonschema. There probably still is some way to get a middle ground where we reduce boilerplate for connectors but also don't end up maintaining too much code on the side of the abstraction, but for now I gave up on it. My attempt is [here](https://github.com/estuary/connectors/commit/de9cc38121882015614fbe7f5ad5fa582ff8aab0). If I was to do this again, I would probably do this with multiple structs, where each struct represents one of the `oneOf` cases, this allows for more control over specifics of each and would probably also provider a better interface, we just would need a way of parsing the config into these …
=> source-sftp: oneOf credentials jsonschema

materialize-redshift/sqlgen.go, materialize-redshift/sqlgen_test.go
Redshift automatically truncates identifiers longer than 127 bytes. We can still make tables and columns with identifiers longer than this, but they are always truncated when interacting with them. Notably, this means we need to be aware of the possibility for truncation when reading the output from the information_schema view, which will show the truncated form.
See also 49a4802aaef6ce63ad11b82c308d288db15e9f28, which is a very similar adaptation for materialize-postgres. …
=> materialize-redshift: locate long identifiers by truncation in information_schema output

source-snowflake/.snapshots/TestSpec, source-snowflake/main.go
This makes the naming more consistent with the pattern used for other entities (user account / role / warehouse) our documentation will guide users to set up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1242)
=> source-snowflake: Use `ESTUARY_STAGING` as default staging schema

source-mysql/.snapshots/TestDatetimeNormalization, source-mysql/.snapshots/TestDatetimeNormalization-replication, source-mysql/capture_test.go, source-mysql/discovery.go
These are invalid and you have to make sure the `NO_ZERO_IN_DATE` mode flag is cleared in order to insert them, but since that's a thing we can receive from the database we need to handle it. We'll handle them by normalizing the zero component to one instead.
This code is rather ugly and produces off-by-one results for backfills versus replication, but it's sufficient to get things unblocked in production and such invalid datetimes are generally a hacky way of saying something like "July 2023" without additional detail anyway, so the inconsistency doesn't feel like the end of the world. We should still chase that down soon, obviously.
- - - …
=> source-mysql: Normalize zero-month/day in MySQL datetimes

source-sftp/main.go
A user entered `/` for the `directory` in the config, and it resulted in the `recommended_name` of the discovered binding being empty. This ensures that the recommended name is always non-empty by defaulting it to `root-directory`. Feel free to suggest a better default name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1247)
=> source-sftp: set recommended_name when directory is /

source-postgres/replication.go, sqlcapture/capture.go, sqlcapture/main.go
Instead we'll just shut down cleanly (while logging a warning) and assume that a subsequent retry will succeed.
This fixes https://github.com/estuary/connectors/issues/1183
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1252)
=> source-postgres: Unexpected EOF is not an error

materialize-boilerplate/validate.go, materialize-boilerplate/validate_test.go
This check was problematic because it didn't allow for "removing" a binding and "adding" a different binding to the same table in the same publication. There is no reason to forbid this, since the actual columns & types of the materialized resource are used for validating that a binding is compatible. So, the source collection of a binding could be changed and still go to the same table, as long as the already materialized table is compatible with the source collection.
There are edge cases where this might be a problem, such as if the previous binding was delta updates and the new one is not and the target table has existing rows in duplicate for certain keys from the delta updates materialization. This same thing could currently happen if the binding were removed, …
=> materializations: don't check for identical resource paths in validate

materialize-boilerplate/apply.go, materialize-boilerplate/validate.go
Matching on both the collection name + resource path doesn't work well if the backfill counter for a binding is incremented simultaneously with changing the source collection. This isn't terribly common, but will automatically happen via the schema evolutions handler when a collection key changes. In this case, the current behavior will consider the binding brand new, and will not re-create the table.
Matching on just the resource path is consistent with how the runtime computes state keys for bindings, which are only based on the resource path. This will allow the materialization to consider a binding with a different source collection for the same resource path to be a continuation of that binding, and will react to backfill counter changes accordingly.
This also …
=> materializations: find existing bindings based only on resource path

source-google-ads/__main__.py, source-google-ads/source_google_ads/source_google_ads/spec.json, source-google-ads/tests/snapshots/source_google_ads_tests_test_snapshots__spec__capture.stdout.json
* Add `"x-oauth2-provider": "google"` to `source-google-ads`
* Fix `accessTokenBody` being improperly formatted/escaped
* Remove `pattern_descriptor` fields, which is apparently an Airbyte-specific thing and was causing jsonschema validation to fail
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1260)
=> fix: `source-google-ads` OAuth config

source-airtable/source_airtable/source_airtable/spec.json, source-airtable/tests/snapshots/source_airtable_tests_test_snapshots__spec__capture.stdout.json
Airtable's access tokens expire after 60m, and their refresh tokens [expire](https://airtable.com/developers/web/api/oauth-reference#token-expiry-refresh-tokens) theoretically after 60 days. Since we don't have a way to store new refresh tokens, theoretically airtable OAuth integrations should work for 60d and then fail. In actuality, this connector is failing after 60 minutes. It _appears_ that the refresh tokens Airtable is giving us expire after 60m. Normally this would be fine as they're supposed to be single-use tokens anyway, but we don't support storing updated credentials like this.
As far as I know, our solution was to just disable OAuth for Airtable captures entirely, and only expose the ability to use PATs. This knowledge got lost when importing this connector and we tried to …
=> fix: Disable Airtable OAuth since it never worked

materialize-boilerplate/apply.go, materialize-boilerplate/validate.go, materialize-boilerplate/validate_test.go, materialize-dynamodb/type_mapping.go, materialize-elasticsearch/apply.go, materialize-elasticsearch/driver.go, materialize-elasticsearch/type_mapping.go, materialize-sql/type_mapping.go
Adds the option to materialize string values as keywords via the field configuration in field selection. Previously we would only materialize string fields as keywords if they were part of the collection key.
I had thought about doing more comprehensive validation on this to disallow setting the "keyword" field config value for non-string fields, but that was surprisingly difficult with the way the code is currently structured. This is going to be a pretty advanced feature currently since the only way to edit the field config is through the JSON of the spec, so it seems alright for now to keep it a little unpolished for the sake for expedience.
Use a spec like this to materialize a string value field `stringField` as a `keyword` mapping instead of a …
=> materialize-elasticsearch: allow materializing string values as keywords

materialize-bigquery/.snapshots/TestValidateAndApply, materialize-boilerplate/.snapshots/TestValidate, materialize-boilerplate/validate.go, materialize-databricks/.snapshots/TestValidateAndApply, materialize-elasticsearch/.snapshots/TestValidateAndApply, materialize-motherduck/.snapshots/TestValidateAndApply, materialize-mysql/.snapshots/TestValidateAndApply, materialize-postgres/.snapshots/TestValidateAndApply, materialize-snowflake/.snapshots/TestValidateAndApply, materialize-sql/type_mapping.go, materialize-sqlserver/.snapshots/TestValidateAndApply, materialize-starburst/.snapshots/TestValidateAndApply, materialize-starburst/sqlgen.go
The changes materializations to provide more actionable messages when producing unsatisfiable constraints.
Particularly for SQL materializations, which will currently report the existing column type and proposed JSON schema of the field, the message will now also report the type of column that is needed to accommodate the proposed JSON schema.
Overall the objective is to make it easier to understand how a user could migrate their existing table to be compatible with a changed collection schema.
Previously a constraint message for an unsatisfiable field change would look like this:
```
Field 'boolField' is already being materialized as endpoint type 'boolean' and cannot be changed to type '[number,string] format: integer content-encoding: base64'
``` …
=> materializations: better unsatisfiable constraint validation messages

source-mysql-batch/.snapshots/TestSpec, source-mysql-batch/driver.go, source-mysql-batch/main.go, source-postgres-batch/.snapshots/TestSpec, source-postgres-batch/driver.go, source-postgres-batch/main.go, source-redshift-batch/.snapshots/TestSpec, source-redshift-batch/driver.go, source-redshift-batch/main.go
Adds a new advanced config property for specifying a list of schemas to discover tables within.
If the property is unset then tables all schemas will still be discovered. If one or more values are specified for this property then only tables from those schemas will be returned and everything else will be ignored.
Note that the discovery queries still fetch information about all tables in the entire database and the filtering is applied within the connector to the query results. In general this should be fine, but if it becomes an issue in the future it should be possible to push down the logic into `WHERE` clauses in the discovery queries themselves.
- - - …
=> source-{mysql,postgres,redshift}-batch: Schema filtering

source-mysql/replication.go
These appear to be ignorable metadata which we don't need to do anything with.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1294)
=> source-mysql: Ignore RowsQueryEvents

source-hubspot/source_hubspot/streams.py
When running long duration captures in source-hubspot, a issue might occur where a new `ACCESS_TOKEN` has not yet refreshed, triggering a backoff.
The maximun try value set for this backoff is 5. Given that this can occur multiple times on a long duration stream, this PR aims to fix this by upgrading the backoff max value to 20.
**Tests**
Two tests were made on `contacts_lists_membership` stream:
1. The first one consisted on lowering the backoff max_try value to 1 ( forcing the issue to be raised ). This happened two hours after the stream initialization.
1. The second one consisted on raising the max_try value to 5 ( default ). Two backoffs were triggered: the first after 3 hours and the second after 6 hours after the stream initialization. Prints:
To my knowledge, the …
=> Fixing source-hubspot for long duration captures

source-bigquery-batch/driver.go, source-mysql-batch/driver.go, source-postgres-batch/driver.go, source-redshift-batch/driver.go
Previously we would emit very unhelpful error messages like:
error polling table: error executing query: expected 0 arguments, got 1
After this change that would instead be:
error polling binding "foo_bar": error executing query: expected 0 arguments, got 1
Which makes it a lot easier to go and fix the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1299)
=> source-*-batch: Specify resource name when polling fails

source-bigquery-batch/main.go
Unlike most SQL databases BigQuery allows NaNs to be stored into a floating-point column. The Go JSON serializer rejects NaNs, as they're not actually representable as JSON numbers.
There's no strictly right answer here, but in the past (see for instance `source-firestore`) we've mapped NaN floats to the string `"NaN"` in captures, so let's do that here too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1300)
=> source-bigquery-batch: Translate NaN to `"NaN"`

estuary-cdk/estuary_cdk/capture/common.py
Use GenericModel to support v1 pydantic polyfill.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1309)
=> estuary-cdk: common.ConnectorState is generic

source-postgres-batch/.snapshots/TestSchemaFilter-FilteredIn, source-postgres-batch/.snapshots/TestSchemaFilter-FilteredOut, source-postgres-batch/.snapshots/TestSchemaFilter-Unfiltered, source-postgres-batch/driver.go, source-postgres-batch/main_test.go, source-redshift-batch/.snapshots/TestSchemaFilter-FilteredIn, source-redshift-batch/.snapshots/TestSchemaFilter-FilteredOut, source-redshift-batch/.snapshots/TestSchemaFilter-Unfiltered, source-redshift-batch/driver.go, source-redshift-batch/main_test.go
Previously schema-filtering of discovery results was done by running a set of "give me everything" queries and then filtering out any results not matching the list of desired schemas.
However we have encountered at least one user whose production database is so large that the complete unfiltered query takes multiple minutes to execute, which can slow down binding refreshes so much that they consistently time out. We have confirmed that this slowdown is fixed by putting the desired schema(s) in a `WHERE` clause of the discovery query itself, so that's how we'll fix it.
So this PR removes the logic that previously filtered discovery based on schema and instead adds a `WHERE table_schema = ANY ($1)` clause to the queries (along with the appropriate argument value) if the …
=> source-{postgres,redshift}-batch: Filter schemas with query

estuary-cdk/estuary_cdk/capture/common.py
Ensure all tasks get a chance to make progress between each tasks's iterations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1314)
=> estuary-cdk: `common` routines should yield to the event loop

source-hubspot/source_hubspot/streams.py
Huspot Custom Streams schema was being generated with a `null` type, rendering the schema invalid to estuary dashboards. This PR removes that
Tests were made using a developer Hubspot account and a custom stream named venues
Results:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1322)
=> Fixing Hubspot Custom streams schema

source-gladly/source_gladly/models.py, source-gladly/tests/snapshots/source_gladly_tests_test_snapshots__discover__stdout.json
BaseDocument includes _meta fields which we don't want for the nested objects of Event, so use BaseModel instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1324)
=> source-gladly: use BaseModel for Event Model nested objects

sqlcapture/main.go
Table name in the resource config for sql captures should be a read only field
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1328)
=> Making table name readOnly

source-mysql/.snapshots/TestGeneric-SpecResponse, source-sqlserver/.snapshots/TestGeneric-SpecResponse, sqlcapture/main.go
Schema field in resource spec switched to read only 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1334)
=> Make schema field read only

materialize-mysql/.snapshots/TestSQLGeneration, materialize-mysql/driver.go, materialize-mysql/infile.go, materialize-mysql/sqlgen.go, materialize-mysql/sqlgen_test.go
Create transactor-scoped buffers and local file readers for uploading data across all bindings, rather than a buffer per binding. Also flush buffers after each time the binding changes during loads to take advantage of the natural grouping of load keys per binding, even though they aren't strictly increasing like for stores.
This greatly reduces memory use of the connector, and allows it to use a constant amount of memory rather than being proportional to the number of bindings.
Closes [#1332](https://github.com/estuary/connectors/issues/1332)
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sh …
=> materialize-mysql: reduce buffer use for data loading

materialize-databricks/.snapshots/TestSQLGeneration, materialize-databricks/driver.go, materialize-databricks/sqlgen.go, materialize-databricks/sqlgen_test.go, materialize-databricks/staged_file.go, tests/materialize/materialize-databricks/cleanup.sh, tests/materialize/materialize-databricks/snapshot.json
- Remove the use of temporary tables and use the Databricks SQL syntax for reading from files described here: https://docs.databricks.com/en/files/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1329)
=> materialize-databricks: read directly from staged files, no temp tables

materialize-motherduck/.snapshots/TestValidateAndApply, materialize-motherduck/sqlgen.go
Materialize UUID fields as string columns since UUID columns are currently broken in the DuckDB version used by MotherDuck.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1337)
=> materialize-motherduck: use string columns for UUIDs

go.mod, go.sum, materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/client.go, materialize-snowflake/config.go, materialize-snowflake/pipe.go, materialize-snowflake/snowflake.go, materialize-snowflake/sqlgen.go, materialize-snowflake/staged_file.go, materialize-sql/driver.go, tests/materialize/materialize-snowflake/checks.sh, tests/materialize/materialize-snowflake/fetch-data.go, tests/materialize/materialize-snowflake/fetch.sh, tests/materialize/materialize-snowflake/setup.sh, tests/materialize/materialize-snowflake/snapshot.json
- Support a new form of authentication using a username and a private key. We generate a JWT token and sign it using the private key to authenticate with Snowflake and Snowpipe REST API
- When using the JWT authentication mode, delta updates bindings are processed using Snowpipe
- Tested erroring out at the end of Acknowledge phase, and confirmed that we maintain idempotency by not replacing the pipe before sending requests again to the pipe.
One part that I still need to test: I need to test missing files again, I think given that snowpipe requires explicit specification of file names, it might break if we delete some files and then end up retrying those files. Need to verify
**Documentation …
=> materialize-snowflake: use snowpipe for delta update bindings + jwt auth

source-dynamodb/pull.go
This may improve throughput when scanning a single large table with large documents.
The originally selected value of 3 was completely arbitrary, and so is this new value. There may be some really fancy way to figure out the optimal value dynamically, but this manual adjustment should be good enough for now to provide useful information.
- - - …
=> source-dynamodb: increase concurrent table backfill scan workers

estuary-cdk/README.md, estuary-cdk/estuary_cdk/capture/common.py, estuary-cdk/estuary_cdk/http.py, source-hubspot-native/source_hubspot_native/api.py
See commits
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1330)
=> estuary-cdk idle backoff tweak & readme

source-mysql/.snapshots/TestAlterTable_AddColumnSetEnum-enum-restart, source-mysql/.snapshots/TestAlterTable_AddColumnSetEnum-enum-stream, source-mysql/.snapshots/TestEnumPrimaryKey, source-mysql/capture_test.go, source-mysql/datatype_test.go, source-mysql/discovery.go, source-mysql/main.go, source-mysql/replication.go
This PR fixes the connector backfill behavior when capturing from tables whose primary key includes a column of enum type whose cases are listed in non-alphabetical order.
The issue in this scenario was previously that if asked to `ORDER BY category` (where `category` is an enum column), MySQL will sort the rows based on the integer representation of those values. However when we ask it to return rows `WHERE category > 'foo'` for some string value `'foo'` the database will return those rows where that column's string representation is lexicographically greater than the string `'foo'`. Which is arguably correct, we need to cast that string to an enum to get the comparison behavior we actually want. But it makes things tricky for us here, because that cast is nontrivial to …
=> source-mysql: Support enum primary keys whose cases are in non-alphabetical order

source-mysql/.snapshots/TestEnumDecodingFix-backfill, source-mysql/.snapshots/TestEnumDecodingFix-replication1, source-mysql/.snapshots/TestEnumDecodingFix-replication2, source-mysql/capture_test.go, source-mysql/replication.go
In https://github.com/estuary/connectors/pull/1336 I (unnecessarily) refactored `source-mysql` to have the enum cases ordered like ["", "A", "B"] where previously they were ["A", "B", ""] and updated the indexing to match. But preexisting captures from before that change have the old style ordering in their metadata, and that's not updated anywhere, so they decode replication events incorrectly.
We can't even revert the changed indexing behavior at this point, because by now there are important captures which have been re-backfilled using the new ordering in their metadata, which would be incorrect if we simply reverted the change.
In order to fix this, we need to roll things forward and implement some metadata update logic which will prepend `""` to the list of options …
=> source-mysql: Fix enum decoding off-by-one bug by migrating old metadata

materialize-databricks/driver.go, materialize-databricks/staged_file.go
- Switch from Files API to PUT API now that it has become publicly available and is the recommended method for uploading files. https://www.databricks.com/blog/announcing-general-availability-unity-catalog-volumes
- Tested by running integration tests and running a large materialization task on this version
- - - …
=> materialize-databricks: use PUT api for uploading files

materialize-snowflake/client.go
Make sure we use the same connection that ran the USE SCHEMA command when running table alterations. Also make sure to return connections to the connection pool when done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1373)
=> materialize-snowflake: USE SCHEMA for alter table executions

materialize-bigquery/sqlgen.go
For string fields with `format: integer` or `format: number`, we have the convention of creating these columns as their underlying "string" column type if they are collection keys. This wasn't happening in `materialize-bigquery`, which causes immediate validation errors when a table like this is created. This fixes that issue, by making `materialize-bigquery` consistently with all other SQL materializations.
**Notes for …
=> materialize-bigquery: create numeric formatted string column key fields as strings columns

materialize-snowflake/client.go
- We were quoting all identifiers and this was leading to "simple" identifiers being quoted which would then distinguish them from then unquoted, upper-case relatives
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1378)
=> materialize-snowflake: use dialect identifier transformer for schema

source-postgres-batch/.snapshots/TestBasicCapture-Discovery, source-postgres-batch/.snapshots/TestKeyDiscovery, source-postgres-batch/.snapshots/TestSchemaFilter-FilteredIn, source-postgres-batch/.snapshots/TestSchemaFilter-Unfiltered, source-postgres-batch/driver.go, source-postgres-batch/main_test.go, source-redshift-batch/.snapshots/TestKeyDiscovery, source-redshift-batch/driver.go, source-redshift-batch/main_test.go
This PR replaces the table and primary key discovery queries used by the batch Postgres and Redshift captures. Previously these queries read from various `information_schema` views, but in practice getting permission grants set up so those views return the needed information could be quite difficult.
The fix is to drop down a level and consult the 'pg_catalog' tables directly. This ended up being a bit more complicated than expected, because Redshift is based on a really old version of Postgres and also changed some things around, but I think the new queries that I ended up with should work well enough for now.
This fixes https://github.com/estuary/connectors/issues/1342
There should be no changes that the user needs to care about, save that discovery …
=> source-{postgres,redshift}-batch: Use 'pg_catalog' for discovery

source-mysql/.snapshots/TestGeneric-KeylessDiscovery, source-mysql/.snapshots/TestGeneric-SimpleDiscovery, source-mysql/.snapshots/TestPartitionedTable-Discovery, source-mysql/.snapshots/TestSecondaryIndexDiscovery-index_only, source-mysql/.snapshots/TestSecondaryIndexDiscovery-nonunique_index, source-mysql/.snapshots/TestSecondaryIndexDiscovery-nothing, source-mysql/.snapshots/TestSecondaryIndexDiscovery-nullable_index, source-mysql/.snapshots/TestSecondaryIndexDiscovery-pk_and_index, source-mysql/.snapshots/TestTrickyColumnNames-discover, source-mysql/.snapshots/TestTrickyTableNames-Discover, source-sqlserver/.snapshots/TestIndexIncludedDiscovery, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-index_only, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-nonunique_index, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-nothing, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-nullable_index, source-sqlserver/.snapshots/TestSecondaryIndexDiscovery-pk_and_index, source-sqlserver/.snapshots/TestVarcharKeyDiscovery, sqlcapture/discovery.go
- Update the schema of `sqlcapture` connector so that when `_meta/op: "d"`, our JSONSchema specifies `reduce: { delete: true }`
- Tested this using `flowctl preview --delay 5s` and adding a log at https://github.com/estuary/flow/blob/74b61c820ffe19472eb435ad67f32b51968e26f5/crates/doc/src/reduce/strategy.rs#L357 to check whether the runtime would detect `delete: true` and it works as expected.
(anything …
=> sqlcapture: delete reduction for _meta/op: "d"

.github/actions/deploy/action.yaml, .github/workflows/ci.yaml
- Previously we would refresh the connector tags of all connectors even if they were not updated in the commit
- With this change, we only refresh connectors which have had their code updated
- One caveat is updating of a SDK / dependencies (go.mod) / shared files will not trigger a refresh unless a connector has also been directly updated. We can also include those shared resources in our condition …
=> ci: only refresh tags if connector is updated

source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py, source-facebook-marketing/test.flow.yaml, source-facebook-marketing/tests/snapshots/snapshots__discover__capture.stdout.json
- Use a default string so we can capture these collections even though sometimes the keys do not exist in certain documents. In these cases those documents will get reduced together (this is what has happened previously as well, since these fields were not even marked as a key)
- - - …
=> facebook: use default empty string for primary keys instead of required

materialize-databricks/sqlgen.go, tests/materialize/materialize-databricks/fetch-data.go, tests/materialize/materialize-databricks/fetch.sh, tests/materialize/materialize-databricks/snapshot.json
- We used to materialize `nil` JSON values as an empty string. This was undetected because we were using `dbsqlcli` for our integration test snapshotting, which didn't allow us to distinguish between an empty string and `nil`.
- Added a `fetch-data.go` file so we can represent values of the table more accurately in our snapshots, including `nil`
- - - …
=> databricks: null for JSON columns

sqlcapture/capture.go
JSON encoding is one of the single largest bottlenecks in the SQL CDC captures at present. A recent example in production where replication throughput was constrained by connector CPU had JSON serialization at around 70% of main thread CPU usage.
The standard library `encoding/json` package is fairly slow with the way it uses reflection everywhere, and the package `github.com/segmentio/encoding/json` is a drop-in replacement which performs 2-3x better in most benchmarks.
So swapping out the JSON encoder used here is a very easy way to improve the situation, although in the long run there are fancier approaches we could potentially use to make it even faster.
See also:
- source-mysql-batch in https://github.com/estuary/connectors/pull/1005
- materialize-sql in …
=> sqlcapture: Use segmentio JSON encoder instead of stdlib

estuary-cdk/estuary_cdk/shim_airbyte_cdk.py, estuary-cdk/tests/test_airbyte_cdk.py
Flow key components are strings that represent JSON pointers. So a key component `/meta/row_id` would mean that the key for document `{"meta": {"row_id": 1234}}` would be `1234`. But we could also have a document like `{"pizza/party": 1234}`, and if we wanted to use that field `"pizza/party"` as the key, that’s where we’d want to escape it as `"pizza~1party"`. I did some digging, and it looks like airbyte handles nested keys a little differently:
```python
@property
@abstractmethod
def primary_key(self) -> Optional[Union[str, List[str], List[List[str]]]]:
"""
:return: string if single primary key, list of strings if composite primary key, list of list of strings if composite primary key consisting of nested fields.
If the stream has no primary keys, return None.
"""
``` …
=> cdk: Fix unneccesary escaping on key components in Airbyte shim

source-redshift-batch/.snapshots/TestBasicCapture-Discovery, source-redshift-batch/.snapshots/TestBasicDatatypes-Discovery, source-redshift-batch/.snapshots/TestKeylessDiscovery, source-redshift-batch/.snapshots/TestSchemaFilter-FilteredIn, source-redshift-batch/.snapshots/TestSchemaFilter-Unfiltered, source-redshift-batch/README.md, source-redshift-batch/driver.go, source-redshift-batch/main_test.go
This PR modifies the `source-redshift-batch` connector so that the generated schemas for discovered collections will include all columns with appropriate JSON schema types, rather than just the primary-key columns as it did previously.
In addition `source-redshift-batch` will no longer suggest a fallback collection key of `[/_meta/polled, /_meta/offset]` for tables without a primary key. This means that users will be forced to pick their desired collection key, which is why it was important that we adjust the discovered schema so that they have appropriate options to choose from.
I haven't given a lot of thought to how the change in discovery output will impact existing uses of the Redshift connector. The omission of a collection key for keyless tables …
=> source-redshift-batch: Discover all columns and omit fallback key

source-postgres-batch/.snapshots/TestSpec, source-postgres-batch/driver.go, source-redshift-batch/.snapshots/TestBasicCapture-Discovery, source-redshift-batch/.snapshots/TestBasicDatatypes-Discovery, source-redshift-batch/.snapshots/TestKeyDiscovery, source-redshift-batch/.snapshots/TestKeylessDiscovery, source-redshift-batch/.snapshots/TestSchemaFilter-FilteredIn, source-redshift-batch/.snapshots/TestSchemaFilter-Unfiltered, source-redshift-batch/.snapshots/TestSpec, source-redshift-batch/driver.go
The cursor values will always be empty, and we want that to be represented by omitting the property from the discovered resource spec entirely rather than with an explicit null.
Also makes the same change to `source-postgres-batch`. It doesn't matter there because discovered resources always have the default cursor `["txid"]` but the fact that I left off the `omitempty` in that case is why the Redshift connector got this wrong.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1398)
=> source-redshift-batch: Omit empty cursors in discovered resources

materialize-databricks/staged_file.go, materialize-sql/driver.go
- We previously applied this change of short-lived database connections elsewhere in the connector, but we got reports that they still see leftover connections _sometimes_. I found that we had this case where we would open a connection in Validate as part of initialising the `client`, but we were not closing it.
- Decreased file upload concurrency until https://github.com/databricks/databricks-sql-go/pull/197 is merged
**Notes …
=> materialize-sql: close client in Validate

materialize-snowflake/snowflake.go, materialize-snowflake/staged_file.go, tests/materialize/materialize-snowflake/setup.sh
This is some janky temporary logging for helping troubleshooting "JSON document too large" errors with on-going snowflake materializations. I intent to remove this after the source collection is identified.
- - - …
=> materialize-snowflake: add temporary logging when encoding excessively large documents

materialize-snowflake/snowflake.go, materialize-snowflake/staged_file.go
This reverts commit 55eee0b153ae05eb72e553659f1b4d989851892f.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1405)
=> Revert "materialize-snowflake: add temporary logging when encoding excessively large documents"

source-redshift-batch/.snapshots/TestBasicCapture-Discovery, source-redshift-batch/.snapshots/TestBasicDatatypes-Discovery, source-redshift-batch/.snapshots/TestKeyDiscovery, source-redshift-batch/.snapshots/TestKeylessDiscovery, source-redshift-batch/.snapshots/TestSchemaFilter-FilteredIn, source-redshift-batch/.snapshots/TestSchemaFilter-Unfiltered, source-redshift-batch/driver.go, source-redshift-batch/main_test.go
Currently most discovery flows are broken because we treat columns as always being non-null due to a dumb oversight in how the boolean nullability value is (not) plumbed through to schema generation, so then the moment you actually start capturing data you get a ton of schema violations wherever nulls actually exist.
This PR fixes that oversight.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1408)
=> source-redshift-batch: Fix handling of column nullability

source-sqlserver/.snapshots/TestDiscoveryIrrelevantConstraints, source-sqlserver/.snapshots/TestGeneric-KeylessDiscovery, source-sqlserver/.snapshots/TestGeneric-SimpleDiscovery, source-sqlserver/datatypes_test.go, source-sqlserver/discovery.go
Previously our discovery schema generation for a `TIME` column in the source database produces `{type: string, format: time}`, but that format means "a string satisfying the `full-time` production rule from RFC3339" and `full-time` has to end in a timezone offset suffix, but the `TIME` column is just a bare `HH:MM:SS[.NNN]` value without any associated time zone offset for us to provide, so right now we don't have any such suffix and that means that the values we capture don't actually satisfy the JSON schema we claimed.
In order to resolve this we could:
1. Slap on a suffix of `"Z"` to every time value
2. Interpret the time values in the capture's configured timezone.
3. Stop claiming these strings match `format: time`
The problem with option 1 is that these times are no …
=> source-sqlserver: Remove `format: time` from `TIME` column type

source-mysql/replication.go
This PR combines two relatively trivial tweaks to the MySQL replication metadata tracking:
- Upgrading the log levels for DDL query event processing so that we'll always get something in the logs at `INFO` level. This should help us actually figure out what's happened the next time our metadata tracking gets out of sync with the source table.
- Whitelisting `ALTER DATABASE` queries as safe. There is no `ALTER DATABASE` query that we actually need to care about, so this was fairly simple.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1412)
=> source-mysql: Two replication metadata tweaks

source-sqlserver/prerequisites.go
Currently this check is *way* too conservative, because we know that the SQL Server CDC functionality has existed in its current form since at least SQL Server 2008 (though not all versions of the database).
In the absence of this check, a database which doesn't support CDC will instead produce several errors, something like:
- CDC is not enabled on database "db" and user "flow_capture" cannot enable it
- unable to query capture instances for table "dbo.flow_watermarks": <something about unknown table cdc.change_tables>
- error querying the current LSN: <something about unknown procedure sys.fn_cdc_get_max_lsn>
(In case it wasn't clear I haven't actually run this against such a database just now, so I'm handwaving exactly what the database- provided portion of those …
=> source-sqlserver: Disable DB version prerequisite check

materialize-databricks/client.go, materialize-sql/std_sql.go
- I found the root cause of the leftover connection in Databricks, we were creating this additional connection here but not closing it.
- I was able to reproduce the original issue and can confirm with this patch it doesn't happen anymore
- - - …
=> stdsql: close connection used to ping database in exec

source-sqlserver/replication.go
Since SQL Server replication works by issuing polling queries and most ways that can fail result in errors, a "silent failure" mode seems most likely to come about if the CDC agent job whose job it is to tail the WAL and copy changes into change tables simply isn't running.
The new diagnostic logic is untested, but it will only be run in the event that replication is already not working as intended, so the risk of breakage is minimal here and I intend to try it out in production shortly after it's live.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1431)
=> source-sqlserver: Query job status during replication diagnostics

materialize-sql/apply.go, materialize-sql/type_mapping.go
A couple of small QoL fixes for sql materializations:
- Forbid fields with no types, since these will error on apply and we currently recommend them by default
- Don't log out the base64 applied spec insert/update, since it's not useful and often so huge as to be problematic
Closes https://github.com/estuary/connectors/issues/1404
When you publish a SQL materialization, the action description for updating or insert the spec will now look something like this:
```
INSERT INTO flow_materializations_v2 (version, spec, materialization) VALUES ('0cff7f5dee810400', '(a-base64-encoded-value)', 'bobCo/mysql2/materialize-mysql')
```
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJ …
=> materialize-sql: forbid fields with no types, and don't log applied specs

go.mod, go.sum
Updates the go snowflake driver from v1.7.2 to v1.9.0, which is the latest version. This is used by `materialize-snowflake` and `source-snowflake`.  I looked through the release notes and didn't see any breaking changes between these versions.
We've been getting segfault errors recently with async queries that resolve on the connector restarting, and have also been getting "session has expired" errors since upgrading to v1.7.2 despite our use of the `client_session_keep_alive` parameter. I don't have any reason to believe that this update will fix those, but it will put us in a better position to further troubleshoot since we'll be able to take the possibility of an outdated driver version out of the conversation.
(How does one use this feature, and …
=> snowflake: update go driver from v1.7.2 to v1.9.0

estuary-cdk/estuary_cdk/shim_airbyte_cdk.py
A couple of fixes for state handling in the airbyte shim. See individual commit messages.
Run an airbyte-shim-based connector and it will persist state, and also be able to migrate from ATF versions of the connector by re-backfilling all of its bindings.
- - - …
=> airbyte shim: fixes for state handling

source-firestore/pull.go
Adds a bit of debug logging to provide greater visibility into backfill state mismatches, and modifies the handling of non-catchup-failure `TargetChange.REMOVE` events to also just retry internally rather than failing the connector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1441)
=> source-firestore: Logging tweak and retry `TargetChange.REMOVE` failures

materialize-snowflake/snowflake.go, tests/materialize/materialize-snowflake/setup.sh
- Allow more time for Snowpipe results to show up
- We have a task which we have seen that requests sent at 11:06 show up in results only at 11:10, that's 4 minutes later. Here I am allowing up to 5 minutes.
- - - …
=> m-snowflake: increase retry count and delay

source-firestore/pull.go
This *probably* isn't necessary, but one of the challenges with Firestore change streaming is that it's actually not super hard to end up in a permanent failure loop where you keep reading the same documents over and over and accidentally rack up large bills.
In other places where we retry after a failure status we generally wait 60 seconds before trying again, and it's probably prudent to do that for the newly added `TargetChange.REMOVE` retry logic as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1445)
=> source-firestore: Only retry TargetChange.REMOVE after 60s

build-local.sh
usage rate is a missing parameter in build-local.sh script, without it local images cannot be processed.
This PR adds this parameter inside the bash script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1449)
=> Adding usage rate to build-local script

source-mysql/.snapshots/TestAlterTable_AddColumnSetEnum-enum-restart, source-mysql/.snapshots/TestAlterTable_AddColumnSetEnum-enum-stream, source-mysql/.snapshots/TestAlterTable_AddColumnSetEnum-set-restart, source-mysql/.snapshots/TestAlterTable_AddColumnSetEnum-set-stream, source-mysql/.snapshots/TestAlterTable_AddEnumColumn-discover1, source-mysql/.snapshots/TestAlterTable_AddEnumColumn-discover2, source-mysql/.snapshots/TestAlterTable_AddEnumColumn-init, source-mysql/.snapshots/TestAlterTable_AddEnumColumn-modified, source-mysql/.snapshots/TestAlterTable_AddEnumColumn-rebackfilled, source-mysql/discovery.go, source-mysql/main_test.go, source-mysql/replication.go
When processing DDL query events involving enum (and set) columns we're relying on the Vitess SQL parser giving us the correct list of options for the column types and using that to update our metadata. However, apparently we've been getting single-quoted (and potentially backslash-escaped) strings back from the parser and so our metadata ends up in an incorrect state which disagrees with our own discovery logic and the results of a subsequent backfill.
The behavior on Vitess's part appears to be deliberate. The single-quoted strings are actually tokenized into plain-old strings and then explicitly turned back into single-quoted strings via the `encodeSQLString()` helper function when the parse tree is built. I have no idea why this would ever be desirable, but whatever. …
=> source-mysql: Correctly handle enum values when processing DDL query events

source-mysql/replication.go, source-mysql/replication_test.go
- Ignore more complex cases of `CREATE VIEW`, such as this one:
```
CREATE ALGORITHM=UNDEFINED DEFINER=`viewer`@`%` SQL SECURITY DEFINER VIEW `capture_facebook_expression` AS SELECT ...
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connect …
=> source-mysql: ignore more complicated CREATE ... DEFINER ... VIEW qs

materialize-boilerplate/apply.go
In e852e80, materializations were made aware of the possibility for default values in the materialized columns, and that we should not try to drop "not null" constraints on columns like this, under the assumption that the destination system is fine with us sending a "null" since it will automatically be populated (in a sense) with that default value.
This didn't take into consideration the fact that Flow projections can also have default values, and in this case we will never see a "null" for these fields from the Flow runtime, and instead will always see that default value. So here too we do not need to drop nullability constraints - the materialized columns can stay "not null" and as long as there is that default value annotation things will work fine.
This is …
=> materializations: don't try to drop nullability if the projection has a default value

source-mysql/.snapshots/TestEmptyBlobs-Capture, source-mysql/.snapshots/TestEmptyBlobs-Discovery, source-mysql/capture_test.go, source-mysql/discovery.go
In order to make absolutely sure that no dirty memory-reuse tricks happen to us, we make a copy of any byte data as part of our value translation logic. However, as previously written the copy would translate the empty byte slice `[]byte{}` into the nil byte slice `[]byte(nil)` as a side effect.
This is incorrect, since `[]byte(nil)` serializes to JSON `null` while `[]byte{}` serializes to JSON `""`, and we need to produce the latter form both because it's a more accurate representation of the source data and because the column could be non-nullable and not allow `null` at all.
This is fixed by instead using `make([]byte, ...)` to always allocate a new byte slice of adequate capacity.
- - - …
=> source-mysql: Fix handling of empty binary columns

source-mysql/.snapshots/TestGeneric-SpecResponse, source-mysql/main.go, source-postgres/.snapshots/TestCapitalizedTables-Discover, source-postgres/.snapshots/TestDiscoveryCapitalization, source-postgres/.snapshots/TestDiscoveryComplex, source-postgres/.snapshots/TestDiscoveryWithoutPermissions, source-postgres/.snapshots/TestGeneric-KeylessDiscovery, source-postgres/.snapshots/TestGeneric-SimpleDiscovery, source-postgres/.snapshots/TestGeneric-SpecResponse, source-postgres/.snapshots/TestPartitionedTableDiscovery, source-postgres/.snapshots/TestSecondaryIndexDiscovery-index_only, source-postgres/.snapshots/TestSecondaryIndexDiscovery-nonunique_index, source-postgres/.snapshots/TestSecondaryIndexDiscovery-nothing, source-postgres/.snapshots/TestSecondaryIndexDiscovery-nullable_index, source-postgres/.snapshots/TestSecondaryIndexDiscovery-pk_and_index, source-postgres/.snapshots/TestTrickyColumnNames-discover, source-postgres/.snapshots/TestUserTypes-Domain-Discovery, source-postgres/.snapshots/TestUserTypes-Enum-Discovery, source-postgres/.snapshots/TestUserTypes-Range-Discovery, source-postgres/.snapshots/TestUserTypes-Tuple-Discovery, source-postgres/Dockerfile, source-postgres/main.go, source-sqlserver/.snapshots/TestGeneric-SpecResponse, source-sqlserver/main.go, sqlcapture/discovery.go, sqlcapture/interface.go, sqlcapture/main.go
- One important realisation about transaction reductions is that the first document of a transaction is never reduced, and it is only the second and third and subsequent documents that may be reduced together.
- Tested this change on postgres, mysql and sqlserver connectors and here are results:
Queries:
```
insert into test(id, x) values(1, 'created'); update test set x='updated'; update test set x='updated 2'; delete from test;
```
Postgres, History mode OFF:
```
["acmeCo/test",{"_meta":{"op":"c","source":{"loc":[24427448,24427448,24427584],"schema":"public","table":"test","ts_ms":1712561583740,"txid":2499}},"id":1,"x":"created"}]                                              
["acmeCo/test",{"_meta":{"op":"d","source":{"loc":[24427888,24427888,24427952],"schema":"public" …
```
=> sqlcapture: history mode

source-google-sheets-native/source_google_sheets_native/models.py, source-google-sheets-native/tests/snapshots/source_google_sheets_native_tests_test_snapshots__spec__stdout.json
accessTokenHeaders was set to x-www-form-urlencoded, breaking OAuth.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1468)
=> Removing access token headers

materialize-snowflake/client.go, materialize-snowflake/pipe.go, materialize-snowflake/snowflake.go, materialize-snowflake/sqlgen.go, tests/materialize/materialize-snowflake/snapshot.json
- We have realised that `CREATE OR REPLACE PIPE` is eventually consistent, and so re-creating a pipe on each connector restart was leading to a race where we would send our file ingestion requests to the old pipe (even though we made the request after having run the `CREATE OR REPLACE` query) while that old pipe was going to be deleted and we would then request status updates from the new pipe which did not know about the old pipe. This lead to maximum retries when trying to fetch status of pipe and then a restart for us to attempt to ingest the file again...
- With this change, we only re-create a pipe if the spec version has changed. We also version the pipe name so that when this change is happening, the new pipe and the old pipe do not collide in names, leading to …
=> m-snowflake: recreate pipes on version change only

sqlcapture/capture.go
This PR bundles together several small logging tweaks each meant to address specific things that keep on annoying me when looking at SQL CDC task logs. The commit messages contain more details on each change, but the TL;DR summaries are:
- Fixed the wording of the `no active bindings, resetting cursor` message because it's inaccurate now that the state key changes allow the cursor to be reset _if all bindings are newly added (including backfill increments) in this restart_ without the need for an intermediate startup without any active bindings.
- Logging the number of backfill rows processed (for symmetry with replication and because this would have been useful info once or twice in the past) and when a particular table is determined to be done backfilling.
- No longer …
=> sqlcapture: Quality-of-life tweaks to log messages

estuary-cdk/estuary_cdk/flow.py, source-google-sheets-native/tests/snapshots/source_google_sheets_native_tests_test_snapshots__spec__stdout.json, source-hubspot-native/acmeCo/companies.schema.yaml, source-hubspot-native/acmeCo/contacts.schema.yaml, source-hubspot-native/acmeCo/deals.schema.yaml, source-hubspot-native/acmeCo/engagements.schema.yaml, source-hubspot-native/acmeCo/engagements_calls.schema.yaml, source-hubspot-native/acmeCo/engagements_emails.schema.yaml, source-hubspot-native/acmeCo/engagements_meetings.schema.yaml, source-hubspot-native/acmeCo/engagements_notes.schema.yaml, source-hubspot-native/acmeCo/engagements_tasks.schema.yaml, source-hubspot-native/acmeCo/feedback_submissions.schema.yaml, source-hubspot-native/acmeCo/goal_targets.schema.yaml, source-hubspot-native/acmeCo/line_items.schema.yaml, source-hubspot-native/acmeCo/products.schema.yaml, source-hubspot-native/acmeCo/ticket_pipelines.schema.yaml, source-hubspot-native/acmeCo/tickets.schema.yaml, source-hubspot-native/source_hubspot_native/__init__.py, source-hubspot-native/source_hubspot_native/api.py, source-hubspot-native/source_hubspot_native/models.py, source-hubspot-native/tests/snapshots/source_hubspot_native_tests_test_snapshots__capture__stdout.json, source-hubspot-native/tests/snapshots/source_hubspot_native_tests_test_snapshots__discover__stdout.json, source-hubspot-native/tests/snapshots/source_hubspot_native_tests_test_snapshots__spec__stdout.json, source-hubspot-native/tests/test_snapshots.py
Tests were made using a flow local stack along with a free-tier version of supabase for materialization.
In order to fix OAuth2 & Access Token issues, both were granted a `secret=True` setting within their sensible data fields.
Also, both `credentials_title` and `credentials` fields were assigned basic types, so that Flow UI would not display warnings. This modified both spec snapshots from `source-hubspot-native` and `source-google-sheets-native`, and they were also updated in this PR. 
The following Streams were validated using the newly built ":local" source-hubspot-native inside Flow UI:
- Companies
- Contact Lists
- Contacts
- Contacts Lists Subscription
- Email Events
- Email Subscriptions
- Marketing Emails
- Properties
- Subscription Changes
- Custom Objects ( Venues is our …
=> Modified OAuth2 and Access Token specs in estuary_cdk & source-hubspot-native fixes

source-mysql/.snapshots/TestEnumEmptyString-backfill, source-mysql/.snapshots/TestEnumEmptyString-replication, source-mysql/capture_test.go, source-mysql/discovery.go
It is possible to define an enum in MySQL with an explicit case for the empty string `''`, for instance `enum('', 'Y', 'N')` is a valid enum definition.
When this is done the empty string is both the text representation of the error value zero *and also* a valid enum option with some particular index (in the above option that index is 1 but it is possible to place that anywhere in the options list), but other than that everything continues to operate as normal.
So to fix that our enum parsing logic needs to accept the empty string, which turns out to only require a single-character fix to the parsing regex because apparently I did a dumb thing and wrote it in such a way that it excluded the empty string before.
This fixes https://github.com/estuary/connectors/issues/1495 …
=> source-mysql: Fix handling of enums with explicit `''` option

estuary-cdk/estuary_cdk/capture/common.py, source-gladly/source_gladly/resources.py, source-google-sheets-native/source_google_sheets_native/resources.py, source-hubspot-native/source_hubspot_native/resources.py
Updates to the CDK that arose out of Netsuite work:
* Relax `PageCursor` to accept negative ints. This is just a typing change, but it was required because some page cursor values in Netsuite are genuinely negative ints
* Teach `FetchChangesFn` and `FetchPageFn` to accept documents for different bindings by way of yielding `AssociatedDocuments`. This is needed in order to enable loading associated documents, which we need to do for e.g `TransactionAccountingLine`
* Pass `open()` information about all bindings in order for it to find the bindings of its associations (specifically so that it knows which binding index to emit documents for when loading associated docs)
- - - …
=> CDK updates

source-firestore/pull.go
We already sanitize `NaN` in this way, I'm just copy-pasting the same logic we apply in other connectors for positive and negative infinity as well.
Since previously this would fail JSON serialization we know that the connector has never successfully processed float infinities before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1525)
=> source-firestore: Sanitize float infinities into strings

source-hubspot/source_hubspot/streams.py
As of now, Hubspot Source still fails due to  re-authentication limits.
This happens due to Hubspot `access_token` short lifespan ( about 30 minutes ), and the connector failing to re-authenticate properly.
Previous attemps set the number of retries to 20, but it seems the amount of user data can be higher than estimated and no issues would arise from removing the limit.
More information on the commit.
Tests were made locally running for about 2 hours and 15 hours
Token rotation is marked with a **GOT NEW TOKEN** info logger message.
as one can validate, each new token now rotates on about 28 minutes run, not 30 ( lifetime of the hubspot access_token)
Fully stats after runing for about 15 hours:
- - - …
=> Source-hubspot: Removing max amount of auth retries

source-hubspot/source_hubspot/streams.py, source-hubspot/tests/snapshots/snapshots__discover__capture.stdout.json
Errors in [source-hubspot](https://github.com/estuary/connectors/actions/runs/8883481172/job/24390442518) build
Updated discovery snapshots, as a new field was added in companies Just a note on this: 
i **think** its not a new field added by hubspot, but a property field that came in a different order when calling the properties API. The code will limit the amount of properties, and given that then can come in different orders, may cause this issue. I saw this behaviour when working with source-hubspot-native , but i still neeed some time to evaluate.
Also added a check on the authenticator type in streams.py. Tests were using TokenAuthenticator and calling the read_records method, causing the code to fail.
All changes were tested with end-to-end tests on a hosted …
=> source-hubspot: Fixing tests

source-mysql/replication.go, source-postgres/replication.go, source-sqlserver/replication.go
This PR adds a couple more queries to the automated replication diagnostics for SQL Server.
It also rewords the `"got row"` log message for all three of Postgres/MySQL/MSSQL -- it was usually clear from context that these were diagnostic query results, but when there are lots of complex result rows that's less obvious so hopefully `"got diagnostic row"` will be clearer in such cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1542)
=> source-sqlserver: Improved replication diagnostics

source-sqlserver/replication.go
Adds another query (`SELECT * FROM msdb.dbo.cdc_jobs;`) to SQL Server replication diagnostics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1543)
=> source-sqlserver: Another replication diagnostic query

source-mongodb/backfill.go, source-mongodb/change_stream.go, source-mongodb/pull.go
Reduces some of the logging noise by adjusting logs to debug level, and makes the frequency of change stream progress updates 5 minutes instead of 1 minute.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1550)
=> source-mongodb: adjust logging

materialize-redshift/.snapshots/TestSQLGeneration, materialize-redshift/client.go, materialize-redshift/driver.go, materialize-redshift/driver_test.go, materialize-redshift/sqlgen.go, materialize-redshift/sqlgen_test.go
The `enable_case_sensitive_identifier` configuration makes it so Redshift does not always lowercase all identifiers, and causes it to preserve the casing of quoted identifiers.
Previously we would always assume that this parameter was OFF and that we should treat identifiers as lowercase, but this breaks materializations where the cluster is configured with the parameter to ON.
The changes here allow us to support clusters where `enable_case_sensitive_identifier` is set to ON.
Tested by running all the unit and e2e tests, and manually ran a materialization with mixed capitalization fields with `enable_case_sensitive_identifier` both on and off to make sure it produced the expected output.
Closes https://github.com/estuary/connectors/issues/1273
(How …
=> materialize-redshift: support clusters with `enable_case_sensitive_identifier` set to ON

source-mysql/backfill.go, source-postgres/backfill.go, source-sqlserver/backfill.go, sqlcapture/capture.go, sqlcapture/interface.go
Historically we have detected when a backfill reaches the end of a table when we receive zero new rows from a backfill query. This usually works fine, but can misbehave when a table is both heavily loaded with new rows constantly inserted at the end *and also* the individual backfill queries are relatively slow.
When this happens, the backfill can keep on issuing queries for up to <chunkSize> rows, and receive a few dozen each time, which keeps the backfill from terminating. And normally that's also benign, so we haven't bothered to fix it up until now.
However there are still a few edge cases where backfill queries can get fairly expensive. The one we're seeing in production right now is queries against a very large keyless table in MySQL, but there are a few other …
=> sqlcapture: Fix backfill termination on slow, high-volume tables

estuary-cdk/estuary_cdk/capture/common.py, source-gladly/tests/snapshots/snapshots__discover__stdout.json, source-google-sheets-native/tests/snapshots/source_google_sheets_native_tests_test_snapshots__discover__stdout.json, source-hubspot-native/source_hubspot_native/__init__.py, source-hubspot-native/source_hubspot_native/api.py, source-hubspot-native/source_hubspot_native/models.py, source-hubspot-native/source_hubspot_native/resources.py, source-hubspot-native/tests/snapshots/source_hubspot_native_tests_test_snapshots__discover__stdout.json, source-hubspot-native/tests/snapshots/source_hubspot_native_tests_test_snapshots__spec__stdout.json
Adds bindings for email events and custom objects to `source-hubspot-native`, as well as some other fixes along the way to get the connector working.
The APIs used for both of these bindings have been noted elsewhere to have consistency issues, so the data from them will be delayed by 5 minutes with the hopes that such a delay is long enough to give us consistent results. Of course this is a total guess, based on almost nothing, and we may need to adjust it based on real-world observations.
I've manually tested the connector built from these changes and compared it with the existing ATF based connector to verify that the outputs are equivalent. I've also run it against a large hubspot account and verified that it captures data that looks reasonably correct.
**Workflow …
=> source-hubspot-native: add email events and custom objects

materialize-redshift/.snapshots/TestSQLGeneration, materialize-redshift/driver.go, materialize-redshift/sqlgen.go, materialize-redshift/sqlgen_test.go
This column truncation was removed in a recent commit under the assumption that the runtime would prevent the connector from seeing strings over the allowed limit, but we are seeing errors resulting from strings being too long to materialize with the newly deployed image.
This adds back the truncation configurations that were removed to get things unbroken in the short-term while I figure out why the original assumption didn't hold. …
=> materialize-redshift: add back column truncation

source-mysql/.snapshots/TestAlterTable_AddUnsignedColumn-discover2, source-mysql/discovery.go
This broke several things in production and we should get those fixed with correct values of unsigned integer columns before we start enforcing that in the schema.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1569)
=> source-mysql: Don't specify `minimum: 0` for now

materialize-databricks/sqlgen.go
- Tested this using my other branch https://github.com/estuary/connectors/pull/1571 which also runs Validate as part of integration tests. Creating the tables, not deleting them, and running integration tests again, verified an error happens without this pull-request complaining about unknown type `DECIMAL`, whereas with this pull-request Validate passes 👍🏽 
- Separated the other pull-request since it requires more time put into it to update all tests for all materialization connectors …
=> materialize-databricks: support decimal column validation

source-mysql/replication.go
This PR stops the MySQL replication DDL parsing logic from ignoring queries which begin with a comment.
There were reasons this was expedient in the past, but it's causing us pain at the moment and the Vitess SQL parser ought to be able to cope with the comments themselves -- IIRC the issue in the past was specific queries which began with a comment and used some unsupported statement type or another.
But right now this is the number one issue with our DDL tracking logic, and unlike the second biggest issue (DDL queries which don't get logged at all) it's unarguably our fault we're not handling it well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/ …
=> source-mysql: Stop ignoring query events with leading comments

materialize-databricks/sqlgen.go
As a simplification to avoid having to deal with equality comparisons between binary columns and staged JSON values, we'll keep materializing collection keys with base64 encoding as strings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connec …
=> materialize-databricks: keep base64 encoded string keys as strings

materialize-databricks/.snapshots/TestSQLGeneration, materialize-databricks/sqlgen.go, materialize-databricks/testdata/flow.yaml, materialize-databricks/testdata/spec.json
Adds support for collection key fields that are base64-encoded strings to be materialized as binary columns, in addition to the previously added support for value fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1575)
=> materialize-databricks: support binary primary keys

source-google-sheets-native/source_google_sheets_native/api.py, source-google-sheets-native/source_google_sheets_native/models.py
source-google-sheets-native is missing [boolValue](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#ExtendedValue) support, causing any Spreadsheet with boolValues to raise. This PR adds this value to the expected values model. 
Tested end-to-end using a local version of flow and a supabase DB materialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1577)
=> source-google-sheets-native: Adding boolValue support

source-postgres/backfill.go, source-postgres/main.go, source-postgres/prerequisites.go, sqlcapture/capture.go
This PR adds a small `map[StreamID]bool` keeping track of which tables are published according to `pg_catalog.pg_publication_tables`, so that when verifying that all active bindings are published we can issue a single query and then just consult the cache instead of having to issue one query for every binding.
This doesn't fix the overall O(n) nature of the per-table prerequisite validation because we still at minimum issue a `SELECT * FROM table LIMIT 0` query to check table readability, but it improves the constant factor by 2x and means there's only the one O(n) operation left, both of which are worthwhile improvements.
(This PR also contains a little bit of fiddling about to introduce a `sqlcapture.StreamID` type alias, because when I went to add a `map[string]bool` …
=> source-postgres: Cache table-publication info used when checking prerequisites

materialize-pinecone/client/client.go
See https://pinecone-2-partner-integration-guide.mintlify.app/integrations/build-integration/attribute-api-activity
There's actually a Go pinecone client now so we could consider changing the connector to use that at some point. A reason to do that would be that I'd imagine it uses the more performant gRPC API, so it would make sense to do if we ever see Pinecone being the bottleneck for the materialization.
For now we can simply add the attribution to own HTTP client though. …
=> materialize-pinecone: add attribution source tag

source-mysql/datatype_test.go, sqlcapture/tests/datatypes.go, sqlcapture/tuples.go
- Added the ability to test datatypes as primary keys to our test harness and used it to test the int8 case
- Prior to this pull-request we would get this error if a `tinyint` was used as [part of] a primary key
```
error encoding row key for \"test.datatypes_5_tinyint_10000005\": error serializing FDB tuple: unencodable element at index 0 (124, type int8)
``` …
=> sqlcapture: handle u/int8 values in fdb tuple packing

source-mysql/replication_test.go
Apparently I broke a test when making the comment-ignoring change in https://github.com/estuary/connectors/pull/1567 and since then the `source-mysql` CI build has been failing. Whoops.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1582)
=> source-mysql: Fix broken test of the query-ignore regexp

source-hubspot-native/source_hubspot_native/api.py
This is temporary logging to help troubleshoot a repeating issue with incremental changes capturing of the "deals" stream repeatably falling behind.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1584)
=> source-hubspot-native: additional debug logging for fetching recent deals

source-hubspot-native/source_hubspot_native/api.py
Follow-up of https://github.com/estuary/connectors/pull/1584; adds a little more (temporary) logging for the `deals` recent changes function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1585)
=> source-hubspot-native: adjust temporary logging for deals stream

estuary-cdk/estuary_cdk/capture/__init__.py, estuary-cdk/estuary_cdk/capture/common.py, source-hubspot-native/source_hubspot_native/api.py
Currently when any incremental task stops yielding documents after the resource-specific interval
has elapsed, the task will exit and remain idle until all other tasks have completed and the
connector exits. This is a problem when there are long-running backfills which make take longer to
complete than the incremental streams can allow because of log cursor expiration, etc.
To address this, backfill tasks are being made aware of the "stopping" signal, and they will return
when this signal is set, even if the backfill isn't 100% complete. This will cause the capture to do
its periodic restart after all incremental tasks have caught up, and not require all backfills to be
complete as well.
To prevent excessive restarting that may negatively impact throughput during …
=> estuary-cdk: use fixed restart interval of 24 hours and make backfills respect it too

materialize-pinecone/client/client.go
This is a follow-up to https://github.com/estuary/connectors/pull/1578, which only added the attribution to a single API call. We need to add it to all Pinecone API calls, especially `Upsert`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/conn …
=> materialize-pinecone: add attribution source tag to additional API calls

source-postgres/backfill.go, source-sqlserver/backfill.go
These connectors previously only checked for errors which occur when first executing the query, but it's possible for something to go wrong partway through streaming query results, and right now if that happens after we've read some rows but before we've received all <chunkSize> then we incorrectly indicate success and the end of a backfill.
Which is really not what we ought to be doing there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1592)
=> source-{postgres,sqlserver}: Check for error after backfill query

source-mysql/discovery.go, source-postgres/discovery.go, source-sqlserver/discovery.go
Tweaks the logging around secondary index selection during discovery so that the messages will be more useful, and so that they will be logged at `DEBUG` level so we can see them more easily.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1606)
=> source-{mysql,postgres,sqlserver}: Secondary index debug logs

source-mysql/discovery.go, source-postgres/discovery.go, source-sqlserver/discovery.go
This commit alters the secondary index selection heuristic (which is used during discovery, if a table has no primary key, to try and provide a useful alternative to use as the collection/backfill key).
Previously we picked the first suitable index, where "first" was defined in terms of iterating over a map from index name to the list of columns making up the index. When stated like that the flaw ought to be obvious -- Go map iteration order is random, so if there were multiple suitable indices we could pick a different one every time discovery gets run.
The fix is to make a list of suitable indexes, sort the list by name, and then pick the first one from that list. This is still not perfect (as it could still change if a new index is created on the source database) but …
=> source-{mysql,postgres,sqlserver}: Sort secondary indices by name

source-mongodb/main.go
MongoDB Atlas SQL doesn't support change streams, so we should report a better error message if a user tries to connect with one of those URLs, which has happened a couple of times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1604 …
=> source-mongodb: better error message if connecting to MongoDB Atlas SQL connection string

materialize-redshift/client.go
Include the name of the (pre-existing) table if we ever find that we would need to drop a nullability constraint on the table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1616)
=> materialize-redshift: include name of table in nullability constrainterror message

materialize-snowflake/.snapshots/TestSpecification, materialize-snowflake/config.go
- A terminology change following Snowflake's own docs
- Docs PR: https://github.com/estuary/flow/pull/1479
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/connectors/1617)
=> materialize-snowflake: Host is called Account URL in Snowflake
